// Generated by tools/gen_binding.py from the public headers: edit the headers or the generator, not this.
package wgf;

import wgf.impl.Raw;

class Action {
	/**
	    Bindings added to `action` (made by the first); false for a name breaking the rule, a
	    65th action, a 17th binding, a key, button, or axis that isn't one, a direction that
	    isn't -1, 0, or 1, a threshold outside 0 to 1, or a region with no area.
	**/
	public static inline function bindKey(action:String, key:KeyboardKey):Bool
		return Raw.wgf_action_bind_key(action, key);

	/**
	    Bindings added to `action` (made by the first); false for a name breaking the rule, a
	    65th action, a 17th binding, a key, button, or axis that isn't one, a direction that
	    isn't -1, 0, or 1, a threshold outside 0 to 1, or a region with no area.
	**/
	public static inline function bindKeys(action:String, negative:KeyboardKey, positive:KeyboardKey):Bool
		return Raw.wgf_action_bind_keys(action, negative, positive);

	/**
	    Bindings added to `action` (made by the first); false for a name breaking the rule, a
	    65th action, a 17th binding, a key, button, or axis that isn't one, a direction that
	    isn't -1, 0, or 1, a threshold outside 0 to 1, or a region with no area.
	**/
	public static inline function bindPadButton(action:String, button:GamepadButton):Bool
		return Raw.wgf_action_bind_pad_button(action, button);

	/**
	    Bindings added to `action` (made by the first); false for a name breaking the rule, a
	    65th action, a 17th binding, a key, button, or axis that isn't one, a direction that
	    isn't -1, 0, or 1, a threshold outside 0 to 1, or a region with no area.
	**/
	public static inline function bindPadAxis(action:String, axis:GamepadAxis, direction:Int, threshold:Float):Bool
		return Raw.wgf_action_bind_pad_axis(action, axis, direction, threshold);

	/**
	    Bindings added to `action` (made by the first); false for a name breaking the rule, a
	    65th action, a 17th binding, a key, button, or axis that isn't one, a direction that
	    isn't -1, 0, or 1, a threshold outside 0 to 1, or a region with no area.
	**/
	public static inline function bindTouch(action:String, x:Float, y:Float, width:Float, height:Float):Bool
		return Raw.wgf_action_bind_touch(action, x, y, width, height);

	/**
	    Every binding of `action` taken off, the action kept (a remap screen binds it again);
	    false for an action there isn't.
	**/
	public static inline function clear(action:String):Bool
		return Raw.wgf_action_clear(action);

	/**
	    The action as it is: its axis (-1 to 1), its value (0 to 1), and its state. 0, 0, and
	    UP for an action there isn't.
	**/
	public static inline function getAxis(action:String):Float
		return Raw.wgf_action_get_axis(action);

	/**
	    The action as it is: its axis (-1 to 1), its value (0 to 1), and its state. 0, 0, and
	    UP for an action there isn't.
	**/
	public static inline function getValue(action:String):Float
		return Raw.wgf_action_get_value(action);

	/**
	    The action as it is: its axis (-1 to 1), its value (0 to 1), and its state. 0, 0, and
	    UP for an action there isn't.
	**/
	public static inline function getState(action:String):InputState
		return Raw.wgf_action_get_state(action);

	/**
	    The action as it is: its axis (-1 to 1), its value (0 to 1), and its state. 0, 0, and
	    UP for an action there isn't.
	**/
	public static inline function isDown(action:String):Bool
		return Raw.wgf_action_is_down(action);

	/**
	    The action as it is: its axis (-1 to 1), its value (0 to 1), and its state. 0, 0, and
	    UP for an action there isn't.
	**/
	public static inline function isPressed(action:String):Bool
		return Raw.wgf_action_is_pressed(action);

	/**
	    The action as it is: its axis (-1 to 1), its value (0 to 1), and its state. 0, 0, and
	    UP for an action there isn't.
	**/
	public static inline function isReleased(action:String):Bool
		return Raw.wgf_action_is_released(action);

	/**
	    The actions, in the order made, and each one's bindings as text for a help line or a
	    remap screen ("Left / Right", "Space", "Pad south", "Left stick X", "Right trigger",
	    "Touch"): libwgf's, valid until the next call here. "" past the end.
	**/
	public static inline function getCount():Int
		return Raw.wgf_action_get_count();

	/**
	    The actions, in the order made, and each one's bindings as text for a help line or a
	    remap screen ("Left / Right", "Space", "Pad south", "Left stick X", "Right trigger",
	    "Touch"): libwgf's, valid until the next call here. "" past the end.
	**/
	public static inline function getName(index:Int):String
		return Raw.wgf_action_get_name(index);

	/**
	    The actions, in the order made, and each one's bindings as text for a help line or a
	    remap screen ("Left / Right", "Space", "Pad south", "Left stick X", "Right trigger",
	    "Touch"): libwgf's, valid until the next call here. "" past the end.
	**/
	public static inline function getBindingCount(action:String):Int
		return Raw.wgf_action_get_binding_count(action);

	/**
	    The actions, in the order made, and each one's bindings as text for a help line or a
	    remap screen ("Left / Right", "Space", "Pad south", "Left stick X", "Right trigger",
	    "Touch"): libwgf's, valid until the next call here. "" past the end.
	**/
	public static inline function getBindingText(action:String, index:Int):String
		return Raw.wgf_action_get_binding_text(action, index);
}
