// Generated by tools/gen_binding.py from the public headers: edit the headers or the generator, not this.
package wgf;

import wgf.impl.Raw;

/** A handle of kind wgf_actor_t (gfx/include/wgf_actor.h): 0 is none. **/
abstract Actor(Int) from Int to Int to wgf.Handle {
	/** Whether this is no handle (0); right on every target, where `== null` is not. **/
	public inline function isNone():Bool
		return this == 0;

	/**
	    A plain actor: a transform, with no parent. 0 when there is no room for another.
	**/
	public static inline function create():Actor
		return Raw.wgf_actor_create();

	/**
	    End an actor of any kind, at once. What it held is released, never destroyed: a
	    sprite drops its reference to its texture.
	**/
	public inline function destroy(children:ActorDestroy):Void
		Raw.wgf_actor_destroy(this, children);

	/**
	    End an actor of any kind, at once. What it held is released, never destroyed: a
	    sprite drops its reference to its texture.
	**/
	public inline function getKind():ActorKind
		return Raw.wgf_actor_get_kind(this);

	/**
	    Put `actor` under `parent`, last among its children, keeping its own transform
	    (so it moves to where it sits relative to the new parent); 0 detaches it, and a
	    detached actor is drawn by nothing. False when `parent` isn't an actor, or is
	    `actor` or under it, or when `actor` is a 2D or 3D stage, which are always roots.
	**/
	public inline function setParent(parent:Actor):Bool
		return Raw.wgf_actor_set_parent(this, parent);

	/**
	    Put `actor` under `parent`, last among its children, keeping its own transform
	    (so it moves to where it sits relative to the new parent); 0 detaches it, and a
	    detached actor is drawn by nothing. False when `parent` isn't an actor, or is
	    `actor` or under it, or when `actor` is a 2D or 3D stage, which are always roots.
	**/
	public inline function getParent():Actor
		return Raw.wgf_actor_get_parent(this);

	/**
	    Put `actor` under `parent`, last among its children, keeping its own transform
	    (so it moves to where it sits relative to the new parent); 0 detaches it, and a
	    detached actor is drawn by nothing. False when `parent` isn't an actor, or is
	    `actor` or under it, or when `actor` is a 2D or 3D stage, which are always roots.
	**/
	public inline function getChildCount():Int
		return Raw.wgf_actor_get_child_count(this);

	/**
	    The child at `index`, 0 first; 0 when there is none.
	**/
	public inline function getChild(index:Int):Actor
		return Raw.wgf_actor_get_child(this, index);

	/**
	    Where `actor` is among its parent's children, which is its drawing order in a
	    2D stage: later children draw over earlier ones. An index past either end is
	    clamped to it, so a large one moves it to the front. False when it has no
	    parent.
	**/
	public inline function setIndex(index:Int):Bool
		return Raw.wgf_actor_set_index(this, index);

	/**
	    Where `actor` is among its parent's children, which is its drawing order in a
	    2D stage: later children draw over earlier ones. An index past either end is
	    clamped to it, so a large one moves it to the front. False when it has no
	    parent.
	**/
	public inline function getIndex():Int
		return Raw.wgf_actor_get_index(this);

	/**
	    The transform, relative to the parent. Rotation is three angles in radians,
	    about x, then y, then z (wgf_quat_from_euler), kept as the rotation they make:
	    get_rotation gives angles for the same rotation, which may not be the ones given
	    (past a half turn, say). Scale 1 is its own size.
	**/
	public inline function setPosition(x:Float, y:Float, z:Float):Bool
		return Raw.wgf_actor_set_position(this, x, y, z);

	/**
	    The transform, relative to the parent. Rotation is three angles in radians,
	    about x, then y, then z (wgf_quat_from_euler), kept as the rotation they make:
	    get_rotation gives angles for the same rotation, which may not be the ones given
	    (past a half turn, say). Scale 1 is its own size.
	**/
	public inline function getPosition(?into:wgf.Vec3):wgf.Vec3
		return Raw.wgf_actor_get_position(this, into);

	/**
	    The transform, relative to the parent. Rotation is three angles in radians,
	    about x, then y, then z (wgf_quat_from_euler), kept as the rotation they make:
	    get_rotation gives angles for the same rotation, which may not be the ones given
	    (past a half turn, say). Scale 1 is its own size.
	**/
	public inline function setRotation(x:Float, y:Float, z:Float):Bool
		return Raw.wgf_actor_set_rotation(this, x, y, z);

	/**
	    The transform, relative to the parent. Rotation is three angles in radians,
	    about x, then y, then z (wgf_quat_from_euler), kept as the rotation they make:
	    get_rotation gives angles for the same rotation, which may not be the ones given
	    (past a half turn, say). Scale 1 is its own size.
	**/
	public inline function getRotation(?into:wgf.Vec3):wgf.Vec3
		return Raw.wgf_actor_get_rotation(this, into);

	/**
	    The transform, relative to the parent. Rotation is three angles in radians,
	    about x, then y, then z (wgf_quat_from_euler), kept as the rotation they make:
	    get_rotation gives angles for the same rotation, which may not be the ones given
	    (past a half turn, say). Scale 1 is its own size.
	**/
	public inline function setScale(x:Float, y:Float, z:Float):Bool
		return Raw.wgf_actor_set_scale(this, x, y, z);

	/**
	    The transform, relative to the parent. Rotation is three angles in radians,
	    about x, then y, then z (wgf_quat_from_euler), kept as the rotation they make:
	    get_rotation gives angles for the same rotation, which may not be the ones given
	    (past a half turn, say). Scale 1 is its own size.
	**/
	public inline function getScale(?into:wgf.Vec3):wgf.Vec3
		return Raw.wgf_actor_get_scale(this, into);

	/**
	    All three at once: the cheapest way to move something each frame.
	**/
	public inline function setTransform(position_x:Float, position_y:Float, position_z:Float, rotation_x:Float, rotation_y:Float, rotation_z:Float, scale_x:Float, scale_y:Float, scale_z:Float):Bool
		return Raw.wgf_actor_set_transform(this, position_x, position_y, position_z, rotation_x, rotation_y, rotation_z, scale_x, scale_y, scale_z);

	/**
	    An actor with a simulated component (motion, bounds, lifetime, a collider: wgf_component.h)
	    moves at the tick rate: its transform is the simulation's, and it is drawn between its
	    last two ticks' at each frame's tick fraction, so it moves smoothly at any frame rate.
	    A change in a tick is so smoothed into the frames after it; snap ends the smoothing, so
	    the actor is drawn where it is now (put somewhere new, it isn't seen sweeping there).
	    False for an actor that isn't one; true and nothing to do for one not simulated.
	**/
	public inline function snap():Bool
		return Raw.wgf_actor_snap(this);

	/**
	    Many positions at once: each of `actors` (count of them) read into `out` as x, y, z in
	    turn, as many as fit in `out_count` floats, returning how many floats it filled (a
	    handle that isn't an actor reads 0, 0, 0); and each set from `positions` (x, y, z in
	    turn, positions_count floats), false when there aren't three floats for each, skipping
	    a handle that isn't an actor.
	**/
	public static inline function getPositions(actors:Array<Actor>, out:Array<Float>):Int
		return Raw.wgf_actor_get_positions(cast actors, out);

	/**
	    Many positions at once: each of `actors` (count of them) read into `out` as x, y, z in
	    turn, as many as fit in `out_count` floats, returning how many floats it filled (a
	    handle that isn't an actor reads 0, 0, 0); and each set from `positions` (x, y, z in
	    turn, positions_count floats), false when there aren't three floats for each, skipping
	    a handle that isn't an actor.
	**/
	public static inline function setPositions(actors:Array<Actor>, positions:Array<Float>):Bool
		return Raw.wgf_actor_set_positions(cast actors, positions);

	/**
	    Where the actor is in its tree's root's space: on a 2D stage, stage units.
	**/
	public inline function getWorldPosition(?into:wgf.Vec3):wgf.Vec3
		return Raw.wgf_actor_get_world_position(this, into);

	/**
	    Turn the actor so its -z points at the target (x, y, z) and its +y is as near to the
	    up direction (up_x, up_y, up_z) as can be, both in its tree's root's space: how a
	    camera is aimed, since it looks down its -z. Its rotation is set relative to its
	    parent, so it points there as it is placed now. False when the target is where the
	    actor is, or the up direction is along the line to it.
	**/
	public inline function lookAt(x:Float, y:Float, z:Float, up_x:Float, up_y:Float, up_z:Float):Bool
		return Raw.wgf_actor_look_at(this, x, y, z, up_x, up_y, up_z);

	/**
	    A name to find the actor by; NULL or "" for none, the default. get_name is "" for none: borrowed, valid until the
	    name changes or the actor goes. A name is found by its stage (wgf_stage2d_find, wgf_stage3d_find) when it is the
	    only one so named there, and by a path from any actor (wgf_actor_find) when it is unique among its siblings.
	**/
	public inline function setName(name:String):Bool
		return Raw.wgf_actor_set_name(this, name);

	/**
	    A name to find the actor by; NULL or "" for none, the default. get_name is "" for none: borrowed, valid until the
	    name changes or the actor goes. A name is found by its stage (wgf_stage2d_find, wgf_stage3d_find) when it is the
	    only one so named there, and by a path from any actor (wgf_actor_find) when it is unique among its siblings.
	**/
	public inline function getName():String
		return Raw.wgf_actor_get_name(this);

	/**
	    The actor at `path` from `actor`: child names joined by '/', so "wheel_rl/smoke" is the
	    child "smoke" of the child "wheel_rl". Each step looks only among one actor's children
	    (the first so named, in order), never through the tree. 0 for none, an empty step
	    ("a//b"), or an empty or NULL path.
	**/
	public inline function find(path:String):Actor
		return Raw.wgf_actor_find(this, path);

	/**
	    Two flags say what an actor takes part in, each the actor's own, read back as set:

	      enabled   off: the actor is skipped altogether, with everything under it, as if
	                it weren't in the tree, by drawing and by every update (an emitter
	                under it isn't moved on): the switch on a part of the game that is off
	                for now. The only one that reaches the children; their own flags are
	                kept, so enabling it again brings each back as it was set
	      visible   off: the actor's own output is off -- a sprite, shape, text, or
	                emitter isn't drawn -- while it is still placed and its children are
	                as they are

	    Defaults: enabled, visible.
	**/
	public inline function setEnabled(enabled:Bool):Bool
		return Raw.wgf_actor_set_enabled(this, enabled);

	/**
	    Two flags say what an actor takes part in, each the actor's own, read back as set:

	      enabled   off: the actor is skipped altogether, with everything under it, as if
	                it weren't in the tree, by drawing and by every update (an emitter
	                under it isn't moved on): the switch on a part of the game that is off
	                for now. The only one that reaches the children; their own flags are
	                kept, so enabling it again brings each back as it was set
	      visible   off: the actor's own output is off -- a sprite, shape, text, or
	                emitter isn't drawn -- while it is still placed and its children are
	                as they are

	    Defaults: enabled, visible.
	**/
	public inline function isEnabled():Bool
		return Raw.wgf_actor_is_enabled(this);

	/**
	    Two flags say what an actor takes part in, each the actor's own, read back as set:

	      enabled   off: the actor is skipped altogether, with everything under it, as if
	                it weren't in the tree, by drawing and by every update (an emitter
	                under it isn't moved on): the switch on a part of the game that is off
	                for now. The only one that reaches the children; their own flags are
	                kept, so enabling it again brings each back as it was set
	      visible   off: the actor's own output is off -- a sprite, shape, text, or
	                emitter isn't drawn -- while it is still placed and its children are
	                as they are

	    Defaults: enabled, visible.
	**/
	public inline function setVisible(visible:Bool):Bool
		return Raw.wgf_actor_set_visible(this, visible);

	/**
	    Two flags say what an actor takes part in, each the actor's own, read back as set:

	      enabled   off: the actor is skipped altogether, with everything under it, as if
	                it weren't in the tree, by drawing and by every update (an emitter
	                under it isn't moved on): the switch on a part of the game that is off
	                for now. The only one that reaches the children; their own flags are
	                kept, so enabling it again brings each back as it was set
	      visible   off: the actor's own output is off -- a sprite, shape, text, or
	                emitter isn't drawn -- while it is still placed and its children are
	                as they are

	    Defaults: enabled, visible.
	**/
	public inline function isVisible():Bool
		return Raw.wgf_actor_is_visible(this);

	/**
	    A behavior named `name` added to `actor`, after the ones it has: its id, or 0 when
	    `actor` isn't an actor, the name breaks the rule above, or it is out of memory.
	**/
	public inline function addBehavior(name:String):Int
		return Raw.wgf_actor_add_behavior(this, name);

	/**
	    The behavior removed (DESTROYED raised for it).
	**/
	public inline function removeBehavior(behavior:Int):Bool
		return Raw.wgf_actor_remove_behavior(this, behavior);

	/**
	    The actor's behaviors in the order they were added: how many, and the id of the one at
	    `index` (0 past the end); and the id of its first named `name` (0 for none).
	**/
	public inline function getBehaviorCount():Int
		return Raw.wgf_actor_get_behavior_count(this);

	/**
	    The actor's behaviors in the order they were added: how many, and the id of the one at
	    `index` (0 past the end); and the id of its first named `name` (0 for none).
	**/
	public inline function getBehavior(index:Int):Int
		return Raw.wgf_actor_get_behavior(this, index);

	/**
	    The actor's behaviors in the order they were added: how many, and the id of the one at
	    `index` (0 past the end); and the id of its first named `name` (0 for none).
	**/
	public inline function findBehavior(name:String):Int
		return Raw.wgf_actor_find_behavior(this, name);

	/**
	    add makes one with its defaults (each component's header says them); adding one it has
	    keeps it as it is. remove ends it (a voice stopped and destroyed). False for a handle
	    that isn't an actor, or a component that isn't one; remove is false too for one it
	    doesn't have.
	**/
	public inline function addComponent(component:Component):Bool
		return Raw.wgf_actor_add_component(this, component);

	/**
	    add makes one with its defaults (each component's header says them); adding one it has
	    keeps it as it is. remove ends it (a voice stopped and destroyed). False for a handle
	    that isn't an actor, or a component that isn't one; remove is false too for one it
	    doesn't have.
	**/
	public inline function removeComponent(component:Component):Bool
		return Raw.wgf_actor_remove_component(this, component);

	/**
	    add makes one with its defaults (each component's header says them); adding one it has
	    keeps it as it is. remove ends it (a voice stopped and destroyed). False for a handle
	    that isn't an actor, or a component that isn't one; remove is false too for one it
	    doesn't have.
	**/
	public inline function hasComponent(component:Component):Bool
		return Raw.wgf_actor_has_component(this, component);

	/**
	    The voice component's voice; 0 for an actor without one. The actor's: play it, never
	    destroy it.
	**/
	public inline function getVoice():Voice
		return Raw.wgf_actor_get_voice(this);
}
