// Generated by tools/gen_binding.py from the public headers: edit the headers or the generator, not this.
package wgf;

/**
    How something drawn uses its alpha. In a stage, OPAQUE and MASK parts write depth and
    aren't sorted; BLEND parts are drawn after them, sorted back to front.
**/
enum abstract AlphaMode(Int) from Int to Int {
	var OPAQUE = 0;
	var MASK = 1;
	var BLEND = 2;
}
