// Generated by tools/gen_binding.py from the public headers: edit the headers or the generator, not this.
package wgf;

import wgf.impl.Raw;

class App {
	/**
	    Ask the program to quit: the frame under way finishes, then shutdown runs.
	**/
	public static inline function quit():Void
		Raw.wgf_app_quit();

	/**
	    Whether quitting means anything here: false on the web, where the page stays when
	    the program would end, and the browser owns Escape. A game offers a quit key or
	    button only where this is true.
	**/
	public static inline function canQuit():Bool
		return Raw.wgf_app_can_quit();

	/**
	    Between wgf_app_run starting the program and shutdown finishing.
	**/
	public static inline function isRunning():Bool
		return Raw.wgf_app_is_running();
}
