// Generated by tools/gen_binding.py from the public headers: edit the headers or the generator, not this.
package wgf;

/**
    Assets: where a resource's file comes from. A path is an asset: creating a resource
    from a path (wgf_texture_create, wgf_font_create, wgf_sound_create, a scene's) goes
    through here, as does any call below, and that is what links it -- a program that
    only makes generated content links none of it. A relative path is looked for under
    the asset host, which needs no setting:

      natively  the host is the program's own directory (where its executable is,
                wherever it was started from), the file storage's root (wgf_fs.h):
                files are read where they are, as without this layer
      web       the host is the page's own directory (its document's base URL, so a
                <base href> moves it): a file not bundled into the page and not cached
                is fetched from beside the page, cached in the browser's storage, and
                checked again on later visits as the cache mode says

    so a web page loads its files with no call here at all, and one that should never
    fetch bundles what it loads. Set another host to fetch from elsewhere (a CDN), or
    natively to download (fetching, below). A path that is a URL ("https://...") is
    fetched from there, cached under its own name; natively that needs fetching turned
    on, and without it the load fails, logged with the URL.

    A resource makes its own file local as it loads (wgf_resource.h), so a program only
    ENSURES a file to have it local without loading it: to fetch ahead (a level's files
    during a menu), from an explicit source (a fetch_url), or to read it itself. An
    ensure is a task: a handle whose status, local path and progress the program reads,
    nothing called back, destroyed when done with. A path ensured from an explicit
    source is what a later create of that path loads, wherever it was found.

    A format whose files name other files is ensured with them, when the layer that
    reads it registers how to list them (core's lister, wgf_core_load_priv.h): the task
    is DONE once all are local. None of libwgf's formats names others yet.

    libwgt's asset layer, carried whole (docs/HISTORY.md).
**/
enum abstract AssetTaskStatus(Int) from Int to Int {
	var NONE = 0;
	var PENDING = 1;
	var DONE = 2;
	var FAILED = 3;
}
