// Generated by tools/gen_binding.py from the public headers: edit the headers or the generator, not this.
package wgf;

import wgf.impl.Raw;

/** A handle of kind wgf_asset_task_t (asset/include/wgf_asset.h): 0 is none. **/
abstract AssetTask(Int) from Int to Int to wgf.Handle {
	/** Whether this is no handle (0); right on every target, where `== null` is not. **/
	public inline function isNone():Bool
		return this == 0;

	/** Whether this refers to something alive: false for none, and for what was destroyed or released (wgf_handle_is_alive). Ask it first where a handle may be dead. **/
	public inline function isAlive():Bool
		return (this : Handle).isAlive();

	/**
	    A task's status: a file's, a group's, or a ping's; NONE for anything that isn't one.
	    It changes only in an update, so a frame reading it sees each change once.
	**/
	public inline function getStatus():AssetTaskStatus
		return Raw.wgf_asset_task_get_status(this);

	/**
	    The local path of a DONE file task, which opens directly (where the file was found:
	    a redirect's, a fetch_url's). "" until then, for a group, and for anything that isn't
	    a task. Borrowed: valid while the task is, until the next ensure.
	**/
	public inline function getPath():String
		return Raw.wgf_asset_task_get_path(this);

	/**
	    Rough progress, 0..1: a file counts half for being local and half for the files it
	    names; a group, its members' average. 1 once DONE or FAILED; 0 for anything that
	    isn't a task. For resources loading, read their statuses (wgf_resource.h).
	**/
	public inline function getProgress():Float
		return Raw.wgf_asset_task_get_progress(this);

	/**
	    Free a task. One still PENDING runs on, its result dropped (a file still lands in
	    the cache). A group's members go with it. False for anything that isn't a task.
	**/
	public inline function destroy():Bool
		return Raw.wgf_asset_task_destroy(this);
}
