// Generated by tools/gen_binding.py from the public headers: edit the headers or the generator, not this.
package wgf;

import wgf.impl.Raw;

class Audio {
	/**
	    Every voice's loudness, times its own: 1 as they are, 0 silent, above 1 louder (and
	    may clip). Refuses a negative or non-finite one.
	**/
	public static inline function setVolume(volume:Float):Bool
		return Raw.wgf_audio_set_volume(volume);

	/**
	    Every voice's loudness, times its own: 1 as they are, 0 silent, above 1 louder (and
	    may clip). Refuses a negative or non-finite one.
	**/
	public static inline function getVolume():Float
		return Raw.wgf_audio_get_volume();

	/**
	    Every voice held where it is, its state unchanged, until unpaused: for a game's pause
	    screen. Paused or not, voices are told to play, pause, and stop as usual.
	**/
	public static inline function setPaused(paused:Bool):Void
		Raw.wgf_audio_set_paused(paused);

	/**
	    Every voice held where it is, its state unchanged, until unpaused: for a game's pause
	    screen. Paused or not, voices are told to play, pause, and stop as usual.
	**/
	public static inline function isPaused():Bool
		return Raw.wgf_audio_is_paused();
}
