// Generated by tools/gen_binding.py from the public headers: edit the headers or the generator, not this.
package wgf;

import wgf.impl.Raw;

/** BehaviorComponent's calls, on a Entity: `var x:BehaviorComponent = handle` gives it them, and a BehaviorComponent is still a Entity. **/
@:forward abstract BehaviorComponent(Entity) from Entity to Entity {
	/**
	    Default: "" (none: no code). Setting a name doesn't raise CREATED again. False too
	    for a name breaking the rule above. get_name's is the entity's, valid until it
	    changes.
	**/
	public inline function setName(name:String):Bool
		return Raw.wgf_behavior_set_name(this, name);

	/**
	    Default: "" (none: no code). Setting a name doesn't raise CREATED again. False too
	    for a name breaking the rule above. get_name's is the entity's, valid until it
	    changes.
	**/
	public inline function getName():String
		return Raw.wgf_behavior_get_name(this);

	/**
	    A parameter, set to `value` (text), added the first time; NULL removes it. False too
	    for a key or value breaking the rule, or a 33rd parameter. get_param's is the
	    entity's: "" for one it doesn't have, valid until it changes. get_param_number reads
	    it as a number: 0 for one it doesn't have or that isn't one.
	**/
	public inline function setParam(key:String, value:String):Bool
		return Raw.wgf_behavior_set_param(this, key, value);

	/**
	    A parameter, set to `value` (text), added the first time; NULL removes it. False too
	    for a key or value breaking the rule, or a 33rd parameter. get_param's is the
	    entity's: "" for one it doesn't have, valid until it changes. get_param_number reads
	    it as a number: 0 for one it doesn't have or that isn't one.
	**/
	public inline function getParam(key:String):String
		return Raw.wgf_behavior_get_param(this, key);

	/**
	    A parameter, set to `value` (text), added the first time; NULL removes it. False too
	    for a key or value breaking the rule, or a 33rd parameter. get_param's is the
	    entity's: "" for one it doesn't have, valid until it changes. get_param_number reads
	    it as a number: 0 for one it doesn't have or that isn't one.
	**/
	public inline function getParamNumber(key:String):Float
		return Raw.wgf_behavior_get_param_number(this, key);

	/**
	    A parameter, set to `value` (text), added the first time; NULL removes it. False too
	    for a key or value breaking the rule, or a 33rd parameter. get_param's is the
	    entity's: "" for one it doesn't have, valid until it changes. get_param_number reads
	    it as a number: 0 for one it doesn't have or that isn't one.
	**/
	public inline function hasParam(key:String):Bool
		return Raw.wgf_behavior_has_param(this, key);

	/**
	    Its parameters in the order first set: how many, and each one's key ("" past the
	    end).
	**/
	public inline function getParamCount():Int
		return Raw.wgf_behavior_get_param_count(this);

	/**
	    Its parameters in the order first set: how many, and each one's key ("" past the
	    end).
	**/
	public inline function getParamKey(index:Int):String
		return Raw.wgf_behavior_get_param_key(this, index);
}
