// Generated by tools/gen_binding.py from the public headers: edit the headers or the generator, not this.
package wgf;

import wgf.impl.Raw;

/** Body's calls, on a Actor: `var x:Body = handle` gives it them, and a Body is still a Actor. **/
@:forward abstract Body(Actor) from Actor to Actor {
	public inline function setType(type:BodyType):Bool
		return Raw.wgf_body_set_type(this, type);

	public inline function getType():BodyType
		return Raw.wgf_body_get_type(this);

	/**
	    Its shape, centered on the actor; x, y, z as the shape says (wgf_body_shape_t), each
	    at least 0.01, and nothing for CONVEX and MESH, whose models' meshes are read when
	    the body is made (a model not yet loaded is left out). get_size is x, y, z as set. A
	    mesh can only be static: on another type it is its convex hull.
	**/
	public inline function setShape(shape:BodyShape, x:Float, y:Float, z:Float):Bool
		return Raw.wgf_body_set_shape(this, shape, x, y, z);

	/**
	    Its shape, centered on the actor; x, y, z as the shape says (wgf_body_shape_t), each
	    at least 0.01, and nothing for CONVEX and MESH, whose models' meshes are read when
	    the body is made (a model not yet loaded is left out). get_size is x, y, z as set. A
	    mesh can only be static: on another type it is its convex hull.
	**/
	public inline function getShape():BodyShape
		return Raw.wgf_body_get_shape(this);

	/**
	    Its shape, centered on the actor; x, y, z as the shape says (wgf_body_shape_t), each
	    at least 0.01, and nothing for CONVEX and MESH, whose models' meshes are read when
	    the body is made (a model not yet loaded is left out). get_size is x, y, z as set. A
	    mesh can only be static: on another type it is its convex hull.
	**/
	public inline function getSize(?into:wgf.Vec3):wgf.Vec3
		return Raw.wgf_body_get_size(this, into);

	/**
	    Kilograms, for a dynamic body; 0 (the default) for its shape's at 1000 a cubic meter.
	**/
	public inline function setMass(kilograms:Float):Bool
		return Raw.wgf_body_set_mass(this, kilograms);

	/**
	    Kilograms, for a dynamic body; 0 (the default) for its shape's at 1000 a cubic meter.
	**/
	public inline function getMass():Float
		return Raw.wgf_body_get_mass(this);

	/**
	    Friction (0 ice, 1 rubber; clamped to 0 or more) and bounce (0 none, 1 all of it;
	    clamped to 0 to 1), each a pair's taken together.
	**/
	public inline function setFriction(friction:Float):Bool
		return Raw.wgf_body_set_friction(this, friction);

	/**
	    Friction (0 ice, 1 rubber; clamped to 0 or more) and bounce (0 none, 1 all of it;
	    clamped to 0 to 1), each a pair's taken together.
	**/
	public inline function getFriction():Float
		return Raw.wgf_body_get_friction(this);

	/**
	    Friction (0 ice, 1 rubber; clamped to 0 or more) and bounce (0 none, 1 all of it;
	    clamped to 0 to 1), each a pair's taken together.
	**/
	public inline function setBounce(bounce:Float):Bool
		return Raw.wgf_body_set_bounce(this, bounce);

	/**
	    Friction (0 ice, 1 rubber; clamped to 0 or more) and bounce (0 none, 1 all of it;
	    clamped to 0 to 1), each a pair's taken together.
	**/
	public inline function getBounce():Float
		return Raw.wgf_body_get_bounce(this);

	/**
	    The share of its velocity and of its spin it loses each second, 0 to 1: get_damping is
	    (linear, angular).
	**/
	public inline function setDamping(linear:Float, angular:Float):Bool
		return Raw.wgf_body_set_damping(this, linear, angular);

	/**
	    The share of its velocity and of its spin it loses each second, 0 to 1: get_damping is
	    (linear, angular).
	**/
	public inline function getDamping(?into:wgf.Vec2):wgf.Vec2
		return Raw.wgf_body_get_damping(this, into);

	/**
	    What it meets: two bodies meet (collide, or a sensor tells of the other) when each
	    one's layer has a bit in the other's mask. 15 bits each (1 to 0x7FFF); a static
	    body meets every moving one its mask lets, and every moving one meets the static world.
	**/
	public inline function setLayer(layer:Int):Bool
		return Raw.wgf_body_set_layer(this, layer);

	/**
	    What it meets: two bodies meet (collide, or a sensor tells of the other) when each
	    one's layer has a bit in the other's mask. 15 bits each (1 to 0x7FFF); a static
	    body meets every moving one its mask lets, and every moving one meets the static world.
	**/
	public inline function getLayer():Int
		return Raw.wgf_body_get_layer(this);

	/**
	    What it meets: two bodies meet (collide, or a sensor tells of the other) when each
	    one's layer has a bit in the other's mask. 15 bits each (1 to 0x7FFF); a static
	    body meets every moving one its mask lets, and every moving one meets the static world.
	**/
	public inline function setMask(mask:Int):Bool
		return Raw.wgf_body_set_mask(this, mask);

	/**
	    What it meets: two bodies meet (collide, or a sensor tells of the other) when each
	    one's layer has a bit in the other's mask. 15 bits each (1 to 0x7FFF); a static
	    body meets every moving one its mask lets, and every moving one meets the static world.
	**/
	public inline function getMask():Int
		return Raw.wgf_body_get_mask(this);

	/**
	    Its velocity (units a second) and spin (radians a second about each axis), in its
	    stage's space; and a push, an impulse (kg units a second) through its center. A body not
	    yet made in the world (before its first tick) reads 0 and takes them when it is.
	**/
	public inline function setVelocity(x:Float, y:Float, z:Float):Bool
		return Raw.wgf_body_set_velocity(this, x, y, z);

	/**
	    Its velocity (units a second) and spin (radians a second about each axis), in its
	    stage's space; and a push, an impulse (kg units a second) through its center. A body not
	    yet made in the world (before its first tick) reads 0 and takes them when it is.
	**/
	public inline function getVelocity(?into:wgf.Vec3):wgf.Vec3
		return Raw.wgf_body_get_velocity(this, into);

	/**
	    Its velocity (units a second) and spin (radians a second about each axis), in its
	    stage's space; and a push, an impulse (kg units a second) through its center. A body not
	    yet made in the world (before its first tick) reads 0 and takes them when it is.
	**/
	public inline function setSpin(x:Float, y:Float, z:Float):Bool
		return Raw.wgf_body_set_spin(this, x, y, z);

	/**
	    Its velocity (units a second) and spin (radians a second about each axis), in its
	    stage's space; and a push, an impulse (kg units a second) through its center. A body not
	    yet made in the world (before its first tick) reads 0 and takes them when it is.
	**/
	public inline function getSpin(?into:wgf.Vec3):wgf.Vec3
		return Raw.wgf_body_get_spin(this, into);

	/**
	    Its velocity (units a second) and spin (radians a second about each axis), in its
	    stage's space; and a push, an impulse (kg units a second) through its center. A body not
	    yet made in the world (before its first tick) reads 0 and takes them when it is.
	**/
	public inline function addImpulse(x:Float, y:Float, z:Float):Bool
		return Raw.wgf_body_add_impulse(this, x, y, z);
}
