// Generated by tools/gen_binding.py from the public headers: edit the headers or the generator, not this.
package wgf;

/**
    Bounds (WGF_COMPONENT_BOUNDS): a rectangle in the entity's parent's space, x and y,
    and what happens to an entity whose position leaves it, by more than its margin, each
    tick after motion. Defaults: 0, 0, 800 by 600, WRAP, a margin of 0. Every call is false
    (or 0) for an entity without bounds.
**/
enum abstract BoundsMode(Int) from Int to Int {
	var WRAP = 0;
	var CLAMP = 1;
	var DESTROY = 2;
}
