// Generated by tools/gen_binding.py from the public headers: edit the headers or the generator, not this.
package wgf;

import wgf.impl.Raw;

/** Camera3d's calls, on a Node: `var x:Camera3d = handle` gives it them, and a Camera3d is still a Node. **/
@:forward abstract Camera3d(Node) from Node to Node {
	/**
	    A camera with a 60 degree vertical field of view, seeing from 0.1 to 1000 units in
	    front of it. 0 when there is no room for another node.
	**/
	public static inline function create():Camera3d
		return ((Raw.wgf_camera3d_create() : Node) : Camera3d);

	/**
	    The vertical field of view, in radians, clamped to 0.01 to 3.13 (just short of a
	    half turn).
	**/
	public inline function setFov(radians:Float):Bool
		return Raw.wgf_camera3d_set_fov(this, radians);

	/**
	    The vertical field of view, in radians, clamped to 0.01 to 3.13 (just short of a
	    half turn).
	**/
	public inline function getFov():Float
		return Raw.wgf_camera3d_get_fov(this);

	/**
	    How near and far in front of the camera it sees. False unless 0 < near < far.
	**/
	public inline function setClip(near_z:Float, far_z:Float):Bool
		return Raw.wgf_camera3d_set_clip(this, near_z, far_z);

	/**
	    How near and far in front of the camera it sees. False unless 0 < near < far.
	**/
	public inline function getNear():Float
		return Raw.wgf_camera3d_get_near(this);

	/**
	    How near and far in front of the camera it sees. False unless 0 < near < far.
	**/
	public inline function getFar():Float
		return Raw.wgf_camera3d_get_far(this);

	/**
	    Orthographic (true) or perspective (false, the default).
	**/
	public inline function setOrthographic(orthographic:Bool):Bool
		return Raw.wgf_camera3d_set_orthographic(this, orthographic);

	/**
	    Orthographic (true) or perspective (false, the default).
	**/
	public inline function isOrthographic():Bool
		return Raw.wgf_camera3d_is_orthographic(this);

	/**
	    How tall a view an orthographic camera sees, in units (default 10). False for 0 or
	    less.
	**/
	public inline function setOrthoHeight(height:Float):Bool
		return Raw.wgf_camera3d_set_ortho_height(this, height);

	/**
	    How tall a view an orthographic camera sees, in units (default 10). False for 0 or
	    less.
	**/
	public inline function getOrthoHeight():Float
		return Raw.wgf_camera3d_get_ortho_height(this);
}
