// Generated by tools/gen_binding.py from the public headers: edit the headers or the generator, not this.
package wgf;

import wgf.impl.Raw;

/** Camera2d's calls, on a Actor: `var x:Camera2d = handle` gives it them, and a Camera2d is still a Actor; it starts as 0, none, as a Actor does. **/
@:forward abstract Camera2d(Actor) from Actor from Int to Actor {
	/**
	    A 2D camera, zoom 1. 0 when there is no room for another actor.
	**/
	public static inline function create():Camera2d
		return ((Raw.wgf_camera2d_create() : Actor) : Camera2d);

	/**
	    How big things look: 2 draws everything twice as big. False for a zoom of 0 or
	    less.
	**/
	public inline function setZoom(zoom:Float):Bool
		return Raw.wgf_camera2d_set_zoom(this, zoom);

	/**
	    How big things look: 2 draws everything twice as big. False for a zoom of 0 or
	    less.
	**/
	public inline function getZoom():Float
		return Raw.wgf_camera2d_get_zoom(this);
}
