// Generated by tools/gen_binding.py from the public headers: edit the headers or the generator, not this.
package wgf;

import wgf.impl.Raw;

/** Canvas's calls, on a Node: `var x:Canvas = handle` gives it them, and a Canvas is still a Node. **/
@:forward abstract Canvas(Node) from Node to Node {
	/**
	    A canvas, with no camera. 0 when there is no room for another node.
	**/
	public static inline function create():Canvas
		return ((Raw.wgf_canvas_create() : Node) : Canvas);

	/**
	    Draw it into this frame. Outside a frame, nothing.
	**/
	public inline function draw():Void
		Raw.wgf_canvas_draw(this);

	/**
	    With a camera (wgf_camera2d.h), the canvas point at the camera's position is
	    drawn at the frame's center, turned and zoomed as the camera is: a 2D world.
	    Without one (0, the default), canvas units are the frame's logical pixels: a HUD.
	    The camera can be anywhere -- in this canvas, parented to the player so it
	    follows, or in no tree at all. False when `camera` isn't a 2D camera. A camera
	    that is destroyed leaves the canvas with none.
	**/
	public inline function setCamera(camera:Node):Bool
		return Raw.wgf_canvas_set_camera(this, camera);

	/**
	    With a camera (wgf_camera2d.h), the canvas point at the camera's position is
	    drawn at the frame's center, turned and zoomed as the camera is: a 2D world.
	    Without one (0, the default), canvas units are the frame's logical pixels: a HUD.
	    The camera can be anywhere -- in this canvas, parented to the player so it
	    follows, or in no tree at all. False when `camera` isn't a 2D camera. A camera
	    that is destroyed leaves the canvas with none.
	**/
	public inline function getCamera():Node
		return Raw.wgf_canvas_get_camera(this);
}
