// Generated by tools/gen_binding.py from the public headers: edit the headers or the generator, not this.
package wgf;

import wgf.impl.Raw;

/** Collider's calls, on a Actor: `var x:Collider = handle` gives it them, and a Collider is still a Actor; it starts as 0, none, as a Actor does. **/
@:forward abstract Collider(Actor) from Actor from Int to Actor {
	/**
	    False too for a radius below 0.
	**/
	public inline function setRadius(radius:Float):Bool
		return Raw.wgf_collider_set_radius(this, radius);

	/**
	    False too for a radius below 0.
	**/
	public inline function getRadius():Float
		return Raw.wgf_collider_get_radius(this);

	/**
	    Bits: what it is, and what it meets. A pair meets when either side's mask has the
	    other's layer, so clearing one collider's mask doesn't stop another whose mask has its
	    layer from meeting it: to make one meet nothing, switch it off (below).
	**/
	public inline function setLayer(layer:Int):Bool
		return Raw.wgf_collider_set_layer(this, layer);

	/**
	    Bits: what it is, and what it meets. A pair meets when either side's mask has the
	    other's layer, so clearing one collider's mask doesn't stop another whose mask has its
	    layer from meeting it: to make one meet nothing, switch it off (below).
	**/
	public inline function getLayer():Int
		return Raw.wgf_collider_get_layer(this);

	/**
	    Bits: what it is, and what it meets. A pair meets when either side's mask has the
	    other's layer, so clearing one collider's mask doesn't stop another whose mask has its
	    layer from meeting it: to make one meet nothing, switch it off (below).
	**/
	public inline function setMask(mask:Int):Bool
		return Raw.wgf_collider_set_mask(this, mask);

	/**
	    Bits: what it is, and what it meets. A pair meets when either side's mask has the
	    other's layer, so clearing one collider's mask doesn't stop another whose mask has its
	    layer from meeting it: to make one meet nothing, switch it off (below).
	**/
	public inline function getMask():Int
		return Raw.wgf_collider_get_mask(this);

	/**
	    Switched off, a collider meets nothing, from either side, and a pair it was in ends
	    (TRIGGER_EXIT at the next tick); its radius, layer, and mask are kept, so switched on
	    again it meets as they say: a ship that can't be hit while it blinks.
	**/
	public inline function setEnabled(enabled:Bool):Bool
		return Raw.wgf_collider_set_enabled(this, enabled);

	/**
	    Switched off, a collider meets nothing, from either side, and a pair it was in ends
	    (TRIGGER_EXIT at the next tick); its radius, layer, and mask are kept, so switched on
	    again it meets as they say: a ship that can't be hit while it blinks.
	**/
	public inline function isEnabled():Bool
		return Raw.wgf_collider_is_enabled(this);

	/**
	    What it overlaps as of the last tick, into `out`, as many as fit in `count`, returning
	    how many it filled.
	**/
	public inline function getOverlaps(out:Array<Actor>):Int
		return Raw.wgf_collider_get_overlaps(this, cast out);
}
