// Generated by tools/gen_binding.py from the public headers: edit the headers or the generator, not this.
package wgf;

import wgf.impl.Raw;

/** Collider's calls, on a Entity: `var x:Collider = handle` gives it them, and a Collider is still a Entity. **/
@:forward abstract Collider(Entity) from Entity to Entity {
	/**
	    False too for a radius below 0.
	**/
	public inline function setRadius(radius:Float):Bool
		return Raw.wgf_collider_set_radius(this, radius);

	/**
	    False too for a radius below 0.
	**/
	public inline function getRadius():Float
		return Raw.wgf_collider_get_radius(this);

	/**
	    Bits: what it is, and what it meets.
	**/
	public inline function setLayer(layer:Int):Bool
		return Raw.wgf_collider_set_layer(this, layer);

	/**
	    Bits: what it is, and what it meets.
	**/
	public inline function getLayer():Int
		return Raw.wgf_collider_get_layer(this);

	/**
	    Bits: what it is, and what it meets.
	**/
	public inline function setMask(mask:Int):Bool
		return Raw.wgf_collider_set_mask(this, mask);

	/**
	    Bits: what it is, and what it meets.
	**/
	public inline function getMask():Int
		return Raw.wgf_collider_get_mask(this);

	/**
	    What it overlaps as of the last tick, into `out`, as many as fit in `count`, returning
	    how many it filled.
	**/
	public inline function getOverlaps(out:Array<Entity>):Int
		return Raw.wgf_collider_get_overlaps(this, cast out);
}
