// Generated by tools/gen_binding.py from the public headers: edit the headers or the generator, not this.
package wgf;

/**
    The stock colors. These name a color; they aren't one: wgf_color_get turns
    a name into its color. (A packed color doesn't fit in an enum, so names are what
    a binding can see.)
**/
enum abstract ColorStock(Int) from Int to Int {
	var BLANK = 0;
	var WHITE = 1;
	var BLACK = 2;
	var LIGHTGRAY = 3;
	var GRAY = 4;
	var DARKGRAY = 5;
	var YELLOW = 6;
	var GOLD = 7;
	var ORANGE = 8;
	var PINK = 9;
	var RED = 10;
	var MAROON = 11;
	var GREEN = 12;
	var LIME = 13;
	var DARKGREEN = 14;
	var SKYBLUE = 15;
	var BLUE = 16;
	var DARKBLUE = 17;
	var PURPLE = 18;
	var VIOLET = 19;
	var DARKPURPLE = 20;
	var BEIGE = 21;
	var BROWN = 22;
	var DARKBROWN = 23;
	var MAGENTA = 24;
	var RAYWHITE = 25;
}
