// Generated by tools/gen_binding.py from the public headers: edit the headers or the generator, not this.
package wgf;

import wgf.impl.Raw;

class Color {
	/**
	    The stock color `stock` names; 0 (transparent) for a value that names none.
	**/
	public static inline function get(stock:ColorStock):Int
		return Raw.wgf_color_get(stock);

	/**
	    A color from components, clamped: 0..255 for make, 0..1 for make_float, which
	    rounds to the nearest 8-bit step. Out-of-range components saturate; they never
	    spill into the next channel.
	**/
	public static inline function make(r:Int, g:Int, b:Int, a:Int):Int
		return Raw.wgf_color_make(r, g, b, a);

	/**
	    A color from components, clamped: 0..255 for make, 0..1 for make_float, which
	    rounds to the nearest 8-bit step. Out-of-range components saturate; they never
	    spill into the next channel.
	**/
	public static inline function makeFloat(r:Float, g:Float, b:Float, a:Float):Int
		return Raw.wgf_color_make_float(r, g, b, a);

	/**
	    `color` with its alpha replaced, clamped to 0..255.
	**/
	public static inline function withAlpha(color:Int, a:Int):Int
		return Raw.wgf_color_with_alpha(color, a);

	/**
	    Components back out, 0..255.
	**/
	public static inline function getRed(color:Int):Int
		return Raw.wgf_color_get_red(color);

	/**
	    Components back out, 0..255.
	**/
	public static inline function getGreen(color:Int):Int
		return Raw.wgf_color_get_green(color);

	/**
	    Components back out, 0..255.
	**/
	public static inline function getBlue(color:Int):Int
		return Raw.wgf_color_get_blue(color);

	/**
	    Components back out, 0..255.
	**/
	public static inline function getAlpha(color:Int):Int
		return Raw.wgf_color_get_alpha(color);

	/**
	    A straight blend, component by component, from `from` (t = 0) to `to` (t = 1);
	    t is clamped to 0..1.
	**/
	public static inline function lerp(from:Int, to:Int, t:Float):Int
		return Raw.wgf_color_lerp(from, to, t);
}
