// Generated by tools/gen_binding.py from the public headers: edit the headers or the generator, not this.
package wgf;

/**
    What an entity can have, at most one of each. The first five are data the systems
    read; the node kinds are a node under the entity's own (wgf_entity_get_component_node),
    set up with its own calls; a voice plays a sound (wgf_entity_get_voice).
**/
enum abstract Component(Int) from Int to Int {
	var NONE = 0;
	var MOTION = 1;
	var BOUNDS = 2;
	var LIFETIME = 3;
	var COLLIDER = 4;
	var BEHAVIOR = 5;
	var SHAPE2D = 6;
	var SPRITE = 7;
	var TEXT = 8;
	var EMITTER2D = 9;
	var VOICE = 10;
}
