// Generated by tools/gen_binding.py from the public headers: edit the headers or the generator, not this.
package wgf;

import wgf.impl.Raw;

class Draw {
	/**
	    Immediate mode 2D: each call draws once, in the frame it is made in, in call order
	    with everything else drawn that frame, and keeps nothing. Logical pixels from the
	    frame's top-left, y down (wgf_render.h). A draw outside a frame draws nothing.

	    Outlines and lines have a thickness in logical pixels, centered on the line; one
	    of 0 or less is a hairline of one logical pixel. A polyline's corners are mitred,
	    and bevelled where a sharp corner's miter would reach past four thicknesses.
	**/
	public static inline function rectangle(x:Float, y:Float, width:Float, height:Float, color:Int):Void
		Raw.wgf_draw_rectangle(x, y, width, height, color);

	/**
	    Immediate mode 2D: each call draws once, in the frame it is made in, in call order
	    with everything else drawn that frame, and keeps nothing. Logical pixels from the
	    frame's top-left, y down (wgf_render.h). A draw outside a frame draws nothing.

	    Outlines and lines have a thickness in logical pixels, centered on the line; one
	    of 0 or less is a hairline of one logical pixel. A polyline's corners are mitred,
	    and bevelled where a sharp corner's miter would reach past four thicknesses.
	**/
	public static inline function rectangleLines(x:Float, y:Float, width:Float, height:Float, thickness:Float, color:Int):Void
		Raw.wgf_draw_rectangle_lines(x, y, width, height, thickness, color);

	/**
	    Immediate mode 2D: each call draws once, in the frame it is made in, in call order
	    with everything else drawn that frame, and keeps nothing. Logical pixels from the
	    frame's top-left, y down (wgf_render.h). A draw outside a frame draws nothing.

	    Outlines and lines have a thickness in logical pixels, centered on the line; one
	    of 0 or less is a hairline of one logical pixel. A polyline's corners are mitred,
	    and bevelled where a sharp corner's miter would reach past four thicknesses.
	**/
	public static inline function line(x0:Float, y0:Float, x1:Float, y1:Float, thickness:Float, color:Int):Void
		Raw.wgf_draw_line(x0, y0, x1, y1, thickness, color);

	/**
	    Circles are drawn with enough segments for their size on screen.
	**/
	public static inline function circle(center_x:Float, center_y:Float, radius:Float, color:Int):Void
		Raw.wgf_draw_circle(center_x, center_y, radius, color);

	/**
	    Circles are drawn with enough segments for their size on screen.
	**/
	public static inline function circleLines(center_x:Float, center_y:Float, radius:Float, thickness:Float, color:Int):Void
		Raw.wgf_draw_circle_lines(center_x, center_y, radius, thickness, color);

	/**
	    Circles are drawn with enough segments for their size on screen.
	**/
	public static inline function triangle(x0:Float, y0:Float, x1:Float, y1:Float, x2:Float, y2:Float, color:Int):Void
		Raw.wgf_draw_triangle(x0, y0, x1, y1, x2, y2, color);

	/**
	    Lines through `points`, x and y in turn (count floats: count / 2 points), the last
	    joined to the first when `closed`. False, drawing nothing, for an odd count, fewer
	    than 2 points, or NULL.
	**/
	public static inline function polyline(points:Array<Float>, closed:Bool, thickness:Float, color:Int):Bool
		return Raw.wgf_draw_polyline(points, closed, thickness, color);

	/**
	    The polygon through `points` filled, x and y in turn (count floats), convex or not,
	    in either winding, as long as its edges don't cross (one that crosses itself is
	    filled as the fan from its first point). False, drawing nothing, for an odd count,
	    fewer than 3 points, or NULL.
	**/
	public static inline function polygon(points:Array<Float>, color:Int):Bool
		return Raw.wgf_draw_polygon(points, color);

	/**
	    Text (UTF-8) in `font` (0: the default font) at `size` logical pixels (16 for 0 or
	    less), its top-left at (x, y). Newlines break lines.
	**/
	public static inline function text(font:Font, text:String, x:Float, y:Float, size:Float, color:Int):Void
		Raw.wgf_draw_text(font, text, x, y, size, color);

	/**
	    The same, (x, y) the point the text is aligned to: its left, center, or right, and its
	    top, middle, or bottom (wgf_text.h's alignments), so a HUD anchored to the visible
	    area's right edge (wgf_presentation_get_visible) needs no guessed width.
	**/
	public static inline function textAligned(font:Font, text:String, x:Float, y:Float, size:Float, color:Int, horizontal:TextHalign, vertical:TextValign):Void
		Raw.wgf_draw_text_aligned(font, text, x, y, size, color, horizontal, vertical);

	/**
	    A texture into the rectangle (x, y, width, height), multiplied by `tint` (white
	    leaves it as it is). A width or height of 0 or less draws it at its own size.
	    Nothing while it is PENDING; the placeholder checker once it has FAILED.
	**/
	public static inline function texture(texture:Texture, x:Float, y:Float, width:Float, height:Float, tint:Int):Void
		Raw.wgf_draw_texture(texture, x, y, width, height, tint);

	/**
	    A region of a texture, in its pixels from the top-left (a source width or height of
	    0 or less: the whole texture), into the rectangle (x, y, width, height), as an icon
	    is cut from an atlas. A width or height of 0 or less draws it at the region's own
	    size. The placeholder fills the rectangle once the texture has FAILED.
	**/
	public static inline function textureRegion(texture:Texture, source_x:Float, source_y:Float, source_width:Float, source_height:Float, x:Float, y:Float, width:Float, height:Float, tint:Int):Void
		Raw.wgf_draw_texture_region(texture, source_x, source_y, source_width, source_height, x, y, width, height, tint);

	/**
	    3D: between begin_3d and end_3d, the 3D calls draw in the world as `camera` (a 3D
	    camera, wgf_camera3d.h) sees it, into the presentation's visible area, depth tested
	    against each other and against the frame's 3D before them, and under the clip. False
	    when `camera` isn't a 3D camera, or outside a frame. A 3D call outside them draws
	    nothing; a frame starts in 2D, and one left in 3D ends there. A 2D call between them
	    lands in the world's x-y plane, as wgrender's did.
	**/
	public static inline function begin3d(camera:Node):Bool
		return Raw.wgf_draw_begin_3d(camera);

	/**
	    3D: between begin_3d and end_3d, the 3D calls draw in the world as `camera` (a 3D
	    camera, wgf_camera3d.h) sees it, into the presentation's visible area, depth tested
	    against each other and against the frame's 3D before them, and under the clip. False
	    when `camera` isn't a 3D camera, or outside a frame. A 3D call outside them draws
	    nothing; a frame starts in 2D, and one left in 3D ends there. A 2D call between them
	    lands in the world's x-y plane, as wgrender's did.
	**/
	public static inline function end3d():Void
		Raw.wgf_draw_end_3d();

	/**
	    Shapes in the world, unlit, their lines a pixel wide (wgrender's shape3d's): a line;
	    a cube, filled or its edges, `width` (x) by `height` (y) by `length` (z), centered on
	    (cx, cy, cz); a sphere; a grid of `slices` by `slices` squares `spacing` apart on the
	    x-z plane, centered on the origin; and a filled rectangle and a circle's outline,
	    centered on (cx, cy, cz), in their x-y plane turned by (rx, ry, rz) radians, as a
	    node's rotation turns it. A color with alpha below 255 is blended over what is
	    behind it, in the order drawn.
	**/
	public static inline function line3d(x0:Float, y0:Float, z0:Float, x1:Float, y1:Float, z1:Float, color:Int):Void
		Raw.wgf_draw_line_3d(x0, y0, z0, x1, y1, z1, color);

	/**
	    Shapes in the world, unlit, their lines a pixel wide (wgrender's shape3d's): a line;
	    a cube, filled or its edges, `width` (x) by `height` (y) by `length` (z), centered on
	    (cx, cy, cz); a sphere; a grid of `slices` by `slices` squares `spacing` apart on the
	    x-z plane, centered on the origin; and a filled rectangle and a circle's outline,
	    centered on (cx, cy, cz), in their x-y plane turned by (rx, ry, rz) radians, as a
	    node's rotation turns it. A color with alpha below 255 is blended over what is
	    behind it, in the order drawn.
	**/
	public static inline function cube(cx:Float, cy:Float, cz:Float, width:Float, height:Float, length:Float, color:Int):Void
		Raw.wgf_draw_cube(cx, cy, cz, width, height, length, color);

	/**
	    Shapes in the world, unlit, their lines a pixel wide (wgrender's shape3d's): a line;
	    a cube, filled or its edges, `width` (x) by `height` (y) by `length` (z), centered on
	    (cx, cy, cz); a sphere; a grid of `slices` by `slices` squares `spacing` apart on the
	    x-z plane, centered on the origin; and a filled rectangle and a circle's outline,
	    centered on (cx, cy, cz), in their x-y plane turned by (rx, ry, rz) radians, as a
	    node's rotation turns it. A color with alpha below 255 is blended over what is
	    behind it, in the order drawn.
	**/
	public static inline function cubeWires(cx:Float, cy:Float, cz:Float, width:Float, height:Float, length:Float, color:Int):Void
		Raw.wgf_draw_cube_wires(cx, cy, cz, width, height, length, color);

	/**
	    Shapes in the world, unlit, their lines a pixel wide (wgrender's shape3d's): a line;
	    a cube, filled or its edges, `width` (x) by `height` (y) by `length` (z), centered on
	    (cx, cy, cz); a sphere; a grid of `slices` by `slices` squares `spacing` apart on the
	    x-z plane, centered on the origin; and a filled rectangle and a circle's outline,
	    centered on (cx, cy, cz), in their x-y plane turned by (rx, ry, rz) radians, as a
	    node's rotation turns it. A color with alpha below 255 is blended over what is
	    behind it, in the order drawn.
	**/
	public static inline function sphere(cx:Float, cy:Float, cz:Float, radius:Float, color:Int):Void
		Raw.wgf_draw_sphere(cx, cy, cz, radius, color);

	/**
	    Shapes in the world, unlit, their lines a pixel wide (wgrender's shape3d's): a line;
	    a cube, filled or its edges, `width` (x) by `height` (y) by `length` (z), centered on
	    (cx, cy, cz); a sphere; a grid of `slices` by `slices` squares `spacing` apart on the
	    x-z plane, centered on the origin; and a filled rectangle and a circle's outline,
	    centered on (cx, cy, cz), in their x-y plane turned by (rx, ry, rz) radians, as a
	    node's rotation turns it. A color with alpha below 255 is blended over what is
	    behind it, in the order drawn.
	**/
	public static inline function grid(slices:Int, spacing:Float, color:Int):Void
		Raw.wgf_draw_grid(slices, spacing, color);

	/**
	    Shapes in the world, unlit, their lines a pixel wide (wgrender's shape3d's): a line;
	    a cube, filled or its edges, `width` (x) by `height` (y) by `length` (z), centered on
	    (cx, cy, cz); a sphere; a grid of `slices` by `slices` squares `spacing` apart on the
	    x-z plane, centered on the origin; and a filled rectangle and a circle's outline,
	    centered on (cx, cy, cz), in their x-y plane turned by (rx, ry, rz) radians, as a
	    node's rotation turns it. A color with alpha below 255 is blended over what is
	    behind it, in the order drawn.
	**/
	public static inline function rectangle3d(cx:Float, cy:Float, cz:Float, width:Float, height:Float, rx:Float, ry:Float, rz:Float, color:Int):Void
		Raw.wgf_draw_rectangle_3d(cx, cy, cz, width, height, rx, ry, rz, color);

	/**
	    Shapes in the world, unlit, their lines a pixel wide (wgrender's shape3d's): a line;
	    a cube, filled or its edges, `width` (x) by `height` (y) by `length` (z), centered on
	    (cx, cy, cz); a sphere; a grid of `slices` by `slices` squares `spacing` apart on the
	    x-z plane, centered on the origin; and a filled rectangle and a circle's outline,
	    centered on (cx, cy, cz), in their x-y plane turned by (rx, ry, rz) radians, as a
	    node's rotation turns it. A color with alpha below 255 is blended over what is
	    behind it, in the order drawn.
	**/
	public static inline function circle3d(cx:Float, cy:Float, cz:Float, radius:Float, rx:Float, ry:Float, rz:Float, color:Int):Void
		Raw.wgf_draw_circle_3d(cx, cy, cz, radius, rx, ry, rz, color);

	/**
	    Text in the world: a block centered on (x, y, z), facing the camera, its lines `size`
	    world units tall (1 for 0 or less), in `font` (0: the default font), depth tested
	    and not hiding what is drawn behind it after it. wgrender's wgr_text_draw_3d.
	**/
	public static inline function text3d(font:Font, text:String, x:Float, y:Float, z:Float, size:Float, color:Int):Void
		Raw.wgf_draw_text_3d(font, text, x, y, z, size, color);
}
