// Generated by tools/gen_binding.py from the public headers: edit the headers or the generator, not this.
package wgf;

import wgf.impl.Raw;

class Draw {
	/**
	    Immediate mode 2D: each call draws once, in the frame it is made in, in call order
	    with everything else drawn that frame, and keeps nothing. Logical pixels from the
	    frame's top-left, y down (wgf_render.h). A draw outside a frame draws nothing.

	    Outlines and lines have a thickness in logical pixels, centered on the line; one
	    of 0 or less is a hairline of one logical pixel. A polyline's corners are mitred,
	    and bevelled where a sharp corner's miter would reach past four thicknesses.
	**/
	public static inline function rectangle(x:Float, y:Float, width:Float, height:Float, color:Int):Void
		Raw.wgf_draw_rectangle(x, y, width, height, color);

	/**
	    Immediate mode 2D: each call draws once, in the frame it is made in, in call order
	    with everything else drawn that frame, and keeps nothing. Logical pixels from the
	    frame's top-left, y down (wgf_render.h). A draw outside a frame draws nothing.

	    Outlines and lines have a thickness in logical pixels, centered on the line; one
	    of 0 or less is a hairline of one logical pixel. A polyline's corners are mitred,
	    and bevelled where a sharp corner's miter would reach past four thicknesses.
	**/
	public static inline function rectangleLines(x:Float, y:Float, width:Float, height:Float, thickness:Float, color:Int):Void
		Raw.wgf_draw_rectangle_lines(x, y, width, height, thickness, color);

	/**
	    Immediate mode 2D: each call draws once, in the frame it is made in, in call order
	    with everything else drawn that frame, and keeps nothing. Logical pixels from the
	    frame's top-left, y down (wgf_render.h). A draw outside a frame draws nothing.

	    Outlines and lines have a thickness in logical pixels, centered on the line; one
	    of 0 or less is a hairline of one logical pixel. A polyline's corners are mitred,
	    and bevelled where a sharp corner's miter would reach past four thicknesses.
	**/
	public static inline function line(x0:Float, y0:Float, x1:Float, y1:Float, thickness:Float, color:Int):Void
		Raw.wgf_draw_line(x0, y0, x1, y1, thickness, color);

	/**
	    Circles are drawn with enough segments for their size on screen.
	**/
	public static inline function circle(center_x:Float, center_y:Float, radius:Float, color:Int):Void
		Raw.wgf_draw_circle(center_x, center_y, radius, color);

	/**
	    Circles are drawn with enough segments for their size on screen.
	**/
	public static inline function circleLines(center_x:Float, center_y:Float, radius:Float, thickness:Float, color:Int):Void
		Raw.wgf_draw_circle_lines(center_x, center_y, radius, thickness, color);

	/**
	    Circles are drawn with enough segments for their size on screen.
	**/
	public static inline function triangle(x0:Float, y0:Float, x1:Float, y1:Float, x2:Float, y2:Float, color:Int):Void
		Raw.wgf_draw_triangle(x0, y0, x1, y1, x2, y2, color);

	/**
	    Lines through `points`, x and y in turn (count floats: count / 2 points), the last
	    joined to the first when `closed`. False, drawing nothing, for an odd count, fewer
	    than 2 points, or NULL.
	**/
	public static inline function polyline(points:Array<Float>, closed:Bool, thickness:Float, color:Int):Bool
		return Raw.wgf_draw_polyline(points, closed, thickness, color);

	/**
	    The polygon through `points` filled, x and y in turn (count floats), convex or not,
	    in either winding, as long as its edges don't cross (one that crosses itself is
	    filled as the fan from its first point). False, drawing nothing, for an odd count,
	    fewer than 3 points, or NULL.
	**/
	public static inline function polygon(points:Array<Float>, color:Int):Bool
		return Raw.wgf_draw_polygon(points, color);

	/**
	    Text (UTF-8) in `font` (0: the default font) at `size` logical pixels (16 for 0 or
	    less), its top-left at (x, y). Newlines break lines.
	**/
	public static inline function text(font:Font, text:String, x:Float, y:Float, size:Float, color:Int):Void
		Raw.wgf_draw_text(font, text, x, y, size, color);

	/**
	    A texture into the rectangle (x, y, width, height), multiplied by `tint` (white
	    leaves it as it is). A width or height of 0 or less draws it at its own size.
	    Nothing while it is PENDING; the placeholder checker once it has FAILED.
	**/
	public static inline function texture(texture:Texture, x:Float, y:Float, width:Float, height:Float, tint:Int):Void
		Raw.wgf_draw_texture(texture, x, y, width, height, tint);

	/**
	    A region of a texture, in its pixels from the top-left (a source width or height of
	    0 or less: the whole texture), into the rectangle (x, y, width, height), as an icon
	    is cut from an atlas. A width or height of 0 or less draws it at the region's own
	    size. The placeholder fills the rectangle once the texture has FAILED.
	**/
	public static inline function textureRegion(texture:Texture, source_x:Float, source_y:Float, source_width:Float, source_height:Float, x:Float, y:Float, width:Float, height:Float, tint:Int):Void
		Raw.wgf_draw_texture_region(texture, source_x, source_y, source_width, source_height, x, y, width, height, tint);
}
