// Generated by tools/gen_binding.py from the public headers: edit the headers or the generator, not this.
package wgf;

import wgf.impl.Raw;

class Ecs {
	/**
	    Events waiting, and the oldest taken off the queue into `out`, three ints each -- the
	    event, the entity, the other entity (0 for none) -- as many whole events as fit in
	    `count` ints, returning how many ints it filled.
	**/
	public static inline function getEventCount():Int
		return Raw.wgf_ecs_get_event_count();

	/**
	    Events waiting, and the oldest taken off the queue into `out`, three ints each -- the
	    event, the entity, the other entity (0 for none) -- as many whole events as fit in
	    `count` ints, returning how many ints it filled.
	**/
	public static inline function takeEvents(out:Array<Int>):Int
		return Raw.wgf_ecs_take_events(out);

	/**
	    The live entities with the behavior `name`, oldest first, into `out`, as many as fit in
	    `count`, returning how many it filled; and how many there are, to size `out`.
	**/
	public static inline function findBehavior(name:String, out:Array<Entity>):Int
		return Raw.wgf_ecs_find_behavior(name, cast out);

	/**
	    The live entities with the behavior `name`, oldest first, into `out`, as many as fit in
	    `count`, returning how many it filled; and how many there are, to size `out`.
	**/
	public static inline function countBehavior(name:String):Int
		return Raw.wgf_ecs_count_behavior(name);

	/**
	    Every live entity destroyed, as wgf_entity_destroy would, oldest first.
	**/
	public static inline function clear():Void
		Raw.wgf_ecs_clear();

	/**
	    The world as a scene's text (wgf_scene.h's format): every live entity, oldest first,
	    with its transform and every component as it is now, so loading it as a scene and
	    instantiating it makes the same world again. libwgf's to keep: valid until the next
	    dump. "" when the ecs hasn't started (no entity was ever made).
	**/
	public static inline function dump():String
		return Raw.wgf_ecs_dump();
}
