// Generated by tools/gen_binding.py from the public headers: edit the headers or the generator, not this.
package wgf;

import wgf.impl.Raw;

/** Emitter2d's calls, on a Node: `var x:Emitter2d = handle` gives it them, and a Emitter2d is still a Node. **/
@:forward abstract Emitter2d(Node) from Node to Node {
	/**
	    An emitter that isn't emitting yet: rate 0, 256 particles at most, white squares of
	    4 units living a second, going nowhere. 0 when there is no room for another node.
	**/
	public static inline function create():Emitter2d
		return ((Raw.wgf_emitter2d_create() : Node) : Emitter2d);

	/**
	    Particles a second while emitting, spread evenly over the frames. Clamped to 0 or
	    more. False for a handle that isn't an emitter.
	**/
	public inline function setRate(per_second:Float):Bool
		return Raw.wgf_emitter2d_set_rate(this, per_second);

	/**
	    Particles a second while emitting, spread evenly over the frames. Clamped to 0 or
	    more. False for a handle that isn't an emitter.
	**/
	public inline function getRate():Float
		return Raw.wgf_emitter2d_get_rate(this);

	/**
	    Whether it emits at its rate (default true; with the rate at 0 nothing comes). Bursts
	    come either way. False for a handle that isn't an emitter.
	**/
	public inline function setEmitting(emitting:Bool):Bool
		return Raw.wgf_emitter2d_set_emitting(this, emitting);

	/**
	    Whether it emits at its rate (default true; with the rate at 0 nothing comes). Bursts
	    come either way. False for a handle that isn't an emitter.
	**/
	public inline function isEmitting():Bool
		return Raw.wgf_emitter2d_is_emitting(this);

	/**
	    `count` particles at once, where the emitter is now. Clamped to the room left. False
	    for a handle that isn't an emitter, or a count below 1.
	**/
	public inline function burst(count:Int):Bool
		return Raw.wgf_emitter2d_burst(this, count);

	/**
	    The most particles it keeps, 1 to 65536 (default 256); a birth past it is dropped.
	    Lowering it drops the oldest. Clamped. False for a handle that isn't an emitter.
	**/
	public inline function setCapacity(capacity:Int):Bool
		return Raw.wgf_emitter2d_set_capacity(this, capacity);

	/**
	    The most particles it keeps, 1 to 65536 (default 256); a birth past it is dropped.
	    Lowering it drops the oldest. Clamped. False for a handle that isn't an emitter.
	**/
	public inline function getCapacity():Int
		return Raw.wgf_emitter2d_get_capacity(this);

	/**
	    Particles alive now.
	**/
	public inline function getCount():Int
		return Raw.wgf_emitter2d_get_count(this);

	/**
	    How long each lives, in seconds, chosen between min and max at birth (swapped when
	    max is less). False for a handle that isn't an emitter, or a min of 0 or less.
	**/
	public inline function setLife(min:Float, max:Float):Bool
		return Raw.wgf_emitter2d_set_life(this, min, max);

	/**
	    How long each lives, in seconds, chosen between min and max at birth (swapped when
	    max is less). False for a handle that isn't an emitter, or a min of 0 or less.
	**/
	public inline function getLifeMin():Float
		return Raw.wgf_emitter2d_get_life_min(this);

	/**
	    How long each lives, in seconds, chosen between min and max at birth (swapped when
	    max is less). False for a handle that isn't an emitter, or a min of 0 or less.
	**/
	public inline function getLifeMax():Float
		return Raw.wgf_emitter2d_get_life_max(this);

	/**
	    The direction they leave in, radians in the canvas (0 along +x, a quarter turn along
	    +y, down the screen), turned by the emitter's own world rotation, give or take
	    `spread` radians either side (TAU: every way); and their speed, in units a second,
	    between min and max. False for a handle that isn't an emitter, or a spread or speed
	    below 0.
	**/
	public inline function setDirection(angle:Float, spread:Float):Bool
		return Raw.wgf_emitter2d_set_direction(this, angle, spread);

	/**
	    The direction they leave in, radians in the canvas (0 along +x, a quarter turn along
	    +y, down the screen), turned by the emitter's own world rotation, give or take
	    `spread` radians either side (TAU: every way); and their speed, in units a second,
	    between min and max. False for a handle that isn't an emitter, or a spread or speed
	    below 0.
	**/
	public inline function getDirection():Float
		return Raw.wgf_emitter2d_get_direction(this);

	/**
	    The direction they leave in, radians in the canvas (0 along +x, a quarter turn along
	    +y, down the screen), turned by the emitter's own world rotation, give or take
	    `spread` radians either side (TAU: every way); and their speed, in units a second,
	    between min and max. False for a handle that isn't an emitter, or a spread or speed
	    below 0.
	**/
	public inline function getSpread():Float
		return Raw.wgf_emitter2d_get_spread(this);

	/**
	    The direction they leave in, radians in the canvas (0 along +x, a quarter turn along
	    +y, down the screen), turned by the emitter's own world rotation, give or take
	    `spread` radians either side (TAU: every way); and their speed, in units a second,
	    between min and max. False for a handle that isn't an emitter, or a spread or speed
	    below 0.
	**/
	public inline function setSpeed(min:Float, max:Float):Bool
		return Raw.wgf_emitter2d_set_speed(this, min, max);

	/**
	    The direction they leave in, radians in the canvas (0 along +x, a quarter turn along
	    +y, down the screen), turned by the emitter's own world rotation, give or take
	    `spread` radians either side (TAU: every way); and their speed, in units a second,
	    between min and max. False for a handle that isn't an emitter, or a spread or speed
	    below 0.
	**/
	public inline function getSpeedMin():Float
		return Raw.wgf_emitter2d_get_speed_min(this);

	/**
	    The direction they leave in, radians in the canvas (0 along +x, a quarter turn along
	    +y, down the screen), turned by the emitter's own world rotation, give or take
	    `spread` radians either side (TAU: every way); and their speed, in units a second,
	    between min and max. False for a handle that isn't an emitter, or a spread or speed
	    below 0.
	**/
	public inline function getSpeedMax():Float
		return Raw.wgf_emitter2d_get_speed_max(this);

	/**
	    Born anywhere within `radius` of the emitter (0, the default: at it). False for a
	    handle that isn't an emitter, or a radius below 0.
	**/
	public inline function setRadius(radius:Float):Bool
		return Raw.wgf_emitter2d_set_radius(this, radius);

	/**
	    Born anywhere within `radius` of the emitter (0, the default: at it). False for a
	    handle that isn't an emitter, or a radius below 0.
	**/
	public inline function getRadius():Float
		return Raw.wgf_emitter2d_get_radius(this);

	/**
	    Acceleration in units a second squared (default 0, 0), and drag, the part of its
	    velocity a particle loses each second (0, the default, to 1: none to all). Drag is
	    clamped to 0..1. False for a handle that isn't an emitter.
	**/
	public inline function setGravity(x:Float, y:Float):Bool
		return Raw.wgf_emitter2d_set_gravity(this, x, y);

	/**
	    Acceleration in units a second squared (default 0, 0), and drag, the part of its
	    velocity a particle loses each second (0, the default, to 1: none to all). Drag is
	    clamped to 0..1. False for a handle that isn't an emitter.
	**/
	public inline function getGravity(?into:wgf.Vec2):wgf.Vec2
		return Raw.wgf_emitter2d_get_gravity(this, into);

	/**
	    Acceleration in units a second squared (default 0, 0), and drag, the part of its
	    velocity a particle loses each second (0, the default, to 1: none to all). Drag is
	    clamped to 0..1. False for a handle that isn't an emitter.
	**/
	public inline function setDrag(drag:Float):Bool
		return Raw.wgf_emitter2d_set_drag(this, drag);

	/**
	    Acceleration in units a second squared (default 0, 0), and drag, the part of its
	    velocity a particle loses each second (0, the default, to 1: none to all). Drag is
	    clamped to 0..1. False for a handle that isn't an emitter.
	**/
	public inline function getDrag():Float
		return Raw.wgf_emitter2d_get_drag(this);

	/**
	    Size in units, and color, at birth and at death, each running between them over the
	    particle's life. False for a handle that isn't an emitter, or a size below 0.
	**/
	public inline function setSize(start:Float, end:Float):Bool
		return Raw.wgf_emitter2d_set_size(this, start, end);

	/**
	    Size in units, and color, at birth and at death, each running between them over the
	    particle's life. False for a handle that isn't an emitter, or a size below 0.
	**/
	public inline function getSizeStart():Float
		return Raw.wgf_emitter2d_get_size_start(this);

	/**
	    Size in units, and color, at birth and at death, each running between them over the
	    particle's life. False for a handle that isn't an emitter, or a size below 0.
	**/
	public inline function getSizeEnd():Float
		return Raw.wgf_emitter2d_get_size_end(this);

	/**
	    Size in units, and color, at birth and at death, each running between them over the
	    particle's life. False for a handle that isn't an emitter, or a size below 0.
	**/
	public inline function setColor(start:Int, end:Int):Bool
		return Raw.wgf_emitter2d_set_color(this, start, end);

	/**
	    Size in units, and color, at birth and at death, each running between them over the
	    particle's life. False for a handle that isn't an emitter, or a size below 0.
	**/
	public inline function getColorStart():Int
		return Raw.wgf_emitter2d_get_color_start(this);

	/**
	    Size in units, and color, at birth and at death, each running between them over the
	    particle's life. False for a handle that isn't an emitter, or a size below 0.
	**/
	public inline function getColorEnd():Int
		return Raw.wgf_emitter2d_get_color_end(this);

	/**
	    A streak instead of a square: each particle drawn as a line from where it is back
	    along its velocity for `seconds` of it, its size the line's thickness; 0 (the
	    default) draws squares. Clamped to 0 or more. False for a handle that isn't an
	    emitter.
	**/
	public inline function setStretch(seconds:Float):Bool
		return Raw.wgf_emitter2d_set_stretch(this, seconds);

	/**
	    A streak instead of a square: each particle drawn as a line from where it is back
	    along its velocity for `seconds` of it, its size the line's thickness; 0 (the
	    default) draws squares. Clamped to 0 or more. False for a handle that isn't an
	    emitter.
	**/
	public inline function getStretch():Float
		return Raw.wgf_emitter2d_get_stretch(this);

	/**
	    Every particle gone at once; it keeps emitting as it was. False for a handle that
	    isn't an emitter.
	**/
	public inline function clear():Bool
		return Raw.wgf_emitter2d_clear(this);
}
