// Generated by tools/gen_binding.py from the public headers: edit the headers or the generator, not this.
package wgf;

import wgf.impl.Raw;

/** A handle of kind wgf_font_t (gfx/include/wgf_font.h): 0 is none. **/
abstract Font(Int) from Int to Int to wgf.Handle {
	/** Whether this is no handle (0); right on every target, where `== null` is not. **/
	public inline function isNone():Bool
		return this == 0;

	/**
	    A font from a .ttf or .otf file under fs's root. 0 only when there is no room
	    for another font; one that can't be loaded FAILED. A font loaded before, and
	    released since, comes back READY at once.
	**/
	public static inline function create(path:String):Font
		return Raw.wgf_font_create(path);

	/**
	    The font that font 0 means. It holds a reference to `font`; 0 goes back to the
	    built-in font. For text beyond ASCII, set a font that has it. False for a handle
	    that isn't a font.
	**/
	public inline function setDefault():Bool
		return Raw.wgf_font_set_default(this);

	/**
	    The font that font 0 means. It holds a reference to `font`; 0 goes back to the
	    built-in font. For text beyond ASCII, set a font that has it. False for a handle
	    that isn't a font.
	**/
	public static inline function getDefault():Font
		return Raw.wgf_font_get_default();

	/**
	    How much room `text` (UTF-8) takes at `size` logical pixels (16 for 0 or less),
	    measured at the frame's pixel density as it is drawn: the widest line, and the
	    lines' height together. Newlines break lines; nothing wraps. A line keeps its
	    spaces, so " " measures a space's advance. 0, 0 for empty text, or before gfx is
	    set up.
	**/
	public inline function measure(text:String, size:Float, ?into:wgf.Vec2):wgf.Vec2
		return Raw.wgf_font_measure(this, text, size, into);
}
