// Generated by tools/gen_binding.py from the public headers: edit the headers or the generator, not this.
package wgf;

enum abstract FsTaskStatus(Int) from Int to Int {
	var NONE = 0;
	var PENDING = 1;
	var DONE = 2;
	var NOT_FOUND = 3;
	var FAILED = 4;
}
