// Generated by tools/gen_binding.py from the public headers: edit the headers or the generator, not this.
package wgf;

import wgf.impl.Raw;

/** A handle of kind wgf_fs_task_t (core/include/wgf_fs.h): 0 is none. **/
abstract FsTask(Int) from Int to Int to wgf.Handle {
	/** Whether this is no handle (0); right on every target, where `== null` is not. **/
	public inline function isNone():Bool
		return this == 0;

	/**
	    Tasks. A getter answers NONE, "", NULL, or 0 for a handle that isn't a task.
	**/
	public inline function getStatus():FsTaskStatus
		return Raw.wgf_fs_task_get_status(this);

	/**
	    Tasks. A getter answers NONE, "", NULL, or 0 for a handle that isn't a task.
	**/
	public inline function getPath():String
		return Raw.wgf_fs_task_get_path(this);

	/**
	    A DONE read's bytes, NUL-terminated so they also read as text, valid until the
	    task is destroyed. Any other task: NULL, 0, and "".
	**/
	public inline function getData():haxe.io.Bytes
		return Raw.wgf_fs_task_get_data(this);

	/**
	    A DONE read's bytes, NUL-terminated so they also read as text, valid until the
	    task is destroyed. Any other task: NULL, 0, and "".
	**/
	public inline function getSize():Int
		return Raw.wgf_fs_task_get_size(this);

	/**
	    A DONE read's bytes, NUL-terminated so they also read as text, valid until the
	    task is destroyed. Any other task: NULL, 0, and "".
	**/
	public inline function getText():String
		return Raw.wgf_fs_task_get_text(this);

	/**
	    False for a handle that isn't a task.
	**/
	public inline function destroy():Bool
		return Raw.wgf_fs_task_destroy(this);
}
