// Generated by tools/gen_binding.py from the public headers: edit the headers or the generator, not this.
package wgf;

/**
    Buttons by where they are on an Xbox-style pad, not by what they're labeled.
**/
enum abstract GamepadButton(Int) from Int to Int {
	var SOUTH = 0;
	var EAST = 1;
	var WEST = 2;
	var NORTH = 3;
	var LEFT_BUMPER = 4;
	var RIGHT_BUMPER = 5;
	var LEFT_TRIGGER = 6;
	var RIGHT_TRIGGER = 7;
	var BACK = 8;
	var START = 9;
	var GUIDE = 10;
	var LEFT_STICK = 11;
	var RIGHT_STICK = 12;
	var DPAD_UP = 13;
	var DPAD_DOWN = 14;
	var DPAD_LEFT = 15;
	var DPAD_RIGHT = 16;
}
