// Generated by tools/gen_binding.py from the public headers: edit the headers or the generator, not this.
package wgf;

enum abstract GamepadStick(Int) from Int to Int {
	var LEFT = 0;
	var RIGHT = 1;
}
