// Generated by tools/gen_binding.py from the public headers: edit the headers or the generator, not this.
package wgf;

/**
    Every axis of a pad, one number each: the sticks' as get_stick gives them (-1 to 1, y
    down, past the dead zone) and the triggers' (0 to 1). What input actions bind
    (wgf_action.h), and the names an autopilot's `pad axis` lines use.
**/
enum abstract GamepadAxis(Int) from Int to Int {
	var LEFT_X = 0;
	var LEFT_Y = 1;
	var RIGHT_X = 2;
	var RIGHT_Y = 3;
	var LEFT_TRIGGER = 4;
	var RIGHT_TRIGGER = 5;
}
