// Generated by tools/gen_binding.py from the public headers: edit the headers or the generator, not this.
package wgf;

import wgf.impl.Raw;

/** A handle of kind wgf_handle_t (core/include/wgf_handle.h): 0 is none. **/
abstract Handle(Int) from Int to Int {
	/** Whether this is no handle (0); right on every target, where `== null` is not. **/
	public inline function isNone():Bool
		return this == 0;

	/**
	    The kind of thing `handle` refers to, as "<layer>.<type>" ("gfx.texture"); ""
	    for 0 or a number no kind has. Read from the handle alone: a handle to
	    something already destroyed still names its kind.
	**/
	public inline function getKindName():String
		return Raw.wgf_handle_get_kind_name(this);
}
