// Generated by tools/gen_binding.py from the public headers: edit the headers or the generator, not this.
package wgf;

import wgf.impl.Raw;

class Input {
	/**
	    The characters typed since the previous tick or frame, in order, as one UTF-8
	    string (a character can be several bytes): what a text field appends. They come
	    after the keyboard layout and any input method -- Shift and A give "A", a held
	    key repeats -- and Backspace, Enter, and the arrows type none (read them as
	    keys). "" when nothing was typed. Reading doesn't use them up: they are there
	    until the next tick or frame.
	**/
	public static inline function getChars():String
		return Raw.wgf_input_get_chars();

	/**
	    Whether game controls (camera drags, selection, hotkeys) should leave the pointer
	    or the keyboard alone because a UI has it. Advisory: input keeps reporting
	    everything; game code checks these first.

	    Each is captured while the game's UI says so, and the say is sticky: libwgf's UI
	    (wgf_ui.h) sets both from its own hit testing and focus every frame it is drawn, and
	    lets them go in a frame it isn't.
	**/
	public static inline function setPointerCaptured(captured:Bool):Void
		Raw.wgf_input_set_pointer_captured(captured);

	/**
	    Whether game controls (camera drags, selection, hotkeys) should leave the pointer
	    or the keyboard alone because a UI has it. Advisory: input keeps reporting
	    everything; game code checks these first.

	    Each is captured while the game's UI says so, and the say is sticky: libwgf's UI
	    (wgf_ui.h) sets both from its own hit testing and focus every frame it is drawn, and
	    lets them go in a frame it isn't.
	**/
	public static inline function isPointerCaptured():Bool
		return Raw.wgf_input_is_pointer_captured();

	/**
	    Whether game controls (camera drags, selection, hotkeys) should leave the pointer
	    or the keyboard alone because a UI has it. Advisory: input keeps reporting
	    everything; game code checks these first.

	    Each is captured while the game's UI says so, and the say is sticky: libwgf's UI
	    (wgf_ui.h) sets both from its own hit testing and focus every frame it is drawn, and
	    lets them go in a frame it isn't.
	**/
	public static inline function setKeyboardCaptured(captured:Bool):Void
		Raw.wgf_input_set_keyboard_captured(captured);

	/**
	    Whether game controls (camera drags, selection, hotkeys) should leave the pointer
	    or the keyboard alone because a UI has it. Advisory: input keeps reporting
	    everything; game code checks these first.

	    Each is captured while the game's UI says so, and the say is sticky: libwgf's UI
	    (wgf_ui.h) sets both from its own hit testing and focus every frame it is drawn, and
	    lets them go in a frame it isn't.
	**/
	public static inline function isKeyboardCaptured():Bool
		return Raw.wgf_input_is_keyboard_captured();
}
