// Generated by tools/gen_binding.py from the public headers: edit the headers or the generator, not this.
package wgf;

/**
    Where a key or button is, as read inside a tick or a frame.
**/
enum abstract InputState(Int) from Int to Int {
	var UP = 0;
	var PRESSED = 1;
	var DOWN = 2;
	var RELEASED = 3;
}
