// Generated by tools/gen_binding.py from the public headers: edit the headers or the generator, not this.
package wgf;

import wgf.impl.Raw;

class Keyboard {
	/**
	    Where `key` is: UP, PRESSED (went down since the previous tick or frame), DOWN,
	    or RELEASED. A key the keyboard doesn't have is UP. A key pressed and released
	    between two reads is PRESSED for one, so no tap is missed.
	**/
	public static inline function getState(key:KeyboardKey):InputState
		return Raw.wgf_keyboard_get_state(key);

	/**
	    PRESSED or DOWN.
	**/
	public static inline function isDown(key:KeyboardKey):Bool
		return Raw.wgf_keyboard_is_down(key);

	/**
	    Went down since the previous tick or frame; held keys repeating don't count.
	**/
	public static inline function isPressed(key:KeyboardKey):Bool
		return Raw.wgf_keyboard_is_pressed(key);

	/**
	    Went up since the previous tick or frame.
	**/
	public static inline function isReleased(key:KeyboardKey):Bool
		return Raw.wgf_keyboard_is_released(key);
}
