// Generated by tools/gen_binding.py from the public headers: edit the headers or the generator, not this.
package wgf;

import wgf.impl.Raw;

/** Light's calls, on a Actor: `var x:Light = handle` gives it them, and a Light is still a Actor; it starts as 0, none, as a Actor does. **/
@:forward abstract Light(Actor) from Actor from Int to Actor {
	/**
	    A white light of intensity 1, no range limit, a spot's cone pi/6 to pi/4. 0 when
	    `type` isn't a type, or there is no room for another actor.
	**/
	public static inline function create(type:LightType):Light
		return ((Raw.wgf_light_create(type) : Actor) : Light);

	/**
	    A white light of intensity 1, no range limit, a spot's cone pi/6 to pi/4. 0 when
	    `type` isn't a type, or there is no room for another actor.
	**/
	public inline function getType():LightType
		return Raw.wgf_light_get_type(this);

	/**
	    Its color (default white); alpha is ignored.
	**/
	public inline function setColor(color:Int):Bool
		return Raw.wgf_light_set_color(this, color);

	/**
	    Its color (default white); alpha is ignored.
	**/
	public inline function getColor():Int
		return Raw.wgf_light_get_color(this);

	/**
	    How strong it is, its color times this (default 1, clamped to 0 or more).
	**/
	public inline function setIntensity(intensity:Float):Bool
		return Raw.wgf_light_set_intensity(this, intensity);

	/**
	    How strong it is, its color times this (default 1, clamped to 0 or more).
	**/
	public inline function getIntensity():Float
		return Raw.wgf_light_get_intensity(this);

	/**
	    How far a point or spot light reaches, in units: it fades to nothing there (default
	    0, unlimited; below 0 is clamped to 0).
	**/
	public inline function setRange(range:Float):Bool
		return Raw.wgf_light_set_range(this, range);

	/**
	    How far a point or spot light reaches, in units: it fades to nothing there (default
	    0, unlimited; below 0 is clamped to 0).
	**/
	public inline function getRange():Float
		return Raw.wgf_light_get_range(this);

	/**
	    A spot light's cone, radians from its direction: full inside `inner`, nothing past
	    `outer`, smooth between (glTF's innerConeAngle and outerConeAngle). outer is clamped
	    to 0..pi/2, inner to 0..outer.
	**/
	public inline function setSpotCone(inner:Float, outer:Float):Bool
		return Raw.wgf_light_set_spot_cone(this, inner, outer);

	/**
	    A spot light's cone, radians from its direction: full inside `inner`, nothing past
	    `outer`, smooth between (glTF's innerConeAngle and outerConeAngle). outer is clamped
	    to 0..pi/2, inner to 0..outer.
	**/
	public inline function getSpotInnerAngle():Float
		return Raw.wgf_light_get_spot_inner_angle(this);

	/**
	    A spot light's cone, radians from its direction: full inside `inner`, nothing past
	    `outer`, smooth between (glTF's innerConeAngle and outerConeAngle). outer is clamped
	    to 0..pi/2, inner to 0..outer.
	**/
	public inline function getSpotOuterAngle():Float
		return Raw.wgf_light_get_spot_outer_angle(this);
}
