// Generated by tools/gen_binding.py from the public headers: edit the headers or the generator, not this.
package wgf;

/**
    Logging to stderr (the browser console on the web). A message below the
    current level is dropped; the level starts at INFO. Text is UTF-8.

    The exported calls take finished text, so a binding formats in its own
    language and passes one string. C code formats with the wgf_log_<level> macros,
    or with wgf_log_debug and the rest from wgf_log.h.
**/
enum abstract LogLevel(Int) from Int to Int {
	var TRACE = 0;
	var DEBUG = 1;
	var INFO = 2;
	var WARN = 3;
	var ERROR = 4;
	var FATAL = 5;
}
