// Generated by tools/gen_binding.py from the public headers: edit the headers or the generator, not this.
package wgf;

import wgf.impl.Raw;

/** A handle of kind wgf_material_t (gfx/include/wgf_material.h): 0 is none. **/
abstract Material(Int) from Int to Int to wgf.Handle {
	/** Whether this is no handle (0); right on every target, where `== null` is not. **/
	public inline function isNone():Bool
		return this == 0;

	/**
	    A material with glTF's defaults. 0 when `shading` isn't one (logged), or there is no
	    room for another material.
	**/
	public static inline function create(shading:MaterialShading):Material
		return Raw.wgf_material_create(shading);

	/**
	    False when `shading` isn't one.
	**/
	public inline function setShading(shading:MaterialShading):Bool
		return Raw.wgf_material_set_shading(this, shading);

	/**
	    False when `shading` isn't one.
	**/
	public inline function getShading():MaterialShading
		return Raw.wgf_material_get_shading(this);

	/**
	    How alpha is used, and the cutoff MASK draws from (default OPAQUE, 0.5; a cutoff below
	    0 is clamped to 0). False when `mode` isn't one.
	**/
	public inline function setAlphaMode(mode:AlphaMode, cutoff:Float):Bool
		return Raw.wgf_material_set_alpha_mode(this, mode, cutoff);

	/**
	    How alpha is used, and the cutoff MASK draws from (default OPAQUE, 0.5; a cutoff below
	    0 is clamped to 0). False when `mode` isn't one.
	**/
	public inline function getAlphaMode():AlphaMode
		return Raw.wgf_material_get_alpha_mode(this);

	/**
	    How alpha is used, and the cutoff MASK draws from (default OPAQUE, 0.5; a cutoff below
	    0 is clamped to 0). False when `mode` isn't one.
	**/
	public inline function getAlphaCutoff():Float
		return Raw.wgf_material_get_alpha_cutoff(this);

	/**
	    A double-sided surface isn't culled from behind; its back faces are lit from their
	    side (default single sided).
	**/
	public inline function setDoubleSided(double_sided:Bool):Bool
		return Raw.wgf_material_set_double_sided(this, double_sided);

	/**
	    A double-sided surface isn't culled from behind; its back faces are lit from their
	    side (default single sided).
	**/
	public inline function isDoubleSided():Bool
		return Raw.wgf_material_is_double_sided(this);

	/**
	    The parameters, by name (the table above). set_int refuses a texture coordinate set
	    other than 0 or 1. set_color takes an sRGB color for a vec3 or vec4 parameter,
	    stored linear, its alpha as it is (read back with get_vec3 or get_vec4).
	**/
	public inline function setInt(name:String, value:Int):Bool
		return Raw.wgf_material_set_int(this, name, value);

	/**
	    The parameters, by name (the table above). set_int refuses a texture coordinate set
	    other than 0 or 1. set_color takes an sRGB color for a vec3 or vec4 parameter,
	    stored linear, its alpha as it is (read back with get_vec3 or get_vec4).
	**/
	public inline function getInt(name:String):Int
		return Raw.wgf_material_get_int(this, name);

	/**
	    The parameters, by name (the table above). set_int refuses a texture coordinate set
	    other than 0 or 1. set_color takes an sRGB color for a vec3 or vec4 parameter,
	    stored linear, its alpha as it is (read back with get_vec3 or get_vec4).
	**/
	public inline function setFloat(name:String, value:Float):Bool
		return Raw.wgf_material_set_float(this, name, value);

	/**
	    The parameters, by name (the table above). set_int refuses a texture coordinate set
	    other than 0 or 1. set_color takes an sRGB color for a vec3 or vec4 parameter,
	    stored linear, its alpha as it is (read back with get_vec3 or get_vec4).
	**/
	public inline function getFloat(name:String):Float
		return Raw.wgf_material_get_float(this, name);

	/**
	    The parameters, by name (the table above). set_int refuses a texture coordinate set
	    other than 0 or 1. set_color takes an sRGB color for a vec3 or vec4 parameter,
	    stored linear, its alpha as it is (read back with get_vec3 or get_vec4).
	**/
	public inline function setVec2(name:String, x:Float, y:Float):Bool
		return Raw.wgf_material_set_vec2(this, name, x, y);

	/**
	    The parameters, by name (the table above). set_int refuses a texture coordinate set
	    other than 0 or 1. set_color takes an sRGB color for a vec3 or vec4 parameter,
	    stored linear, its alpha as it is (read back with get_vec3 or get_vec4).
	**/
	public inline function getVec2(name:String, ?into:wgf.Vec2):wgf.Vec2
		return Raw.wgf_material_get_vec2(this, name, into);

	/**
	    The parameters, by name (the table above). set_int refuses a texture coordinate set
	    other than 0 or 1. set_color takes an sRGB color for a vec3 or vec4 parameter,
	    stored linear, its alpha as it is (read back with get_vec3 or get_vec4).
	**/
	public inline function setVec3(name:String, x:Float, y:Float, z:Float):Bool
		return Raw.wgf_material_set_vec3(this, name, x, y, z);

	/**
	    The parameters, by name (the table above). set_int refuses a texture coordinate set
	    other than 0 or 1. set_color takes an sRGB color for a vec3 or vec4 parameter,
	    stored linear, its alpha as it is (read back with get_vec3 or get_vec4).
	**/
	public inline function getVec3(name:String, ?into:wgf.Vec3):wgf.Vec3
		return Raw.wgf_material_get_vec3(this, name, into);

	/**
	    The parameters, by name (the table above). set_int refuses a texture coordinate set
	    other than 0 or 1. set_color takes an sRGB color for a vec3 or vec4 parameter,
	    stored linear, its alpha as it is (read back with get_vec3 or get_vec4).
	**/
	public inline function setVec4(name:String, x:Float, y:Float, z:Float, w:Float):Bool
		return Raw.wgf_material_set_vec4(this, name, x, y, z, w);

	/**
	    The parameters, by name (the table above). set_int refuses a texture coordinate set
	    other than 0 or 1. set_color takes an sRGB color for a vec3 or vec4 parameter,
	    stored linear, its alpha as it is (read back with get_vec3 or get_vec4).
	**/
	public inline function getVec4(name:String, ?into:wgf.Vec4):wgf.Vec4
		return Raw.wgf_material_get_vec4(this, name, into);

	/**
	    The parameters, by name (the table above). set_int refuses a texture coordinate set
	    other than 0 or 1. set_color takes an sRGB color for a vec3 or vec4 parameter,
	    stored linear, its alpha as it is (read back with get_vec3 or get_vec4).
	**/
	public inline function setColor(name:String, color:Int):Bool
		return Raw.wgf_material_set_color(this, name, color);

	/**
	    A texture parameter: the material holds its own reference to the texture; 0 clears
	    it. False when `texture` isn't a texture.
	**/
	public inline function setTexture(name:String, texture:Texture):Bool
		return Raw.wgf_material_set_texture(this, name, texture);

	/**
	    A texture parameter: the material holds its own reference to the texture; 0 clears
	    it. False when `texture` isn't a texture.
	**/
	public inline function getTexture(name:String):Texture
		return Raw.wgf_material_get_texture(this, name);

	/**
	    How texture parameter `name` is sampled (default repeat, linear). False for a wrap or
	    filter that isn't one.
	**/
	public inline function setTextureSampling(name:String, wrap_u:TextureWrap, wrap_v:TextureWrap, filter:TextureFilter):Bool
		return Raw.wgf_material_set_texture_sampling(this, name, wrap_u, wrap_v, filter);

	/**
	    How texture parameter `name` is sampled (default repeat, linear). False for a wrap or
	    filter that isn't one.
	**/
	public inline function getTextureWrapU(name:String):TextureWrap
		return Raw.wgf_material_get_texture_wrap_u(this, name);

	/**
	    How texture parameter `name` is sampled (default repeat, linear). False for a wrap or
	    filter that isn't one.
	**/
	public inline function getTextureWrapV(name:String):TextureWrap
		return Raw.wgf_material_get_texture_wrap_v(this, name);

	/**
	    How texture parameter `name` is sampled (default repeat, linear). False for a wrap or
	    filter that isn't one.
	**/
	public inline function getTextureFilter(name:String):TextureFilter
		return Raw.wgf_material_get_texture_filter(this, name);
}
