// Generated by tools/gen_binding.py from the public headers: edit the headers or the generator, not this.
package wgf;

enum abstract MaterialShading(Int) from Int to Int {
	var PBR = 0;
	var UNLIT = 1;
}
