// Generated by tools/gen_binding.py from the public headers: edit the headers or the generator, not this.
package wgf;

import wgf.impl.Raw;

/** A handle of kind wgf_mesh_t (gfx/include/wgf_mesh.h): 0 is none. **/
abstract Mesh(Int) from Int to Int to wgf.Handle {
	/** Whether this is no handle (0); right on every target, where `== null` is not. **/
	public inline function isNone():Bool
		return this == 0;

	/** Whether this refers to something alive: false for none, and for what was destroyed or released (wgf_handle_is_alive). Ask it first where a handle may be dead. **/
	public inline function isAlive():Bool
		return (this : Handle).isAlive();

	public static inline function createPlane(width:Float, length:Float, subdivisions:Int):Mesh
		return Raw.wgf_mesh_create_plane(width, length, subdivisions);

	public static inline function createCube(width:Float, height:Float, length:Float):Mesh
		return Raw.wgf_mesh_create_cube(width, height, length);

	public static inline function createSphere(radius:Float, rings:Int, segments:Int):Mesh
		return Raw.wgf_mesh_create_sphere(radius, rings, segments);

	public static inline function createCylinder(radius:Float, height:Float, segments:Int):Mesh
		return Raw.wgf_mesh_create_cylinder(radius, height, segments);

	public static inline function createCone(radius:Float, height:Float, segments:Int):Mesh
		return Raw.wgf_mesh_create_cone(radius, height, segments);

	public static inline function createCapsule(radius:Float, height:Float, rings:Int, segments:Int):Mesh
		return Raw.wgf_mesh_create_capsule(radius, height, rings, segments);

	public static inline function createTorus(radius:Float, thickness:Float, rings:Int, segments:Int):Mesh
		return Raw.wgf_mesh_create_torus(radius, thickness, rings, segments);

	/**
	    The mesh's materials, one a slot (wgf_material.h); a generated mesh has one. The
	    handle is borrowed: valid while the mesh is, and changing it changes every model
	    drawing the mesh with it. 0 for a slot it hasn't.
	**/
	public inline function getMaterialCount():Int
		return Raw.wgf_mesh_get_material_count(this);

	/**
	    The mesh's materials, one a slot (wgf_material.h); a generated mesh has one. The
	    handle is borrowed: valid while the mesh is, and changing it changes every model
	    drawing the mesh with it. 0 for a slot it hasn't.
	**/
	public inline function getMaterial(slot:Int):Material
		return Raw.wgf_mesh_get_material(this, slot);
}
