// Generated by tools/gen_binding.py from the public headers: edit the headers or the generator, not this.
package wgf;

import wgf.impl.Raw;

/** A handle of kind wgf_mesh_t (gfx/include/wgf_mesh.h): 0 is none. **/
abstract Mesh(Int) from Int to Int to wgf.Handle {
	/** Whether this is no handle (0); right on every target, where `== null` is not. **/
	public inline function isNone():Bool
		return this == 0;

	/** Whether this refers to something alive: false for none, and for what was destroyed or released (wgf_handle_is_alive). Ask it first where a handle may be dead. **/
	public inline function isAlive():Bool
		return (this : Handle).isAlive();

	public static inline function createPlane(width:Float, length:Float, subdivisions:Int):Mesh
		return Raw.wgf_mesh_create_plane(width, length, subdivisions);

	public static inline function createCube(width:Float, height:Float, length:Float):Mesh
		return Raw.wgf_mesh_create_cube(width, height, length);

	public static inline function createSphere(radius:Float, rings:Int, segments:Int):Mesh
		return Raw.wgf_mesh_create_sphere(radius, rings, segments);

	public static inline function createCylinder(radius:Float, height:Float, segments:Int):Mesh
		return Raw.wgf_mesh_create_cylinder(radius, height, segments);

	public static inline function createCone(radius:Float, height:Float, segments:Int):Mesh
		return Raw.wgf_mesh_create_cone(radius, height, segments);

	public static inline function createCapsule(radius:Float, height:Float, rings:Int, segments:Int):Mesh
		return Raw.wgf_mesh_create_capsule(radius, height, rings, segments);

	public static inline function createTorus(radius:Float, thickness:Float, rings:Int, segments:Int):Mesh
		return Raw.wgf_mesh_create_torus(radius, thickness, rings, segments);

	/**
	    A mesh of the program's own triangles (a road along a centerline, a terrain): its
	    corners' positions (x, y, z each: position_count floats, a multiple of 3), their normals
	    (as many, or none for smooth ones made from the triangles), their texture coordinates
	    (u, v each, or none for 0, 0), and its triangles as indices into the corners, three
	    each, counterclockwise seen from its front (none: the corners in threes); a count of 0
	    is none, whatever its pointer. Ready at once, as a generated mesh is, with its one
	    material slot, white, not metallic, roughness 0.5; the arrays are copied. 0 (logged)
	    for counts that don't fit, or an index past the corners.
	**/
	public static inline function createTriangles(positions:Array<Float>, normals:Array<Float>, uvs:Array<Float>, indices:Array<Int>):Mesh
		return Raw.wgf_mesh_create_triangles(positions, normals, uvs, indices);

	/**
	    The mesh in a glTF file (.gltf, its buffers and images beside it, or .glb), loaded in the
	    background as a texture is (wgf_resource.h: PENDING, then READY or FAILED, the asset
	    part's search paths finding it), shared by its path. All of its scene's nodes: their
	    meshes (each glTF mesh one mesh, shared by every node showing it, its primitives each
	    with a material slot: glTF's metallic-roughness materials, their textures loaded with
	    it), their names and places, and the lights KHR_lights_punctual gives them. A model of it
	    (wgf_model_set_mesh) is the file's root: once READY, the file's node tree is made its
	    children, a model of the mesh each node shows (wgf_model_get_mesh: one handle for the
	    nodes sharing one) and a plain actor for a node with none, named and placed as in the
	    file, found as any actor is (wgf_actor_find), and a light under a node that carries one.
	    The file's own mesh holds the tree, the materials, and no triangles. A model of a PENDING mesh
	    draws nothing; of a FAILED one, the placeholder checker on a unit cube. Skins,
	    animations, morph targets, cameras, and `extras` (a node's or the file's own data) in the
	    file are not read: a game's data beside its geometry is a file of its own. 0 (logged) for an
	    empty path or one that isn't .gltf or .glb.
	**/
	public static inline function create(path:String):Mesh
		return Raw.wgf_mesh_create(path);

	/**
	    The mesh's materials, one a slot (wgf_material.h); a generated mesh has one. The
	    handle is borrowed: valid while the mesh is, and changing it changes every model
	    drawing the mesh with it. 0 for a slot it hasn't.
	**/
	public inline function getMaterialCount():Int
		return Raw.wgf_mesh_get_material_count(this);

	/**
	    The mesh's materials, one a slot (wgf_material.h); a generated mesh has one. The
	    handle is borrowed: valid while the mesh is, and changing it changes every model
	    drawing the mesh with it. 0 for a slot it hasn't.
	**/
	public inline function getMaterial(slot:Int):Material
		return Raw.wgf_mesh_get_material(this, slot);
}
