// Generated by tools/gen_binding.py from the public headers: edit the headers or the generator, not this.
package wgf;

import wgf.impl.Raw;

/** Motion's calls, on a Entity: `var x:Motion = handle` gives it them, and a Motion is still a Entity. **/
@:forward abstract Motion(Entity) from Entity to Entity {
	/**
	    Units a second, in its parent's space.
	**/
	public inline function setVelocity(x:Float, y:Float, z:Float):Bool
		return Raw.wgf_motion_set_velocity(this, x, y, z);

	/**
	    Units a second, in its parent's space.
	**/
	public inline function getVelocity(?into:wgf.Vec3):wgf.Vec3
		return Raw.wgf_motion_get_velocity(this, into);

	/**
	    Radians a second about each axis (in 2D, z alone), added to its rotation's angles.
	**/
	public inline function setSpin(x:Float, y:Float, z:Float):Bool
		return Raw.wgf_motion_set_spin(this, x, y, z);

	/**
	    Radians a second about each axis (in 2D, z alone), added to its rotation's angles.
	**/
	public inline function getSpin(?into:wgf.Vec3):wgf.Vec3
		return Raw.wgf_motion_get_spin(this, into);

	/**
	    The part of its velocity it loses each second: 0 none, 1 all of it; clamped to that.
	**/
	public inline function setDamping(damping:Float):Bool
		return Raw.wgf_motion_set_damping(this, damping);

	/**
	    The part of its velocity it loses each second: 0 none, 1 all of it; clamped to that.
	**/
	public inline function getDamping():Float
		return Raw.wgf_motion_get_damping(this);

	/**
	    The most its speed can be, in units a second; 0 for no limit. Clamped to 0 or more.
	**/
	public inline function setMaxSpeed(speed:Float):Bool
		return Raw.wgf_motion_set_max_speed(this, speed);

	/**
	    The most its speed can be, in units a second; 0 for no limit. Clamped to 0 or more.
	**/
	public inline function getMaxSpeed():Float
		return Raw.wgf_motion_get_max_speed(this);
}
