// Generated by tools/gen_binding.py from the public headers: edit the headers or the generator, not this.
package wgf;

/**
    The mouse, read inside a tick or a frame: what changed since the previous tick,
    or the previous frame. Positions are logical pixels from the window's top-left,
    y down, as gfx draws.
**/
enum abstract MouseButton(Int) from Int to Int {
	var LEFT = 0;
	var RIGHT = 1;
	var MIDDLE = 2;
}
