// Generated by tools/gen_binding.py from the public headers: edit the headers or the generator, not this.
package wgf;

enum abstract NodeType(Int) from Int to Int {
	var NONE = 0;
	var NODE = 1;
	var CANVAS = 2;
	var SPRITE = 3;
	var CAMERA2D = 4;
	var TEXT = 5;
	var SHAPE2D = 6;
	var EMITTER2D = 7;
}
