// Generated by tools/gen_binding.py from the public headers: edit the headers or the generator, not this.
package wgf;

import wgf.impl.Raw;

/** A handle of kind wgf_node_t (gfx/include/wgf_node.h): 0 is none. **/
abstract Node(Int) from Int to Int to wgf.Handle {
	/** Whether this is no handle (0); right on every target, where `== null` is not. **/
	public inline function isNone():Bool
		return this == 0;

	/**
	    A plain node: a transform, with no parent. 0 when there is no room for another.
	**/
	public static inline function create():Node
		return Raw.wgf_node_create();

	/**
	    End a node of any kind, at once. What it held is released, never destroyed: a
	    sprite drops its reference to its texture.
	**/
	public inline function destroy(children:NodeDestroy):Void
		Raw.wgf_node_destroy(this, children);

	/**
	    End a node of any kind, at once. What it held is released, never destroyed: a
	    sprite drops its reference to its texture.
	**/
	public inline function getType():NodeType
		return Raw.wgf_node_get_type(this);

	/**
	    Put `node` under `parent`, last among its children, keeping its own transform
	    (so it moves to where it sits relative to the new parent); 0 detaches it, and a
	    detached node is drawn by nothing. False when `parent` isn't a node, or is
	    `node` or under it, or when `node` is a canvas, which is always a root.
	**/
	public inline function setParent(parent:Node):Bool
		return Raw.wgf_node_set_parent(this, parent);

	/**
	    Put `node` under `parent`, last among its children, keeping its own transform
	    (so it moves to where it sits relative to the new parent); 0 detaches it, and a
	    detached node is drawn by nothing. False when `parent` isn't a node, or is
	    `node` or under it, or when `node` is a canvas, which is always a root.
	**/
	public inline function getParent():Node
		return Raw.wgf_node_get_parent(this);

	/**
	    Put `node` under `parent`, last among its children, keeping its own transform
	    (so it moves to where it sits relative to the new parent); 0 detaches it, and a
	    detached node is drawn by nothing. False when `parent` isn't a node, or is
	    `node` or under it, or when `node` is a canvas, which is always a root.
	**/
	public inline function getChildCount():Int
		return Raw.wgf_node_get_child_count(this);

	/**
	    The child at `index`, 0 first; 0 when there is none.
	**/
	public inline function getChild(index:Int):Node
		return Raw.wgf_node_get_child(this, index);

	/**
	    Where `node` is among its parent's children, which is its drawing order in a
	    canvas: later children draw over earlier ones. An index past either end is
	    clamped to it, so a large one moves it to the front. False when it has no
	    parent.
	**/
	public inline function setIndex(index:Int):Bool
		return Raw.wgf_node_set_index(this, index);

	/**
	    Where `node` is among its parent's children, which is its drawing order in a
	    canvas: later children draw over earlier ones. An index past either end is
	    clamped to it, so a large one moves it to the front. False when it has no
	    parent.
	**/
	public inline function getIndex():Int
		return Raw.wgf_node_get_index(this);

	/**
	    The transform, relative to the parent. Rotation is three angles in radians,
	    about x, then y, then z (wgf_quat_from_euler), kept as the rotation they make:
	    get_rotation gives angles for the same rotation, which may not be the ones given
	    (past a half turn, say). Scale 1 is its own size.
	**/
	public inline function setPosition(x:Float, y:Float, z:Float):Bool
		return Raw.wgf_node_set_position(this, x, y, z);

	/**
	    The transform, relative to the parent. Rotation is three angles in radians,
	    about x, then y, then z (wgf_quat_from_euler), kept as the rotation they make:
	    get_rotation gives angles for the same rotation, which may not be the ones given
	    (past a half turn, say). Scale 1 is its own size.
	**/
	public inline function getPosition(?into:wgf.Vec3):wgf.Vec3
		return Raw.wgf_node_get_position(this, into);

	/**
	    The transform, relative to the parent. Rotation is three angles in radians,
	    about x, then y, then z (wgf_quat_from_euler), kept as the rotation they make:
	    get_rotation gives angles for the same rotation, which may not be the ones given
	    (past a half turn, say). Scale 1 is its own size.
	**/
	public inline function setRotation(x:Float, y:Float, z:Float):Bool
		return Raw.wgf_node_set_rotation(this, x, y, z);

	/**
	    The transform, relative to the parent. Rotation is three angles in radians,
	    about x, then y, then z (wgf_quat_from_euler), kept as the rotation they make:
	    get_rotation gives angles for the same rotation, which may not be the ones given
	    (past a half turn, say). Scale 1 is its own size.
	**/
	public inline function getRotation(?into:wgf.Vec3):wgf.Vec3
		return Raw.wgf_node_get_rotation(this, into);

	/**
	    The transform, relative to the parent. Rotation is three angles in radians,
	    about x, then y, then z (wgf_quat_from_euler), kept as the rotation they make:
	    get_rotation gives angles for the same rotation, which may not be the ones given
	    (past a half turn, say). Scale 1 is its own size.
	**/
	public inline function setScale(x:Float, y:Float, z:Float):Bool
		return Raw.wgf_node_set_scale(this, x, y, z);

	/**
	    The transform, relative to the parent. Rotation is three angles in radians,
	    about x, then y, then z (wgf_quat_from_euler), kept as the rotation they make:
	    get_rotation gives angles for the same rotation, which may not be the ones given
	    (past a half turn, say). Scale 1 is its own size.
	**/
	public inline function getScale(?into:wgf.Vec3):wgf.Vec3
		return Raw.wgf_node_get_scale(this, into);

	/**
	    All three at once: the cheapest way to move something each frame.
	**/
	public inline function setTransform(position_x:Float, position_y:Float, position_z:Float, rotation_x:Float, rotation_y:Float, rotation_z:Float, scale_x:Float, scale_y:Float, scale_z:Float):Bool
		return Raw.wgf_node_set_transform(this, position_x, position_y, position_z, rotation_x, rotation_y, rotation_z, scale_x, scale_y, scale_z);

	/**
	    Where the node is in its tree's root's space: in a canvas, canvas units.
	**/
	public inline function getWorldPosition(?into:wgf.Vec3):wgf.Vec3
		return Raw.wgf_node_get_world_position(this, into);

	/**
	    A name to find the node by; NULL or "" for none, the default. get_name is "" for none: borrowed, valid until the
	    name changes or the node goes. Names needn't be unique.
	**/
	public inline function setName(name:String):Bool
		return Raw.wgf_node_set_name(this, name);

	/**
	    A name to find the node by; NULL or "" for none, the default. get_name is "" for none: borrowed, valid until the
	    name changes or the node goes. Names needn't be unique.
	**/
	public inline function getName():String
		return Raw.wgf_node_get_name(this);

	/**
	    The first node named `name` in the tree from `root`, `root` included, depth
	    first, children in order; 0 for none.
	**/
	public inline function find(name:String):Node
		return Raw.wgf_node_find(this, name);

	/**
	    Two flags say what a node takes part in, each the node's own, read back as set:

	      enabled   off: the node is skipped altogether, with everything under it, as if
	                it weren't in the tree: the switch on a part of the game that is off
	                for now. The only one that reaches the children; their own flags are
	                kept, so enabling it again brings each back as it was set
	      visible   off: the node's own output is off -- a sprite, shape, text, or
	                emitter isn't drawn -- while it is still placed and its children are
	                as they are

	    Defaults: enabled, visible.
	**/
	public inline function setEnabled(enabled:Bool):Bool
		return Raw.wgf_node_set_enabled(this, enabled);

	/**
	    Two flags say what a node takes part in, each the node's own, read back as set:

	      enabled   off: the node is skipped altogether, with everything under it, as if
	                it weren't in the tree: the switch on a part of the game that is off
	                for now. The only one that reaches the children; their own flags are
	                kept, so enabling it again brings each back as it was set
	      visible   off: the node's own output is off -- a sprite, shape, text, or
	                emitter isn't drawn -- while it is still placed and its children are
	                as they are

	    Defaults: enabled, visible.
	**/
	public inline function isEnabled():Bool
		return Raw.wgf_node_is_enabled(this);

	/**
	    Two flags say what a node takes part in, each the node's own, read back as set:

	      enabled   off: the node is skipped altogether, with everything under it, as if
	                it weren't in the tree: the switch on a part of the game that is off
	                for now. The only one that reaches the children; their own flags are
	                kept, so enabling it again brings each back as it was set
	      visible   off: the node's own output is off -- a sprite, shape, text, or
	                emitter isn't drawn -- while it is still placed and its children are
	                as they are

	    Defaults: enabled, visible.
	**/
	public inline function setVisible(visible:Bool):Bool
		return Raw.wgf_node_set_visible(this, visible);

	/**
	    Two flags say what a node takes part in, each the node's own, read back as set:

	      enabled   off: the node is skipped altogether, with everything under it, as if
	                it weren't in the tree: the switch on a part of the game that is off
	                for now. The only one that reaches the children; their own flags are
	                kept, so enabling it again brings each back as it was set
	      visible   off: the node's own output is off -- a sprite, shape, text, or
	                emitter isn't drawn -- while it is still placed and its children are
	                as they are

	    Defaults: enabled, visible.
	**/
	public inline function isVisible():Bool
		return Raw.wgf_node_is_visible(this);
}
