// Generated by tools/gen_binding.py from the public headers: edit the headers or the generator, not this.
package wgf;

import wgf.impl.Raw;

class Physics {
	/**
	    The world's gravity, in units a second squared (default 0, -9.81, 0: y up, in meters);
	    starting physics. False only when physics couldn't start (logged).
	**/
	public static inline function setGravity(x:Float, y:Float, z:Float):Bool
		return Raw.wgf_physics_set_gravity(x, y, z);

	/**
	    The world's gravity, in units a second squared (default 0, -9.81, 0: y up, in meters);
	    starting physics. False only when physics couldn't start (logged).
	**/
	public static inline function getGravity(?into:wgf.Vec3):wgf.Vec3
		return Raw.wgf_physics_get_gravity(into);

	/**
	    Every body's shape outlined in `color` (a sensor's in half its alpha), and each vehicle's
	    wheels: a debug view, drawn into the 3D drawing begun (wgf_draw_begin_3d, wgf_draw.h);
	    nothing outside one, or before physics starts. A mesh is drawn by its triangles' edges.
	**/
	public static inline function drawBodies(color:Int):Void
		Raw.wgf_physics_draw_bodies(color);
}
