// Generated by tools/gen_binding.py from the public headers: edit the headers or the generator, not this.
package wgf;

/**
    The state of anything that plays over time: an audio voice and a model's animation
    now (docs/CONVENTIONS.md, "What plays over time has one state and four calls"). Each
    such object has play, pause, resume, and stop, with the same transitions:

      play     to PLAYING from the start, from any state (COMPLETE included: that is how
               a one-shot plays again)
      pause    from PLAYING only, to PAUSED, held where it was
      resume   from PAUSED only, back to PLAYING
      stop     to STOPPED, rewound to the start, from any state

    and each returns false where it doesn't apply, its header naming those cases. A speed
    or pitch of 0 holds where it is, still PLAYING: that is not pause. A negative one runs
    backwards: play starts at the end and COMPLETE comes at the start. Read it as a
    resource's status is read (wgf_resource.h): it changes only in an update.
**/
enum abstract PlayState(Int) from Int to Int {
	var STOPPED = 0;
	var PLAYING = 1;
	var PAUSED = 2;
	var COMPLETE = 3;
}
