// Generated by tools/gen_binding.py from the public headers: edit the headers or the generator, not this.
package wgf;

import wgf.impl.Raw;

class Presentation {
	public static inline function set(mode:PresentationMode, width:Int, height:Int):Bool
		return Raw.wgf_presentation_set(mode, width, height);

	public static inline function getMode():PresentationMode
		return Raw.wgf_presentation_get_mode();

	/**
	    The bars (FIT and INTEGER): the framebuffer outside the visible area, which nothing is
	    drawn in. Default: black.
	**/
	public static inline function setBarColor(color:Int):Void
		Raw.wgf_presentation_set_bar_color(color);

	/**
	    The bars (FIT and INTEGER): the framebuffer outside the visible area, which nothing is
	    drawn in. Default: black.
	**/
	public static inline function getBarColor():Int
		return Raw.wgf_presentation_get_bar_color();

	/**
	    The design resolution; the window's logical size under NONE.
	**/
	public static inline function getWidth():Int
		return Raw.wgf_presentation_get_width();

	/**
	    The design resolution; the window's logical size under NONE.
	**/
	public static inline function getHeight():Int
		return Raw.wgf_presentation_get_height();

	/**
	    What is visible now, in logical coordinates: x, y, width, height. The design area
	    (0, 0, its width, its height) under STRETCH, FIT, and INTEGER; less of it under FILL;
	    more under EXPAND, x and y below 0 when it grows. A HUD anchored to a corner places
	    itself from this.
	**/
	public static inline function getVisible(?into:wgf.Vec4):wgf.Vec4
		return Raw.wgf_presentation_get_visible(into);

	/**
	    Framebuffer pixels to a logical pixel, across (under STRETCH, each axis has its own:
	    this is the horizontal one).
	**/
	public static inline function getScale():Float
		return Raw.wgf_presentation_get_scale();
}
