// Generated by tools/gen_binding.py from the public headers: edit the headers or the generator, not this.
package wgf;

/**
    How a game's design is fitted to the window or the screen (Godot's stretch modes
    and aspects are the prior art). A game is written for a design resolution, and its
    logical coordinates stay the design's at any window size and in fullscreen: drawing,
    canvases, the UI, the pointer and touches (mapped back into them), and an autopilot's
    mouse. The same on the desktop, in a resized browser window, and in fullscreen.

      NONE     the default: logical pixels are the window's (a framebuffer pixel over the
               DPI scale), and the visible area is the window
      STRETCH  the design scaled to the window on each axis apart, its aspect lost
      FIT      scaled alike on both axes, as large as it fits whole, centered; the rest
               are bars (wgf_render_set_bar_color), nothing drawn in them
      FILL     scaled alike, as small as covers the window, centered; what is past the
               window's edges is cropped
      EXPAND   scaled as FIT is, but the visible area grows past the design to the
               window's edges, centered on it: the design is the least the game shows,
               and a UI anchored to the visible area's edges stays at them
      INTEGER  as FIT, at a whole number of framebuffer pixels to a logical one (at
               least 1), for pixel art; bars around it

    Set any time; it takes effect at the next frame. A program that never sets a mode
    links none of its fitting. Natively, a window whose size the program didn't set
    (wgf_window_set_size) opens at the design size. False for a size under 1 (but for
    NONE, which takes none) or a mode that isn't one.
**/
enum abstract PresentationMode(Int) from Int to Int {
	var NONE = 0;
	var STRETCH = 1;
	var FIT = 2;
	var FILL = 3;
	var EXPAND = 4;
	var INTEGER = 5;
}
