// Generated by tools/gen_binding.py from the public headers: edit the headers or the generator, not this.
package wgf;

import wgf.impl.Raw;

class Probe {
	/**
	    Set `name` to `value`, adding it the first time. False, and nothing set, for a name
	    that breaks the rule above, a value that isn't finite, a 257th probe, or core not
	    running.
	**/
	public static inline function setValue(name:String, value:Float):Bool
		return Raw.wgf_probe_set_value(name, value);

	/**
	    The value of `name`; 0 for one never set (wgf_probe_has_value tells them apart).
	**/
	public static inline function getValue(name:String):Float
		return Raw.wgf_probe_get_value(name);

	/**
	    Whether `name` has been set since core started.
	**/
	public static inline function hasValue(name:String):Bool
		return Raw.wgf_probe_has_value(name);

	/**
	    The probes, in the order they were first set: how many, and each one's name ("" for
	    an index out of range). Borrowed: valid until core stops.
	**/
	public static inline function getCount():Int
		return Raw.wgf_probe_get_count();

	/**
	    The probes, in the order they were first set: how many, and each one's name ("" for
	    an index out of range). Borrowed: valid until core stops.
	**/
	public static inline function getName(index:Int):String
		return Raw.wgf_probe_get_name(index);
}
