// Generated by tools/gen_binding.py from the public headers: edit the headers or the generator, not this.
package wgf;

import wgf.impl.Raw;

class Render {
	/**
	    What each frame starts cleared to. Default: black.
	**/
	public static inline function setClearColor(color:Int):Void
		Raw.wgf_render_set_clear_color(color);

	/**
	    What each frame starts cleared to. Default: black.
	**/
	public static inline function getClearColor():Int
		return Raw.wgf_render_get_clear_color();

	/**
	    The presentation's bars (wgf_presentation.h's FIT and INTEGER): the framebuffer
	    outside the visible area, which nothing is drawn in. Default: black.
	**/
	public static inline function setBarColor(color:Int):Void
		Raw.wgf_render_set_bar_color(color);

	/**
	    The presentation's bars (wgf_presentation.h's FIT and INTEGER): the framebuffer
	    outside the visible area, which nothing is drawn in. Default: black.
	**/
	public static inline function getBarColor():Int
		return Raw.wgf_render_get_bar_color();

	/**
	    The frame's size in pixels, and how many pixels make one logical pixel (2 on most
	    high-density displays); 0, 0, and 1 while there is no surface. Drawing is in logical
	    pixels: the frame is get_width() / get_dpi_scale() of them wide.
	**/
	public static inline function getWidth():Int
		return Raw.wgf_render_get_width();

	/**
	    The frame's size in pixels, and how many pixels make one logical pixel (2 on most
	    high-density displays); 0, 0, and 1 while there is no surface. Drawing is in logical
	    pixels: the frame is get_width() / get_dpi_scale() of them wide.
	**/
	public static inline function getHeight():Int
		return Raw.wgf_render_get_height();

	/**
	    The frame's size in pixels, and how many pixels make one logical pixel (2 on most
	    high-density displays); 0, 0, and 1 while there is no surface. Drawing is in logical
	    pixels: the frame is get_width() / get_dpi_scale() of them wide.
	**/
	public static inline function getDpiScale():Float
		return Raw.wgf_render_get_dpi_scale();

	/**
	    Clip drawing to a rectangle (logical pixels, top-left origin) until the matching
	    pop. Clips nest: each push intersects with the clip it's pushed inside, so a scroll
	    area inside a panel stays inside the panel. Everything drawn between is clipped:
	    immediate mode, and the 2D stages drawn there. A width or height of 0 clips
	    everything away. Every push should be popped within the frame: unmatched ones are
	    dropped at its end, with a warning, as is a pop without a push. Up to 32 deep; a
	    push past that clips nothing more, warned once. Outside a frame: nothing, warned.
	**/
	public static inline function pushClip(x:Float, y:Float, width:Float, height:Float):Void
		Raw.wgf_render_push_clip(x, y, width, height);

	/**
	    Clip drawing to a rectangle (logical pixels, top-left origin) until the matching
	    pop. Clips nest: each push intersects with the clip it's pushed inside, so a scroll
	    area inside a panel stays inside the panel. Everything drawn between is clipped:
	    immediate mode, and the 2D stages drawn there. A width or height of 0 clips
	    everything away. Every push should be popped within the frame: unmatched ones are
	    dropped at its end, with a warning, as is a pop without a push. Up to 32 deep; a
	    push past that clips nothing more, warned once. Outside a frame: nothing, warned.
	**/
	public static inline function popClip():Void
		Raw.wgf_render_pop_clip();
}
