// Generated by tools/gen_binding.py from the public headers: edit the headers or the generator, not this.
package wgf;

import wgf.impl.Raw;

class Resource {
	/**
	    PENDING, READY, or FAILED for a resource of any kind; NONE for anything else.
	**/
	public static inline function getStatus(resource:Handle):ResourceStatus
		return Raw.wgf_resource_get_status(resource);

	/**
	    The file it was read from, as a path under fs's root: for "name.ktx" the variant
	    this GPU got (or the PNG). "" until it is READY, for one made from numbers, and for
	    anything that isn't a resource. Borrowed: valid while the resource is.
	**/
	public static inline function getPath(resource:Handle):String
		return Raw.wgf_resource_get_path(resource);

	/**
	    Drop this handle's reference. Resources are shared and reference counted, so one is
	    freed when its last reference goes, not when this is called; one still loading then
	    stops loading. Objects hold their own references, so handing a resource to one and
	    releasing it right away is the normal pattern. A built-in (the placeholder texture)
	    is never freed. False for a handle that isn't a resource: 0, an object, or one
	    already freed.
	**/
	public static inline function release(resource:Handle):Bool
		return Raw.wgf_resource_release(resource);

	/**
	    Milliseconds a frame spent finishing loads on the main thread, such as GPU uploads
	    (default 4), so loading doesn't stall the frames it runs beside. At least one step
	    runs each frame however small it is, so one large file can exceed it: a 4096x4096
	    texture is one upload of about 45 ms (wgrender's measurement). 0 finishes one step a
	    frame. It applies to every load, from a bundled, cached, or fetched file alike. False,
	    and nothing changed, for a negative or non-finite one.
	**/
	public static inline function setLoadBudget(milliseconds:Float):Bool
		return Raw.wgf_resource_set_load_budget(milliseconds);

	/**
	    Milliseconds a frame spent finishing loads on the main thread, such as GPU uploads
	    (default 4), so loading doesn't stall the frames it runs beside. At least one step
	    runs each frame however small it is, so one large file can exceed it: a 4096x4096
	    texture is one upload of about 45 ms (wgrender's measurement). 0 finishes one step a
	    frame. It applies to every load, from a bundled, cached, or fetched file alike. False,
	    and nothing changed, for a negative or non-finite one.
	**/
	public static inline function getLoadBudget():Float
		return Raw.wgf_resource_get_load_budget();
}
