// Generated by tools/gen_binding.py from the public headers: edit the headers or the generator, not this.
package wgf;

import wgf.impl.Raw;

/** A handle of kind wgf_scene_t (libwgf/ecs/include/wgf_scene.h): 0 is none. **/
abstract Scene(Int) from Int to Int to wgf.Handle {
	/** Whether this is no handle (0); right on every target, where `== null` is not. **/
	public inline function isNone():Bool
		return this == 0;

	/** Whether this refers to something alive: false for none, and for what was destroyed or released (wgf_handle_is_alive). Ask it first where a handle may be dead. **/
	public inline function isAlive():Bool
		return (this : Handle).isAlive();

	/**
	    The scene at `path`, loading. The same path again gives the same scene, with one more
	    reference. 0 only when there is no room for another.
	**/
	public static inline function create(path:String):Scene
		return Raw.wgf_scene_create(path);

	/**
	    Make the scene's top actors' trees, in file order, under `parent` (0: none), each actor
	    as the file says and each behavior's CREATED raised. The number of top actors made; 0
	    for a scene that isn't READY, or a `parent` that isn't an actor (0 is).
	**/
	public inline function instantiate(parent:Actor):Int
		return Raw.wgf_scene_instantiate(this, parent);

	/**
	    The prefab `name` of a READY scene, to spawn: the same handle each time it is asked
	    for. 0 for a scene that isn't READY, or a prefab it doesn't have. A released scene's
	    prefabs go with it (their handles stale).
	**/
	public inline function prefab(name:String):Prefab
		return Raw.wgf_scene_find_prefab(this, name);

	/**
	    What the file holds, once READY: its top actors and its prefabs, and each prefab's name
	    in file order ("" past the end). 0 and "" until then.
	**/
	public inline function getActorCount():Int
		return Raw.wgf_scene_get_actor_count(this);

	/**
	    What the file holds, once READY: its top actors and its prefabs, and each prefab's name
	    in file order ("" past the end). 0 and "" until then.
	**/
	public inline function getPrefabCount():Int
		return Raw.wgf_scene_get_prefab_count(this);

	/**
	    What the file holds, once READY: its top actors and its prefabs, and each prefab's name
	    in file order ("" past the end). 0 and "" until then.
	**/
	public inline function getPrefabName(index:Int):String
		return Raw.wgf_scene_get_prefab_name(this, index);

	/**
	    What the file holds, once READY: its top actors and its prefabs, and each prefab's name
	    in file order ("" past the end). 0 and "" until then.
	**/
	public inline function hasPrefab(name:String):Bool
		return Raw.wgf_scene_has_prefab(this, name);

	/**
		The prefab `name` found (scene.prefab) and spawned under `parent`: placed at (x, y, z), turned `angle`, and snapped when a place is given (Prefab.spawnAt), else at the prefab's own transform (Prefab.spawn). It looks the prefab up on every call: a hot path finds it once and keeps the handle. 0 as those calls give it.
	**/
	public inline function spawnPrefab(name:String, parent:Actor, ?x:Float, ?y:Float, ?z:Float, ?angle:Float):Actor {
		final found:Prefab = prefab(name);
		return x == null ? found.spawn(parent) : found.spawnAt(parent, x, y ?? 0, z ?? 0, angle ?? 0);
	}
}
