// Generated by tools/gen_binding.py from the public headers: edit the headers or the generator, not this.
package wgf;

import wgf.impl.Raw;

/** Shape2d's calls, on a Node: `var x:Shape2d = handle` gives it them, and a Shape2d is still a Node. **/
@:forward abstract Shape2d(Node) from Node to Node {
	/**
	    A shape with nothing to draw yet, white, filled. 0 when there is no room for another
	    node.
	**/
	public static inline function create():Shape2d
		return ((Raw.wgf_shape2d_create() : Node) : Shape2d);

	/**
	    What it is, set by the calls below; NONE for a handle that isn't a 2D shape.
	**/
	public inline function getKind():Shape2dKind
		return Raw.wgf_shape2d_get_kind(this);

	/**
	    A rectangle `width` by `height` from its own origin (its top-left corner, unless a
	    pivot is set). False for a handle that isn't a 2D shape, or a size below 0.
	**/
	public inline function setRectangle(width:Float, height:Float):Bool
		return Raw.wgf_shape2d_set_rectangle(this, width, height);

	/**
	    A circle of `radius` about its own origin (its center, unless a pivot is set). False
	    for a handle that isn't a 2D shape, or a radius below 0.
	**/
	public inline function setCircle(radius:Float):Bool
		return Raw.wgf_shape2d_set_circle(this, radius);

	/**
	    A line from (x0, y0) to (x1, y1) in its own units, as thick as the outline (a hairline
	    at 0). Its ends are its own, so the pivot doesn't move them. False for a handle that
	    isn't a 2D shape.
	**/
	public inline function setLine(x0:Float, y0:Float, x1:Float, y1:Float):Bool
		return Raw.wgf_shape2d_set_line(this, x0, y0, x1, y1);

	/**
	    A polygon through `points` in its own units, x and y in turn (count floats: count / 2
	    points, at most 1024), copied; filled whether convex or not, or outlined, closed. Its
	    points are its own, so the pivot doesn't move them. False for a handle that isn't a
	    2D shape, NULL, an odd count, fewer than 3 points, or more than 1024.
	**/
	public inline function setPolygon(points:Array<Float>):Bool
		return Raw.wgf_shape2d_set_polygon(this, points);

	/**
	    What was set: a rectangle's width and height (0, 0 otherwise), a circle's radius (0
	    otherwise), a line's ends, and a polygon's points: into `out`, x and y in turn, as
	    many as fit in `count` floats, returning how many floats it filled (0 for anything
	    but a polygon).
	**/
	public inline function getSize(?into:wgf.Vec2):wgf.Vec2
		return Raw.wgf_shape2d_get_size(this, into);

	/**
	    What was set: a rectangle's width and height (0, 0 otherwise), a circle's radius (0
	    otherwise), a line's ends, and a polygon's points: into `out`, x and y in turn, as
	    many as fit in `count` floats, returning how many floats it filled (0 for anything
	    but a polygon).
	**/
	public inline function getRadius():Float
		return Raw.wgf_shape2d_get_radius(this);

	/**
	    What was set: a rectangle's width and height (0, 0 otherwise), a circle's radius (0
	    otherwise), a line's ends, and a polygon's points: into `out`, x and y in turn, as
	    many as fit in `count` floats, returning how many floats it filled (0 for anything
	    but a polygon).
	**/
	public inline function getLineStart(?into:wgf.Vec2):wgf.Vec2
		return Raw.wgf_shape2d_get_line_start(this, into);

	/**
	    What was set: a rectangle's width and height (0, 0 otherwise), a circle's radius (0
	    otherwise), a line's ends, and a polygon's points: into `out`, x and y in turn, as
	    many as fit in `count` floats, returning how many floats it filled (0 for anything
	    but a polygon).
	**/
	public inline function getLineEnd(?into:wgf.Vec2):wgf.Vec2
		return Raw.wgf_shape2d_get_line_end(this, into);

	/**
	    What was set: a rectangle's width and height (0, 0 otherwise), a circle's radius (0
	    otherwise), a line's ends, and a polygon's points: into `out`, x and y in turn, as
	    many as fit in `count` floats, returning how many floats it filled (0 for anything
	    but a polygon).
	**/
	public inline function getPointCount():Int
		return Raw.wgf_shape2d_get_point_count(this);

	/**
	    What was set: a rectangle's width and height (0, 0 otherwise), a circle's radius (0
	    otherwise), a line's ends, and a polygon's points: into `out`, x and y in turn, as
	    many as fit in `count` floats, returning how many floats it filled (0 for anything
	    but a polygon).
	**/
	public inline function getPoints(out:Array<Float>):Int
		return Raw.wgf_shape2d_get_points(this, out);

	/**
	    The point of a rectangle or circle at its node's position, which it turns and scales
	    about, as a fraction of it: 0, 0 its top-left, 1, 1 its bottom-right. Unset (the
	    default), each keeps its own origin -- a rectangle's top-left corner, a circle's
	    center -- read back as that fraction (0, 0 or 0.5, 0.5). False for a handle that
	    isn't a 2D shape.
	**/
	public inline function setPivot(x:Float, y:Float):Bool
		return Raw.wgf_shape2d_set_pivot(this, x, y);

	/**
	    The point of a rectangle or circle at its node's position, which it turns and scales
	    about, as a fraction of it: 0, 0 its top-left, 1, 1 its bottom-right. Unset (the
	    default), each keeps its own origin -- a rectangle's top-left corner, a circle's
	    center -- read back as that fraction (0, 0 or 0.5, 0.5). False for a handle that
	    isn't a 2D shape.
	**/
	public inline function getPivot(?into:wgf.Vec2):wgf.Vec2
		return Raw.wgf_shape2d_get_pivot(this, into);

	/**
	    Drawn as an outline `thickness` logical pixels wide, centered on its edge; 0 (the
	    default) fills it, and a line is then a hairline. Clamped to 0 or more. False for a
	    handle that isn't a 2D shape.
	**/
	public inline function setOutline(thickness:Float):Bool
		return Raw.wgf_shape2d_set_outline(this, thickness);

	/**
	    Drawn as an outline `thickness` logical pixels wide, centered on its edge; 0 (the
	    default) fills it, and a line is then a hairline. Clamped to 0 or more. False for a
	    handle that isn't a 2D shape.
	**/
	public inline function getOutline():Float
		return Raw.wgf_shape2d_get_outline(this);

	/**
	    Default: white. False for a handle that isn't a 2D shape.
	**/
	public inline function setColor(color:Int):Bool
		return Raw.wgf_shape2d_set_color(this, color);

	/**
	    Default: white. False for a handle that isn't a 2D shape.
	**/
	public inline function getColor():Int
		return Raw.wgf_shape2d_get_color(this);
}
