// Generated by tools/gen_binding.py from the public headers: edit the headers or the generator, not this.
package wgf;

/**
    A 2D shape: a node drawing a rectangle, a circle, a line, or a polygon, filled or
    outlined, in one color, in a canvas. Shapes are nodes (wgf_node.h): place, turn,
    scale, parent, and destroy them with the node calls; the shape turns and scales with
    its node, and an outline's thickness stays in the frame's logical pixels.
**/
enum abstract Shape2dKind(Int) from Int to Int {
	var NONE = 0;
	var RECTANGLE = 1;
	var CIRCLE = 2;
	var LINE = 3;
	var POLYGON = 4;
}
