// Generated by tools/gen_binding.py from the public headers: edit the headers or the generator, not this.
package wgf;

import wgf.impl.Raw;

/** Shape3d's calls, on a Actor: `var x:Shape3d = handle` gives it them, and a Shape3d is still a Actor. **/
@:forward abstract Shape3d(Actor) from Actor to Actor {
	/**
	    A shape with nothing to draw yet, white. 0 when there is no room for another actor.
	**/
	public static inline function create():Shape3d
		return ((Raw.wgf_shape3d_create() : Actor) : Shape3d);

	/**
	    What it is, set by the calls below; NONE for an actor that isn't a 3D shape.
	**/
	public inline function getKind():Shape3dKind
		return Raw.wgf_shape3d_get_kind(this);

	/**
	    About its actor's origin: a cube `width` by `height` by `length`; a sphere of
	    `radius`; a filled rectangle `width` by `height`, and a circle's outline of `radius`,
	    in its local x-y plane. False for a size below 0.
	**/
	public inline function setCube(width:Float, height:Float, length:Float):Bool
		return Raw.wgf_shape3d_set_cube(this, width, height, length);

	/**
	    About its actor's origin: a cube `width` by `height` by `length`; a sphere of
	    `radius`; a filled rectangle `width` by `height`, and a circle's outline of `radius`,
	    in its local x-y plane. False for a size below 0.
	**/
	public inline function setSphere(radius:Float):Bool
		return Raw.wgf_shape3d_set_sphere(this, radius);

	/**
	    About its actor's origin: a cube `width` by `height` by `length`; a sphere of
	    `radius`; a filled rectangle `width` by `height`, and a circle's outline of `radius`,
	    in its local x-y plane. False for a size below 0.
	**/
	public inline function setRectangle(width:Float, height:Float):Bool
		return Raw.wgf_shape3d_set_rectangle(this, width, height);

	/**
	    About its actor's origin: a cube `width` by `height` by `length`; a sphere of
	    `radius`; a filled rectangle `width` by `height`, and a circle's outline of `radius`,
	    in its local x-y plane. False for a size below 0.
	**/
	public inline function setCircle(radius:Float):Bool
		return Raw.wgf_shape3d_set_circle(this, radius);

	/**
	    A line from (x0, y0, z0) to (x1, y1, z1), in its own space.
	**/
	public inline function setLine(x0:Float, y0:Float, z0:Float, x1:Float, y1:Float, z1:Float):Bool
		return Raw.wgf_shape3d_set_line(this, x0, y0, z0, x1, y1, z1);

	/**
	    A line strip, from a caller-owned array of points, x, y, and z in turn (`float_count`
	    floats: three a point), copied: drawn once it has two. False for a count that isn't a
	    multiple of 3, or past 65536 points. get_points fills the caller's array with up to
	    `float_count` floats of them and returns how many it filled.
	**/
	public inline function setLineStrip(points:Array<Float>):Bool
		return Raw.wgf_shape3d_set_line_strip(this, points);

	/**
	    A line strip, from a caller-owned array of points, x, y, and z in turn (`float_count`
	    floats: three a point), copied: drawn once it has two. False for a count that isn't a
	    multiple of 3, or past 65536 points. get_points fills the caller's array with up to
	    `float_count` floats of them and returns how many it filled.
	**/
	public inline function getPointCount():Int
		return Raw.wgf_shape3d_get_point_count(this);

	/**
	    A line strip, from a caller-owned array of points, x, y, and z in turn (`float_count`
	    floats: three a point), copied: drawn once it has two. False for a count that isn't a
	    multiple of 3, or past 65536 points. get_points fills the caller's array with up to
	    `float_count` floats of them and returns how many it filled.
	**/
	public inline function getPoints(points:Array<Float>):Int
		return Raw.wgf_shape3d_get_points(this, points);

	/**
	    What was set: a cube's or rectangle's size (a rectangle's z 0; 0, 0, 0 otherwise), a
	    sphere's or circle's radius (0 otherwise), and a line's ends.
	**/
	public inline function getSize(?into:wgf.Vec3):wgf.Vec3
		return Raw.wgf_shape3d_get_size(this, into);

	/**
	    What was set: a cube's or rectangle's size (a rectangle's z 0; 0, 0, 0 otherwise), a
	    sphere's or circle's radius (0 otherwise), and a line's ends.
	**/
	public inline function getRadius():Float
		return Raw.wgf_shape3d_get_radius(this);

	/**
	    What was set: a cube's or rectangle's size (a rectangle's z 0; 0, 0, 0 otherwise), a
	    sphere's or circle's radius (0 otherwise), and a line's ends.
	**/
	public inline function getLineStart(?into:wgf.Vec3):wgf.Vec3
		return Raw.wgf_shape3d_get_line_start(this, into);

	/**
	    What was set: a cube's or rectangle's size (a rectangle's z 0; 0, 0, 0 otherwise), a
	    sphere's or circle's radius (0 otherwise), and a line's ends.
	**/
	public inline function getLineEnd(?into:wgf.Vec3):wgf.Vec3
		return Raw.wgf_shape3d_get_line_end(this, into);

	/**
	    Default: white. Alpha below 255 makes it see-through.
	**/
	public inline function setColor(color:Int):Bool
		return Raw.wgf_shape3d_set_color(this, color);

	/**
	    Default: white. Alpha below 255 makes it see-through.
	**/
	public inline function getColor():Int
		return Raw.wgf_shape3d_get_color(this);
}
