// Generated by tools/gen_binding.py from the public headers: edit the headers or the generator, not this.
package wgf;

import wgf.impl.Raw;

/** Stage's calls, on a Node: `var x:Stage = handle` gives it them, and a Stage is still a Node. **/
@:forward abstract Stage(Node) from Node to Node {
	/**
	    A stage, with no camera, no ambient light, and NEUTRAL tone mapping at an exposure of
	    0. 0 when there is no room for another node.
	**/
	public static inline function create():Stage
		return ((Raw.wgf_stage_create() : Node) : Stage);

	/**
	    Draw it into this frame, through its camera: its opaque models, then its 3D shapes
	    (wgf_shape3d.h), then its see-through models (a BLEND material, or a tint with alpha
	    below 255) back to front, depth tested against each other and against the frame's 3D
	    drawn before it. Each model is lit by
	    the up to 8 lights that reach it most. Outside a frame, or with no camera, nothing.
	**/
	public inline function draw():Void
		Raw.wgf_stage_draw(this);

	/**
	    The camera it is seen through: a 3D camera anywhere, on this stage or not (default 0,
	    none: nothing is drawn). False when `camera` isn't a 3D camera. A camera that is
	    destroyed leaves the stage with none.
	**/
	public inline function setCamera(camera:Node):Bool
		return Raw.wgf_stage_set_camera(this, camera);

	/**
	    The camera it is seen through: a 3D camera anywhere, on this stage or not (default 0,
	    none: nothing is drawn). False when `camera` isn't a 3D camera. A camera that is
	    destroyed leaves the stage with none.
	**/
	public inline function getCamera():Node
		return Raw.wgf_stage_get_camera(this);

	/**
	    The light that reaches everything evenly, from no direction: its color times
	    `intensity` (clamped to 0 or more). Default: none, an intensity of 0. Alpha is
	    ignored.
	**/
	public inline function setAmbient(color:Int, intensity:Float):Bool
		return Raw.wgf_stage_set_ambient(this, color, intensity);

	/**
	    The light that reaches everything evenly, from no direction: its color times
	    `intensity` (clamped to 0 or more). Default: none, an intensity of 0. Alpha is
	    ignored.
	**/
	public inline function getAmbientColor():Int
		return Raw.wgf_stage_get_ambient_color(this);

	/**
	    The light that reaches everything evenly, from no direction: its color times
	    `intensity` (clamped to 0 or more). Default: none, an intensity of 0. Alpha is
	    ignored.
	**/
	public inline function getAmbientIntensity():Float
		return Raw.wgf_stage_get_ambient_intensity(this);

	/**
	    Its tone mapping, and its exposure in stops (EV): +1 doubles the brightness. Default:
	    NEUTRAL, 0. False for a tone mapping that isn't one.
	**/
	public inline function setTonemap(tonemap:StageTonemap, exposure:Float):Bool
		return Raw.wgf_stage_set_tonemap(this, tonemap, exposure);

	/**
	    Its tone mapping, and its exposure in stops (EV): +1 doubles the brightness. Default:
	    NEUTRAL, 0. False for a tone mapping that isn't one.
	**/
	public inline function getTonemap():StageTonemap
		return Raw.wgf_stage_get_tonemap(this);

	/**
	    Its tone mapping, and its exposure in stops (EV): +1 doubles the brightness. Default:
	    NEUTRAL, 0. False for a tone mapping that isn't one.
	**/
	public inline function getExposure():Float
		return Raw.wgf_stage_get_exposure(this);

	/**
	    Skip models the camera can't see (on by default): each is tested by the box around it
	    as it is placed now, grown a little against rounding, against the camera's view
	    before it is drawn, which is far cheaper than drawing it. Turn it off to draw
	    everything, when checking whether a model's bounds are right, say.
	**/
	public inline function setCulling(culling:Bool):Bool
		return Raw.wgf_stage_set_culling(this, culling);

	/**
	    Skip models the camera can't see (on by default): each is tested by the box around it
	    as it is placed now, grown a little against rounding, against the camera's view
	    before it is drawn, which is far cheaper than drawing it. Turn it off to draw
	    everything, when checking whether a model's bounds are right, say.
	**/
	public inline function isCulling():Bool
		return Raw.wgf_stage_is_culling(this);
}
