// Generated by tools/gen_binding.py from the public headers: edit the headers or the generator, not this.
package wgf;

import wgf.impl.Raw;

/** Stage3d's calls, on a Actor: `var x:Stage3d = handle` gives it them, and a Stage3d is still a Actor; it starts as 0, none, as a Actor does. **/
@:forward abstract Stage3d(Actor) from Actor from Int to Actor {
	/**
	    A stage, with no camera, no ambient light, and NEUTRAL tone mapping at an exposure of
	    0. 0 when there is no room for another actor.
	**/
	public static inline function create():Stage3d
		return ((Raw.wgf_stage3d_create() : Actor) : Stage3d);

	/**
	    Draw it into this frame, through its camera: its opaque models, then its 3D shapes
	    (wgf_shape3d.h), then its see-through models (a BLEND material, or a tint with alpha
	    below 255) back to front, depth tested against each other and against the frame's 3D
	    drawn before it. Each model is lit by
	    the up to 8 lights that reach it most. Outside a frame, or with no camera, nothing.
	**/
	public inline function draw():Void
		Raw.wgf_stage3d_draw(this);

	/**
	    The camera it is seen through: a 3D camera anywhere, on this stage or not (default 0,
	    none: nothing is drawn). False when `camera` isn't a 3D camera. A camera that is
	    destroyed leaves the stage with none.
	**/
	public inline function setCamera(camera:Actor):Bool
		return Raw.wgf_stage3d_set_camera(this, camera);

	/**
	    The camera it is seen through: a 3D camera anywhere, on this stage or not (default 0,
	    none: nothing is drawn). False when `camera` isn't a 3D camera. A camera that is
	    destroyed leaves the stage with none.
	**/
	public inline function getCamera():Actor
		return Raw.wgf_stage3d_get_camera(this);

	/**
	    The actor on this stage named `name`, as wgf_stage2d_find: by an index, never a walk;
	    0 for none, for a stage that isn't a 3D stage, and for a shared name (warned).
	**/
	public inline function find(name:String):Actor
		return Raw.wgf_stage3d_find(this, name);

	/**
	    The light that reaches everything evenly, from no direction: its color times
	    `intensity` (clamped to 0 or more). Default: none, an intensity of 0. Alpha is
	    ignored.
	**/
	public inline function setAmbient(color:Int, intensity:Float):Bool
		return Raw.wgf_stage3d_set_ambient(this, color, intensity);

	/**
	    The light that reaches everything evenly, from no direction: its color times
	    `intensity` (clamped to 0 or more). Default: none, an intensity of 0. Alpha is
	    ignored.
	**/
	public inline function getAmbientColor():Int
		return Raw.wgf_stage3d_get_ambient_color(this);

	/**
	    The light that reaches everything evenly, from no direction: its color times
	    `intensity` (clamped to 0 or more). Default: none, an intensity of 0. Alpha is
	    ignored.
	**/
	public inline function getAmbientIntensity():Float
		return Raw.wgf_stage3d_get_ambient_intensity(this);

	/**
	    Its tone mapping, and its exposure in stops (EV): +1 doubles the brightness. Default:
	    NEUTRAL, 0. False for a tone mapping that isn't one.
	**/
	public inline function setTonemap(tonemap:Stage3dTonemap, exposure:Float):Bool
		return Raw.wgf_stage3d_set_tonemap(this, tonemap, exposure);

	/**
	    Its tone mapping, and its exposure in stops (EV): +1 doubles the brightness. Default:
	    NEUTRAL, 0. False for a tone mapping that isn't one.
	**/
	public inline function getTonemap():Stage3dTonemap
		return Raw.wgf_stage3d_get_tonemap(this);

	/**
	    Its tone mapping, and its exposure in stops (EV): +1 doubles the brightness. Default:
	    NEUTRAL, 0. False for a tone mapping that isn't one.
	**/
	public inline function getExposure():Float
		return Raw.wgf_stage3d_get_exposure(this);

	/**
	    Light its PBR models with an environment (wgf_environment.h) as well as its lights and
	    ambient light: soft light from all around, and reflections sharp or blurred by each
	    surface's roughness, darkened by its occlusion. `intensity` scales it (1 as the image
	    is; clamped to 0 or more); `rotation` (radians) turns it about +y. 0 removes it.
	    Default: none. The stage holds a reference of its own; one not READY lights nothing
	    until it is. False when `environment` isn't one.
	**/
	public inline function setEnvironment(environment:Environment, intensity:Float, rotation:Float):Bool
		return Raw.wgf_stage3d_set_environment(this, environment, intensity, rotation);

	/**
	    Light its PBR models with an environment (wgf_environment.h) as well as its lights and
	    ambient light: soft light from all around, and reflections sharp or blurred by each
	    surface's roughness, darkened by its occlusion. `intensity` scales it (1 as the image
	    is; clamped to 0 or more); `rotation` (radians) turns it about +y. 0 removes it.
	    Default: none. The stage holds a reference of its own; one not READY lights nothing
	    until it is. False when `environment` isn't one.
	**/
	public inline function getEnvironment():Environment
		return Raw.wgf_stage3d_get_environment(this);

	/**
	    Light its PBR models with an environment (wgf_environment.h) as well as its lights and
	    ambient light: soft light from all around, and reflections sharp or blurred by each
	    surface's roughness, darkened by its occlusion. `intensity` scales it (1 as the image
	    is; clamped to 0 or more); `rotation` (radians) turns it about +y. 0 removes it.
	    Default: none. The stage holds a reference of its own; one not READY lights nothing
	    until it is. False when `environment` isn't one.
	**/
	public inline function getEnvironmentIntensity():Float
		return Raw.wgf_stage3d_get_environment_intensity(this);

	/**
	    Light its PBR models with an environment (wgf_environment.h) as well as its lights and
	    ambient light: soft light from all around, and reflections sharp or blurred by each
	    surface's roughness, darkened by its occlusion. `intensity` scales it (1 as the image
	    is; clamped to 0 or more); `rotation` (radians) turns it about +y. 0 removes it.
	    Default: none. The stage holds a reference of its own; one not READY lights nothing
	    until it is. False when `environment` isn't one.
	**/
	public inline function getEnvironmentRotation():Float
		return Raw.wgf_stage3d_get_environment_rotation(this);

	/**
	    Draw an environment behind everything the stage draws (a sky), before its models,
	    where nothing drawn before it in the frame's 3D is nearer: with the stage's environment
	    intensity and rotation when it is the same environment, else at 1 and unturned, and
	    tone mapped as the stage is. `blur` 0..1: sharp to fully blurred (clamped). 0 removes
	    it. Default: none. The stage holds a reference of its own; one not READY draws nothing
	    until it is. False when `environment` isn't one.
	**/
	public inline function setBackground(environment:Environment, blur:Float):Bool
		return Raw.wgf_stage3d_set_background(this, environment, blur);

	/**
	    Draw an environment behind everything the stage draws (a sky), before its models,
	    where nothing drawn before it in the frame's 3D is nearer: with the stage's environment
	    intensity and rotation when it is the same environment, else at 1 and unturned, and
	    tone mapped as the stage is. `blur` 0..1: sharp to fully blurred (clamped). 0 removes
	    it. Default: none. The stage holds a reference of its own; one not READY draws nothing
	    until it is. False when `environment` isn't one.
	**/
	public inline function getBackground():Environment
		return Raw.wgf_stage3d_get_background(this);

	/**
	    Draw an environment behind everything the stage draws (a sky), before its models,
	    where nothing drawn before it in the frame's 3D is nearer: with the stage's environment
	    intensity and rotation when it is the same environment, else at 1 and unturned, and
	    tone mapped as the stage is. `blur` 0..1: sharp to fully blurred (clamped). 0 removes
	    it. Default: none. The stage holds a reference of its own; one not READY draws nothing
	    until it is. False when `environment` isn't one.
	**/
	public inline function getBackgroundBlur():Float
		return Raw.wgf_stage3d_get_background_blur(this);

	/**
	    Skip models the camera can't see (on by default): each is tested by the box around it
	    as it is placed now, grown a little against rounding, against the camera's view
	    before it is drawn, which is far cheaper than drawing it. Turn it off to draw
	    everything, when checking whether a model's bounds are right, say.
	**/
	public inline function setCulling(culling:Bool):Bool
		return Raw.wgf_stage3d_set_culling(this, culling);

	/**
	    Skip models the camera can't see (on by default): each is tested by the box around it
	    as it is placed now, grown a little against rounding, against the camera's view
	    before it is drawn, which is far cheaper than drawing it. Turn it off to draw
	    everything, when checking whether a model's bounds are right, say.
	**/
	public inline function isCulling():Bool
		return Raw.wgf_stage3d_is_culling(this);
}
