// Generated by tools/gen_binding.py from the public headers: edit the headers or the generator, not this.
package wgf;

enum abstract TextureFilter(Int) from Int to Int {
	var LINEAR = 0;
	var NEAREST = 1;
}
