// Generated by tools/gen_binding.py from the public headers: edit the headers or the generator, not this.
package wgf;

/**
    A text node: a string drawn in a font, in a canvas. Its node's position is where its
    block of lines sits, by its alignment, and the node turns and scales it like any
    other. It holds a reference to its font (0: the default font). Text is a
    node (wgf_node.h): place, parent, and destroy it with the node calls.
**/
enum abstract TextHalign(Int) from Int to Int {
	var LEFT = 0;
	var CENTER = 1;
	var RIGHT = 2;
}
