// Generated by tools/gen_binding.py from the public headers: edit the headers or the generator, not this.
package wgf;

import wgf.impl.Raw;

/** A handle of kind wgf_texture_t (gfx/include/wgf_texture.h): 0 is none. **/
abstract Texture(Int) from Int to Int to wgf.Handle {
	/** Whether this is no handle (0); right on every target, where `== null` is not. **/
	public inline function isNone():Bool
		return this == 0;

	/**
	    A texture from an image file: PNG, JPEG, BMP, TGA, or GIF (its first frame). 0 only
	    when there is no room for another texture; a path or file that can't be loaded gives
	    a texture that FAILED. wgf_resource_get_path gives the file it read.
	**/
	public static inline function create(path:String):Texture
		return Raw.wgf_texture_create(path);

	/**
	    Its size in pixels; 0 until it is READY.
	**/
	public inline function getWidth():Int
		return Raw.wgf_texture_get_width(this);

	/**
	    Its size in pixels; 0 until it is READY.
	**/
	public inline function getHeight():Int
		return Raw.wgf_texture_get_height(this);

	/**
	    How it is sampled where it is drawn, from its mipmaps where it is drawn smaller than
	    it is (built when it loads). Default: clamp, linear. False for a handle that isn't a
	    texture, or a wrap or filter that isn't one.
	**/
	public inline function setSampling(wrap_u:TextureWrap, wrap_v:TextureWrap, filter:TextureFilter):Bool
		return Raw.wgf_texture_set_sampling(this, wrap_u, wrap_v, filter);

	/**
	    How it is sampled where it is drawn, from its mipmaps where it is drawn smaller than
	    it is (built when it loads). Default: clamp, linear. False for a handle that isn't a
	    texture, or a wrap or filter that isn't one.
	**/
	public inline function getWrapU():TextureWrap
		return Raw.wgf_texture_get_wrap_u(this);

	/**
	    How it is sampled where it is drawn, from its mipmaps where it is drawn smaller than
	    it is (built when it loads). Default: clamp, linear. False for a handle that isn't a
	    texture, or a wrap or filter that isn't one.
	**/
	public inline function getWrapV():TextureWrap
		return Raw.wgf_texture_get_wrap_v(this);

	/**
	    How it is sampled where it is drawn, from its mipmaps where it is drawn smaller than
	    it is (built when it loads). Default: clamp, linear. False for a handle that isn't a
	    texture, or a wrap or filter that isn't one.
	**/
	public inline function getFilter():TextureFilter
		return Raw.wgf_texture_get_filter(this);
}
