// Generated by tools/gen_binding.py from the public headers: edit the headers or the generator, not this.
package wgf;

/**
    A text actor: a string drawn in a font, on a 2D stage. Its actor's position is where its
    block of lines sits, by its alignment, and the actor turns and scales it like any
    other. It holds a reference to its font (0: the default font). Text is a
    actor (wgf_actor.h): place, parent, and destroy it with the actor calls.
**/
enum abstract TextHalign(Int) from Int to Int {
	var LEFT = 0;
	var CENTER = 1;
	var RIGHT = 2;
}
