// Generated by tools/gen_binding.py from the public headers: edit the headers or the generator, not this.
package wgf;

enum abstract TextValign(Int) from Int to Int {
	var TOP = 0;
	var MIDDLE = 1;
	var BOTTOM = 2;
}
