// Generated by tools/gen_binding.py from the public headers: edit the headers or the generator, not this.
package wgf;

import wgf.impl.Raw;

class Time {
	/**
	    Seconds since the runtime started, from a monotonic clock: it never goes back, and
	    isn't moved by changes to the wall clock. 0 when core isn't running.
	**/
	public static inline function getSeconds():Float
		return Raw.wgf_time_get_seconds();
}
