// Generated by tools/gen_binding.py from the public headers: edit the headers or the generator, not this.
package wgf;

import wgf.impl.Raw;

class Ui {
	/**
	    The frame's UI begun, the screen at its logical size as the root; false when one is
	    already begun, or outside a frame.
	**/
	public static inline function begin():Bool
		return Raw.wgf_ui_begin();

	/**
	    Laid out, answered, and drawn; boxes left open are closed, and the call is false
	    (logged). False too with no UI begun.
	**/
	public static inline function end():Bool
		return Raw.wgf_ui_end();

	/**
	    A box, its children laid out in `direction`; closed by wgf_ui_end_box. A panel is a
	    column drawn with the style's panel color, corners, and padding, and gapped by the
	    style's gap; closed by wgf_ui_end_panel. False for an end with nothing of its kind
	    open.
	**/
	public static inline function beginBox(id:String, direction:UiDirection):Bool
		return Raw.wgf_ui_begin_box(id, direction);

	/**
	    A box, its children laid out in `direction`; closed by wgf_ui_end_box. A panel is a
	    column drawn with the style's panel color, corners, and padding, and gapped by the
	    style's gap; closed by wgf_ui_end_panel. False for an end with nothing of its kind
	    open.
	**/
	public static inline function endBox():Bool
		return Raw.wgf_ui_end_box();

	/**
	    A box, its children laid out in `direction`; closed by wgf_ui_end_box. A panel is a
	    column drawn with the style's panel color, corners, and padding, and gapped by the
	    style's gap; closed by wgf_ui_end_panel. False for an end with nothing of its kind
	    open.
	**/
	public static inline function beginPanel(id:String):Bool
		return Raw.wgf_ui_begin_panel(id);

	/**
	    A box, its children laid out in `direction`; closed by wgf_ui_end_box. A panel is a
	    column drawn with the style's panel color, corners, and padding, and gapped by the
	    style's gap; closed by wgf_ui_end_panel. False for an end with nothing of its kind
	    open.
	**/
	public static inline function endPanel():Bool
		return Raw.wgf_ui_end_panel();

	/**
	    The open box's or panel's layout, before its first child; false after it, with none
	    open, for a sizing or alignment that isn't one, or a value below 0 (above 1 for a
	    percent). The open one is the program's to describe each frame: nothing keeps it to
	    read back. A color draws its background; 0 (the default) none.
	**/
	public static inline function setWidth(sizing:UiSizing, value:Float):Bool
		return Raw.wgf_ui_set_width(sizing, value);

	/**
	    The open box's or panel's layout, before its first child; false after it, with none
	    open, for a sizing or alignment that isn't one, or a value below 0 (above 1 for a
	    percent). The open one is the program's to describe each frame: nothing keeps it to
	    read back. A color draws its background; 0 (the default) none.
	**/
	public static inline function setHeight(sizing:UiSizing, value:Float):Bool
		return Raw.wgf_ui_set_height(sizing, value);

	/**
	    The open box's or panel's layout, before its first child; false after it, with none
	    open, for a sizing or alignment that isn't one, or a value below 0 (above 1 for a
	    percent). The open one is the program's to describe each frame: nothing keeps it to
	    read back. A color draws its background; 0 (the default) none.
	**/
	public static inline function setPadding(x:Float, y:Float):Bool
		return Raw.wgf_ui_set_padding(x, y);

	/**
	    The open box's or panel's layout, before its first child; false after it, with none
	    open, for a sizing or alignment that isn't one, or a value below 0 (above 1 for a
	    percent). The open one is the program's to describe each frame: nothing keeps it to
	    read back. A color draws its background; 0 (the default) none.
	**/
	public static inline function setGap(gap:Float):Bool
		return Raw.wgf_ui_set_gap(gap);

	/**
	    The open box's or panel's layout, before its first child; false after it, with none
	    open, for a sizing or alignment that isn't one, or a value below 0 (above 1 for a
	    percent). The open one is the program's to describe each frame: nothing keeps it to
	    read back. A color draws its background; 0 (the default) none.
	**/
	public static inline function setAlign(x:UiAlign, y:UiAlign):Bool
		return Raw.wgf_ui_set_align(x, y);

	/**
	    The open box's or panel's layout, before its first child; false after it, with none
	    open, for a sizing or alignment that isn't one, or a value below 0 (above 1 for a
	    percent). The open one is the program's to describe each frame: nothing keeps it to
	    read back. A color draws its background; 0 (the default) none.
	**/
	public static inline function setColor(color:Int):Bool
		return Raw.wgf_ui_set_color(color);

	/**
	    Text, in the style's font and text color, at `size` logical pixels (0 or less: the
	    style's text size), on one line per newline. False too for no text.
	**/
	public static inline function label(text:String, size:Float):Bool
		return Raw.wgf_ui_label(text, size);

	/**
	    Room, along the open box's direction: `size` logical pixels, or the room left (0).
	**/
	public static inline function spacer(size:Float):Bool
		return Raw.wgf_ui_spacer(size);

	/**
	    A button showing `text`, true in the frame it is activated. False too for no id.
	**/
	public static inline function button(id:String, text:String):Bool
		return Raw.wgf_ui_button(id, text);

	/**
	    The focus given to the button `id` (NULL or "": none), drawn as a key or pad would
	    draw it; false for an id of 64 bytes or more. The focused button's id, "" for none,
	    valid until the focus changes. These two work outside a begun UI too.
	**/
	public static inline function setFocus(id:String):Bool
		return Raw.wgf_ui_set_focus(id);

	/**
	    The focus given to the button `id` (NULL or "": none), drawn as a key or pad would
	    draw it; false for an id of 64 bytes or more. The focused button's id, "" for none,
	    valid until the focus changes. These two work outside a begun UI too.
	**/
	public static inline function getFocus():String
		return Raw.wgf_ui_get_focus();

	/**
	    False for a color or value that isn't one, or a value below 0. 0 for one that isn't.
	**/
	public static inline function setStyleColor(which:UiColor, color:Int):Bool
		return Raw.wgf_ui_set_style_color(which, color);

	/**
	    False for a color or value that isn't one, or a value below 0. 0 for one that isn't.
	**/
	public static inline function getStyleColor(which:UiColor):Int
		return Raw.wgf_ui_get_style_color(which);

	/**
	    False for a color or value that isn't one, or a value below 0. 0 for one that isn't.
	**/
	public static inline function setStyleValue(which:UiValue, value:Float):Bool
		return Raw.wgf_ui_set_style_value(which, value);

	/**
	    False for a color or value that isn't one, or a value below 0. 0 for one that isn't.
	**/
	public static inline function getStyleValue(which:UiValue):Float
		return Raw.wgf_ui_get_style_value(which);

	/**
	    False for a handle that isn't a font (0 is).
	**/
	public static inline function setStyleFont(font:Font):Bool
		return Raw.wgf_ui_set_style_font(font);

	/**
	    False for a handle that isn't a font (0 is).
	**/
	public static inline function getStyleFont():Font
		return Raw.wgf_ui_get_style_font();

	/**
	    False for a handle that isn't a font (0 is).
	**/
	public static inline function resetStyle():Void
		Raw.wgf_ui_reset_style();
}
