// Generated by tools/gen_binding.py from the public headers: edit the headers or the generator, not this.
package wgf;

/**
    Game UI, immediate mode: each frame the program describes the UI as it is now --
    boxes, panels, labels, buttons, progress bars -- between wgf_ui_begin and wgf_ui_end, inside the
    frame callback; libwgf lays it out (Clay), answers what the pointer, the keys, and the
    pads did to it, and draws it at wgf_ui_end, over what the frame drew before.

    The screen is the root: a column of everything given, centered both ways. A box lays
    its children out in a column or a row, sized to fit them unless set otherwise. A
    button's answer comes from where things were in the frame before, as with every
    immediate-mode UI: a UI that moves under the pointer is answered where it was.

    Focus: one button at a time has it, by its id. Arrow keys, Tab and Shift+Tab, and a
    pad's D-pad move it through the frame's buttons in the order they were given (the
    first press of one puts it on the first or the last); Enter, Space, or a pad's south
    button activates it. The pointer activates the button it is pressed and released over,
    and gives it the focus; a focus moved by keys or pads is drawn, one given by the
    pointer isn't. A focused button that isn't given in a frame loses the focus.

    The UI says when it has the pointer (wgf_input_set_pointer_captured): while the
    pointer is over a panel, a button, or a box with a color, or a press on a button is
    held; and the keyboard (wgf_input_set_keyboard_captured) while a button has the focus.
    A frame without wgf_ui_end lets both go.

    Ids name boxes, panels, and buttons, and are unique in a frame (Clay refuses a
    second, logged); a box or panel may have none (NULL or ""). Text is copied: it may
    change or go after the call. Every call but the style's is false outside a begun UI.
**/
enum abstract UiDirection(Int) from Int to Int {
	var COLUMN = 0;
	var ROW = 1;
}
