// Generated by tools/gen_binding.py from the public headers: edit the headers or the generator, not this.
package wgf;

enum abstract UiSizing(Int) from Int to Int {
	var FIT = 0;
	var GROW = 1;
	var FIXED = 2;
	var PERCENT = 3;
}
