// Generated by tools/gen_binding.py from the public headers: edit the headers or the generator, not this.
package wgf;

enum abstract UiValue(Int) from Int to Int {
	var TEXT_SIZE = 0;
	var PADDING = 1;
	var GAP = 2;
	var CORNER_RADIUS = 3;
	var BUTTON_PADDING = 4;
	var BUTTON_WIDTH = 5;
	var FOCUS_WIDTH = 6;
	var BAR_WIDTH = 7;
	var BAR_HEIGHT = 8;
}
