// Generated by tools/gen_binding.py from the public headers: edit the headers or the generator, not this.
package wgf;

import wgf.impl.Raw;

/** Vehicle's calls, on a Actor: `var x:Vehicle = handle` gives it them, and a Vehicle is still a Actor. **/
@:forward abstract Vehicle(Actor) from Actor to Actor {
	/**
	    Its wheels: 2 to 8 actors under it, in left and right pairs, front first; false for an
	    odd count, more than 8, or one that isn't an actor under it.
	**/
	public inline function setWheels(wheels:Array<Actor>):Bool
		return Raw.wgf_vehicle_set_wheels(this, cast wheels);

	/**
	    Its wheels: 2 to 8 actors under it, in left and right pairs, front first; false for an
	    odd count, more than 8, or one that isn't an actor under it.
	**/
	public inline function getWheelCount():Int
		return Raw.wgf_vehicle_get_wheel_count(this);

	/**
	    Its wheels: 2 to 8 actors under it, in left and right pairs, front first; false for an
	    odd count, more than 8, or one that isn't an actor under it.
	**/
	public inline function getWheel(index:Int):Actor
		return Raw.wgf_vehicle_get_wheel(this, index);

	/**
	    Each wheel's radius and width (m), its spring's travel (m), stiffness (Hz), and damping
	    (0 none, 1 just enough), the front pair's steering (radians), and the tires' grip
	    (1 a road tire's; more grips harder).
	**/
	public inline function setWheelSize(radius:Float, width:Float):Bool
		return Raw.wgf_vehicle_set_wheel_size(this, radius, width);

	/**
	    Each wheel's radius and width (m), its spring's travel (m), stiffness (Hz), and damping
	    (0 none, 1 just enough), the front pair's steering (radians), and the tires' grip
	    (1 a road tire's; more grips harder).
	**/
	public inline function setSuspension(travel:Float, stiffness:Float, damping:Float):Bool
		return Raw.wgf_vehicle_set_suspension(this, travel, stiffness, damping);

	/**
	    Each wheel's radius and width (m), its spring's travel (m), stiffness (Hz), and damping
	    (0 none, 1 just enough), the front pair's steering (radians), and the tires' grip
	    (1 a road tire's; more grips harder).
	**/
	public inline function setSteering(radians:Float):Bool
		return Raw.wgf_vehicle_set_steering(this, radians);

	/**
	    Each wheel's radius and width (m), its spring's travel (m), stiffness (Hz), and damping
	    (0 none, 1 just enough), the front pair's steering (radians), and the tires' grip
	    (1 a road tire's; more grips harder).
	**/
	public inline function setGrip(grip:Float):Bool
		return Raw.wgf_vehicle_set_grip(this, grip);

	/**
	    As set: (radius, width); (travel, stiffness, damping); radians; grip.
	**/
	public inline function getWheelSize(?into:wgf.Vec2):wgf.Vec2
		return Raw.wgf_vehicle_get_wheel_size(this, into);

	/**
	    As set: (radius, width); (travel, stiffness, damping); radians; grip.
	**/
	public inline function getSuspension(?into:wgf.Vec3):wgf.Vec3
		return Raw.wgf_vehicle_get_suspension(this, into);

	/**
	    As set: (radius, width); (travel, stiffness, damping); radians; grip.
	**/
	public inline function getSteering():Float
		return Raw.wgf_vehicle_get_steering(this);

	/**
	    As set: (radius, width); (travel, stiffness, damping); radians; grip.
	**/
	public inline function getGrip():Float
		return Raw.wgf_vehicle_get_grip(this);

	/**
	    The engine's torque (Nm) and top speed (rpm), its gearbox's forward ratios (1 to 8, the
	    first the lowest: 3.2 down to 0.9, say), and which axles it drives.
	**/
	public inline function setEngine(torque:Float, max_rpm:Float):Bool
		return Raw.wgf_vehicle_set_engine(this, torque, max_rpm);

	/**
	    The engine's torque (Nm) and top speed (rpm), its gearbox's forward ratios (1 to 8, the
	    first the lowest: 3.2 down to 0.9, say), and which axles it drives.
	**/
	public inline function setGears(ratios:Array<Float>):Bool
		return Raw.wgf_vehicle_set_gears(this, ratios);

	/**
	    The engine's torque (Nm) and top speed (rpm), its gearbox's forward ratios (1 to 8, the
	    first the lowest: 3.2 down to 0.9, say), and which axles it drives.
	**/
	public inline function setDrive(drive:VehicleDrive):Bool
		return Raw.wgf_vehicle_set_drive(this, drive);

	/**
	    As set: (torque, max_rpm); how many forward ratios, and ratio `index` (0 for one it
	    hasn't); the drive.
	**/
	public inline function getEngine(?into:wgf.Vec2):wgf.Vec2
		return Raw.wgf_vehicle_get_engine(this, into);

	/**
	    As set: (torque, max_rpm); how many forward ratios, and ratio `index` (0 for one it
	    hasn't); the drive.
	**/
	public inline function getGearCount():Int
		return Raw.wgf_vehicle_get_gear_count(this);

	/**
	    As set: (torque, max_rpm); how many forward ratios, and ratio `index` (0 for one it
	    hasn't); the drive.
	**/
	public inline function getGearRatio(index:Int):Float
		return Raw.wgf_vehicle_get_gear_ratio(this, index);

	/**
	    As set: (torque, max_rpm); how many forward ratios, and ratio `index` (0 for one it
	    hasn't); the drive.
	**/
	public inline function getDrive():VehicleDrive
		return Raw.wgf_vehicle_get_drive(this);

	/**
	    The driver's intent, until set again: throttle 0 to 1 (below 0 is reverse), brake 0 to 1,
	    steering -1 (full left) to 1 (full right), and the hand brake on the rear wheels; each
	    clamped. Set it each tick from the input (wgf_action.h).
	**/
	public inline function setInput(throttle:Float, brake:Float, steer:Float, hand_brake:Bool):Bool
		return Raw.wgf_vehicle_set_input(this, throttle, brake, steer, hand_brake);

	/**
	    How it goes: its speed along its +z (m/s; below 0 backing), the engine's rpm, the gear
	    it is in (1 the lowest, -1 reverse, 0 neutral), and how far wheel `index`'s tire slides
	    (0 gripping, 1 sliding: tire smoke above about 0.3; 0 for a wheel it hasn't, or in the
	    air).
	**/
	public inline function getSpeed():Float
		return Raw.wgf_vehicle_get_speed(this);

	/**
	    How it goes: its speed along its +z (m/s; below 0 backing), the engine's rpm, the gear
	    it is in (1 the lowest, -1 reverse, 0 neutral), and how far wheel `index`'s tire slides
	    (0 gripping, 1 sliding: tire smoke above about 0.3; 0 for a wheel it hasn't, or in the
	    air).
	**/
	public inline function getRpm():Float
		return Raw.wgf_vehicle_get_rpm(this);

	/**
	    How it goes: its speed along its +z (m/s; below 0 backing), the engine's rpm, the gear
	    it is in (1 the lowest, -1 reverse, 0 neutral), and how far wheel `index`'s tire slides
	    (0 gripping, 1 sliding: tire smoke above about 0.3; 0 for a wheel it hasn't, or in the
	    air).
	**/
	public inline function getGear():Int
		return Raw.wgf_vehicle_get_gear(this);

	/**
	    How it goes: its speed along its +z (m/s; below 0 backing), the engine's rpm, the gear
	    it is in (1 the lowest, -1 reverse, 0 neutral), and how far wheel `index`'s tire slides
	    (0 gripping, 1 sliding: tire smoke above about 0.3; 0 for a wheel it hasn't, or in the
	    air).
	**/
	public inline function getWheelSlip(index:Int):Float
		return Raw.wgf_vehicle_get_wheel_slip(this, index);

	/**
	    At rest where it is: its velocity, spin, wheels, engine, and gearbox stopped, its intent
	    none (a car put back on the grid: set its transform, then reset).
	**/
	public inline function reset():Bool
		return Raw.wgf_vehicle_reset(this);
}
