// Generated by tools/gen_binding.py from the public headers: edit the headers or the generator, not this.
package wgf;

import wgf.impl.Raw;

class Version {
	/**
	    The libwgf version, "MAJOR.MINOR.PATCH", from the repo's VERSION file.
	**/
	public static inline function get():String
		return Raw.wgf_version_get();

	/**
	    Its numbers: a binding built against one version checks them at start, and refuses a
	    library of another major or minor version (a patch apart is compatible).
	**/
	public static inline function getMajor():Int
		return Raw.wgf_version_get_major();

	/**
	    Its numbers: a binding built against one version checks them at start, and refuses a
	    library of another major or minor version (a patch apart is compatible).
	**/
	public static inline function getMinor():Int
		return Raw.wgf_version_get_minor();

	/**
	    Its numbers: a binding built against one version checks them at start, and refuses a
	    library of another major or minor version (a patch apart is compatible).
	**/
	public static inline function getPatch():Int
		return Raw.wgf_version_get_patch();
}
