// Generated by tools/gen_binding.py from the public headers: edit the headers or the generator, not this.
package wgf;

import wgf.impl.Raw;

class Window {
	/**
	    The title (default "libwgf"). Natively the window's title bar; on the web the
	    page's title. NULL counts as "".
	**/
	public static inline function setTitle(title:String):Void
		Raw.wgf_window_set_title(title);

	/**
	    The title (default "libwgf"). Natively the window's title bar; on the web the
	    page's title. NULL counts as "".
	**/
	public static inline function getTitle():String
		return Raw.wgf_window_get_title();

	/**
	    The size inside the window's frame (default 1024 by 768). Values under 1 are
	    refused (false). On the web, the canvas's size on the page: left to the page
	    unless set. Set, it is the canvas's own style, which wins over the page's: the
	    canvas stays that size, at the page's top left, whatever the browser window does,
	    so a game meant to fill the page doesn't set it on the web. A game written for one
	    size sets a presentation (wgf_presentation.h) instead, which fits it to whatever the
	    window is, and natively opens the window at that size when this isn't set.
	**/
	public static inline function setSize(width:Int, height:Int):Bool
		return Raw.wgf_window_set_size(width, height);

	/**
	    The size inside the window's frame (default 1024 by 768). Values under 1 are
	    refused (false). On the web, the canvas's size on the page: left to the page
	    unless set. Set, it is the canvas's own style, which wins over the page's: the
	    canvas stays that size, at the page's top left, whatever the browser window does,
	    so a game meant to fill the page doesn't set it on the web. A game written for one
	    size sets a presentation (wgf_presentation.h) instead, which fits it to whatever the
	    window is, and natively opens the window at that size when this isn't set.
	**/
	public static inline function getWidth():Int
		return Raw.wgf_window_get_width();

	/**
	    The size inside the window's frame (default 1024 by 768). Values under 1 are
	    refused (false). On the web, the canvas's size on the page: left to the page
	    unless set. Set, it is the canvas's own style, which wins over the page's: the
	    canvas stays that size, at the page's top left, whatever the browser window does,
	    so a game meant to fill the page doesn't set it on the web. A game written for one
	    size sets a presentation (wgf_presentation.h) instead, which fits it to whatever the
	    window is, and natively opens the window at that size when this isn't set.
	**/
	public static inline function getHeight():Int
		return Raw.wgf_window_get_height();

	/**
	    Fill the screen (default off). False where the platform can't; on the web it is
	    a request the browser grants only during a key press or click, so ask
	    wgf_window_is_fullscreen for the answer.
	**/
	public static inline function setFullscreen(fullscreen:Bool):Bool
		return Raw.wgf_window_set_fullscreen(fullscreen);

	/**
	    Fill the screen (default off). False where the platform can't; on the web it is
	    a request the browser grants only during a key press or click, so ask
	    wgf_window_is_fullscreen for the answer.
	**/
	public static inline function isFullscreen():Bool
		return Raw.wgf_window_is_fullscreen();

	/**
	    Whether the window can fill the screen at all: true on the desktop, and on the web
	    what the browser says (false in a frame that doesn't allow it). Ask before
	    offering a fullscreen key.
	**/
	public static inline function canFullscreen():Bool
		return Raw.wgf_window_can_fullscreen();

	/**
	    Where the window is: its top-left in the desktop's coordinates (0, 0 being the top-
	    left of the main monitor). False, and 0, where programs don't place their windows:
	    the web, and a Wayland desktop, whose compositor places them. Only once the window
	    is open.
	**/
	public static inline function setPosition(x:Int, y:Int):Bool
		return Raw.wgf_window_set_position(x, y);

	/**
	    Where the window is: its top-left in the desktop's coordinates (0, 0 being the top-
	    left of the main monitor). False, and 0, where programs don't place their windows:
	    the web, and a Wayland desktop, whose compositor places them. Only once the window
	    is open.
	**/
	public static inline function getX():Int
		return Raw.wgf_window_get_x();

	/**
	    Where the window is: its top-left in the desktop's coordinates (0, 0 being the top-
	    left of the main monitor). False, and 0, where programs don't place their windows:
	    the web, and a Wayland desktop, whose compositor places them. Only once the window
	    is open.
	**/
	public static inline function getY():Int
		return Raw.wgf_window_get_y();

	/**
	    The monitors, 0 up to the count, and the one the window is on: at least one, the
	    screen. Moving the window to another is false where programs don't place their
	    windows. A monitor's size is in logical pixels, its position in the desktop's
	    coordinates; 0 and "" for one that isn't there. Only once the window is open.
	**/
	public static inline function getMonitorCount():Int
		return Raw.wgf_window_get_monitor_count();

	/**
	    The monitors, 0 up to the count, and the one the window is on: at least one, the
	    screen. Moving the window to another is false where programs don't place their
	    windows. A monitor's size is in logical pixels, its position in the desktop's
	    coordinates; 0 and "" for one that isn't there. Only once the window is open.
	**/
	public static inline function setMonitor(monitor:Int):Bool
		return Raw.wgf_window_set_monitor(monitor);

	/**
	    The monitors, 0 up to the count, and the one the window is on: at least one, the
	    screen. Moving the window to another is false where programs don't place their
	    windows. A monitor's size is in logical pixels, its position in the desktop's
	    coordinates; 0 and "" for one that isn't there. Only once the window is open.
	**/
	public static inline function getMonitor():Int
		return Raw.wgf_window_get_monitor();

	/**
	    The monitors, 0 up to the count, and the one the window is on: at least one, the
	    screen. Moving the window to another is false where programs don't place their
	    windows. A monitor's size is in logical pixels, its position in the desktop's
	    coordinates; 0 and "" for one that isn't there. Only once the window is open.
	**/
	public static inline function getMonitorWidth(monitor:Int):Int
		return Raw.wgf_window_get_monitor_width(monitor);

	/**
	    The monitors, 0 up to the count, and the one the window is on: at least one, the
	    screen. Moving the window to another is false where programs don't place their
	    windows. A monitor's size is in logical pixels, its position in the desktop's
	    coordinates; 0 and "" for one that isn't there. Only once the window is open.
	**/
	public static inline function getMonitorHeight(monitor:Int):Int
		return Raw.wgf_window_get_monitor_height(monitor);

	/**
	    The monitors, 0 up to the count, and the one the window is on: at least one, the
	    screen. Moving the window to another is false where programs don't place their
	    windows. A monitor's size is in logical pixels, its position in the desktop's
	    coordinates; 0 and "" for one that isn't there. Only once the window is open.
	**/
	public static inline function getMonitorX(monitor:Int):Int
		return Raw.wgf_window_get_monitor_x(monitor);

	/**
	    The monitors, 0 up to the count, and the one the window is on: at least one, the
	    screen. Moving the window to another is false where programs don't place their
	    windows. A monitor's size is in logical pixels, its position in the desktop's
	    coordinates; 0 and "" for one that isn't there. Only once the window is open.
	**/
	public static inline function getMonitorY(monitor:Int):Int
		return Raw.wgf_window_get_monitor_y(monitor);

	/**
	    The monitors, 0 up to the count, and the one the window is on: at least one, the
	    screen. Moving the window to another is false where programs don't place their
	    windows. A monitor's size is in logical pixels, its position in the desktop's
	    coordinates; 0 and "" for one that isn't there. Only once the window is open.
	**/
	public static inline function getMonitorName(monitor:Int):String
		return Raw.wgf_window_get_monitor_name(monitor);

	/**
	    Shown (default) or hidden; the program runs either way. Hidden at open, then
	    shown once loaded, avoids showing an empty window.
	**/
	public static inline function setVisible(visible:Bool):Void
		Raw.wgf_window_set_visible(visible);

	/**
	    Shown (default) or hidden; the program runs either way. Hidden at open, then
	    shown once loaded, avoids showing an empty window.
	**/
	public static inline function isVisible():Bool
		return Raw.wgf_window_is_visible();

	/**
	    Whether the user can resize the window (default true), and whether it has a
	    title bar and border (default true). Desktop only: the web ignores them.
	**/
	public static inline function setResizable(resizable:Bool):Void
		Raw.wgf_window_set_resizable(resizable);

	/**
	    Whether the user can resize the window (default true), and whether it has a
	    title bar and border (default true). Desktop only: the web ignores them.
	**/
	public static inline function isResizable():Bool
		return Raw.wgf_window_is_resizable();

	/**
	    Whether the user can resize the window (default true), and whether it has a
	    title bar and border (default true). Desktop only: the web ignores them.
	**/
	public static inline function setDecorated(decorated:Bool):Void
		Raw.wgf_window_set_decorated(decorated);

	/**
	    Whether the user can resize the window (default true), and whether it has a
	    title bar and border (default true). Desktop only: the web ignores them.
	**/
	public static inline function isDecorated():Bool
		return Raw.wgf_window_is_decorated();

	/**
	    Whether the window has the keyboard. A game pauses itself on losing it, if it
	    wants to (wgf_loop_set_time_scale).
	**/
	public static inline function isFocused():Bool
		return Raw.wgf_window_is_focused();

	/**
	    Options fixed when the window opens: refused (false) once it has.
	      transparent  what is behind the window shows through where gfx clears with
	                   alpha below 1 (default off). Desktop: where the window system
	                   allows it; web: the page under the canvas
	      high_dpi     draw at the display's full density (default on); off draws one
	                   pixel per logical pixel, scaled up by the display: fewer pixels,
	                   softer edges
	      vsync        wait for the display between frames (default on); off runs as
	                   fast as it can, or at the target fps. The web is always in step
	                   with the display
	      msaa         smooth edges by drawing with 4 samples a pixel (default off): a
	                   request, which a platform may give fewer for; gfx draws with
	                   what the window got
	**/
	public static inline function setTransparent(transparent:Bool):Bool
		return Raw.wgf_window_set_transparent(transparent);

	/**
	    Options fixed when the window opens: refused (false) once it has.
	      transparent  what is behind the window shows through where gfx clears with
	                   alpha below 1 (default off). Desktop: where the window system
	                   allows it; web: the page under the canvas
	      high_dpi     draw at the display's full density (default on); off draws one
	                   pixel per logical pixel, scaled up by the display: fewer pixels,
	                   softer edges
	      vsync        wait for the display between frames (default on); off runs as
	                   fast as it can, or at the target fps. The web is always in step
	                   with the display
	      msaa         smooth edges by drawing with 4 samples a pixel (default off): a
	                   request, which a platform may give fewer for; gfx draws with
	                   what the window got
	**/
	public static inline function isTransparent():Bool
		return Raw.wgf_window_is_transparent();

	/**
	    Options fixed when the window opens: refused (false) once it has.
	      transparent  what is behind the window shows through where gfx clears with
	                   alpha below 1 (default off). Desktop: where the window system
	                   allows it; web: the page under the canvas
	      high_dpi     draw at the display's full density (default on); off draws one
	                   pixel per logical pixel, scaled up by the display: fewer pixels,
	                   softer edges
	      vsync        wait for the display between frames (default on); off runs as
	                   fast as it can, or at the target fps. The web is always in step
	                   with the display
	      msaa         smooth edges by drawing with 4 samples a pixel (default off): a
	                   request, which a platform may give fewer for; gfx draws with
	                   what the window got
	**/
	public static inline function setHighDpi(high_dpi:Bool):Bool
		return Raw.wgf_window_set_high_dpi(high_dpi);

	/**
	    Options fixed when the window opens: refused (false) once it has.
	      transparent  what is behind the window shows through where gfx clears with
	                   alpha below 1 (default off). Desktop: where the window system
	                   allows it; web: the page under the canvas
	      high_dpi     draw at the display's full density (default on); off draws one
	                   pixel per logical pixel, scaled up by the display: fewer pixels,
	                   softer edges
	      vsync        wait for the display between frames (default on); off runs as
	                   fast as it can, or at the target fps. The web is always in step
	                   with the display
	      msaa         smooth edges by drawing with 4 samples a pixel (default off): a
	                   request, which a platform may give fewer for; gfx draws with
	                   what the window got
	**/
	public static inline function isHighDpi():Bool
		return Raw.wgf_window_is_high_dpi();

	/**
	    Options fixed when the window opens: refused (false) once it has.
	      transparent  what is behind the window shows through where gfx clears with
	                   alpha below 1 (default off). Desktop: where the window system
	                   allows it; web: the page under the canvas
	      high_dpi     draw at the display's full density (default on); off draws one
	                   pixel per logical pixel, scaled up by the display: fewer pixels,
	                   softer edges
	      vsync        wait for the display between frames (default on); off runs as
	                   fast as it can, or at the target fps. The web is always in step
	                   with the display
	      msaa         smooth edges by drawing with 4 samples a pixel (default off): a
	                   request, which a platform may give fewer for; gfx draws with
	                   what the window got
	**/
	public static inline function setVsync(vsync:Bool):Bool
		return Raw.wgf_window_set_vsync(vsync);

	/**
	    Options fixed when the window opens: refused (false) once it has.
	      transparent  what is behind the window shows through where gfx clears with
	                   alpha below 1 (default off). Desktop: where the window system
	                   allows it; web: the page under the canvas
	      high_dpi     draw at the display's full density (default on); off draws one
	                   pixel per logical pixel, scaled up by the display: fewer pixels,
	                   softer edges
	      vsync        wait for the display between frames (default on); off runs as
	                   fast as it can, or at the target fps. The web is always in step
	                   with the display
	      msaa         smooth edges by drawing with 4 samples a pixel (default off): a
	                   request, which a platform may give fewer for; gfx draws with
	                   what the window got
	**/
	public static inline function isVsync():Bool
		return Raw.wgf_window_is_vsync();

	/**
	    Options fixed when the window opens: refused (false) once it has.
	      transparent  what is behind the window shows through where gfx clears with
	                   alpha below 1 (default off). Desktop: where the window system
	                   allows it; web: the page under the canvas
	      high_dpi     draw at the display's full density (default on); off draws one
	                   pixel per logical pixel, scaled up by the display: fewer pixels,
	                   softer edges
	      vsync        wait for the display between frames (default on); off runs as
	                   fast as it can, or at the target fps. The web is always in step
	                   with the display
	      msaa         smooth edges by drawing with 4 samples a pixel (default off): a
	                   request, which a platform may give fewer for; gfx draws with
	                   what the window got
	**/
	public static inline function setMsaa(msaa:Bool):Bool
		return Raw.wgf_window_set_msaa(msaa);

	/**
	    Options fixed when the window opens: refused (false) once it has.
	      transparent  what is behind the window shows through where gfx clears with
	                   alpha below 1 (default off). Desktop: where the window system
	                   allows it; web: the page under the canvas
	      high_dpi     draw at the display's full density (default on); off draws one
	                   pixel per logical pixel, scaled up by the display: fewer pixels,
	                   softer edges
	      vsync        wait for the display between frames (default on); off runs as
	                   fast as it can, or at the target fps. The web is always in step
	                   with the display
	      msaa         smooth edges by drawing with 4 samples a pixel (default off): a
	                   request, which a platform may give fewer for; gfx draws with
	                   what the window got
	**/
	public static inline function isMsaa():Bool
		return Raw.wgf_window_is_msaa();
}
