// Generated by tools/gen_binding.py from the public headers: edit the headers or the generator, not this.
package wgf.impl;

/** Each exported C call for the JS target: the host's export by its quoted key. **/
class Raw {
	/** The wasm host every call goes through (Host.attach). **/
	public static var host:haxe.DynamicAccess<Dynamic> = Host.notAttached();

	public static function wgf_version_get():String {
		final value:Dynamic = Raw.host["_wgf_version_get"]();
		return Host.str(value);
	}
	public static function wgf_version_get_major():Int {
		final value:Dynamic = Raw.host["_wgf_version_get_major"]();
		return value;
	}
	public static function wgf_version_get_minor():Int {
		final value:Dynamic = Raw.host["_wgf_version_get_minor"]();
		return value;
	}
	public static function wgf_version_get_patch():Int {
		final value:Dynamic = Raw.host["_wgf_version_get_patch"]();
		return value;
	}
	public static function wgf_handle_get_kind_name(handle:Int):String {
		final value:Dynamic = Raw.host["_wgf_handle_get_kind_name"](handle);
		return Host.str(value);
	}
	public static function wgf_fs_set_root(root:String):Bool {
		final mark = Host.stackSave();
		final value:Dynamic = Raw.host["_wgf_fs_set_root"](Host.cstr(root));
		Host.stackRestore(mark);
		return value != 0;
	}
	public static function wgf_fs_get_root():String {
		final value:Dynamic = Raw.host["_wgf_fs_get_root"]();
		return Host.str(value);
	}
	public static function wgf_fs_read(path:String):Int {
		final mark = Host.stackSave();
		final value:Dynamic = Raw.host["_wgf_fs_read"](Host.cstr(path));
		Host.stackRestore(mark);
		return value;
	}
	public static function wgf_fs_write(path:String, data:haxe.io.Bytes):Int {
		final mark = Host.stackSave();
		final dataPointer = Host.bytesIn(data, 0);
		final value:Dynamic = Raw.host["_wgf_fs_write"](Host.cstr(path), dataPointer, (data == null ? 0 : data.length));
		Host.stackRestore(mark);
		return value;
	}
	public static function wgf_fs_exists(path:String):Int {
		final mark = Host.stackSave();
		final value:Dynamic = Raw.host["_wgf_fs_exists"](Host.cstr(path));
		Host.stackRestore(mark);
		return value;
	}
	public static function wgf_fs_remove(path:String):Int {
		final mark = Host.stackSave();
		final value:Dynamic = Raw.host["_wgf_fs_remove"](Host.cstr(path));
		Host.stackRestore(mark);
		return value;
	}
	public static function wgf_fs_mkdir(path:String):Int {
		final mark = Host.stackSave();
		final value:Dynamic = Raw.host["_wgf_fs_mkdir"](Host.cstr(path));
		Host.stackRestore(mark);
		return value;
	}
	public static function wgf_fs_rmdir(path:String):Int {
		final mark = Host.stackSave();
		final value:Dynamic = Raw.host["_wgf_fs_rmdir"](Host.cstr(path));
		Host.stackRestore(mark);
		return value;
	}
	public static function wgf_fs_task_get_status(task:Int):Int {
		final value:Dynamic = Raw.host["_wgf_fs_task_get_status"](task);
		return value;
	}
	public static function wgf_fs_task_get_path(task:Int):String {
		final value:Dynamic = Raw.host["_wgf_fs_task_get_path"](task);
		return Host.str(value);
	}
	public static function wgf_fs_task_get_data(task:Int):haxe.io.Bytes {
		final value:Dynamic = Raw.host["_wgf_fs_task_get_data"](task);
		return Host.bytesOut(value, (Raw.host["_wgf_fs_task_get_size"](task) : Int));
	}
	public static function wgf_fs_task_get_size(task:Int):Int {
		final value:Dynamic = Raw.host["_wgf_fs_task_get_size"](task);
		return value;
	}
	public static function wgf_fs_task_get_text(task:Int):String {
		final value:Dynamic = Raw.host["_wgf_fs_task_get_text"](task);
		return Host.str(value);
	}
	public static function wgf_fs_task_destroy(task:Int):Bool {
		final value:Dynamic = Raw.host["_wgf_fs_task_destroy"](task);
		return value != 0;
	}
	public static function wgf_identity_set_company(company:String):Bool {
		final mark = Host.stackSave();
		final value:Dynamic = Raw.host["_wgf_identity_set_company"](Host.cstr(company));
		Host.stackRestore(mark);
		return value != 0;
	}
	public static function wgf_identity_get_company():String {
		final value:Dynamic = Raw.host["_wgf_identity_get_company"]();
		return Host.str(value);
	}
	public static function wgf_identity_set_product(name:String):Bool {
		final mark = Host.stackSave();
		final value:Dynamic = Raw.host["_wgf_identity_set_product"](Host.cstr(name));
		Host.stackRestore(mark);
		return value != 0;
	}
	public static function wgf_identity_get_product():String {
		final value:Dynamic = Raw.host["_wgf_identity_get_product"]();
		return Host.str(value);
	}
	public static function wgf_log_set_level(level:Int):Void {
		Raw.host["_wgf_log_set_level"](level);
	}
	public static function wgf_log_get_level():Int {
		final value:Dynamic = Raw.host["_wgf_log_get_level"]();
		return value;
	}
	public static function wgf_log_message(level:Int, text:String):Void {
		final mark = Host.stackSave();
		Raw.host["_wgf_log_message"](level, Host.cstr(text));
		Host.stackRestore(mark);
	}
	public static function wgf_log_message_source(level:Int, file:String, line:Int, text:String):Void {
		final mark = Host.stackSave();
		Raw.host["_wgf_log_message_source"](level, Host.cstr(file), line, Host.cstr(text));
		Host.stackRestore(mark);
	}
	public static function wgf_probe_set_value(name:String, value:Float):Bool {
		final mark = Host.stackSave();
		final value:Dynamic = Raw.host["_wgf_probe_set_value"](Host.cstr(name), value);
		Host.stackRestore(mark);
		return value != 0;
	}
	public static function wgf_probe_get_value(name:String):Float {
		final mark = Host.stackSave();
		final value:Dynamic = Raw.host["_wgf_probe_get_value"](Host.cstr(name));
		Host.stackRestore(mark);
		return value;
	}
	public static function wgf_probe_has_value(name:String):Bool {
		final mark = Host.stackSave();
		final value:Dynamic = Raw.host["_wgf_probe_has_value"](Host.cstr(name));
		Host.stackRestore(mark);
		return value != 0;
	}
	public static function wgf_probe_get_count():Int {
		final value:Dynamic = Raw.host["_wgf_probe_get_count"]();
		return value;
	}
	public static function wgf_probe_get_name(index:Int):String {
		final value:Dynamic = Raw.host["_wgf_probe_get_name"](index);
		return Host.str(value);
	}
	public static function wgf_random_set_seed(seed:Int):Void {
		Raw.host["_wgf_random_set_seed"](seed);
	}
	public static function wgf_random_get_seed():Int {
		final value:Dynamic = Raw.host["_wgf_random_get_seed"]();
		return value;
	}
	public static function wgf_random_get_float():Float {
		final value:Dynamic = Raw.host["_wgf_random_get_float"]();
		return value;
	}
	public static function wgf_random_get_range(min:Float, max:Float):Float {
		final value:Dynamic = Raw.host["_wgf_random_get_range"](min, max);
		return value;
	}
	public static function wgf_random_get_int(min:Int, max:Int):Int {
		final value:Dynamic = Raw.host["_wgf_random_get_int"](min, max);
		return value;
	}
	public static function wgf_resource_get_status(resource:Int):Int {
		final value:Dynamic = Raw.host["_wgf_resource_get_status"](resource);
		return value;
	}
	public static function wgf_resource_get_path(resource:Int):String {
		final value:Dynamic = Raw.host["_wgf_resource_get_path"](resource);
		return Host.str(value);
	}
	public static function wgf_resource_release(resource:Int):Bool {
		final value:Dynamic = Raw.host["_wgf_resource_release"](resource);
		return value != 0;
	}
	public static function wgf_resource_set_load_budget(milliseconds:Float):Bool {
		final value:Dynamic = Raw.host["_wgf_resource_set_load_budget"](milliseconds);
		return value != 0;
	}
	public static function wgf_resource_get_load_budget():Float {
		final value:Dynamic = Raw.host["_wgf_resource_get_load_budget"]();
		return value;
	}
	public static function wgf_time_get_seconds():Float {
		final value:Dynamic = Raw.host["_wgf_time_get_seconds"]();
		return value;
	}
	public static function wgf_input_get_chars():String {
		final value:Dynamic = Raw.host["_wgf_input_get_chars"]();
		return Host.str(value);
	}
	public static function wgf_input_set_pointer_captured(captured:Bool):Void {
		Raw.host["_wgf_input_set_pointer_captured"]((captured ? 1 : 0));
	}
	public static function wgf_input_is_pointer_captured():Bool {
		final value:Dynamic = Raw.host["_wgf_input_is_pointer_captured"]();
		return value != 0;
	}
	public static function wgf_input_set_keyboard_captured(captured:Bool):Void {
		Raw.host["_wgf_input_set_keyboard_captured"]((captured ? 1 : 0));
	}
	public static function wgf_input_is_keyboard_captured():Bool {
		final value:Dynamic = Raw.host["_wgf_input_is_keyboard_captured"]();
		return value != 0;
	}
	public static function wgf_gamepad_is_connected(pad:Int):Bool {
		final value:Dynamic = Raw.host["_wgf_gamepad_is_connected"](pad);
		return value != 0;
	}
	public static function wgf_gamepad_get_name(pad:Int):String {
		final value:Dynamic = Raw.host["_wgf_gamepad_get_name"](pad);
		return Host.str(value);
	}
	public static function wgf_gamepad_get_button_state(pad:Int, button:Int):Int {
		final value:Dynamic = Raw.host["_wgf_gamepad_get_button_state"](pad, button);
		return value;
	}
	public static function wgf_gamepad_is_down(pad:Int, button:Int):Bool {
		final value:Dynamic = Raw.host["_wgf_gamepad_is_down"](pad, button);
		return value != 0;
	}
	public static function wgf_gamepad_is_pressed(pad:Int, button:Int):Bool {
		final value:Dynamic = Raw.host["_wgf_gamepad_is_pressed"](pad, button);
		return value != 0;
	}
	public static function wgf_gamepad_is_released(pad:Int, button:Int):Bool {
		final value:Dynamic = Raw.host["_wgf_gamepad_is_released"](pad, button);
		return value != 0;
	}
	public static function wgf_gamepad_get_stick(pad:Int, stick:Int, into:Null<wgf.Vec2>):wgf.Vec2 {
		final result = Host.result(8);
		Raw.host["_wgf_gamepad_get_stick"](result, pad, stick);
		return Host.vec2(result, into);
	}
	public static function wgf_gamepad_get_trigger(pad:Int, trigger:Int):Float {
		final value:Dynamic = Raw.host["_wgf_gamepad_get_trigger"](pad, trigger);
		return value;
	}
	public static function wgf_gamepad_set_deadzone(radius:Float):Void {
		Raw.host["_wgf_gamepad_set_deadzone"](radius);
	}
	public static function wgf_gamepad_get_deadzone():Float {
		final value:Dynamic = Raw.host["_wgf_gamepad_get_deadzone"]();
		return value;
	}
	public static function wgf_keyboard_get_state(key:Int):Int {
		final value:Dynamic = Raw.host["_wgf_keyboard_get_state"](key);
		return value;
	}
	public static function wgf_keyboard_is_down(key:Int):Bool {
		final value:Dynamic = Raw.host["_wgf_keyboard_is_down"](key);
		return value != 0;
	}
	public static function wgf_keyboard_is_pressed(key:Int):Bool {
		final value:Dynamic = Raw.host["_wgf_keyboard_is_pressed"](key);
		return value != 0;
	}
	public static function wgf_keyboard_is_released(key:Int):Bool {
		final value:Dynamic = Raw.host["_wgf_keyboard_is_released"](key);
		return value != 0;
	}
	public static function wgf_mouse_get_position(into:Null<wgf.Vec2>):wgf.Vec2 {
		final result = Host.result(8);
		Raw.host["_wgf_mouse_get_position"](result);
		return Host.vec2(result, into);
	}
	public static function wgf_mouse_get_delta(into:Null<wgf.Vec2>):wgf.Vec2 {
		final result = Host.result(8);
		Raw.host["_wgf_mouse_get_delta"](result);
		return Host.vec2(result, into);
	}
	public static function wgf_mouse_get_wheel(into:Null<wgf.Vec2>):wgf.Vec2 {
		final result = Host.result(8);
		Raw.host["_wgf_mouse_get_wheel"](result);
		return Host.vec2(result, into);
	}
	public static function wgf_mouse_get_button_state(button:Int):Int {
		final value:Dynamic = Raw.host["_wgf_mouse_get_button_state"](button);
		return value;
	}
	public static function wgf_mouse_is_down(button:Int):Bool {
		final value:Dynamic = Raw.host["_wgf_mouse_is_down"](button);
		return value != 0;
	}
	public static function wgf_mouse_is_pressed(button:Int):Bool {
		final value:Dynamic = Raw.host["_wgf_mouse_is_pressed"](button);
		return value != 0;
	}
	public static function wgf_mouse_is_released(button:Int):Bool {
		final value:Dynamic = Raw.host["_wgf_mouse_is_released"](button);
		return value != 0;
	}
	public static function wgf_mouse_set_locked(locked:Bool):Void {
		Raw.host["_wgf_mouse_set_locked"]((locked ? 1 : 0));
	}
	public static function wgf_mouse_is_locked():Bool {
		final value:Dynamic = Raw.host["_wgf_mouse_is_locked"]();
		return value != 0;
	}
	public static function wgf_mouse_set_cursor_visible(visible:Bool):Void {
		Raw.host["_wgf_mouse_set_cursor_visible"]((visible ? 1 : 0));
	}
	public static function wgf_mouse_is_cursor_visible():Bool {
		final value:Dynamic = Raw.host["_wgf_mouse_is_cursor_visible"]();
		return value != 0;
	}
	public static function wgf_touch_get_count():Int {
		final value:Dynamic = Raw.host["_wgf_touch_get_count"]();
		return value;
	}
	public static function wgf_touch_get_id(index:Int):Int {
		final value:Dynamic = Raw.host["_wgf_touch_get_id"](index);
		return value;
	}
	public static function wgf_touch_get_state(id:Int):Int {
		final value:Dynamic = Raw.host["_wgf_touch_get_state"](id);
		return value;
	}
	public static function wgf_touch_get_position(id:Int, into:Null<wgf.Vec2>):wgf.Vec2 {
		final result = Host.result(8);
		Raw.host["_wgf_touch_get_position"](result, id);
		return Host.vec2(result, into);
	}
	public static function wgf_touch_get_delta(id:Int, into:Null<wgf.Vec2>):wgf.Vec2 {
		final result = Host.result(8);
		Raw.host["_wgf_touch_get_delta"](result, id);
		return Host.vec2(result, into);
	}
	public static function wgf_touch_set_mouse_emulated(emulated:Bool):Void {
		Raw.host["_wgf_touch_set_mouse_emulated"]((emulated ? 1 : 0));
	}
	public static function wgf_touch_is_mouse_emulated():Bool {
		final value:Dynamic = Raw.host["_wgf_touch_is_mouse_emulated"]();
		return value != 0;
	}
	public static function wgf_touch_is_gesture():Bool {
		final value:Dynamic = Raw.host["_wgf_touch_is_gesture"]();
		return value != 0;
	}
	public static function wgf_touch_get_gesture_center(into:Null<wgf.Vec2>):wgf.Vec2 {
		final result = Host.result(8);
		Raw.host["_wgf_touch_get_gesture_center"](result);
		return Host.vec2(result, into);
	}
	public static function wgf_touch_get_gesture_pan(into:Null<wgf.Vec2>):wgf.Vec2 {
		final result = Host.result(8);
		Raw.host["_wgf_touch_get_gesture_pan"](result);
		return Host.vec2(result, into);
	}
	public static function wgf_touch_get_gesture_scale():Float {
		final value:Dynamic = Raw.host["_wgf_touch_get_gesture_scale"]();
		return value;
	}
	public static function wgf_touch_get_gesture_rotation():Float {
		final value:Dynamic = Raw.host["_wgf_touch_get_gesture_rotation"]();
		return value;
	}
	public static function wgf_window_set_title(title:String):Void {
		final mark = Host.stackSave();
		Raw.host["_wgf_window_set_title"](Host.cstr(title));
		Host.stackRestore(mark);
	}
	public static function wgf_window_get_title():String {
		final value:Dynamic = Raw.host["_wgf_window_get_title"]();
		return Host.str(value);
	}
	public static function wgf_window_set_size(width:Int, height:Int):Bool {
		final value:Dynamic = Raw.host["_wgf_window_set_size"](width, height);
		return value != 0;
	}
	public static function wgf_window_get_width():Int {
		final value:Dynamic = Raw.host["_wgf_window_get_width"]();
		return value;
	}
	public static function wgf_window_get_height():Int {
		final value:Dynamic = Raw.host["_wgf_window_get_height"]();
		return value;
	}
	public static function wgf_window_set_fullscreen(fullscreen:Bool):Bool {
		final value:Dynamic = Raw.host["_wgf_window_set_fullscreen"]((fullscreen ? 1 : 0));
		return value != 0;
	}
	public static function wgf_window_is_fullscreen():Bool {
		final value:Dynamic = Raw.host["_wgf_window_is_fullscreen"]();
		return value != 0;
	}
	public static function wgf_window_can_fullscreen():Bool {
		final value:Dynamic = Raw.host["_wgf_window_can_fullscreen"]();
		return value != 0;
	}
	public static function wgf_window_set_position(x:Int, y:Int):Bool {
		final value:Dynamic = Raw.host["_wgf_window_set_position"](x, y);
		return value != 0;
	}
	public static function wgf_window_get_x():Int {
		final value:Dynamic = Raw.host["_wgf_window_get_x"]();
		return value;
	}
	public static function wgf_window_get_y():Int {
		final value:Dynamic = Raw.host["_wgf_window_get_y"]();
		return value;
	}
	public static function wgf_window_get_monitor_count():Int {
		final value:Dynamic = Raw.host["_wgf_window_get_monitor_count"]();
		return value;
	}
	public static function wgf_window_set_monitor(monitor:Int):Bool {
		final value:Dynamic = Raw.host["_wgf_window_set_monitor"](monitor);
		return value != 0;
	}
	public static function wgf_window_get_monitor():Int {
		final value:Dynamic = Raw.host["_wgf_window_get_monitor"]();
		return value;
	}
	public static function wgf_window_get_monitor_width(monitor:Int):Int {
		final value:Dynamic = Raw.host["_wgf_window_get_monitor_width"](monitor);
		return value;
	}
	public static function wgf_window_get_monitor_height(monitor:Int):Int {
		final value:Dynamic = Raw.host["_wgf_window_get_monitor_height"](monitor);
		return value;
	}
	public static function wgf_window_get_monitor_x(monitor:Int):Int {
		final value:Dynamic = Raw.host["_wgf_window_get_monitor_x"](monitor);
		return value;
	}
	public static function wgf_window_get_monitor_y(monitor:Int):Int {
		final value:Dynamic = Raw.host["_wgf_window_get_monitor_y"](monitor);
		return value;
	}
	public static function wgf_window_get_monitor_name(monitor:Int):String {
		final value:Dynamic = Raw.host["_wgf_window_get_monitor_name"](monitor);
		return Host.str(value);
	}
	public static function wgf_window_set_visible(visible:Bool):Void {
		Raw.host["_wgf_window_set_visible"]((visible ? 1 : 0));
	}
	public static function wgf_window_is_visible():Bool {
		final value:Dynamic = Raw.host["_wgf_window_is_visible"]();
		return value != 0;
	}
	public static function wgf_window_set_resizable(resizable:Bool):Void {
		Raw.host["_wgf_window_set_resizable"]((resizable ? 1 : 0));
	}
	public static function wgf_window_is_resizable():Bool {
		final value:Dynamic = Raw.host["_wgf_window_is_resizable"]();
		return value != 0;
	}
	public static function wgf_window_set_decorated(decorated:Bool):Void {
		Raw.host["_wgf_window_set_decorated"]((decorated ? 1 : 0));
	}
	public static function wgf_window_is_decorated():Bool {
		final value:Dynamic = Raw.host["_wgf_window_is_decorated"]();
		return value != 0;
	}
	public static function wgf_window_is_focused():Bool {
		final value:Dynamic = Raw.host["_wgf_window_is_focused"]();
		return value != 0;
	}
	public static function wgf_window_set_transparent(transparent:Bool):Bool {
		final value:Dynamic = Raw.host["_wgf_window_set_transparent"]((transparent ? 1 : 0));
		return value != 0;
	}
	public static function wgf_window_is_transparent():Bool {
		final value:Dynamic = Raw.host["_wgf_window_is_transparent"]();
		return value != 0;
	}
	public static function wgf_window_set_high_dpi(high_dpi:Bool):Bool {
		final value:Dynamic = Raw.host["_wgf_window_set_high_dpi"]((high_dpi ? 1 : 0));
		return value != 0;
	}
	public static function wgf_window_is_high_dpi():Bool {
		final value:Dynamic = Raw.host["_wgf_window_is_high_dpi"]();
		return value != 0;
	}
	public static function wgf_window_set_vsync(vsync:Bool):Bool {
		final value:Dynamic = Raw.host["_wgf_window_set_vsync"]((vsync ? 1 : 0));
		return value != 0;
	}
	public static function wgf_window_is_vsync():Bool {
		final value:Dynamic = Raw.host["_wgf_window_is_vsync"]();
		return value != 0;
	}
	public static function wgf_window_set_msaa(msaa:Bool):Bool {
		final value:Dynamic = Raw.host["_wgf_window_set_msaa"]((msaa ? 1 : 0));
		return value != 0;
	}
	public static function wgf_window_is_msaa():Bool {
		final value:Dynamic = Raw.host["_wgf_window_is_msaa"]();
		return value != 0;
	}
	public static function wgf_asset_set_host(host:String):Bool {
		final mark = Host.stackSave();
		final value:Dynamic = Raw.host["_wgf_asset_set_host"](Host.cstr(host));
		Host.stackRestore(mark);
		return value != 0;
	}
	public static function wgf_asset_get_host():String {
		final value:Dynamic = Raw.host["_wgf_asset_get_host"]();
		return Host.str(value);
	}
	public static function wgf_asset_set_cache_dir(dir:String):Bool {
		final mark = Host.stackSave();
		final value:Dynamic = Raw.host["_wgf_asset_set_cache_dir"](Host.cstr(dir));
		Host.stackRestore(mark);
		return value != 0;
	}
	public static function wgf_asset_get_cache_dir():String {
		final value:Dynamic = Raw.host["_wgf_asset_get_cache_dir"]();
		return Host.str(value);
	}
	public static function wgf_asset_set_fetching(enabled:Bool):Bool {
		final value:Dynamic = Raw.host["_wgf_asset_set_fetching"]((enabled ? 1 : 0));
		return value != 0;
	}
	public static function wgf_asset_is_fetching():Bool {
		final value:Dynamic = Raw.host["_wgf_asset_is_fetching"]();
		return value != 0;
	}
	public static function wgf_asset_fetch_next():Int {
		final value:Dynamic = Raw.host["_wgf_asset_fetch_next"]();
		return value;
	}
	public static function wgf_asset_fetch_get_url(request:Int):String {
		final value:Dynamic = Raw.host["_wgf_asset_fetch_get_url"](request);
		return Host.str(value);
	}
	public static function wgf_asset_fetch_get_dest(request:Int):String {
		final value:Dynamic = Raw.host["_wgf_asset_fetch_get_dest"](request);
		return Host.str(value);
	}
	public static function wgf_asset_fetch_is_ping(request:Int):Bool {
		final value:Dynamic = Raw.host["_wgf_asset_fetch_is_ping"](request);
		return value != 0;
	}
	public static function wgf_asset_fetch_done(request:Int, ok:Bool):Bool {
		final value:Dynamic = Raw.host["_wgf_asset_fetch_done"](request, (ok ? 1 : 0));
		return value != 0;
	}
	public static function wgf_asset_set_fetch_timeout(seconds:Float):Bool {
		final value:Dynamic = Raw.host["_wgf_asset_set_fetch_timeout"](seconds);
		return value != 0;
	}
	public static function wgf_asset_get_fetch_timeout():Float {
		final value:Dynamic = Raw.host["_wgf_asset_get_fetch_timeout"]();
		return value;
	}
	public static function wgf_asset_evict(path:String):Bool {
		final mark = Host.stackSave();
		final value:Dynamic = Raw.host["_wgf_asset_evict"](Host.cstr(path));
		Host.stackRestore(mark);
		return value != 0;
	}
	public static function wgf_asset_clear_cache():Void {
		Raw.host["_wgf_asset_clear_cache"]();
	}
	public static function wgf_asset_set_cache_mode(mode:Int):Bool {
		final value:Dynamic = Raw.host["_wgf_asset_set_cache_mode"](mode);
		return value != 0;
	}
	public static function wgf_asset_get_cache_mode():Int {
		final value:Dynamic = Raw.host["_wgf_asset_get_cache_mode"]();
		return value;
	}
	public static function wgf_asset_set_manifest(path:String):Bool {
		final mark = Host.stackSave();
		final value:Dynamic = Raw.host["_wgf_asset_set_manifest"](Host.cstr(path));
		Host.stackRestore(mark);
		return value != 0;
	}
	public static function wgf_asset_get_manifest():String {
		final value:Dynamic = Raw.host["_wgf_asset_get_manifest"]();
		return Host.str(value);
	}
	public static function wgf_asset_ensure(path:String, fetch_url:String, flags:Int):Int {
		final mark = Host.stackSave();
		final value:Dynamic = Raw.host["_wgf_asset_ensure"](Host.cstr(path), Host.cstr(fetch_url), flags);
		Host.stackRestore(mark);
		return value;
	}
	public static function wgf_asset_task_get_status(task:Int):Int {
		final value:Dynamic = Raw.host["_wgf_asset_task_get_status"](task);
		return value;
	}
	public static function wgf_asset_task_get_path(task:Int):String {
		final value:Dynamic = Raw.host["_wgf_asset_task_get_path"](task);
		return Host.str(value);
	}
	public static function wgf_asset_task_get_progress(task:Int):Float {
		final value:Dynamic = Raw.host["_wgf_asset_task_get_progress"](task);
		return value;
	}
	public static function wgf_asset_task_destroy(task:Int):Bool {
		final value:Dynamic = Raw.host["_wgf_asset_task_destroy"](task);
		return value != 0;
	}
	public static function wgf_asset_group_create():Int {
		final value:Dynamic = Raw.host["_wgf_asset_group_create"]();
		return value;
	}
	public static function wgf_asset_group_add(group:Int, task:Int):Bool {
		final value:Dynamic = Raw.host["_wgf_asset_group_add"](group, task);
		return value != 0;
	}
	public static function wgf_asset_add_redirect(prefix:String, target:String):Bool {
		final mark = Host.stackSave();
		final value:Dynamic = Raw.host["_wgf_asset_add_redirect"](Host.cstr(prefix), Host.cstr(target));
		Host.stackRestore(mark);
		return value != 0;
	}
	public static function wgf_asset_clear_redirects():Void {
		Raw.host["_wgf_asset_clear_redirects"]();
	}
	public static function wgf_asset_ping_host(host:String, timeout_ms:Int):Int {
		final mark = Host.stackSave();
		final value:Dynamic = Raw.host["_wgf_asset_ping_host"](Host.cstr(host), timeout_ms);
		Host.stackRestore(mark);
		return value;
	}
	public static function wgf_asset_ping_get_milliseconds(ping:Int):Float {
		final value:Dynamic = Raw.host["_wgf_asset_ping_get_milliseconds"](ping);
		return value;
	}
	public static function wgf_node_create():Int {
		final value:Dynamic = Raw.host["_wgf_node_create"]();
		return value;
	}
	public static function wgf_node_destroy(node:Int, children:Int):Void {
		Raw.host["_wgf_node_destroy"](node, children);
	}
	public static function wgf_node_get_type(node:Int):Int {
		final value:Dynamic = Raw.host["_wgf_node_get_type"](node);
		return value;
	}
	public static function wgf_node_set_parent(node:Int, parent:Int):Bool {
		final value:Dynamic = Raw.host["_wgf_node_set_parent"](node, parent);
		return value != 0;
	}
	public static function wgf_node_get_parent(node:Int):Int {
		final value:Dynamic = Raw.host["_wgf_node_get_parent"](node);
		return value;
	}
	public static function wgf_node_get_child_count(node:Int):Int {
		final value:Dynamic = Raw.host["_wgf_node_get_child_count"](node);
		return value;
	}
	public static function wgf_node_get_child(node:Int, index:Int):Int {
		final value:Dynamic = Raw.host["_wgf_node_get_child"](node, index);
		return value;
	}
	public static function wgf_node_set_index(node:Int, index:Int):Bool {
		final value:Dynamic = Raw.host["_wgf_node_set_index"](node, index);
		return value != 0;
	}
	public static function wgf_node_get_index(node:Int):Int {
		final value:Dynamic = Raw.host["_wgf_node_get_index"](node);
		return value;
	}
	public static function wgf_node_set_position(node:Int, x:Float, y:Float, z:Float):Bool {
		final value:Dynamic = Raw.host["_wgf_node_set_position"](node, x, y, z);
		return value != 0;
	}
	public static function wgf_node_get_position(node:Int, into:Null<wgf.Vec3>):wgf.Vec3 {
		final result = Host.result(12);
		Raw.host["_wgf_node_get_position"](result, node);
		return Host.vec3(result, into);
	}
	public static function wgf_node_set_rotation(node:Int, x:Float, y:Float, z:Float):Bool {
		final value:Dynamic = Raw.host["_wgf_node_set_rotation"](node, x, y, z);
		return value != 0;
	}
	public static function wgf_node_get_rotation(node:Int, into:Null<wgf.Vec3>):wgf.Vec3 {
		final result = Host.result(12);
		Raw.host["_wgf_node_get_rotation"](result, node);
		return Host.vec3(result, into);
	}
	public static function wgf_node_set_scale(node:Int, x:Float, y:Float, z:Float):Bool {
		final value:Dynamic = Raw.host["_wgf_node_set_scale"](node, x, y, z);
		return value != 0;
	}
	public static function wgf_node_get_scale(node:Int, into:Null<wgf.Vec3>):wgf.Vec3 {
		final result = Host.result(12);
		Raw.host["_wgf_node_get_scale"](result, node);
		return Host.vec3(result, into);
	}
	public static function wgf_node_set_transform(node:Int, position_x:Float, position_y:Float, position_z:Float, rotation_x:Float, rotation_y:Float, rotation_z:Float, scale_x:Float, scale_y:Float, scale_z:Float):Bool {
		final value:Dynamic = Raw.host["_wgf_node_set_transform"](node, position_x, position_y, position_z, rotation_x, rotation_y, rotation_z, scale_x, scale_y, scale_z);
		return value != 0;
	}
	public static function wgf_node_get_world_position(node:Int, into:Null<wgf.Vec3>):wgf.Vec3 {
		final result = Host.result(12);
		Raw.host["_wgf_node_get_world_position"](result, node);
		return Host.vec3(result, into);
	}
	public static function wgf_node_set_name(node:Int, name:String):Bool {
		final mark = Host.stackSave();
		final value:Dynamic = Raw.host["_wgf_node_set_name"](node, Host.cstr(name));
		Host.stackRestore(mark);
		return value != 0;
	}
	public static function wgf_node_get_name(node:Int):String {
		final value:Dynamic = Raw.host["_wgf_node_get_name"](node);
		return Host.str(value);
	}
	public static function wgf_node_find(root:Int, name:String):Int {
		final mark = Host.stackSave();
		final value:Dynamic = Raw.host["_wgf_node_find"](root, Host.cstr(name));
		Host.stackRestore(mark);
		return value;
	}
	public static function wgf_node_set_enabled(node:Int, enabled:Bool):Bool {
		final value:Dynamic = Raw.host["_wgf_node_set_enabled"](node, (enabled ? 1 : 0));
		return value != 0;
	}
	public static function wgf_node_is_enabled(node:Int):Bool {
		final value:Dynamic = Raw.host["_wgf_node_is_enabled"](node);
		return value != 0;
	}
	public static function wgf_node_set_visible(node:Int, visible:Bool):Bool {
		final value:Dynamic = Raw.host["_wgf_node_set_visible"](node, (visible ? 1 : 0));
		return value != 0;
	}
	public static function wgf_node_is_visible(node:Int):Bool {
		final value:Dynamic = Raw.host["_wgf_node_is_visible"](node);
		return value != 0;
	}
	public static function wgf_camera2d_create():Int {
		final value:Dynamic = Raw.host["_wgf_camera2d_create"]();
		return value;
	}
	public static function wgf_camera2d_set_zoom(camera:Int, zoom:Float):Bool {
		final value:Dynamic = Raw.host["_wgf_camera2d_set_zoom"](camera, zoom);
		return value != 0;
	}
	public static function wgf_camera2d_get_zoom(camera:Int):Float {
		final value:Dynamic = Raw.host["_wgf_camera2d_get_zoom"](camera);
		return value;
	}
	public static function wgf_canvas_create():Int {
		final value:Dynamic = Raw.host["_wgf_canvas_create"]();
		return value;
	}
	public static function wgf_canvas_draw(canvas:Int):Void {
		Raw.host["_wgf_canvas_draw"](canvas);
	}
	public static function wgf_canvas_set_camera(canvas:Int, camera:Int):Bool {
		final value:Dynamic = Raw.host["_wgf_canvas_set_camera"](canvas, camera);
		return value != 0;
	}
	public static function wgf_canvas_get_camera(canvas:Int):Int {
		final value:Dynamic = Raw.host["_wgf_canvas_get_camera"](canvas);
		return value;
	}
	public static function wgf_color_get(stock:Int):Int {
		final value:Dynamic = Raw.host["_wgf_color_get"](stock);
		return value;
	}
	public static function wgf_color_make(r:Int, g:Int, b:Int, a:Int):Int {
		final value:Dynamic = Raw.host["_wgf_color_make"](r, g, b, a);
		return value;
	}
	public static function wgf_color_make_float(r:Float, g:Float, b:Float, a:Float):Int {
		final value:Dynamic = Raw.host["_wgf_color_make_float"](r, g, b, a);
		return value;
	}
	public static function wgf_color_with_alpha(color:Int, a:Int):Int {
		final value:Dynamic = Raw.host["_wgf_color_with_alpha"](color, a);
		return value;
	}
	public static function wgf_color_get_red(color:Int):Int {
		final value:Dynamic = Raw.host["_wgf_color_get_red"](color);
		return value;
	}
	public static function wgf_color_get_green(color:Int):Int {
		final value:Dynamic = Raw.host["_wgf_color_get_green"](color);
		return value;
	}
	public static function wgf_color_get_blue(color:Int):Int {
		final value:Dynamic = Raw.host["_wgf_color_get_blue"](color);
		return value;
	}
	public static function wgf_color_get_alpha(color:Int):Int {
		final value:Dynamic = Raw.host["_wgf_color_get_alpha"](color);
		return value;
	}
	public static function wgf_color_lerp(from:Int, to:Int, t:Float):Int {
		final value:Dynamic = Raw.host["_wgf_color_lerp"](from, to, t);
		return value;
	}
	public static function wgf_font_create(path:String):Int {
		final mark = Host.stackSave();
		final value:Dynamic = Raw.host["_wgf_font_create"](Host.cstr(path));
		Host.stackRestore(mark);
		return value;
	}
	public static function wgf_font_set_default(font:Int):Bool {
		final value:Dynamic = Raw.host["_wgf_font_set_default"](font);
		return value != 0;
	}
	public static function wgf_font_get_default():Int {
		final value:Dynamic = Raw.host["_wgf_font_get_default"]();
		return value;
	}
	public static function wgf_font_measure(font:Int, text:String, size:Float, into:Null<wgf.Vec2>):wgf.Vec2 {
		final mark = Host.stackSave();
		final result = Host.result(8);
		Raw.host["_wgf_font_measure"](result, font, Host.cstr(text), size);
		Host.stackRestore(mark);
		return Host.vec2(result, into);
	}
	public static function wgf_texture_create(path:String):Int {
		final mark = Host.stackSave();
		final value:Dynamic = Raw.host["_wgf_texture_create"](Host.cstr(path));
		Host.stackRestore(mark);
		return value;
	}
	public static function wgf_texture_get_width(texture:Int):Int {
		final value:Dynamic = Raw.host["_wgf_texture_get_width"](texture);
		return value;
	}
	public static function wgf_texture_get_height(texture:Int):Int {
		final value:Dynamic = Raw.host["_wgf_texture_get_height"](texture);
		return value;
	}
	public static function wgf_texture_set_sampling(texture:Int, wrap_u:Int, wrap_v:Int, filter:Int):Bool {
		final value:Dynamic = Raw.host["_wgf_texture_set_sampling"](texture, wrap_u, wrap_v, filter);
		return value != 0;
	}
	public static function wgf_texture_get_wrap_u(texture:Int):Int {
		final value:Dynamic = Raw.host["_wgf_texture_get_wrap_u"](texture);
		return value;
	}
	public static function wgf_texture_get_wrap_v(texture:Int):Int {
		final value:Dynamic = Raw.host["_wgf_texture_get_wrap_v"](texture);
		return value;
	}
	public static function wgf_texture_get_filter(texture:Int):Int {
		final value:Dynamic = Raw.host["_wgf_texture_get_filter"](texture);
		return value;
	}
	public static function wgf_draw_rectangle(x:Float, y:Float, width:Float, height:Float, color:Int):Void {
		Raw.host["_wgf_draw_rectangle"](x, y, width, height, color);
	}
	public static function wgf_draw_rectangle_lines(x:Float, y:Float, width:Float, height:Float, thickness:Float, color:Int):Void {
		Raw.host["_wgf_draw_rectangle_lines"](x, y, width, height, thickness, color);
	}
	public static function wgf_draw_line(x0:Float, y0:Float, x1:Float, y1:Float, thickness:Float, color:Int):Void {
		Raw.host["_wgf_draw_line"](x0, y0, x1, y1, thickness, color);
	}
	public static function wgf_draw_circle(center_x:Float, center_y:Float, radius:Float, color:Int):Void {
		Raw.host["_wgf_draw_circle"](center_x, center_y, radius, color);
	}
	public static function wgf_draw_circle_lines(center_x:Float, center_y:Float, radius:Float, thickness:Float, color:Int):Void {
		Raw.host["_wgf_draw_circle_lines"](center_x, center_y, radius, thickness, color);
	}
	public static function wgf_draw_triangle(x0:Float, y0:Float, x1:Float, y1:Float, x2:Float, y2:Float, color:Int):Void {
		Raw.host["_wgf_draw_triangle"](x0, y0, x1, y1, x2, y2, color);
	}
	public static function wgf_draw_polyline(points:Array<Float>, closed:Bool, thickness:Float, color:Int):Bool {
		final pointsPointer = Host.floatsIn(points, 0);
		final value:Dynamic = Raw.host["_wgf_draw_polyline"](pointsPointer, (points == null ? 0 : points.length), (closed ? 1 : 0), thickness, color);
		return value != 0;
	}
	public static function wgf_draw_polygon(points:Array<Float>, color:Int):Bool {
		final pointsPointer = Host.floatsIn(points, 0);
		final value:Dynamic = Raw.host["_wgf_draw_polygon"](pointsPointer, (points == null ? 0 : points.length), color);
		return value != 0;
	}
	public static function wgf_draw_text(font:Int, text:String, x:Float, y:Float, size:Float, color:Int):Void {
		final mark = Host.stackSave();
		Raw.host["_wgf_draw_text"](font, Host.cstr(text), x, y, size, color);
		Host.stackRestore(mark);
	}
	public static function wgf_draw_texture(texture:Int, x:Float, y:Float, width:Float, height:Float, tint:Int):Void {
		Raw.host["_wgf_draw_texture"](texture, x, y, width, height, tint);
	}
	public static function wgf_draw_texture_region(texture:Int, source_x:Float, source_y:Float, source_width:Float, source_height:Float, x:Float, y:Float, width:Float, height:Float, tint:Int):Void {
		Raw.host["_wgf_draw_texture_region"](texture, source_x, source_y, source_width, source_height, x, y, width, height, tint);
	}
	public static function wgf_emitter2d_create():Int {
		final value:Dynamic = Raw.host["_wgf_emitter2d_create"]();
		return value;
	}
	public static function wgf_emitter2d_set_rate(emitter:Int, per_second:Float):Bool {
		final value:Dynamic = Raw.host["_wgf_emitter2d_set_rate"](emitter, per_second);
		return value != 0;
	}
	public static function wgf_emitter2d_get_rate(emitter:Int):Float {
		final value:Dynamic = Raw.host["_wgf_emitter2d_get_rate"](emitter);
		return value;
	}
	public static function wgf_emitter2d_set_emitting(emitter:Int, emitting:Bool):Bool {
		final value:Dynamic = Raw.host["_wgf_emitter2d_set_emitting"](emitter, (emitting ? 1 : 0));
		return value != 0;
	}
	public static function wgf_emitter2d_is_emitting(emitter:Int):Bool {
		final value:Dynamic = Raw.host["_wgf_emitter2d_is_emitting"](emitter);
		return value != 0;
	}
	public static function wgf_emitter2d_burst(emitter:Int, count:Int):Bool {
		final value:Dynamic = Raw.host["_wgf_emitter2d_burst"](emitter, count);
		return value != 0;
	}
	public static function wgf_emitter2d_set_capacity(emitter:Int, capacity:Int):Bool {
		final value:Dynamic = Raw.host["_wgf_emitter2d_set_capacity"](emitter, capacity);
		return value != 0;
	}
	public static function wgf_emitter2d_get_capacity(emitter:Int):Int {
		final value:Dynamic = Raw.host["_wgf_emitter2d_get_capacity"](emitter);
		return value;
	}
	public static function wgf_emitter2d_get_count(emitter:Int):Int {
		final value:Dynamic = Raw.host["_wgf_emitter2d_get_count"](emitter);
		return value;
	}
	public static function wgf_emitter2d_set_life(emitter:Int, min:Float, max:Float):Bool {
		final value:Dynamic = Raw.host["_wgf_emitter2d_set_life"](emitter, min, max);
		return value != 0;
	}
	public static function wgf_emitter2d_get_life_min(emitter:Int):Float {
		final value:Dynamic = Raw.host["_wgf_emitter2d_get_life_min"](emitter);
		return value;
	}
	public static function wgf_emitter2d_get_life_max(emitter:Int):Float {
		final value:Dynamic = Raw.host["_wgf_emitter2d_get_life_max"](emitter);
		return value;
	}
	public static function wgf_emitter2d_set_direction(emitter:Int, angle:Float, spread:Float):Bool {
		final value:Dynamic = Raw.host["_wgf_emitter2d_set_direction"](emitter, angle, spread);
		return value != 0;
	}
	public static function wgf_emitter2d_get_direction(emitter:Int):Float {
		final value:Dynamic = Raw.host["_wgf_emitter2d_get_direction"](emitter);
		return value;
	}
	public static function wgf_emitter2d_get_spread(emitter:Int):Float {
		final value:Dynamic = Raw.host["_wgf_emitter2d_get_spread"](emitter);
		return value;
	}
	public static function wgf_emitter2d_set_speed(emitter:Int, min:Float, max:Float):Bool {
		final value:Dynamic = Raw.host["_wgf_emitter2d_set_speed"](emitter, min, max);
		return value != 0;
	}
	public static function wgf_emitter2d_get_speed_min(emitter:Int):Float {
		final value:Dynamic = Raw.host["_wgf_emitter2d_get_speed_min"](emitter);
		return value;
	}
	public static function wgf_emitter2d_get_speed_max(emitter:Int):Float {
		final value:Dynamic = Raw.host["_wgf_emitter2d_get_speed_max"](emitter);
		return value;
	}
	public static function wgf_emitter2d_set_radius(emitter:Int, radius:Float):Bool {
		final value:Dynamic = Raw.host["_wgf_emitter2d_set_radius"](emitter, radius);
		return value != 0;
	}
	public static function wgf_emitter2d_get_radius(emitter:Int):Float {
		final value:Dynamic = Raw.host["_wgf_emitter2d_get_radius"](emitter);
		return value;
	}
	public static function wgf_emitter2d_set_gravity(emitter:Int, x:Float, y:Float):Bool {
		final value:Dynamic = Raw.host["_wgf_emitter2d_set_gravity"](emitter, x, y);
		return value != 0;
	}
	public static function wgf_emitter2d_get_gravity(emitter:Int, into:Null<wgf.Vec2>):wgf.Vec2 {
		final result = Host.result(8);
		Raw.host["_wgf_emitter2d_get_gravity"](result, emitter);
		return Host.vec2(result, into);
	}
	public static function wgf_emitter2d_set_drag(emitter:Int, drag:Float):Bool {
		final value:Dynamic = Raw.host["_wgf_emitter2d_set_drag"](emitter, drag);
		return value != 0;
	}
	public static function wgf_emitter2d_get_drag(emitter:Int):Float {
		final value:Dynamic = Raw.host["_wgf_emitter2d_get_drag"](emitter);
		return value;
	}
	public static function wgf_emitter2d_set_size(emitter:Int, start:Float, end:Float):Bool {
		final value:Dynamic = Raw.host["_wgf_emitter2d_set_size"](emitter, start, end);
		return value != 0;
	}
	public static function wgf_emitter2d_get_size_start(emitter:Int):Float {
		final value:Dynamic = Raw.host["_wgf_emitter2d_get_size_start"](emitter);
		return value;
	}
	public static function wgf_emitter2d_get_size_end(emitter:Int):Float {
		final value:Dynamic = Raw.host["_wgf_emitter2d_get_size_end"](emitter);
		return value;
	}
	public static function wgf_emitter2d_set_color(emitter:Int, start:Int, end:Int):Bool {
		final value:Dynamic = Raw.host["_wgf_emitter2d_set_color"](emitter, start, end);
		return value != 0;
	}
	public static function wgf_emitter2d_get_color_start(emitter:Int):Int {
		final value:Dynamic = Raw.host["_wgf_emitter2d_get_color_start"](emitter);
		return value;
	}
	public static function wgf_emitter2d_get_color_end(emitter:Int):Int {
		final value:Dynamic = Raw.host["_wgf_emitter2d_get_color_end"](emitter);
		return value;
	}
	public static function wgf_emitter2d_set_stretch(emitter:Int, seconds:Float):Bool {
		final value:Dynamic = Raw.host["_wgf_emitter2d_set_stretch"](emitter, seconds);
		return value != 0;
	}
	public static function wgf_emitter2d_get_stretch(emitter:Int):Float {
		final value:Dynamic = Raw.host["_wgf_emitter2d_get_stretch"](emitter);
		return value;
	}
	public static function wgf_emitter2d_clear(emitter:Int):Bool {
		final value:Dynamic = Raw.host["_wgf_emitter2d_clear"](emitter);
		return value != 0;
	}
	public static function wgf_render_set_clear_color(color:Int):Void {
		Raw.host["_wgf_render_set_clear_color"](color);
	}
	public static function wgf_render_get_clear_color():Int {
		final value:Dynamic = Raw.host["_wgf_render_get_clear_color"]();
		return value;
	}
	public static function wgf_render_get_width():Int {
		final value:Dynamic = Raw.host["_wgf_render_get_width"]();
		return value;
	}
	public static function wgf_render_get_height():Int {
		final value:Dynamic = Raw.host["_wgf_render_get_height"]();
		return value;
	}
	public static function wgf_render_get_dpi_scale():Float {
		final value:Dynamic = Raw.host["_wgf_render_get_dpi_scale"]();
		return value;
	}
	public static function wgf_render_push_clip(x:Float, y:Float, width:Float, height:Float):Void {
		Raw.host["_wgf_render_push_clip"](x, y, width, height);
	}
	public static function wgf_render_pop_clip():Void {
		Raw.host["_wgf_render_pop_clip"]();
	}
	public static function wgf_shape2d_create():Int {
		final value:Dynamic = Raw.host["_wgf_shape2d_create"]();
		return value;
	}
	public static function wgf_shape2d_get_kind(shape:Int):Int {
		final value:Dynamic = Raw.host["_wgf_shape2d_get_kind"](shape);
		return value;
	}
	public static function wgf_shape2d_set_rectangle(shape:Int, width:Float, height:Float):Bool {
		final value:Dynamic = Raw.host["_wgf_shape2d_set_rectangle"](shape, width, height);
		return value != 0;
	}
	public static function wgf_shape2d_set_circle(shape:Int, radius:Float):Bool {
		final value:Dynamic = Raw.host["_wgf_shape2d_set_circle"](shape, radius);
		return value != 0;
	}
	public static function wgf_shape2d_set_line(shape:Int, x0:Float, y0:Float, x1:Float, y1:Float):Bool {
		final value:Dynamic = Raw.host["_wgf_shape2d_set_line"](shape, x0, y0, x1, y1);
		return value != 0;
	}
	public static function wgf_shape2d_set_polygon(shape:Int, points:Array<Float>):Bool {
		final pointsPointer = Host.floatsIn(points, 0);
		final value:Dynamic = Raw.host["_wgf_shape2d_set_polygon"](shape, pointsPointer, (points == null ? 0 : points.length));
		return value != 0;
	}
	public static function wgf_shape2d_get_size(shape:Int, into:Null<wgf.Vec2>):wgf.Vec2 {
		final result = Host.result(8);
		Raw.host["_wgf_shape2d_get_size"](result, shape);
		return Host.vec2(result, into);
	}
	public static function wgf_shape2d_get_radius(shape:Int):Float {
		final value:Dynamic = Raw.host["_wgf_shape2d_get_radius"](shape);
		return value;
	}
	public static function wgf_shape2d_get_line_start(shape:Int, into:Null<wgf.Vec2>):wgf.Vec2 {
		final result = Host.result(8);
		Raw.host["_wgf_shape2d_get_line_start"](result, shape);
		return Host.vec2(result, into);
	}
	public static function wgf_shape2d_get_line_end(shape:Int, into:Null<wgf.Vec2>):wgf.Vec2 {
		final result = Host.result(8);
		Raw.host["_wgf_shape2d_get_line_end"](result, shape);
		return Host.vec2(result, into);
	}
	public static function wgf_shape2d_get_point_count(shape:Int):Int {
		final value:Dynamic = Raw.host["_wgf_shape2d_get_point_count"](shape);
		return value;
	}
	public static function wgf_shape2d_get_points(shape:Int, out:Array<Float>):Int {
		final outPointer = Host.arrayOut(out, 0);
		final value:Dynamic = Raw.host["_wgf_shape2d_get_points"](shape, outPointer, (out == null ? 0 : out.length));
		Host.floatsOut(outPointer, out);
		return value;
	}
	public static function wgf_shape2d_set_pivot(shape:Int, x:Float, y:Float):Bool {
		final value:Dynamic = Raw.host["_wgf_shape2d_set_pivot"](shape, x, y);
		return value != 0;
	}
	public static function wgf_shape2d_get_pivot(shape:Int, into:Null<wgf.Vec2>):wgf.Vec2 {
		final result = Host.result(8);
		Raw.host["_wgf_shape2d_get_pivot"](result, shape);
		return Host.vec2(result, into);
	}
	public static function wgf_shape2d_set_outline(shape:Int, thickness:Float):Bool {
		final value:Dynamic = Raw.host["_wgf_shape2d_set_outline"](shape, thickness);
		return value != 0;
	}
	public static function wgf_shape2d_get_outline(shape:Int):Float {
		final value:Dynamic = Raw.host["_wgf_shape2d_get_outline"](shape);
		return value;
	}
	public static function wgf_shape2d_set_color(shape:Int, color:Int):Bool {
		final value:Dynamic = Raw.host["_wgf_shape2d_set_color"](shape, color);
		return value != 0;
	}
	public static function wgf_shape2d_get_color(shape:Int):Int {
		final value:Dynamic = Raw.host["_wgf_shape2d_get_color"](shape);
		return value;
	}
	public static function wgf_sprite_create(texture:Int):Int {
		final value:Dynamic = Raw.host["_wgf_sprite_create"](texture);
		return value;
	}
	public static function wgf_sprite_set_texture(sprite:Int, texture:Int):Bool {
		final value:Dynamic = Raw.host["_wgf_sprite_set_texture"](sprite, texture);
		return value != 0;
	}
	public static function wgf_sprite_get_texture(sprite:Int):Int {
		final value:Dynamic = Raw.host["_wgf_sprite_get_texture"](sprite);
		return value;
	}
	public static function wgf_sprite_set_source(sprite:Int, x:Float, y:Float, width:Float, height:Float):Bool {
		final value:Dynamic = Raw.host["_wgf_sprite_set_source"](sprite, x, y, width, height);
		return value != 0;
	}
	public static function wgf_sprite_get_source(sprite:Int, into:Null<wgf.Vec4>):wgf.Vec4 {
		final result = Host.result(16);
		Raw.host["_wgf_sprite_get_source"](result, sprite);
		return Host.vec4(result, into);
	}
	public static function wgf_sprite_set_size(sprite:Int, width:Float, height:Float):Bool {
		final value:Dynamic = Raw.host["_wgf_sprite_set_size"](sprite, width, height);
		return value != 0;
	}
	public static function wgf_sprite_get_size(sprite:Int, into:Null<wgf.Vec2>):wgf.Vec2 {
		final result = Host.result(8);
		Raw.host["_wgf_sprite_get_size"](result, sprite);
		return Host.vec2(result, into);
	}
	public static function wgf_sprite_set_pivot(sprite:Int, x:Float, y:Float):Bool {
		final value:Dynamic = Raw.host["_wgf_sprite_set_pivot"](sprite, x, y);
		return value != 0;
	}
	public static function wgf_sprite_get_pivot(sprite:Int, into:Null<wgf.Vec2>):wgf.Vec2 {
		final result = Host.result(8);
		Raw.host["_wgf_sprite_get_pivot"](result, sprite);
		return Host.vec2(result, into);
	}
	public static function wgf_sprite_set_tint(sprite:Int, tint:Int):Bool {
		final value:Dynamic = Raw.host["_wgf_sprite_set_tint"](sprite, tint);
		return value != 0;
	}
	public static function wgf_sprite_get_tint(sprite:Int):Int {
		final value:Dynamic = Raw.host["_wgf_sprite_get_tint"](sprite);
		return value;
	}
	public static function wgf_text_create(font:Int):Int {
		final value:Dynamic = Raw.host["_wgf_text_create"](font);
		return value;
	}
	public static function wgf_text_set_font(text:Int, font:Int):Bool {
		final value:Dynamic = Raw.host["_wgf_text_set_font"](text, font);
		return value != 0;
	}
	public static function wgf_text_get_font(text:Int):Int {
		final value:Dynamic = Raw.host["_wgf_text_get_font"](text);
		return value;
	}
	public static function wgf_text_set_string(text:Int, string:String):Bool {
		final mark = Host.stackSave();
		final value:Dynamic = Raw.host["_wgf_text_set_string"](text, Host.cstr(string));
		Host.stackRestore(mark);
		return value != 0;
	}
	public static function wgf_text_get_string(text:Int):String {
		final value:Dynamic = Raw.host["_wgf_text_get_string"](text);
		return Host.str(value);
	}
	public static function wgf_text_set_font_size(text:Int, size:Float):Bool {
		final value:Dynamic = Raw.host["_wgf_text_set_font_size"](text, size);
		return value != 0;
	}
	public static function wgf_text_get_font_size(text:Int):Float {
		final value:Dynamic = Raw.host["_wgf_text_get_font_size"](text);
		return value;
	}
	public static function wgf_text_set_color(text:Int, color:Int):Bool {
		final value:Dynamic = Raw.host["_wgf_text_set_color"](text, color);
		return value != 0;
	}
	public static function wgf_text_get_color(text:Int):Int {
		final value:Dynamic = Raw.host["_wgf_text_get_color"](text);
		return value;
	}
	public static function wgf_text_set_wrap_width(text:Int, width:Float):Bool {
		final value:Dynamic = Raw.host["_wgf_text_set_wrap_width"](text, width);
		return value != 0;
	}
	public static function wgf_text_get_wrap_width(text:Int):Float {
		final value:Dynamic = Raw.host["_wgf_text_get_wrap_width"](text);
		return value;
	}
	public static function wgf_text_set_align(text:Int, horizontal:Int, vertical:Int):Bool {
		final value:Dynamic = Raw.host["_wgf_text_set_align"](text, horizontal, vertical);
		return value != 0;
	}
	public static function wgf_text_get_halign(text:Int):Int {
		final value:Dynamic = Raw.host["_wgf_text_get_halign"](text);
		return value;
	}
	public static function wgf_text_get_valign(text:Int):Int {
		final value:Dynamic = Raw.host["_wgf_text_get_valign"](text);
		return value;
	}
	public static function wgf_audio_set_volume(volume:Float):Bool {
		final value:Dynamic = Raw.host["_wgf_audio_set_volume"](volume);
		return value != 0;
	}
	public static function wgf_audio_get_volume():Float {
		final value:Dynamic = Raw.host["_wgf_audio_get_volume"]();
		return value;
	}
	public static function wgf_audio_set_paused(paused:Bool):Void {
		Raw.host["_wgf_audio_set_paused"]((paused ? 1 : 0));
	}
	public static function wgf_audio_is_paused():Bool {
		final value:Dynamic = Raw.host["_wgf_audio_is_paused"]();
		return value != 0;
	}
	public static function wgf_sound_create(path:String):Int {
		final mark = Host.stackSave();
		final value:Dynamic = Raw.host["_wgf_sound_create"](Host.cstr(path));
		Host.stackRestore(mark);
		return value;
	}
	public static function wgf_sound_create_streamed(path:String):Int {
		final mark = Host.stackSave();
		final value:Dynamic = Raw.host["_wgf_sound_create_streamed"](Host.cstr(path));
		Host.stackRestore(mark);
		return value;
	}
	public static function wgf_sound_add_segment(sound:Int, name:String, start:Float, end:Float):Bool {
		final mark = Host.stackSave();
		final value:Dynamic = Raw.host["_wgf_sound_add_segment"](sound, Host.cstr(name), start, end);
		Host.stackRestore(mark);
		return value != 0;
	}
	public static function wgf_sound_get_duration(sound:Int):Float {
		final value:Dynamic = Raw.host["_wgf_sound_get_duration"](sound);
		return value;
	}
	public static function wgf_voice_create(sound:Int):Int {
		final value:Dynamic = Raw.host["_wgf_voice_create"](sound);
		return value;
	}
	public static function wgf_voice_destroy(voice:Int):Void {
		Raw.host["_wgf_voice_destroy"](voice);
	}
	public static function wgf_voice_set_sound(voice:Int, sound:Int):Bool {
		final value:Dynamic = Raw.host["_wgf_voice_set_sound"](voice, sound);
		return value != 0;
	}
	public static function wgf_voice_get_sound(voice:Int):Int {
		final value:Dynamic = Raw.host["_wgf_voice_get_sound"](voice);
		return value;
	}
	public static function wgf_voice_play(voice:Int):Bool {
		final value:Dynamic = Raw.host["_wgf_voice_play"](voice);
		return value != 0;
	}
	public static function wgf_voice_pause(voice:Int):Bool {
		final value:Dynamic = Raw.host["_wgf_voice_pause"](voice);
		return value != 0;
	}
	public static function wgf_voice_resume(voice:Int):Bool {
		final value:Dynamic = Raw.host["_wgf_voice_resume"](voice);
		return value != 0;
	}
	public static function wgf_voice_stop(voice:Int):Bool {
		final value:Dynamic = Raw.host["_wgf_voice_stop"](voice);
		return value != 0;
	}
	public static function wgf_voice_get_state(voice:Int):Int {
		final value:Dynamic = Raw.host["_wgf_voice_get_state"](voice);
		return value;
	}
	public static function wgf_voice_set_loop(voice:Int, loop:Bool):Bool {
		final value:Dynamic = Raw.host["_wgf_voice_set_loop"](voice, (loop ? 1 : 0));
		return value != 0;
	}
	public static function wgf_voice_is_loop(voice:Int):Bool {
		final value:Dynamic = Raw.host["_wgf_voice_is_loop"](voice);
		return value != 0;
	}
	public static function wgf_voice_set_volume(voice:Int, volume:Float):Bool {
		final value:Dynamic = Raw.host["_wgf_voice_set_volume"](voice, volume);
		return value != 0;
	}
	public static function wgf_voice_get_volume(voice:Int):Float {
		final value:Dynamic = Raw.host["_wgf_voice_get_volume"](voice);
		return value;
	}
	public static function wgf_voice_set_pitch(voice:Int, pitch:Float):Bool {
		final value:Dynamic = Raw.host["_wgf_voice_set_pitch"](voice, pitch);
		return value != 0;
	}
	public static function wgf_voice_get_pitch(voice:Int):Float {
		final value:Dynamic = Raw.host["_wgf_voice_get_pitch"](voice);
		return value;
	}
	public static function wgf_voice_set_pan(voice:Int, pan:Float):Bool {
		final value:Dynamic = Raw.host["_wgf_voice_set_pan"](voice, pan);
		return value != 0;
	}
	public static function wgf_voice_get_pan(voice:Int):Float {
		final value:Dynamic = Raw.host["_wgf_voice_get_pan"](voice);
		return value;
	}
	public static function wgf_voice_set_position(voice:Int, seconds:Float):Bool {
		final value:Dynamic = Raw.host["_wgf_voice_set_position"](voice, seconds);
		return value != 0;
	}
	public static function wgf_voice_get_position(voice:Int):Float {
		final value:Dynamic = Raw.host["_wgf_voice_get_position"](voice);
		return value;
	}
	public static function wgf_voice_set_segment(voice:Int, name:String):Bool {
		final mark = Host.stackSave();
		final value:Dynamic = Raw.host["_wgf_voice_set_segment"](voice, Host.cstr(name));
		Host.stackRestore(mark);
		return value != 0;
	}
	public static function wgf_voice_get_segment(voice:Int):String {
		final value:Dynamic = Raw.host["_wgf_voice_get_segment"](voice);
		return Host.str(value);
	}
	public static function wgf_entity_create(parent:Int):Int {
		final value:Dynamic = Raw.host["_wgf_entity_create"](parent);
		return value;
	}
	public static function wgf_entity_destroy(entity:Int):Bool {
		final value:Dynamic = Raw.host["_wgf_entity_destroy"](entity);
		return value != 0;
	}
	public static function wgf_entity_is_alive(entity:Int):Bool {
		final value:Dynamic = Raw.host["_wgf_entity_is_alive"](entity);
		return value != 0;
	}
	public static function wgf_entity_get_count():Int {
		final value:Dynamic = Raw.host["_wgf_entity_get_count"]();
		return value;
	}
	public static function wgf_entity_get_node(entity:Int):Int {
		final value:Dynamic = Raw.host["_wgf_entity_get_node"](entity);
		return value;
	}
	public static function wgf_entity_set_name(entity:Int, name:String):Bool {
		final mark = Host.stackSave();
		final value:Dynamic = Raw.host["_wgf_entity_set_name"](entity, Host.cstr(name));
		Host.stackRestore(mark);
		return value != 0;
	}
	public static function wgf_entity_get_name(entity:Int):String {
		final value:Dynamic = Raw.host["_wgf_entity_get_name"](entity);
		return Host.str(value);
	}
	public static function wgf_entity_find(name:String):Int {
		final mark = Host.stackSave();
		final value:Dynamic = Raw.host["_wgf_entity_find"](Host.cstr(name));
		Host.stackRestore(mark);
		return value;
	}
	public static function wgf_entity_set_position(entity:Int, x:Float, y:Float, z:Float):Bool {
		final value:Dynamic = Raw.host["_wgf_entity_set_position"](entity, x, y, z);
		return value != 0;
	}
	public static function wgf_entity_get_position(entity:Int, into:Null<wgf.Vec3>):wgf.Vec3 {
		final result = Host.result(12);
		Raw.host["_wgf_entity_get_position"](result, entity);
		return Host.vec3(result, into);
	}
	public static function wgf_entity_set_rotation(entity:Int, x:Float, y:Float, z:Float):Bool {
		final value:Dynamic = Raw.host["_wgf_entity_set_rotation"](entity, x, y, z);
		return value != 0;
	}
	public static function wgf_entity_get_rotation(entity:Int, into:Null<wgf.Vec3>):wgf.Vec3 {
		final result = Host.result(12);
		Raw.host["_wgf_entity_get_rotation"](result, entity);
		return Host.vec3(result, into);
	}
	public static function wgf_entity_set_scale(entity:Int, x:Float, y:Float, z:Float):Bool {
		final value:Dynamic = Raw.host["_wgf_entity_set_scale"](entity, x, y, z);
		return value != 0;
	}
	public static function wgf_entity_get_scale(entity:Int, into:Null<wgf.Vec3>):wgf.Vec3 {
		final result = Host.result(12);
		Raw.host["_wgf_entity_get_scale"](result, entity);
		return Host.vec3(result, into);
	}
	public static function wgf_entity_set_transform(entity:Int, position_x:Float, position_y:Float, position_z:Float, rotation_x:Float, rotation_y:Float, rotation_z:Float, scale_x:Float, scale_y:Float, scale_z:Float):Bool {
		final value:Dynamic = Raw.host["_wgf_entity_set_transform"](entity, position_x, position_y, position_z, rotation_x, rotation_y, rotation_z, scale_x, scale_y, scale_z);
		return value != 0;
	}
	public static function wgf_entity_snap(entity:Int):Bool {
		final value:Dynamic = Raw.host["_wgf_entity_snap"](entity);
		return value != 0;
	}
	public static function wgf_entity_get_positions(entities:Array<Int>, out:Array<Float>):Int {
		final entitiesPointer = Host.intsIn(entities, 0);
		final outPointer = Host.arrayOut(out, 1);
		final value:Dynamic = Raw.host["_wgf_entity_get_positions"](entitiesPointer, (entities == null ? 0 : entities.length), outPointer, (out == null ? 0 : out.length));
		Host.floatsOut(outPointer, out);
		return value;
	}
	public static function wgf_entity_set_positions(entities:Array<Int>, positions:Array<Float>):Bool {
		final entitiesPointer = Host.intsIn(entities, 0);
		final positionsPointer = Host.floatsIn(positions, 1);
		final value:Dynamic = Raw.host["_wgf_entity_set_positions"](entitiesPointer, (entities == null ? 0 : entities.length), positionsPointer, (positions == null ? 0 : positions.length));
		return value != 0;
	}
	public static function wgf_entity_add_component(entity:Int, component:Int):Bool {
		final value:Dynamic = Raw.host["_wgf_entity_add_component"](entity, component);
		return value != 0;
	}
	public static function wgf_entity_remove_component(entity:Int, component:Int):Bool {
		final value:Dynamic = Raw.host["_wgf_entity_remove_component"](entity, component);
		return value != 0;
	}
	public static function wgf_entity_has_component(entity:Int, component:Int):Bool {
		final value:Dynamic = Raw.host["_wgf_entity_has_component"](entity, component);
		return value != 0;
	}
	public static function wgf_entity_get_component_node(entity:Int, component:Int):Int {
		final value:Dynamic = Raw.host["_wgf_entity_get_component_node"](entity, component);
		return value;
	}
	public static function wgf_entity_get_voice(entity:Int):Int {
		final value:Dynamic = Raw.host["_wgf_entity_get_voice"](entity);
		return value;
	}
	public static function wgf_behavior_set_name(entity:Int, name:String):Bool {
		final mark = Host.stackSave();
		final value:Dynamic = Raw.host["_wgf_behavior_set_name"](entity, Host.cstr(name));
		Host.stackRestore(mark);
		return value != 0;
	}
	public static function wgf_behavior_get_name(entity:Int):String {
		final value:Dynamic = Raw.host["_wgf_behavior_get_name"](entity);
		return Host.str(value);
	}
	public static function wgf_behavior_set_param(entity:Int, key:String, value:String):Bool {
		final mark = Host.stackSave();
		final value:Dynamic = Raw.host["_wgf_behavior_set_param"](entity, Host.cstr(key), Host.cstr(value));
		Host.stackRestore(mark);
		return value != 0;
	}
	public static function wgf_behavior_get_param(entity:Int, key:String):String {
		final mark = Host.stackSave();
		final value:Dynamic = Raw.host["_wgf_behavior_get_param"](entity, Host.cstr(key));
		Host.stackRestore(mark);
		return Host.str(value);
	}
	public static function wgf_behavior_get_param_number(entity:Int, key:String):Float {
		final mark = Host.stackSave();
		final value:Dynamic = Raw.host["_wgf_behavior_get_param_number"](entity, Host.cstr(key));
		Host.stackRestore(mark);
		return value;
	}
	public static function wgf_behavior_has_param(entity:Int, key:String):Bool {
		final mark = Host.stackSave();
		final value:Dynamic = Raw.host["_wgf_behavior_has_param"](entity, Host.cstr(key));
		Host.stackRestore(mark);
		return value != 0;
	}
	public static function wgf_behavior_get_param_count(entity:Int):Int {
		final value:Dynamic = Raw.host["_wgf_behavior_get_param_count"](entity);
		return value;
	}
	public static function wgf_behavior_get_param_key(entity:Int, index:Int):String {
		final value:Dynamic = Raw.host["_wgf_behavior_get_param_key"](entity, index);
		return Host.str(value);
	}
	public static function wgf_bounds_set_rect(entity:Int, x:Float, y:Float, width:Float, height:Float):Bool {
		final value:Dynamic = Raw.host["_wgf_bounds_set_rect"](entity, x, y, width, height);
		return value != 0;
	}
	public static function wgf_bounds_get_rect(entity:Int, into:Null<wgf.Vec4>):wgf.Vec4 {
		final result = Host.result(16);
		Raw.host["_wgf_bounds_get_rect"](result, entity);
		return Host.vec4(result, into);
	}
	public static function wgf_bounds_set_mode(entity:Int, mode:Int):Bool {
		final value:Dynamic = Raw.host["_wgf_bounds_set_mode"](entity, mode);
		return value != 0;
	}
	public static function wgf_bounds_get_mode(entity:Int):Int {
		final value:Dynamic = Raw.host["_wgf_bounds_get_mode"](entity);
		return value;
	}
	public static function wgf_bounds_set_margin(entity:Int, margin:Float):Bool {
		final value:Dynamic = Raw.host["_wgf_bounds_set_margin"](entity, margin);
		return value != 0;
	}
	public static function wgf_bounds_get_margin(entity:Int):Float {
		final value:Dynamic = Raw.host["_wgf_bounds_get_margin"](entity);
		return value;
	}
	public static function wgf_collider_set_radius(entity:Int, radius:Float):Bool {
		final value:Dynamic = Raw.host["_wgf_collider_set_radius"](entity, radius);
		return value != 0;
	}
	public static function wgf_collider_get_radius(entity:Int):Float {
		final value:Dynamic = Raw.host["_wgf_collider_get_radius"](entity);
		return value;
	}
	public static function wgf_collider_set_layer(entity:Int, layer:Int):Bool {
		final value:Dynamic = Raw.host["_wgf_collider_set_layer"](entity, layer);
		return value != 0;
	}
	public static function wgf_collider_get_layer(entity:Int):Int {
		final value:Dynamic = Raw.host["_wgf_collider_get_layer"](entity);
		return value;
	}
	public static function wgf_collider_set_mask(entity:Int, mask:Int):Bool {
		final value:Dynamic = Raw.host["_wgf_collider_set_mask"](entity, mask);
		return value != 0;
	}
	public static function wgf_collider_get_mask(entity:Int):Int {
		final value:Dynamic = Raw.host["_wgf_collider_get_mask"](entity);
		return value;
	}
	public static function wgf_collider_get_overlaps(entity:Int, out:Array<Int>):Int {
		final outPointer = Host.arrayOut(out, 0);
		final value:Dynamic = Raw.host["_wgf_collider_get_overlaps"](entity, outPointer, (out == null ? 0 : out.length));
		Host.intsOut(outPointer, out);
		return value;
	}
	public static function wgf_ecs_get_event_count():Int {
		final value:Dynamic = Raw.host["_wgf_ecs_get_event_count"]();
		return value;
	}
	public static function wgf_ecs_take_events(out:Array<Int>):Int {
		final outPointer = Host.arrayOut(out, 0);
		final value:Dynamic = Raw.host["_wgf_ecs_take_events"](outPointer, (out == null ? 0 : out.length));
		Host.intsOut(outPointer, out);
		return value;
	}
	public static function wgf_ecs_find_behavior(name:String, out:Array<Int>):Int {
		final mark = Host.stackSave();
		final outPointer = Host.arrayOut(out, 0);
		final value:Dynamic = Raw.host["_wgf_ecs_find_behavior"](Host.cstr(name), outPointer, (out == null ? 0 : out.length));
		Host.intsOut(outPointer, out);
		Host.stackRestore(mark);
		return value;
	}
	public static function wgf_ecs_count_behavior(name:String):Int {
		final mark = Host.stackSave();
		final value:Dynamic = Raw.host["_wgf_ecs_count_behavior"](Host.cstr(name));
		Host.stackRestore(mark);
		return value;
	}
	public static function wgf_ecs_clear():Void {
		Raw.host["_wgf_ecs_clear"]();
	}
	public static function wgf_ecs_dump():String {
		final value:Dynamic = Raw.host["_wgf_ecs_dump"]();
		return Host.str(value);
	}
	public static function wgf_lifetime_set_seconds(entity:Int, seconds:Float):Bool {
		final value:Dynamic = Raw.host["_wgf_lifetime_set_seconds"](entity, seconds);
		return value != 0;
	}
	public static function wgf_lifetime_get_seconds(entity:Int):Float {
		final value:Dynamic = Raw.host["_wgf_lifetime_get_seconds"](entity);
		return value;
	}
	public static function wgf_motion_set_velocity(entity:Int, x:Float, y:Float, z:Float):Bool {
		final value:Dynamic = Raw.host["_wgf_motion_set_velocity"](entity, x, y, z);
		return value != 0;
	}
	public static function wgf_motion_get_velocity(entity:Int, into:Null<wgf.Vec3>):wgf.Vec3 {
		final result = Host.result(12);
		Raw.host["_wgf_motion_get_velocity"](result, entity);
		return Host.vec3(result, into);
	}
	public static function wgf_motion_set_spin(entity:Int, x:Float, y:Float, z:Float):Bool {
		final value:Dynamic = Raw.host["_wgf_motion_set_spin"](entity, x, y, z);
		return value != 0;
	}
	public static function wgf_motion_get_spin(entity:Int, into:Null<wgf.Vec3>):wgf.Vec3 {
		final result = Host.result(12);
		Raw.host["_wgf_motion_get_spin"](result, entity);
		return Host.vec3(result, into);
	}
	public static function wgf_motion_set_damping(entity:Int, damping:Float):Bool {
		final value:Dynamic = Raw.host["_wgf_motion_set_damping"](entity, damping);
		return value != 0;
	}
	public static function wgf_motion_get_damping(entity:Int):Float {
		final value:Dynamic = Raw.host["_wgf_motion_get_damping"](entity);
		return value;
	}
	public static function wgf_motion_set_max_speed(entity:Int, speed:Float):Bool {
		final value:Dynamic = Raw.host["_wgf_motion_set_max_speed"](entity, speed);
		return value != 0;
	}
	public static function wgf_motion_get_max_speed(entity:Int):Float {
		final value:Dynamic = Raw.host["_wgf_motion_get_max_speed"](entity);
		return value;
	}
	public static function wgf_scene_create(path:String):Int {
		final mark = Host.stackSave();
		final value:Dynamic = Raw.host["_wgf_scene_create"](Host.cstr(path));
		Host.stackRestore(mark);
		return value;
	}
	public static function wgf_scene_instantiate(scene:Int, parent:Int):Int {
		final value:Dynamic = Raw.host["_wgf_scene_instantiate"](scene, parent);
		return value;
	}
	public static function wgf_scene_spawn(scene:Int, name:String, parent:Int):Int {
		final mark = Host.stackSave();
		final value:Dynamic = Raw.host["_wgf_scene_spawn"](scene, Host.cstr(name), parent);
		Host.stackRestore(mark);
		return value;
	}
	public static function wgf_scene_get_entity_count(scene:Int):Int {
		final value:Dynamic = Raw.host["_wgf_scene_get_entity_count"](scene);
		return value;
	}
	public static function wgf_scene_get_prefab_count(scene:Int):Int {
		final value:Dynamic = Raw.host["_wgf_scene_get_prefab_count"](scene);
		return value;
	}
	public static function wgf_scene_get_prefab_name(scene:Int, index:Int):String {
		final value:Dynamic = Raw.host["_wgf_scene_get_prefab_name"](scene, index);
		return Host.str(value);
	}
	public static function wgf_scene_has_prefab(scene:Int, name:String):Bool {
		final mark = Host.stackSave();
		final value:Dynamic = Raw.host["_wgf_scene_has_prefab"](scene, Host.cstr(name));
		Host.stackRestore(mark);
		return value != 0;
	}
	public static function wgf_ui_begin():Bool {
		final value:Dynamic = Raw.host["_wgf_ui_begin"]();
		return value != 0;
	}
	public static function wgf_ui_end():Bool {
		final value:Dynamic = Raw.host["_wgf_ui_end"]();
		return value != 0;
	}
	public static function wgf_ui_begin_box(id:String, direction:Int):Bool {
		final mark = Host.stackSave();
		final value:Dynamic = Raw.host["_wgf_ui_begin_box"](Host.cstr(id), direction);
		Host.stackRestore(mark);
		return value != 0;
	}
	public static function wgf_ui_end_box():Bool {
		final value:Dynamic = Raw.host["_wgf_ui_end_box"]();
		return value != 0;
	}
	public static function wgf_ui_begin_panel(id:String):Bool {
		final mark = Host.stackSave();
		final value:Dynamic = Raw.host["_wgf_ui_begin_panel"](Host.cstr(id));
		Host.stackRestore(mark);
		return value != 0;
	}
	public static function wgf_ui_end_panel():Bool {
		final value:Dynamic = Raw.host["_wgf_ui_end_panel"]();
		return value != 0;
	}
	public static function wgf_ui_set_width(sizing:Int, value:Float):Bool {
		final value:Dynamic = Raw.host["_wgf_ui_set_width"](sizing, value);
		return value != 0;
	}
	public static function wgf_ui_set_height(sizing:Int, value:Float):Bool {
		final value:Dynamic = Raw.host["_wgf_ui_set_height"](sizing, value);
		return value != 0;
	}
	public static function wgf_ui_set_padding(x:Float, y:Float):Bool {
		final value:Dynamic = Raw.host["_wgf_ui_set_padding"](x, y);
		return value != 0;
	}
	public static function wgf_ui_set_gap(gap:Float):Bool {
		final value:Dynamic = Raw.host["_wgf_ui_set_gap"](gap);
		return value != 0;
	}
	public static function wgf_ui_set_align(x:Int, y:Int):Bool {
		final value:Dynamic = Raw.host["_wgf_ui_set_align"](x, y);
		return value != 0;
	}
	public static function wgf_ui_set_color(color:Int):Bool {
		final value:Dynamic = Raw.host["_wgf_ui_set_color"](color);
		return value != 0;
	}
	public static function wgf_ui_label(text:String, size:Float):Bool {
		final mark = Host.stackSave();
		final value:Dynamic = Raw.host["_wgf_ui_label"](Host.cstr(text), size);
		Host.stackRestore(mark);
		return value != 0;
	}
	public static function wgf_ui_spacer(size:Float):Bool {
		final value:Dynamic = Raw.host["_wgf_ui_spacer"](size);
		return value != 0;
	}
	public static function wgf_ui_button(id:String, text:String):Bool {
		final mark = Host.stackSave();
		final value:Dynamic = Raw.host["_wgf_ui_button"](Host.cstr(id), Host.cstr(text));
		Host.stackRestore(mark);
		return value != 0;
	}
	public static function wgf_ui_set_focus(id:String):Bool {
		final mark = Host.stackSave();
		final value:Dynamic = Raw.host["_wgf_ui_set_focus"](Host.cstr(id));
		Host.stackRestore(mark);
		return value != 0;
	}
	public static function wgf_ui_get_focus():String {
		final value:Dynamic = Raw.host["_wgf_ui_get_focus"]();
		return Host.str(value);
	}
	public static function wgf_ui_set_style_color(which:Int, color:Int):Bool {
		final value:Dynamic = Raw.host["_wgf_ui_set_style_color"](which, color);
		return value != 0;
	}
	public static function wgf_ui_get_style_color(which:Int):Int {
		final value:Dynamic = Raw.host["_wgf_ui_get_style_color"](which);
		return value;
	}
	public static function wgf_ui_set_style_value(which:Int, value:Float):Bool {
		final value:Dynamic = Raw.host["_wgf_ui_set_style_value"](which, value);
		return value != 0;
	}
	public static function wgf_ui_get_style_value(which:Int):Float {
		final value:Dynamic = Raw.host["_wgf_ui_get_style_value"](which);
		return value;
	}
	public static function wgf_ui_set_style_font(font:Int):Bool {
		final value:Dynamic = Raw.host["_wgf_ui_set_style_font"](font);
		return value != 0;
	}
	public static function wgf_ui_get_style_font():Int {
		final value:Dynamic = Raw.host["_wgf_ui_get_style_font"]();
		return value;
	}
	public static function wgf_ui_reset_style():Void {
		Raw.host["_wgf_ui_reset_style"]();
	}
	public static function wgf_app_quit():Void {
		Raw.host["_wgf_app_quit"]();
	}
	public static function wgf_app_can_quit():Bool {
		final value:Dynamic = Raw.host["_wgf_app_can_quit"]();
		return value != 0;
	}
	public static function wgf_app_is_running():Bool {
		final value:Dynamic = Raw.host["_wgf_app_is_running"]();
		return value != 0;
	}
	public static function wgf_loop_get_frame_delta():Float {
		final value:Dynamic = Raw.host["_wgf_loop_get_frame_delta"]();
		return value;
	}
	public static function wgf_loop_set_tick_rate(hz:Int):Void {
		Raw.host["_wgf_loop_set_tick_rate"](hz);
	}
	public static function wgf_loop_get_tick_rate():Int {
		final value:Dynamic = Raw.host["_wgf_loop_get_tick_rate"]();
		return value;
	}
	public static function wgf_loop_get_tick_delta():Float {
		final value:Dynamic = Raw.host["_wgf_loop_get_tick_delta"]();
		return value;
	}
	public static function wgf_loop_get_tick_fraction():Float {
		final value:Dynamic = Raw.host["_wgf_loop_get_tick_fraction"]();
		return value;
	}
	public static function wgf_loop_set_time_scale(scale:Float):Void {
		Raw.host["_wgf_loop_set_time_scale"](scale);
	}
	public static function wgf_loop_get_time_scale():Float {
		final value:Dynamic = Raw.host["_wgf_loop_get_time_scale"]();
		return value;
	}
	public static function wgf_loop_set_target_fps(fps:Int):Void {
		Raw.host["_wgf_loop_set_target_fps"](fps);
	}
	public static function wgf_loop_get_target_fps():Int {
		final value:Dynamic = Raw.host["_wgf_loop_get_target_fps"]();
		return value;
	}
	public static function wgf_loop_get_fps():Float {
		final value:Dynamic = Raw.host["_wgf_loop_get_fps"]();
		return value;
	}
}
