// Generated by tools/gen_binding.py from the public headers: edit the headers or the generator, not this.
// libwgf's typed JS layer (bindings/js/README.md): the raw binding's calls (wgf.js) in the typed Haxe API's names.

import * as raw from "./wgf.js";
/** The host handed over, as the raw binding takes it: a program on this layer imports nothing else. */
export { attach, isAttached } from "./wgf.js";
// wgf: typed Action
export const Action = Object.freeze({
    // wgf: call wgf_action_bind_key
    bindKey: raw.wgf_action_bind_key,
    // wgf: call wgf_action_bind_keys
    bindKeys: raw.wgf_action_bind_keys,
    // wgf: call wgf_action_bind_pad_button
    bindPadButton: raw.wgf_action_bind_pad_button,
    // wgf: call wgf_action_bind_pad_buttons
    bindPadButtons: raw.wgf_action_bind_pad_buttons,
    // wgf: call wgf_action_bind_pad_axis
    bindPadAxis: raw.wgf_action_bind_pad_axis,
    // wgf: call wgf_action_bind_touch
    bindTouch: raw.wgf_action_bind_touch,
    // wgf: call wgf_action_clear
    clear: raw.wgf_action_clear,
    // wgf: call wgf_action_get_axis
    getAxis: raw.wgf_action_get_axis,
    // wgf: call wgf_action_get_value
    getValue: raw.wgf_action_get_value,
    // wgf: call wgf_action_get_state
    getState: raw.wgf_action_get_state,
    // wgf: call wgf_action_is_down
    isDown: raw.wgf_action_is_down,
    // wgf: call wgf_action_is_pressed
    isPressed: raw.wgf_action_is_pressed,
    // wgf: call wgf_action_is_released
    isReleased: raw.wgf_action_is_released,
    // wgf: call wgf_action_get_count
    getCount: raw.wgf_action_get_count,
    // wgf: call wgf_action_get_name
    getName: raw.wgf_action_get_name,
    // wgf: call wgf_action_get_binding_count
    getBindingCount: raw.wgf_action_get_binding_count,
    // wgf: call wgf_action_get_binding_text
    getBindingText: raw.wgf_action_get_binding_text,
});
// wgf: typed Actor
export const Actor = Object.freeze({
    // wgf: call wgf_actor_create
    create: raw.wgf_actor_create,
    // wgf: call wgf_actor_destroy
    destroy: raw.wgf_actor_destroy,
    // wgf: call wgf_actor_get_kind
    getKind: raw.wgf_actor_get_kind,
    // wgf: call wgf_actor_set_parent
    setParent: raw.wgf_actor_set_parent,
    // wgf: call wgf_actor_get_parent
    getParent: raw.wgf_actor_get_parent,
    // wgf: call wgf_actor_get_child_count
    getChildCount: raw.wgf_actor_get_child_count,
    // wgf: call wgf_actor_get_child
    getChild: raw.wgf_actor_get_child,
    // wgf: call wgf_actor_set_index
    setIndex: raw.wgf_actor_set_index,
    // wgf: call wgf_actor_get_index
    getIndex: raw.wgf_actor_get_index,
    // wgf: call wgf_actor_set_position
    setPosition: raw.wgf_actor_set_position,
    // wgf: call wgf_actor_get_position
    getPosition: raw.wgf_actor_get_position,
    // wgf: call wgf_actor_set_rotation
    setRotation: raw.wgf_actor_set_rotation,
    // wgf: call wgf_actor_get_rotation
    getRotation: raw.wgf_actor_get_rotation,
    // wgf: call wgf_actor_set_scale
    setScale: raw.wgf_actor_set_scale,
    // wgf: call wgf_actor_get_scale
    getScale: raw.wgf_actor_get_scale,
    // wgf: call wgf_actor_set_transform
    setTransform: raw.wgf_actor_set_transform,
    // wgf: call wgf_actor_snap
    snap: raw.wgf_actor_snap,
    // wgf: call wgf_actor_get_positions
    getPositions: raw.wgf_actor_get_positions,
    // wgf: call wgf_actor_set_positions
    setPositions: raw.wgf_actor_set_positions,
    // wgf: call wgf_actor_get_world_position
    getWorldPosition: raw.wgf_actor_get_world_position,
    // wgf: call wgf_actor_get_drawn_position
    getDrawnPosition: raw.wgf_actor_get_drawn_position,
    // wgf: call wgf_actor_get_world_direction
    getWorldDirection: raw.wgf_actor_get_world_direction,
    // wgf: call wgf_actor_get_drawn_direction
    getDrawnDirection: raw.wgf_actor_get_drawn_direction,
    // wgf: call wgf_actor_look_at
    lookAt: raw.wgf_actor_look_at,
    // wgf: call wgf_actor_set_name
    setName: raw.wgf_actor_set_name,
    // wgf: call wgf_actor_get_name
    getName: raw.wgf_actor_get_name,
    // wgf: call wgf_actor_find
    find: raw.wgf_actor_find,
    // wgf: call wgf_actor_set_enabled
    setEnabled: raw.wgf_actor_set_enabled,
    // wgf: call wgf_actor_is_enabled
    isEnabled: raw.wgf_actor_is_enabled,
    // wgf: call wgf_actor_set_visible
    setVisible: raw.wgf_actor_set_visible,
    // wgf: call wgf_actor_is_visible
    isVisible: raw.wgf_actor_is_visible,
    // wgf: call wgf_actor_add_behavior
    addBehavior: raw.wgf_actor_add_behavior,
    // wgf: call wgf_actor_remove_behavior
    removeBehavior: raw.wgf_actor_remove_behavior,
    // wgf: call wgf_actor_get_behavior_count
    getBehaviorCount: raw.wgf_actor_get_behavior_count,
    // wgf: call wgf_actor_get_behavior
    getBehavior: raw.wgf_actor_get_behavior,
    // wgf: call wgf_actor_find_behavior
    findBehavior: raw.wgf_actor_find_behavior,
    // wgf: call wgf_actor_find_with_behavior
    findWithBehavior: raw.wgf_actor_find_with_behavior,
    // wgf: call wgf_actor_count_with_behavior
    countWithBehavior: raw.wgf_actor_count_with_behavior,
    // wgf: call wgf_actor_add_component
    addComponent: raw.wgf_actor_add_component,
    // wgf: call wgf_actor_remove_component
    removeComponent: raw.wgf_actor_remove_component,
    // wgf: call wgf_actor_has_component
    hasComponent: raw.wgf_actor_has_component,
    // wgf: call wgf_actor_get_voice
    getVoice: raw.wgf_actor_get_voice,
    // wgf: call wgf_actor_find_with_component
    findWithComponent: raw.wgf_actor_find_with_component,
    // wgf: call wgf_actor_count_with_component
    countWithComponent: raw.wgf_actor_count_with_component,
    // wgf: call wgf_actor_get_count
    getCount: raw.wgf_actor_get_count,
    // wgf: call wgf_handle_is_alive
    isAlive: raw.wgf_handle_is_alive,
});
// wgf: typed App
export const App = Object.freeze({
    // wgf: call wgf_app_run
    run: raw.wgf_app_run,
    // wgf: call wgf_app_quit
    quit: raw.wgf_app_quit,
    // wgf: call wgf_app_can_quit
    canQuit: raw.wgf_app_can_quit,
    // wgf: call wgf_app_is_running
    isRunning: raw.wgf_app_is_running,
});
// wgf: typed Asset
export const Asset = Object.freeze({
    // wgf: call wgf_asset_set_host
    setHost: raw.wgf_asset_set_host,
    // wgf: call wgf_asset_get_host
    getHost: raw.wgf_asset_get_host,
    // wgf: call wgf_asset_set_cache_dir
    setCacheDir: raw.wgf_asset_set_cache_dir,
    // wgf: call wgf_asset_get_cache_dir
    getCacheDir: raw.wgf_asset_get_cache_dir,
    // wgf: call wgf_asset_set_fetching
    setFetching: raw.wgf_asset_set_fetching,
    // wgf: call wgf_asset_is_fetching
    isFetching: raw.wgf_asset_is_fetching,
    // wgf: call wgf_asset_fetch_next
    fetchNext: raw.wgf_asset_fetch_next,
    // wgf: call wgf_asset_fetch_get_url
    fetchGetUrl: raw.wgf_asset_fetch_get_url,
    // wgf: call wgf_asset_fetch_get_dest
    fetchGetDest: raw.wgf_asset_fetch_get_dest,
    // wgf: call wgf_asset_fetch_is_ping
    fetchIsPing: raw.wgf_asset_fetch_is_ping,
    // wgf: call wgf_asset_fetch_done
    fetchDone: raw.wgf_asset_fetch_done,
    // wgf: call wgf_asset_set_fetch_timeout
    setFetchTimeout: raw.wgf_asset_set_fetch_timeout,
    // wgf: call wgf_asset_get_fetch_timeout
    getFetchTimeout: raw.wgf_asset_get_fetch_timeout,
    // wgf: call wgf_asset_evict
    evict: raw.wgf_asset_evict,
    // wgf: call wgf_asset_clear_cache
    clearCache: raw.wgf_asset_clear_cache,
    // wgf: call wgf_asset_set_cache_mode
    setCacheMode: raw.wgf_asset_set_cache_mode,
    // wgf: call wgf_asset_get_cache_mode
    getCacheMode: raw.wgf_asset_get_cache_mode,
    // wgf: call wgf_asset_set_manifest
    setManifest: raw.wgf_asset_set_manifest,
    // wgf: call wgf_asset_get_manifest
    getManifest: raw.wgf_asset_get_manifest,
    // wgf: call wgf_asset_ensure
    ensure: raw.wgf_asset_ensure,
    // wgf: call wgf_asset_group_create
    groupCreate: raw.wgf_asset_group_create,
    // wgf: call wgf_asset_group_add
    groupAdd: raw.wgf_asset_group_add,
    // wgf: call wgf_asset_add_redirect
    addRedirect: raw.wgf_asset_add_redirect,
    // wgf: call wgf_asset_clear_redirects
    clearRedirects: raw.wgf_asset_clear_redirects,
    // wgf: call wgf_asset_ping_host
    pingHost: raw.wgf_asset_ping_host,
    // wgf: call wgf_asset_ping_get_milliseconds
    pingGetMilliseconds: raw.wgf_asset_ping_get_milliseconds,
});
// wgf: typed AssetTask
export const AssetTask = Object.freeze({
    // wgf: call wgf_asset_task_get_status
    getStatus: raw.wgf_asset_task_get_status,
    // wgf: call wgf_asset_task_get_path
    getPath: raw.wgf_asset_task_get_path,
    // wgf: call wgf_asset_task_get_progress
    getProgress: raw.wgf_asset_task_get_progress,
    // wgf: call wgf_asset_task_destroy
    destroy: raw.wgf_asset_task_destroy,
    // wgf: call wgf_handle_is_alive
    isAlive: raw.wgf_handle_is_alive,
});
// wgf: typed Audio
export const Audio = Object.freeze({
    // wgf: call wgf_audio_set_volume
    setVolume: raw.wgf_audio_set_volume,
    // wgf: call wgf_audio_get_volume
    getVolume: raw.wgf_audio_get_volume,
    // wgf: call wgf_audio_set_paused
    setPaused: raw.wgf_audio_set_paused,
    // wgf: call wgf_audio_is_paused
    isPaused: raw.wgf_audio_is_paused,
});
// wgf: typed BehaviorComponent
export const BehaviorComponent = Object.freeze({
    // wgf: call wgf_behavior_get_name
    getName: raw.wgf_behavior_get_name,
    // wgf: call wgf_behavior_set_param
    setParam: raw.wgf_behavior_set_param,
    // wgf: call wgf_behavior_get_param
    getParam: raw.wgf_behavior_get_param,
    // wgf: call wgf_behavior_get_param_number
    getParamNumber: raw.wgf_behavior_get_param_number,
    // wgf: call wgf_behavior_get_param_actor
    getParamActor: raw.wgf_behavior_get_param_actor,
    // wgf: call wgf_behavior_has_param
    hasParam: raw.wgf_behavior_has_param,
    // wgf: call wgf_behavior_get_param_count
    getParamCount: raw.wgf_behavior_get_param_count,
    // wgf: call wgf_behavior_get_param_key
    getParamKey: raw.wgf_behavior_get_param_key,
    // wgf: call wgf_handle_is_alive
    isAlive: raw.wgf_handle_is_alive,
});
// wgf: typed Body
export const Body = Object.freeze({
    // wgf: call wgf_body_set_type
    setType: raw.wgf_body_set_type,
    // wgf: call wgf_body_get_type
    getType: raw.wgf_body_get_type,
    // wgf: call wgf_body_set_shape
    setShape: raw.wgf_body_set_shape,
    // wgf: call wgf_body_get_shape
    getShape: raw.wgf_body_get_shape,
    // wgf: call wgf_body_get_size
    getSize: raw.wgf_body_get_size,
    // wgf: call wgf_body_set_mass
    setMass: raw.wgf_body_set_mass,
    // wgf: call wgf_body_get_mass
    getMass: raw.wgf_body_get_mass,
    // wgf: call wgf_body_set_friction
    setFriction: raw.wgf_body_set_friction,
    // wgf: call wgf_body_get_friction
    getFriction: raw.wgf_body_get_friction,
    // wgf: call wgf_body_set_bounce
    setBounce: raw.wgf_body_set_bounce,
    // wgf: call wgf_body_get_bounce
    getBounce: raw.wgf_body_get_bounce,
    // wgf: call wgf_body_set_damping
    setDamping: raw.wgf_body_set_damping,
    // wgf: call wgf_body_get_damping
    getDamping: raw.wgf_body_get_damping,
    // wgf: call wgf_body_set_layer
    setLayer: raw.wgf_body_set_layer,
    // wgf: call wgf_body_get_layer
    getLayer: raw.wgf_body_get_layer,
    // wgf: call wgf_body_set_mask
    setMask: raw.wgf_body_set_mask,
    // wgf: call wgf_body_get_mask
    getMask: raw.wgf_body_get_mask,
    // wgf: call wgf_body_set_velocity
    setVelocity: raw.wgf_body_set_velocity,
    // wgf: call wgf_body_get_velocity
    getVelocity: raw.wgf_body_get_velocity,
    // wgf: call wgf_body_set_spin
    setSpin: raw.wgf_body_set_spin,
    // wgf: call wgf_body_get_spin
    getSpin: raw.wgf_body_get_spin,
    // wgf: call wgf_body_add_impulse
    addImpulse: raw.wgf_body_add_impulse,
    // wgf: call wgf_handle_is_alive
    isAlive: raw.wgf_handle_is_alive,
});
// wgf: typed Bounds
export const Bounds = Object.freeze({
    // wgf: call wgf_bounds_set_rect
    setRect: raw.wgf_bounds_set_rect,
    // wgf: call wgf_bounds_get_rect
    getRect: raw.wgf_bounds_get_rect,
    // wgf: call wgf_bounds_set_mode
    setMode: raw.wgf_bounds_set_mode,
    // wgf: call wgf_bounds_get_mode
    getMode: raw.wgf_bounds_get_mode,
    // wgf: call wgf_bounds_set_visible
    setVisible: raw.wgf_bounds_set_visible,
    // wgf: call wgf_bounds_is_visible
    isVisible: raw.wgf_bounds_is_visible,
    // wgf: call wgf_bounds_set_margin
    setMargin: raw.wgf_bounds_set_margin,
    // wgf: call wgf_bounds_get_margin
    getMargin: raw.wgf_bounds_get_margin,
    // wgf: call wgf_handle_is_alive
    isAlive: raw.wgf_handle_is_alive,
});
// wgf: typed Camera2d
export const Camera2d = Object.freeze({
    // wgf: call wgf_camera2d_create
    create: raw.wgf_camera2d_create,
    // wgf: call wgf_camera2d_set_zoom
    setZoom: raw.wgf_camera2d_set_zoom,
    // wgf: call wgf_camera2d_get_zoom
    getZoom: raw.wgf_camera2d_get_zoom,
    // wgf: call wgf_handle_is_alive
    isAlive: raw.wgf_handle_is_alive,
});
// wgf: typed Camera3d
export const Camera3d = Object.freeze({
    // wgf: call wgf_camera3d_create
    create: raw.wgf_camera3d_create,
    // wgf: call wgf_camera3d_set_fov
    setFov: raw.wgf_camera3d_set_fov,
    // wgf: call wgf_camera3d_get_fov
    getFov: raw.wgf_camera3d_get_fov,
    // wgf: call wgf_camera3d_set_clip
    setClip: raw.wgf_camera3d_set_clip,
    // wgf: call wgf_camera3d_get_near
    getNear: raw.wgf_camera3d_get_near,
    // wgf: call wgf_camera3d_get_far
    getFar: raw.wgf_camera3d_get_far,
    // wgf: call wgf_camera3d_set_orthographic
    setOrthographic: raw.wgf_camera3d_set_orthographic,
    // wgf: call wgf_camera3d_is_orthographic
    isOrthographic: raw.wgf_camera3d_is_orthographic,
    // wgf: call wgf_camera3d_set_ortho_height
    setOrthoHeight: raw.wgf_camera3d_set_ortho_height,
    // wgf: call wgf_camera3d_get_ortho_height
    getOrthoHeight: raw.wgf_camera3d_get_ortho_height,
    // wgf: call wgf_handle_is_alive
    isAlive: raw.wgf_handle_is_alive,
});
// wgf: typed Collider
export const Collider = Object.freeze({
    // wgf: call wgf_collider_set_radius
    setRadius: raw.wgf_collider_set_radius,
    // wgf: call wgf_collider_get_radius
    getRadius: raw.wgf_collider_get_radius,
    // wgf: call wgf_collider_set_layer
    setLayer: raw.wgf_collider_set_layer,
    // wgf: call wgf_collider_get_layer
    getLayer: raw.wgf_collider_get_layer,
    // wgf: call wgf_collider_set_mask
    setMask: raw.wgf_collider_set_mask,
    // wgf: call wgf_collider_get_mask
    getMask: raw.wgf_collider_get_mask,
    // wgf: call wgf_collider_set_enabled
    setEnabled: raw.wgf_collider_set_enabled,
    // wgf: call wgf_collider_is_enabled
    isEnabled: raw.wgf_collider_is_enabled,
    // wgf: call wgf_collider_get_overlaps
    getOverlaps: raw.wgf_collider_get_overlaps,
    // wgf: call wgf_handle_is_alive
    isAlive: raw.wgf_handle_is_alive,
});
// wgf: typed Color
export const Color = Object.freeze({
    // wgf: call wgf_color_get
    get: raw.wgf_color_get,
    // wgf: call wgf_color_make
    make: raw.wgf_color_make,
    // wgf: call wgf_color_make_float
    makeFloat: raw.wgf_color_make_float,
    // wgf: call wgf_color_with_alpha
    withAlpha: raw.wgf_color_with_alpha,
    // wgf: call wgf_color_get_red
    getRed: raw.wgf_color_get_red,
    // wgf: call wgf_color_get_green
    getGreen: raw.wgf_color_get_green,
    // wgf: call wgf_color_get_blue
    getBlue: raw.wgf_color_get_blue,
    // wgf: call wgf_color_get_alpha
    getAlpha: raw.wgf_color_get_alpha,
    // wgf: call wgf_color_lerp
    lerp: raw.wgf_color_lerp,
});
// wgf: typed Debug
export const Debug = Object.freeze({
    // wgf: call wgf_debug_show_fps
    showFps: raw.wgf_debug_show_fps,
    // wgf: call wgf_debug_hide_fps
    hideFps: raw.wgf_debug_hide_fps,
    // wgf: call wgf_debug_is_fps_shown
    isFpsShown: raw.wgf_debug_is_fps_shown,
});
// wgf: typed Draw
export const Draw = Object.freeze({
    // wgf: call wgf_draw_rectangle
    rectangle: raw.wgf_draw_rectangle,
    // wgf: call wgf_draw_rectangle_lines
    rectangleLines: raw.wgf_draw_rectangle_lines,
    // wgf: call wgf_draw_line
    line: raw.wgf_draw_line,
    // wgf: call wgf_draw_circle
    circle: raw.wgf_draw_circle,
    // wgf: call wgf_draw_circle_lines
    circleLines: raw.wgf_draw_circle_lines,
    // wgf: call wgf_draw_triangle
    triangle: raw.wgf_draw_triangle,
    // wgf: call wgf_draw_polyline
    polyline: raw.wgf_draw_polyline,
    // wgf: call wgf_draw_polygon
    polygon: raw.wgf_draw_polygon,
    // wgf: call wgf_draw_text
    text: raw.wgf_draw_text,
    // wgf: call wgf_draw_text_aligned
    textAligned: raw.wgf_draw_text_aligned,
    // wgf: call wgf_draw_texture
    texture: raw.wgf_draw_texture,
    // wgf: call wgf_draw_texture_region
    textureRegion: raw.wgf_draw_texture_region,
    // wgf: call wgf_draw_begin_3d
    begin3d: raw.wgf_draw_begin_3d,
    // wgf: call wgf_draw_end_3d
    end3d: raw.wgf_draw_end_3d,
    // wgf: call wgf_draw_line_3d
    line3d: raw.wgf_draw_line_3d,
    // wgf: call wgf_draw_cube
    cube: raw.wgf_draw_cube,
    // wgf: call wgf_draw_cube_wires
    cubeWires: raw.wgf_draw_cube_wires,
    // wgf: call wgf_draw_sphere
    sphere: raw.wgf_draw_sphere,
    // wgf: call wgf_draw_grid
    grid: raw.wgf_draw_grid,
    // wgf: call wgf_draw_rectangle_3d
    rectangle3d: raw.wgf_draw_rectangle_3d,
    // wgf: call wgf_draw_circle_3d
    circle3d: raw.wgf_draw_circle_3d,
    // wgf: call wgf_draw_text_3d
    text3d: raw.wgf_draw_text_3d,
});
// wgf: typed Emitter2d
export const Emitter2d = Object.freeze({
    // wgf: call wgf_emitter2d_create
    create: raw.wgf_emitter2d_create,
    // wgf: call wgf_emitter2d_set_rate
    setRate: raw.wgf_emitter2d_set_rate,
    // wgf: call wgf_emitter2d_get_rate
    getRate: raw.wgf_emitter2d_get_rate,
    // wgf: call wgf_emitter2d_set_emitting
    setEmitting: raw.wgf_emitter2d_set_emitting,
    // wgf: call wgf_emitter2d_is_emitting
    isEmitting: raw.wgf_emitter2d_is_emitting,
    // wgf: call wgf_emitter2d_burst
    burst: raw.wgf_emitter2d_burst,
    // wgf: call wgf_emitter2d_set_capacity
    setCapacity: raw.wgf_emitter2d_set_capacity,
    // wgf: call wgf_emitter2d_get_capacity
    getCapacity: raw.wgf_emitter2d_get_capacity,
    // wgf: call wgf_emitter2d_get_count
    getCount: raw.wgf_emitter2d_get_count,
    // wgf: call wgf_emitter2d_set_life
    setLife: raw.wgf_emitter2d_set_life,
    // wgf: call wgf_emitter2d_get_life_min
    getLifeMin: raw.wgf_emitter2d_get_life_min,
    // wgf: call wgf_emitter2d_get_life_max
    getLifeMax: raw.wgf_emitter2d_get_life_max,
    // wgf: call wgf_emitter2d_set_direction
    setDirection: raw.wgf_emitter2d_set_direction,
    // wgf: call wgf_emitter2d_get_direction
    getDirection: raw.wgf_emitter2d_get_direction,
    // wgf: call wgf_emitter2d_get_spread
    getSpread: raw.wgf_emitter2d_get_spread,
    // wgf: call wgf_emitter2d_set_speed
    setSpeed: raw.wgf_emitter2d_set_speed,
    // wgf: call wgf_emitter2d_get_speed_min
    getSpeedMin: raw.wgf_emitter2d_get_speed_min,
    // wgf: call wgf_emitter2d_get_speed_max
    getSpeedMax: raw.wgf_emitter2d_get_speed_max,
    // wgf: call wgf_emitter2d_set_radius
    setRadius: raw.wgf_emitter2d_set_radius,
    // wgf: call wgf_emitter2d_get_radius
    getRadius: raw.wgf_emitter2d_get_radius,
    // wgf: call wgf_emitter2d_set_gravity
    setGravity: raw.wgf_emitter2d_set_gravity,
    // wgf: call wgf_emitter2d_get_gravity
    getGravity: raw.wgf_emitter2d_get_gravity,
    // wgf: call wgf_emitter2d_set_drag
    setDrag: raw.wgf_emitter2d_set_drag,
    // wgf: call wgf_emitter2d_get_drag
    getDrag: raw.wgf_emitter2d_get_drag,
    // wgf: call wgf_emitter2d_set_size
    setSize: raw.wgf_emitter2d_set_size,
    // wgf: call wgf_emitter2d_get_size_start
    getSizeStart: raw.wgf_emitter2d_get_size_start,
    // wgf: call wgf_emitter2d_get_size_end
    getSizeEnd: raw.wgf_emitter2d_get_size_end,
    // wgf: call wgf_emitter2d_set_color
    setColor: raw.wgf_emitter2d_set_color,
    // wgf: call wgf_emitter2d_get_color_start
    getColorStart: raw.wgf_emitter2d_get_color_start,
    // wgf: call wgf_emitter2d_get_color_end
    getColorEnd: raw.wgf_emitter2d_get_color_end,
    // wgf: call wgf_emitter2d_set_stretch
    setStretch: raw.wgf_emitter2d_set_stretch,
    // wgf: call wgf_emitter2d_get_stretch
    getStretch: raw.wgf_emitter2d_get_stretch,
    // wgf: call wgf_emitter2d_clear
    clear: raw.wgf_emitter2d_clear,
    // wgf: call wgf_handle_is_alive
    isAlive: raw.wgf_handle_is_alive,
});
// wgf: typed Font
export const Font = Object.freeze({
    // wgf: call wgf_font_create
    create: raw.wgf_font_create,
    // wgf: call wgf_font_set_default
    setDefault: raw.wgf_font_set_default,
    // wgf: call wgf_font_get_default
    getDefault: raw.wgf_font_get_default,
    // wgf: call wgf_font_measure
    measure: raw.wgf_font_measure,
    // wgf: call wgf_handle_is_alive
    isAlive: raw.wgf_handle_is_alive,
});
// wgf: typed Fs
export const Fs = Object.freeze({
    // wgf: call wgf_fs_set_root
    setRoot: raw.wgf_fs_set_root,
    // wgf: call wgf_fs_get_root
    getRoot: raw.wgf_fs_get_root,
    // wgf: call wgf_fs_read
    read: raw.wgf_fs_read,
    // wgf: call wgf_fs_write
    write: raw.wgf_fs_write,
    // wgf: call wgf_fs_exists
    exists: raw.wgf_fs_exists,
    // wgf: call wgf_fs_remove
    remove: raw.wgf_fs_remove,
    // wgf: call wgf_fs_mkdir
    mkdir: raw.wgf_fs_mkdir,
    // wgf: call wgf_fs_rmdir
    rmdir: raw.wgf_fs_rmdir,
});
// wgf: typed FsTask
export const FsTask = Object.freeze({
    // wgf: call wgf_fs_task_get_status
    getStatus: raw.wgf_fs_task_get_status,
    // wgf: call wgf_fs_task_get_path
    getPath: raw.wgf_fs_task_get_path,
    // wgf: call wgf_fs_task_get_data
    getData: raw.wgf_fs_task_get_data,
    // wgf: call wgf_fs_task_get_size
    getSize: raw.wgf_fs_task_get_size,
    // wgf: call wgf_fs_task_get_text
    getText: raw.wgf_fs_task_get_text,
    // wgf: call wgf_fs_task_destroy
    destroy: raw.wgf_fs_task_destroy,
    // wgf: call wgf_handle_is_alive
    isAlive: raw.wgf_handle_is_alive,
});
// wgf: typed Gamepad
export const Gamepad = Object.freeze({
    // wgf: call wgf_gamepad_is_connected
    isConnected: raw.wgf_gamepad_is_connected,
    // wgf: call wgf_gamepad_get_name
    getName: raw.wgf_gamepad_get_name,
    // wgf: call wgf_gamepad_get_button_state
    getButtonState: raw.wgf_gamepad_get_button_state,
    // wgf: call wgf_gamepad_is_down
    isDown: raw.wgf_gamepad_is_down,
    // wgf: call wgf_gamepad_is_pressed
    isPressed: raw.wgf_gamepad_is_pressed,
    // wgf: call wgf_gamepad_is_released
    isReleased: raw.wgf_gamepad_is_released,
    // wgf: call wgf_gamepad_get_stick
    getStick: raw.wgf_gamepad_get_stick,
    // wgf: call wgf_gamepad_get_trigger
    getTrigger: raw.wgf_gamepad_get_trigger,
    // wgf: call wgf_gamepad_get_axis
    getAxis: raw.wgf_gamepad_get_axis,
    // wgf: call wgf_gamepad_set_deadzone
    setDeadzone: raw.wgf_gamepad_set_deadzone,
    // wgf: call wgf_gamepad_get_deadzone
    getDeadzone: raw.wgf_gamepad_get_deadzone,
});
// wgf: typed Handle
export const Handle = Object.freeze({
    // wgf: call wgf_handle_get_kind_name
    getKindName: raw.wgf_handle_get_kind_name,
    // wgf: call wgf_handle_is_alive
    isAlive: raw.wgf_handle_is_alive,
});
// wgf: typed Identity
export const Identity = Object.freeze({
    // wgf: call wgf_identity_set_company
    setCompany: raw.wgf_identity_set_company,
    // wgf: call wgf_identity_get_company
    getCompany: raw.wgf_identity_get_company,
    // wgf: call wgf_identity_set_product
    setProduct: raw.wgf_identity_set_product,
    // wgf: call wgf_identity_get_product
    getProduct: raw.wgf_identity_get_product,
});
// wgf: typed Input
export const Input = Object.freeze({
    // wgf: call wgf_input_get_chars
    getChars: raw.wgf_input_get_chars,
    // wgf: call wgf_input_set_pointer_captured
    setPointerCaptured: raw.wgf_input_set_pointer_captured,
    // wgf: call wgf_input_is_pointer_captured
    isPointerCaptured: raw.wgf_input_is_pointer_captured,
    // wgf: call wgf_input_set_keyboard_captured
    setKeyboardCaptured: raw.wgf_input_set_keyboard_captured,
    // wgf: call wgf_input_is_keyboard_captured
    isKeyboardCaptured: raw.wgf_input_is_keyboard_captured,
});
// wgf: typed Keyboard
export const Keyboard = Object.freeze({
    // wgf: call wgf_keyboard_get_state
    getState: raw.wgf_keyboard_get_state,
    // wgf: call wgf_keyboard_is_down
    isDown: raw.wgf_keyboard_is_down,
    // wgf: call wgf_keyboard_is_pressed
    isPressed: raw.wgf_keyboard_is_pressed,
    // wgf: call wgf_keyboard_is_released
    isReleased: raw.wgf_keyboard_is_released,
});
// wgf: typed Lifetime
export const Lifetime = Object.freeze({
    // wgf: call wgf_lifetime_set_seconds
    setSeconds: raw.wgf_lifetime_set_seconds,
    // wgf: call wgf_lifetime_get_seconds
    getSeconds: raw.wgf_lifetime_get_seconds,
    // wgf: call wgf_handle_is_alive
    isAlive: raw.wgf_handle_is_alive,
});
// wgf: typed Light
export const Light = Object.freeze({
    // wgf: call wgf_light_create
    create: raw.wgf_light_create,
    // wgf: call wgf_light_get_type
    getType: raw.wgf_light_get_type,
    // wgf: call wgf_light_set_color
    setColor: raw.wgf_light_set_color,
    // wgf: call wgf_light_get_color
    getColor: raw.wgf_light_get_color,
    // wgf: call wgf_light_set_intensity
    setIntensity: raw.wgf_light_set_intensity,
    // wgf: call wgf_light_get_intensity
    getIntensity: raw.wgf_light_get_intensity,
    // wgf: call wgf_light_set_range
    setRange: raw.wgf_light_set_range,
    // wgf: call wgf_light_get_range
    getRange: raw.wgf_light_get_range,
    // wgf: call wgf_light_set_spot_cone
    setSpotCone: raw.wgf_light_set_spot_cone,
    // wgf: call wgf_light_get_spot_inner_angle
    getSpotInnerAngle: raw.wgf_light_get_spot_inner_angle,
    // wgf: call wgf_light_get_spot_outer_angle
    getSpotOuterAngle: raw.wgf_light_get_spot_outer_angle,
    // wgf: call wgf_handle_is_alive
    isAlive: raw.wgf_handle_is_alive,
});
// wgf: typed Log
export const Log = Object.freeze({
    // wgf: call wgf_log_set_level
    setLevel: raw.wgf_log_set_level,
    // wgf: call wgf_log_get_level
    getLevel: raw.wgf_log_get_level,
    // wgf: call wgf_log_message
    message: raw.wgf_log_message,
    // wgf: call wgf_log_message_source
    messageSource: raw.wgf_log_message_source,
});
// wgf: typed Loop
export const Loop = Object.freeze({
    // wgf: call wgf_loop_get_frame_delta
    getFrameDelta: raw.wgf_loop_get_frame_delta,
    // wgf: call wgf_loop_set_tick_rate
    setTickRate: raw.wgf_loop_set_tick_rate,
    // wgf: call wgf_loop_get_tick_rate
    getTickRate: raw.wgf_loop_get_tick_rate,
    // wgf: call wgf_loop_get_tick_delta
    getTickDelta: raw.wgf_loop_get_tick_delta,
    // wgf: call wgf_loop_get_tick_fraction
    getTickFraction: raw.wgf_loop_get_tick_fraction,
    // wgf: call wgf_loop_set_time_scale
    setTimeScale: raw.wgf_loop_set_time_scale,
    // wgf: call wgf_loop_get_time_scale
    getTimeScale: raw.wgf_loop_get_time_scale,
    // wgf: call wgf_loop_set_target_fps
    setTargetFps: raw.wgf_loop_set_target_fps,
    // wgf: call wgf_loop_get_target_fps
    getTargetFps: raw.wgf_loop_get_target_fps,
    // wgf: call wgf_loop_get_fps
    getFps: raw.wgf_loop_get_fps,
    // wgf: call wgf_loop_get_frame_cost
    getFrameCost: raw.wgf_loop_get_frame_cost,
});
// wgf: typed Material
export const Material = Object.freeze({
    // wgf: call wgf_material_create
    create: raw.wgf_material_create,
    // wgf: call wgf_material_set_shading
    setShading: raw.wgf_material_set_shading,
    // wgf: call wgf_material_get_shading
    getShading: raw.wgf_material_get_shading,
    // wgf: call wgf_material_set_alpha_mode
    setAlphaMode: raw.wgf_material_set_alpha_mode,
    // wgf: call wgf_material_get_alpha_mode
    getAlphaMode: raw.wgf_material_get_alpha_mode,
    // wgf: call wgf_material_get_alpha_cutoff
    getAlphaCutoff: raw.wgf_material_get_alpha_cutoff,
    // wgf: call wgf_material_set_double_sided
    setDoubleSided: raw.wgf_material_set_double_sided,
    // wgf: call wgf_material_is_double_sided
    isDoubleSided: raw.wgf_material_is_double_sided,
    // wgf: call wgf_material_set_int
    setInt: raw.wgf_material_set_int,
    // wgf: call wgf_material_get_int
    getInt: raw.wgf_material_get_int,
    // wgf: call wgf_material_set_float
    setFloat: raw.wgf_material_set_float,
    // wgf: call wgf_material_get_float
    getFloat: raw.wgf_material_get_float,
    // wgf: call wgf_material_set_vec2
    setVec2: raw.wgf_material_set_vec2,
    // wgf: call wgf_material_get_vec2
    getVec2: raw.wgf_material_get_vec2,
    // wgf: call wgf_material_set_vec3
    setVec3: raw.wgf_material_set_vec3,
    // wgf: call wgf_material_get_vec3
    getVec3: raw.wgf_material_get_vec3,
    // wgf: call wgf_material_set_vec4
    setVec4: raw.wgf_material_set_vec4,
    // wgf: call wgf_material_get_vec4
    getVec4: raw.wgf_material_get_vec4,
    // wgf: call wgf_material_set_color
    setColor: raw.wgf_material_set_color,
    // wgf: call wgf_material_set_texture
    setTexture: raw.wgf_material_set_texture,
    // wgf: call wgf_material_get_texture
    getTexture: raw.wgf_material_get_texture,
    // wgf: call wgf_material_set_texture_sampling
    setTextureSampling: raw.wgf_material_set_texture_sampling,
    // wgf: call wgf_material_get_texture_wrap_u
    getTextureWrapU: raw.wgf_material_get_texture_wrap_u,
    // wgf: call wgf_material_get_texture_wrap_v
    getTextureWrapV: raw.wgf_material_get_texture_wrap_v,
    // wgf: call wgf_material_get_texture_filter
    getTextureFilter: raw.wgf_material_get_texture_filter,
    // wgf: call wgf_handle_is_alive
    isAlive: raw.wgf_handle_is_alive,
});
// wgf: typed Mesh
export const Mesh = Object.freeze({
    // wgf: call wgf_mesh_create_plane
    createPlane: raw.wgf_mesh_create_plane,
    // wgf: call wgf_mesh_create_cube
    createCube: raw.wgf_mesh_create_cube,
    // wgf: call wgf_mesh_create_sphere
    createSphere: raw.wgf_mesh_create_sphere,
    // wgf: call wgf_mesh_create_cylinder
    createCylinder: raw.wgf_mesh_create_cylinder,
    // wgf: call wgf_mesh_create_cone
    createCone: raw.wgf_mesh_create_cone,
    // wgf: call wgf_mesh_create_capsule
    createCapsule: raw.wgf_mesh_create_capsule,
    // wgf: call wgf_mesh_create_torus
    createTorus: raw.wgf_mesh_create_torus,
    // wgf: call wgf_mesh_get_material_count
    getMaterialCount: raw.wgf_mesh_get_material_count,
    // wgf: call wgf_mesh_get_material
    getMaterial: raw.wgf_mesh_get_material,
    // wgf: call wgf_handle_is_alive
    isAlive: raw.wgf_handle_is_alive,
});
// wgf: typed Model
export const Model = Object.freeze({
    // wgf: call wgf_model_create
    create: raw.wgf_model_create,
    // wgf: call wgf_model_set_mesh
    setMesh: raw.wgf_model_set_mesh,
    // wgf: call wgf_model_get_mesh
    getMesh: raw.wgf_model_get_mesh,
    // wgf: call wgf_model_set_tint
    setTint: raw.wgf_model_set_tint,
    // wgf: call wgf_model_get_tint
    getTint: raw.wgf_model_get_tint,
    // wgf: call wgf_model_set_material
    setMaterial: raw.wgf_model_set_material,
    // wgf: call wgf_model_get_material
    getMaterial: raw.wgf_model_get_material,
    // wgf: call wgf_handle_is_alive
    isAlive: raw.wgf_handle_is_alive,
});
// wgf: typed Motion
export const Motion = Object.freeze({
    // wgf: call wgf_motion_set_velocity
    setVelocity: raw.wgf_motion_set_velocity,
    // wgf: call wgf_motion_get_velocity
    getVelocity: raw.wgf_motion_get_velocity,
    // wgf: call wgf_motion_set_spin
    setSpin: raw.wgf_motion_set_spin,
    // wgf: call wgf_motion_get_spin
    getSpin: raw.wgf_motion_get_spin,
    // wgf: call wgf_motion_set_damping
    setDamping: raw.wgf_motion_set_damping,
    // wgf: call wgf_motion_get_damping
    getDamping: raw.wgf_motion_get_damping,
    // wgf: call wgf_motion_set_max_speed
    setMaxSpeed: raw.wgf_motion_set_max_speed,
    // wgf: call wgf_motion_get_max_speed
    getMaxSpeed: raw.wgf_motion_get_max_speed,
    // wgf: call wgf_handle_is_alive
    isAlive: raw.wgf_handle_is_alive,
});
// wgf: typed Mouse
export const Mouse = Object.freeze({
    // wgf: call wgf_mouse_get_position
    getPosition: raw.wgf_mouse_get_position,
    // wgf: call wgf_mouse_get_delta
    getDelta: raw.wgf_mouse_get_delta,
    // wgf: call wgf_mouse_get_wheel
    getWheel: raw.wgf_mouse_get_wheel,
    // wgf: call wgf_mouse_get_button_state
    getButtonState: raw.wgf_mouse_get_button_state,
    // wgf: call wgf_mouse_is_down
    isDown: raw.wgf_mouse_is_down,
    // wgf: call wgf_mouse_is_pressed
    isPressed: raw.wgf_mouse_is_pressed,
    // wgf: call wgf_mouse_is_released
    isReleased: raw.wgf_mouse_is_released,
    // wgf: call wgf_mouse_set_locked
    setLocked: raw.wgf_mouse_set_locked,
    // wgf: call wgf_mouse_is_locked
    isLocked: raw.wgf_mouse_is_locked,
    // wgf: call wgf_mouse_set_cursor_visible
    setCursorVisible: raw.wgf_mouse_set_cursor_visible,
    // wgf: call wgf_mouse_is_cursor_visible
    isCursorVisible: raw.wgf_mouse_is_cursor_visible,
});
// wgf: typed Physics
export const Physics = Object.freeze({
    // wgf: call wgf_physics_set_gravity
    setGravity: raw.wgf_physics_set_gravity,
    // wgf: call wgf_physics_get_gravity
    getGravity: raw.wgf_physics_get_gravity,
    // wgf: call wgf_physics_draw_bodies
    drawBodies: raw.wgf_physics_draw_bodies,
});
// wgf: typed Prefab
export const Prefab = Object.freeze({
    // wgf: call wgf_prefab_spawn
    spawn: raw.wgf_prefab_spawn,
    // wgf: call wgf_prefab_spawn_at
    spawnAt: raw.wgf_prefab_spawn_at,
    // wgf: call wgf_handle_is_alive
    isAlive: raw.wgf_handle_is_alive,
});
// wgf: typed Presentation
export const Presentation = Object.freeze({
    // wgf: call wgf_presentation_set
    set: raw.wgf_presentation_set,
    // wgf: call wgf_presentation_get_mode
    getMode: raw.wgf_presentation_get_mode,
    // wgf: call wgf_presentation_set_bar_color
    setBarColor: raw.wgf_presentation_set_bar_color,
    // wgf: call wgf_presentation_get_bar_color
    getBarColor: raw.wgf_presentation_get_bar_color,
    // wgf: call wgf_presentation_get_width
    getWidth: raw.wgf_presentation_get_width,
    // wgf: call wgf_presentation_get_height
    getHeight: raw.wgf_presentation_get_height,
    // wgf: call wgf_presentation_get_visible
    getVisible: raw.wgf_presentation_get_visible,
    // wgf: call wgf_presentation_get_scale
    getScale: raw.wgf_presentation_get_scale,
});
// wgf: typed Probe
export const Probe = Object.freeze({
    // wgf: call wgf_probe_set_value
    setValue: raw.wgf_probe_set_value,
    // wgf: call wgf_probe_get_value
    getValue: raw.wgf_probe_get_value,
    // wgf: call wgf_probe_has_value
    hasValue: raw.wgf_probe_has_value,
    // wgf: call wgf_probe_set_text
    setText: raw.wgf_probe_set_text,
    // wgf: call wgf_probe_get_text
    getText: raw.wgf_probe_get_text,
    // wgf: call wgf_probe_get_count
    getCount: raw.wgf_probe_get_count,
    // wgf: call wgf_probe_get_name
    getName: raw.wgf_probe_get_name,
});
// wgf: typed Random
export const Random = Object.freeze({
    // wgf: call wgf_random_set_seed
    setSeed: raw.wgf_random_set_seed,
    // wgf: call wgf_random_get_seed
    getSeed: raw.wgf_random_get_seed,
    // wgf: call wgf_random_get_float
    getFloat: raw.wgf_random_get_float,
    // wgf: call wgf_random_get_range
    getRange: raw.wgf_random_get_range,
    // wgf: call wgf_random_get_int
    getInt: raw.wgf_random_get_int,
});
// wgf: typed Render
export const Render = Object.freeze({
    // wgf: call wgf_render_set_clear_color
    setClearColor: raw.wgf_render_set_clear_color,
    // wgf: call wgf_render_get_clear_color
    getClearColor: raw.wgf_render_get_clear_color,
    // wgf: call wgf_render_get_width
    getWidth: raw.wgf_render_get_width,
    // wgf: call wgf_render_get_height
    getHeight: raw.wgf_render_get_height,
    // wgf: call wgf_render_get_dpi_scale
    getDpiScale: raw.wgf_render_get_dpi_scale,
    // wgf: call wgf_render_push_clip
    pushClip: raw.wgf_render_push_clip,
    // wgf: call wgf_render_pop_clip
    popClip: raw.wgf_render_pop_clip,
});
// wgf: typed Resource
export const Resource = Object.freeze({
    // wgf: call wgf_resource_get_status
    getStatus: raw.wgf_resource_get_status,
    // wgf: call wgf_resource_get_path
    getPath: raw.wgf_resource_get_path,
    // wgf: call wgf_resource_release
    release: raw.wgf_resource_release,
    // wgf: call wgf_resource_set_load_budget
    setLoadBudget: raw.wgf_resource_set_load_budget,
    // wgf: call wgf_resource_get_load_budget
    getLoadBudget: raw.wgf_resource_get_load_budget,
});
// wgf: typed Scene
export const Scene = Object.freeze({
    // wgf: call wgf_scene_create
    create: raw.wgf_scene_create,
    // wgf: call wgf_scene_instantiate
    instantiate: raw.wgf_scene_instantiate,
    // wgf: call wgf_scene_find_prefab
    prefab: raw.wgf_scene_find_prefab,
    // wgf: call wgf_scene_get_actor_count
    getActorCount: raw.wgf_scene_get_actor_count,
    // wgf: call wgf_scene_get_prefab_count
    getPrefabCount: raw.wgf_scene_get_prefab_count,
    // wgf: call wgf_scene_get_prefab_name
    getPrefabName: raw.wgf_scene_get_prefab_name,
    // wgf: call wgf_scene_has_prefab
    hasPrefab: raw.wgf_scene_has_prefab,
    // wgf: call wgf_handle_is_alive
    isAlive: raw.wgf_handle_is_alive,
    // wgf: call wgf_scene_find_prefab wgf_prefab_spawn wgf_prefab_spawn_at
    spawnPrefab(scene, name, parent, x, y, z, angle) {
        const prefab = raw.wgf_scene_find_prefab(scene, name);
        return x === undefined ? raw.wgf_prefab_spawn(prefab, parent)
            : raw.wgf_prefab_spawn_at(prefab, parent, x, y ?? 0, z ?? 0, angle ?? 0);
    },
});
// wgf: typed Shape2d
export const Shape2d = Object.freeze({
    // wgf: call wgf_shape2d_create
    create: raw.wgf_shape2d_create,
    // wgf: call wgf_shape2d_get_kind
    getKind: raw.wgf_shape2d_get_kind,
    // wgf: call wgf_shape2d_set_rectangle
    setRectangle: raw.wgf_shape2d_set_rectangle,
    // wgf: call wgf_shape2d_set_circle
    setCircle: raw.wgf_shape2d_set_circle,
    // wgf: call wgf_shape2d_set_line
    setLine: raw.wgf_shape2d_set_line,
    // wgf: call wgf_shape2d_set_polygon
    setPolygon: raw.wgf_shape2d_set_polygon,
    // wgf: call wgf_shape2d_get_size
    getSize: raw.wgf_shape2d_get_size,
    // wgf: call wgf_shape2d_get_radius
    getRadius: raw.wgf_shape2d_get_radius,
    // wgf: call wgf_shape2d_get_line_start
    getLineStart: raw.wgf_shape2d_get_line_start,
    // wgf: call wgf_shape2d_get_line_end
    getLineEnd: raw.wgf_shape2d_get_line_end,
    // wgf: call wgf_shape2d_get_point_count
    getPointCount: raw.wgf_shape2d_get_point_count,
    // wgf: call wgf_shape2d_get_points
    getPoints: raw.wgf_shape2d_get_points,
    // wgf: call wgf_shape2d_set_pivot
    setPivot: raw.wgf_shape2d_set_pivot,
    // wgf: call wgf_shape2d_get_pivot
    getPivot: raw.wgf_shape2d_get_pivot,
    // wgf: call wgf_shape2d_set_outline
    setOutline: raw.wgf_shape2d_set_outline,
    // wgf: call wgf_shape2d_get_outline
    getOutline: raw.wgf_shape2d_get_outline,
    // wgf: call wgf_shape2d_set_color
    setColor: raw.wgf_shape2d_set_color,
    // wgf: call wgf_shape2d_get_color
    getColor: raw.wgf_shape2d_get_color,
    // wgf: call wgf_handle_is_alive
    isAlive: raw.wgf_handle_is_alive,
});
// wgf: typed Shape3d
export const Shape3d = Object.freeze({
    // wgf: call wgf_shape3d_create
    create: raw.wgf_shape3d_create,
    // wgf: call wgf_shape3d_get_kind
    getKind: raw.wgf_shape3d_get_kind,
    // wgf: call wgf_shape3d_set_cube
    setCube: raw.wgf_shape3d_set_cube,
    // wgf: call wgf_shape3d_set_sphere
    setSphere: raw.wgf_shape3d_set_sphere,
    // wgf: call wgf_shape3d_set_rectangle
    setRectangle: raw.wgf_shape3d_set_rectangle,
    // wgf: call wgf_shape3d_set_circle
    setCircle: raw.wgf_shape3d_set_circle,
    // wgf: call wgf_shape3d_set_line
    setLine: raw.wgf_shape3d_set_line,
    // wgf: call wgf_shape3d_set_line_strip
    setLineStrip: raw.wgf_shape3d_set_line_strip,
    // wgf: call wgf_shape3d_get_point_count
    getPointCount: raw.wgf_shape3d_get_point_count,
    // wgf: call wgf_shape3d_get_points
    getPoints: raw.wgf_shape3d_get_points,
    // wgf: call wgf_shape3d_get_size
    getSize: raw.wgf_shape3d_get_size,
    // wgf: call wgf_shape3d_get_radius
    getRadius: raw.wgf_shape3d_get_radius,
    // wgf: call wgf_shape3d_get_line_start
    getLineStart: raw.wgf_shape3d_get_line_start,
    // wgf: call wgf_shape3d_get_line_end
    getLineEnd: raw.wgf_shape3d_get_line_end,
    // wgf: call wgf_shape3d_set_color
    setColor: raw.wgf_shape3d_set_color,
    // wgf: call wgf_shape3d_get_color
    getColor: raw.wgf_shape3d_get_color,
    // wgf: call wgf_handle_is_alive
    isAlive: raw.wgf_handle_is_alive,
});
// wgf: typed Sound
export const Sound = Object.freeze({
    // wgf: call wgf_sound_create
    create: raw.wgf_sound_create,
    // wgf: call wgf_sound_create_streamed
    createStreamed: raw.wgf_sound_create_streamed,
    // wgf: call wgf_sound_add_segment
    addSegment: raw.wgf_sound_add_segment,
    // wgf: call wgf_sound_get_duration
    getDuration: raw.wgf_sound_get_duration,
    // wgf: call wgf_handle_is_alive
    isAlive: raw.wgf_handle_is_alive,
});
// wgf: typed Sprite
export const Sprite = Object.freeze({
    // wgf: call wgf_sprite_create
    create: raw.wgf_sprite_create,
    // wgf: call wgf_sprite_set_texture
    setTexture: raw.wgf_sprite_set_texture,
    // wgf: call wgf_sprite_get_texture
    getTexture: raw.wgf_sprite_get_texture,
    // wgf: call wgf_sprite_set_source
    setSource: raw.wgf_sprite_set_source,
    // wgf: call wgf_sprite_get_source
    getSource: raw.wgf_sprite_get_source,
    // wgf: call wgf_sprite_set_size
    setSize: raw.wgf_sprite_set_size,
    // wgf: call wgf_sprite_get_size
    getSize: raw.wgf_sprite_get_size,
    // wgf: call wgf_sprite_set_pivot
    setPivot: raw.wgf_sprite_set_pivot,
    // wgf: call wgf_sprite_get_pivot
    getPivot: raw.wgf_sprite_get_pivot,
    // wgf: call wgf_sprite_set_tint
    setTint: raw.wgf_sprite_set_tint,
    // wgf: call wgf_sprite_get_tint
    getTint: raw.wgf_sprite_get_tint,
    // wgf: call wgf_handle_is_alive
    isAlive: raw.wgf_handle_is_alive,
});
// wgf: typed Stage2d
export const Stage2d = Object.freeze({
    // wgf: call wgf_stage2d_create
    create: raw.wgf_stage2d_create,
    // wgf: call wgf_stage2d_draw
    draw: raw.wgf_stage2d_draw,
    // wgf: call wgf_stage2d_set_camera
    setCamera: raw.wgf_stage2d_set_camera,
    // wgf: call wgf_stage2d_get_camera
    getCamera: raw.wgf_stage2d_get_camera,
    // wgf: call wgf_stage2d_find
    find: raw.wgf_stage2d_find,
    // wgf: call wgf_handle_is_alive
    isAlive: raw.wgf_handle_is_alive,
});
// wgf: typed Stage3d
export const Stage3d = Object.freeze({
    // wgf: call wgf_stage3d_create
    create: raw.wgf_stage3d_create,
    // wgf: call wgf_stage3d_draw
    draw: raw.wgf_stage3d_draw,
    // wgf: call wgf_stage3d_set_camera
    setCamera: raw.wgf_stage3d_set_camera,
    // wgf: call wgf_stage3d_get_camera
    getCamera: raw.wgf_stage3d_get_camera,
    // wgf: call wgf_stage3d_find
    find: raw.wgf_stage3d_find,
    // wgf: call wgf_stage3d_set_ambient
    setAmbient: raw.wgf_stage3d_set_ambient,
    // wgf: call wgf_stage3d_get_ambient_color
    getAmbientColor: raw.wgf_stage3d_get_ambient_color,
    // wgf: call wgf_stage3d_get_ambient_intensity
    getAmbientIntensity: raw.wgf_stage3d_get_ambient_intensity,
    // wgf: call wgf_stage3d_set_tonemap
    setTonemap: raw.wgf_stage3d_set_tonemap,
    // wgf: call wgf_stage3d_get_tonemap
    getTonemap: raw.wgf_stage3d_get_tonemap,
    // wgf: call wgf_stage3d_get_exposure
    getExposure: raw.wgf_stage3d_get_exposure,
    // wgf: call wgf_stage3d_set_culling
    setCulling: raw.wgf_stage3d_set_culling,
    // wgf: call wgf_stage3d_is_culling
    isCulling: raw.wgf_stage3d_is_culling,
    // wgf: call wgf_handle_is_alive
    isAlive: raw.wgf_handle_is_alive,
});
// wgf: typed Text
export const Text = Object.freeze({
    // wgf: call wgf_text_create
    create: raw.wgf_text_create,
    // wgf: call wgf_text_set_font
    setFont: raw.wgf_text_set_font,
    // wgf: call wgf_text_get_font
    getFont: raw.wgf_text_get_font,
    // wgf: call wgf_text_set_string
    setString: raw.wgf_text_set_string,
    // wgf: call wgf_text_get_string
    getString: raw.wgf_text_get_string,
    // wgf: call wgf_text_set_font_size
    setFontSize: raw.wgf_text_set_font_size,
    // wgf: call wgf_text_get_font_size
    getFontSize: raw.wgf_text_get_font_size,
    // wgf: call wgf_text_set_color
    setColor: raw.wgf_text_set_color,
    // wgf: call wgf_text_get_color
    getColor: raw.wgf_text_get_color,
    // wgf: call wgf_text_set_wrap_width
    setWrapWidth: raw.wgf_text_set_wrap_width,
    // wgf: call wgf_text_get_wrap_width
    getWrapWidth: raw.wgf_text_get_wrap_width,
    // wgf: call wgf_text_set_align
    setAlign: raw.wgf_text_set_align,
    // wgf: call wgf_text_get_halign
    getHalign: raw.wgf_text_get_halign,
    // wgf: call wgf_text_get_valign
    getValign: raw.wgf_text_get_valign,
    // wgf: call wgf_handle_is_alive
    isAlive: raw.wgf_handle_is_alive,
});
// wgf: typed Texture
export const Texture = Object.freeze({
    // wgf: call wgf_texture_create
    create: raw.wgf_texture_create,
    // wgf: call wgf_texture_get_width
    getWidth: raw.wgf_texture_get_width,
    // wgf: call wgf_texture_get_height
    getHeight: raw.wgf_texture_get_height,
    // wgf: call wgf_texture_set_sampling
    setSampling: raw.wgf_texture_set_sampling,
    // wgf: call wgf_texture_get_wrap_u
    getWrapU: raw.wgf_texture_get_wrap_u,
    // wgf: call wgf_texture_get_wrap_v
    getWrapV: raw.wgf_texture_get_wrap_v,
    // wgf: call wgf_texture_get_filter
    getFilter: raw.wgf_texture_get_filter,
    // wgf: call wgf_handle_is_alive
    isAlive: raw.wgf_handle_is_alive,
});
// wgf: typed Time
export const Time = Object.freeze({
    // wgf: call wgf_time_get_seconds
    getSeconds: raw.wgf_time_get_seconds,
});
// wgf: typed Touch
export const Touch = Object.freeze({
    // wgf: call wgf_touch_get_count
    getCount: raw.wgf_touch_get_count,
    // wgf: call wgf_touch_get_id
    getId: raw.wgf_touch_get_id,
    // wgf: call wgf_touch_get_state
    getState: raw.wgf_touch_get_state,
    // wgf: call wgf_touch_get_position
    getPosition: raw.wgf_touch_get_position,
    // wgf: call wgf_touch_get_delta
    getDelta: raw.wgf_touch_get_delta,
    // wgf: call wgf_touch_set_mouse_emulated
    setMouseEmulated: raw.wgf_touch_set_mouse_emulated,
    // wgf: call wgf_touch_is_mouse_emulated
    isMouseEmulated: raw.wgf_touch_is_mouse_emulated,
    // wgf: call wgf_touch_is_gesture
    isGesture: raw.wgf_touch_is_gesture,
    // wgf: call wgf_touch_get_gesture_center
    getGestureCenter: raw.wgf_touch_get_gesture_center,
    // wgf: call wgf_touch_get_gesture_pan
    getGesturePan: raw.wgf_touch_get_gesture_pan,
    // wgf: call wgf_touch_get_gesture_scale
    getGestureScale: raw.wgf_touch_get_gesture_scale,
    // wgf: call wgf_touch_get_gesture_rotation
    getGestureRotation: raw.wgf_touch_get_gesture_rotation,
});
// wgf: typed Ui
export const Ui = Object.freeze({
    // wgf: call wgf_ui_begin
    begin: raw.wgf_ui_begin,
    // wgf: call wgf_ui_end
    end: raw.wgf_ui_end,
    // wgf: call wgf_ui_begin_box
    beginBox: raw.wgf_ui_begin_box,
    // wgf: call wgf_ui_end_box
    endBox: raw.wgf_ui_end_box,
    // wgf: call wgf_ui_begin_panel
    beginPanel: raw.wgf_ui_begin_panel,
    // wgf: call wgf_ui_end_panel
    endPanel: raw.wgf_ui_end_panel,
    // wgf: call wgf_ui_set_width
    setWidth: raw.wgf_ui_set_width,
    // wgf: call wgf_ui_set_height
    setHeight: raw.wgf_ui_set_height,
    // wgf: call wgf_ui_set_padding
    setPadding: raw.wgf_ui_set_padding,
    // wgf: call wgf_ui_set_gap
    setGap: raw.wgf_ui_set_gap,
    // wgf: call wgf_ui_set_align
    setAlign: raw.wgf_ui_set_align,
    // wgf: call wgf_ui_set_color
    setColor: raw.wgf_ui_set_color,
    // wgf: call wgf_ui_label
    label: raw.wgf_ui_label,
    // wgf: call wgf_ui_spacer
    spacer: raw.wgf_ui_spacer,
    // wgf: call wgf_ui_button
    button: raw.wgf_ui_button,
    // wgf: call wgf_ui_set_focus
    setFocus: raw.wgf_ui_set_focus,
    // wgf: call wgf_ui_get_focus
    getFocus: raw.wgf_ui_get_focus,
    // wgf: call wgf_ui_set_style_color
    setStyleColor: raw.wgf_ui_set_style_color,
    // wgf: call wgf_ui_get_style_color
    getStyleColor: raw.wgf_ui_get_style_color,
    // wgf: call wgf_ui_set_style_value
    setStyleValue: raw.wgf_ui_set_style_value,
    // wgf: call wgf_ui_get_style_value
    getStyleValue: raw.wgf_ui_get_style_value,
    // wgf: call wgf_ui_set_style_font
    setStyleFont: raw.wgf_ui_set_style_font,
    // wgf: call wgf_ui_get_style_font
    getStyleFont: raw.wgf_ui_get_style_font,
    // wgf: call wgf_ui_reset_style
    resetStyle: raw.wgf_ui_reset_style,
});
// wgf: typed Vehicle
export const Vehicle = Object.freeze({
    // wgf: call wgf_vehicle_set_wheels
    setWheels: raw.wgf_vehicle_set_wheels,
    // wgf: call wgf_vehicle_get_wheel_count
    getWheelCount: raw.wgf_vehicle_get_wheel_count,
    // wgf: call wgf_vehicle_get_wheel
    getWheel: raw.wgf_vehicle_get_wheel,
    // wgf: call wgf_vehicle_set_wheel_size
    setWheelSize: raw.wgf_vehicle_set_wheel_size,
    // wgf: call wgf_vehicle_set_suspension
    setSuspension: raw.wgf_vehicle_set_suspension,
    // wgf: call wgf_vehicle_set_steering
    setSteering: raw.wgf_vehicle_set_steering,
    // wgf: call wgf_vehicle_set_grip
    setGrip: raw.wgf_vehicle_set_grip,
    // wgf: call wgf_vehicle_get_wheel_size
    getWheelSize: raw.wgf_vehicle_get_wheel_size,
    // wgf: call wgf_vehicle_get_suspension
    getSuspension: raw.wgf_vehicle_get_suspension,
    // wgf: call wgf_vehicle_get_steering
    getSteering: raw.wgf_vehicle_get_steering,
    // wgf: call wgf_vehicle_get_grip
    getGrip: raw.wgf_vehicle_get_grip,
    // wgf: call wgf_vehicle_set_engine
    setEngine: raw.wgf_vehicle_set_engine,
    // wgf: call wgf_vehicle_set_gears
    setGears: raw.wgf_vehicle_set_gears,
    // wgf: call wgf_vehicle_set_drive
    setDrive: raw.wgf_vehicle_set_drive,
    // wgf: call wgf_vehicle_get_engine
    getEngine: raw.wgf_vehicle_get_engine,
    // wgf: call wgf_vehicle_get_gear_count
    getGearCount: raw.wgf_vehicle_get_gear_count,
    // wgf: call wgf_vehicle_get_gear_ratio
    getGearRatio: raw.wgf_vehicle_get_gear_ratio,
    // wgf: call wgf_vehicle_get_drive
    getDrive: raw.wgf_vehicle_get_drive,
    // wgf: call wgf_vehicle_set_input
    setInput: raw.wgf_vehicle_set_input,
    // wgf: call wgf_vehicle_get_speed
    getSpeed: raw.wgf_vehicle_get_speed,
    // wgf: call wgf_vehicle_get_rpm
    getRpm: raw.wgf_vehicle_get_rpm,
    // wgf: call wgf_vehicle_get_gear
    getGear: raw.wgf_vehicle_get_gear,
    // wgf: call wgf_vehicle_get_wheel_slip
    getWheelSlip: raw.wgf_vehicle_get_wheel_slip,
    // wgf: call wgf_vehicle_reset
    reset: raw.wgf_vehicle_reset,
    // wgf: call wgf_handle_is_alive
    isAlive: raw.wgf_handle_is_alive,
});
// wgf: typed Version
export const Version = Object.freeze({
    // wgf: call wgf_version_get
    get: raw.wgf_version_get,
    // wgf: call wgf_version_get_major
    getMajor: raw.wgf_version_get_major,
    // wgf: call wgf_version_get_minor
    getMinor: raw.wgf_version_get_minor,
    // wgf: call wgf_version_get_patch
    getPatch: raw.wgf_version_get_patch,
});
// wgf: typed Voice
export const Voice = Object.freeze({
    // wgf: call wgf_voice_create
    create: raw.wgf_voice_create,
    // wgf: call wgf_voice_destroy
    destroy: raw.wgf_voice_destroy,
    // wgf: call wgf_voice_set_sound
    setSound: raw.wgf_voice_set_sound,
    // wgf: call wgf_voice_get_sound
    getSound: raw.wgf_voice_get_sound,
    // wgf: call wgf_voice_play
    play: raw.wgf_voice_play,
    // wgf: call wgf_voice_pause
    pause: raw.wgf_voice_pause,
    // wgf: call wgf_voice_resume
    resume: raw.wgf_voice_resume,
    // wgf: call wgf_voice_stop
    stop: raw.wgf_voice_stop,
    // wgf: call wgf_voice_get_state
    getState: raw.wgf_voice_get_state,
    // wgf: call wgf_voice_set_loop
    setLoop: raw.wgf_voice_set_loop,
    // wgf: call wgf_voice_is_loop
    isLoop: raw.wgf_voice_is_loop,
    // wgf: call wgf_voice_set_volume
    setVolume: raw.wgf_voice_set_volume,
    // wgf: call wgf_voice_get_volume
    getVolume: raw.wgf_voice_get_volume,
    // wgf: call wgf_voice_set_pitch
    setPitch: raw.wgf_voice_set_pitch,
    // wgf: call wgf_voice_get_pitch
    getPitch: raw.wgf_voice_get_pitch,
    // wgf: call wgf_voice_set_pan
    setPan: raw.wgf_voice_set_pan,
    // wgf: call wgf_voice_get_pan
    getPan: raw.wgf_voice_get_pan,
    // wgf: call wgf_voice_set_position
    setPosition: raw.wgf_voice_set_position,
    // wgf: call wgf_voice_get_position
    getPosition: raw.wgf_voice_get_position,
    // wgf: call wgf_voice_set_segment
    setSegment: raw.wgf_voice_set_segment,
    // wgf: call wgf_voice_get_segment
    getSegment: raw.wgf_voice_get_segment,
    // wgf: call wgf_handle_is_alive
    isAlive: raw.wgf_handle_is_alive,
});
// wgf: typed Window
export const Window = Object.freeze({
    // wgf: call wgf_window_set_title
    setTitle: raw.wgf_window_set_title,
    // wgf: call wgf_window_get_title
    getTitle: raw.wgf_window_get_title,
    // wgf: call wgf_window_set_size
    setSize: raw.wgf_window_set_size,
    // wgf: call wgf_window_get_width
    getWidth: raw.wgf_window_get_width,
    // wgf: call wgf_window_get_height
    getHeight: raw.wgf_window_get_height,
    // wgf: call wgf_window_request_fullscreen
    requestFullscreen: raw.wgf_window_request_fullscreen,
    // wgf: call wgf_window_is_fullscreen
    isFullscreen: raw.wgf_window_is_fullscreen,
    // wgf: call wgf_window_can_fullscreen
    canFullscreen: raw.wgf_window_can_fullscreen,
    // wgf: call wgf_window_set_position
    setPosition: raw.wgf_window_set_position,
    // wgf: call wgf_window_get_x
    getX: raw.wgf_window_get_x,
    // wgf: call wgf_window_get_y
    getY: raw.wgf_window_get_y,
    // wgf: call wgf_window_get_monitor_count
    getMonitorCount: raw.wgf_window_get_monitor_count,
    // wgf: call wgf_window_set_monitor
    setMonitor: raw.wgf_window_set_monitor,
    // wgf: call wgf_window_get_monitor
    getMonitor: raw.wgf_window_get_monitor,
    // wgf: call wgf_window_get_monitor_width
    getMonitorWidth: raw.wgf_window_get_monitor_width,
    // wgf: call wgf_window_get_monitor_height
    getMonitorHeight: raw.wgf_window_get_monitor_height,
    // wgf: call wgf_window_get_monitor_x
    getMonitorX: raw.wgf_window_get_monitor_x,
    // wgf: call wgf_window_get_monitor_y
    getMonitorY: raw.wgf_window_get_monitor_y,
    // wgf: call wgf_window_get_monitor_name
    getMonitorName: raw.wgf_window_get_monitor_name,
    // wgf: call wgf_window_set_visible
    setVisible: raw.wgf_window_set_visible,
    // wgf: call wgf_window_is_visible
    isVisible: raw.wgf_window_is_visible,
    // wgf: call wgf_window_set_resizable
    setResizable: raw.wgf_window_set_resizable,
    // wgf: call wgf_window_is_resizable
    isResizable: raw.wgf_window_is_resizable,
    // wgf: call wgf_window_set_decorated
    setDecorated: raw.wgf_window_set_decorated,
    // wgf: call wgf_window_is_decorated
    isDecorated: raw.wgf_window_is_decorated,
    // wgf: call wgf_window_is_focused
    isFocused: raw.wgf_window_is_focused,
    // wgf: call wgf_window_set_transparent
    setTransparent: raw.wgf_window_set_transparent,
    // wgf: call wgf_window_is_transparent
    isTransparent: raw.wgf_window_is_transparent,
    // wgf: call wgf_window_set_high_dpi
    setHighDpi: raw.wgf_window_set_high_dpi,
    // wgf: call wgf_window_is_high_dpi
    isHighDpi: raw.wgf_window_is_high_dpi,
    // wgf: call wgf_window_set_vsync
    setVsync: raw.wgf_window_set_vsync,
    // wgf: call wgf_window_is_vsync
    isVsync: raw.wgf_window_is_vsync,
    // wgf: call wgf_window_set_msaa
    setMsaa: raw.wgf_window_set_msaa,
    // wgf: call wgf_window_is_msaa
    isMsaa: raw.wgf_window_is_msaa,
});
// wgf: typed World
export const World = Object.freeze({
    // wgf: call wgf_world_get_event_count
    getEventCount: raw.wgf_world_get_event_count,
    // wgf: call wgf_world_take_events
    takeEvents: raw.wgf_world_take_events,
    // wgf: call wgf_world_clear
    clear: raw.wgf_world_clear,
    // wgf: call wgf_world_dump
    dump: raw.wgf_world_dump,
});
// wgf: enum ActorDestroy
export const ActorDestroy = Object.freeze({ DESTROY_CHILDREN: 0, KEEP_CHILDREN: 1 });
// wgf: enum ActorKind
export const ActorKind = Object.freeze({ NONE: 0, PLAIN: 1, STAGE2D: 2, SPRITE: 3, CAMERA2D: 4, TEXT: 5, SHAPE2D: 6, EMITTER2D: 7, CAMERA3D: 8, STAGE3D: 9, LIGHT: 10, MODEL: 11, SHAPE3D: 12 });
// wgf: enum AlphaMode
export const AlphaMode = Object.freeze({ OPAQUE: 0, MASK: 1, BLEND: 2 });
// wgf: enum AssetCacheMode
export const AssetCacheMode = Object.freeze({ REVALIDATE: 0, TRUST: 1, OFF: 2 });
// wgf: enum AssetTaskStatus
export const AssetTaskStatus = Object.freeze({ NONE: 0, PENDING: 1, DONE: 2, FAILED: 3 });
// wgf: enum BodyShape
export const BodyShape = Object.freeze({ BOX: 0, SPHERE: 1, CAPSULE: 2, CONVEX: 3, MESH: 4 });
// wgf: enum BodyType
export const BodyType = Object.freeze({ STATIC: 0, DYNAMIC: 1, KINEMATIC: 2, SENSOR: 3 });
// wgf: enum BoundsMode
export const BoundsMode = Object.freeze({ WRAP: 0, CLAMP: 1, DESTROY: 2 });
// wgf: enum ColorStock
export const ColorStock = Object.freeze({ BLANK: 0, WHITE: 1, BLACK: 2, LIGHTGRAY: 3, GRAY: 4, DARKGRAY: 5, YELLOW: 6, GOLD: 7, ORANGE: 8, PINK: 9, RED: 10, MAROON: 11, GREEN: 12, LIME: 13, DARKGREEN: 14, SKYBLUE: 15, BLUE: 16, DARKBLUE: 17, PURPLE: 18, VIOLET: 19, DARKPURPLE: 20, BEIGE: 21, BROWN: 22, DARKBROWN: 23, MAGENTA: 24, RAYWHITE: 25 });
// wgf: enum Component
export const Component = Object.freeze({ NONE: 0, MOTION: 1, BOUNDS: 2, LIFETIME: 3, COLLIDER: 4, VOICE: 5, BODY: 6, VEHICLE: 7 });
// wgf: enum FsTaskStatus
export const FsTaskStatus = Object.freeze({ NONE: 0, PENDING: 1, DONE: 2, NOT_FOUND: 3, FAILED: 4 });
// wgf: enum GamepadAxis
export const GamepadAxis = Object.freeze({ LEFT_X: 0, LEFT_Y: 1, RIGHT_X: 2, RIGHT_Y: 3, LEFT_TRIGGER: 4, RIGHT_TRIGGER: 5 });
// wgf: enum GamepadButton
export const GamepadButton = Object.freeze({ SOUTH: 0, EAST: 1, WEST: 2, NORTH: 3, LEFT_BUMPER: 4, RIGHT_BUMPER: 5, LEFT_TRIGGER: 6, RIGHT_TRIGGER: 7, BACK: 8, START: 9, GUIDE: 10, LEFT_STICK: 11, RIGHT_STICK: 12, DPAD_UP: 13, DPAD_DOWN: 14, DPAD_LEFT: 15, DPAD_RIGHT: 16 });
// wgf: enum GamepadStick
export const GamepadStick = Object.freeze({ LEFT: 0, RIGHT: 1 });
// wgf: enum GamepadTrigger
export const GamepadTrigger = Object.freeze({ LEFT: 0, RIGHT: 1 });
// wgf: enum InputState
export const InputState = Object.freeze({ UP: 0, PRESSED: 1, DOWN: 2, RELEASED: 3 });
// wgf: enum KeyboardKey
export const KeyboardKey = Object.freeze({ SPACE: 32, APOSTROPHE: 39, COMMA: 44, MINUS: 45, PERIOD: 46, SLASH: 47, KEY_0: 48, KEY_1: 49, KEY_2: 50, KEY_3: 51, KEY_4: 52, KEY_5: 53, KEY_6: 54, KEY_7: 55, KEY_8: 56, KEY_9: 57, SEMICOLON: 59, EQUAL: 61, A: 65, B: 66, C: 67, D: 68, E: 69, F: 70, G: 71, H: 72, I: 73, J: 74, K: 75, L: 76, M: 77, N: 78, O: 79, P: 80, Q: 81, R: 82, S: 83, T: 84, U: 85, V: 86, W: 87, X: 88, Y: 89, Z: 90, LEFT_BRACKET: 91, BACKSLASH: 92, RIGHT_BRACKET: 93, GRAVE_ACCENT: 96, WORLD_1: 161, WORLD_2: 162, ESCAPE: 256, ENTER: 257, TAB: 258, BACKSPACE: 259, INSERT: 260, DELETE: 261, RIGHT: 262, LEFT: 263, DOWN: 264, UP: 265, PAGE_UP: 266, PAGE_DOWN: 267, HOME: 268, END: 269, CAPS_LOCK: 280, SCROLL_LOCK: 281, NUM_LOCK: 282, PRINT_SCREEN: 283, PAUSE: 284, F1: 290, F2: 291, F3: 292, F4: 293, F5: 294, F6: 295, F7: 296, F8: 297, F9: 298, F10: 299, F11: 300, F12: 301, F13: 302, F14: 303, F15: 304, F16: 305, F17: 306, F18: 307, F19: 308, F20: 309, F21: 310, F22: 311, F23: 312, F24: 313, F25: 314, KP_0: 320, KP_1: 321, KP_2: 322, KP_3: 323, KP_4: 324, KP_5: 325, KP_6: 326, KP_7: 327, KP_8: 328, KP_9: 329, KP_DECIMAL: 330, KP_DIVIDE: 331, KP_MULTIPLY: 332, KP_SUBTRACT: 333, KP_ADD: 334, KP_ENTER: 335, KP_EQUAL: 336, LEFT_SHIFT: 340, LEFT_CONTROL: 341, LEFT_ALT: 342, LEFT_SUPER: 343, RIGHT_SHIFT: 344, RIGHT_CONTROL: 345, RIGHT_ALT: 346, RIGHT_SUPER: 347, MENU: 348 });
// wgf: enum LightType
export const LightType = Object.freeze({ DIRECTIONAL: 0, POINT: 1, SPOT: 2 });
// wgf: enum LogLevel
export const LogLevel = Object.freeze({ TRACE: 0, DEBUG: 1, INFO: 2, WARN: 3, ERROR: 4, FATAL: 5 });
// wgf: enum MaterialShading
export const MaterialShading = Object.freeze({ PBR: 0, UNLIT: 1 });
// wgf: enum MouseButton
export const MouseButton = Object.freeze({ LEFT: 0, RIGHT: 1, MIDDLE: 2 });
// wgf: enum PlayState
export const PlayState = Object.freeze({ STOPPED: 0, PLAYING: 1, PAUSED: 2, COMPLETE: 3 });
// wgf: enum PresentationMode
export const PresentationMode = Object.freeze({ NONE: 0, STRETCH: 1, FIT: 2, FILL: 3, EXPAND: 4, INTEGER: 5 });
// wgf: enum ResourceStatus
export const ResourceStatus = Object.freeze({ NONE: 0, PENDING: 1, READY: 2, FAILED: 3 });
// wgf: enum Shape2dKind
export const Shape2dKind = Object.freeze({ NONE: 0, RECTANGLE: 1, CIRCLE: 2, LINE: 3, POLYGON: 4 });
// wgf: enum Shape3dKind
export const Shape3dKind = Object.freeze({ NONE: 0, CUBE: 1, SPHERE: 2, RECTANGLE: 3, CIRCLE: 4, LINE: 5, LINE_STRIP: 6 });
// wgf: enum Stage3dTonemap
export const Stage3dTonemap = Object.freeze({ NONE: 0, NEUTRAL: 1, ACES: 2 });
// wgf: enum TextHalign
export const TextHalign = Object.freeze({ LEFT: 0, CENTER: 1, RIGHT: 2 });
// wgf: enum TextValign
export const TextValign = Object.freeze({ TOP: 0, MIDDLE: 1, BOTTOM: 2 });
// wgf: enum TextureFilter
export const TextureFilter = Object.freeze({ LINEAR: 0, NEAREST: 1 });
// wgf: enum TextureWrap
export const TextureWrap = Object.freeze({ REPEAT: 0, CLAMP: 1, MIRROR: 2 });
// wgf: enum UiAlign
export const UiAlign = Object.freeze({ START: 0, CENTER: 1, END: 2 });
// wgf: enum UiColor
export const UiColor = Object.freeze({ TEXT: 0, PANEL: 1, BUTTON: 2, BUTTON_HOVERED: 3, BUTTON_PRESSED: 4, BUTTON_TEXT: 5, FOCUS: 6 });
// wgf: enum UiDirection
export const UiDirection = Object.freeze({ COLUMN: 0, ROW: 1 });
// wgf: enum UiSizing
export const UiSizing = Object.freeze({ FIT: 0, GROW: 1, FIXED: 2, PERCENT: 3 });
// wgf: enum UiValue
export const UiValue = Object.freeze({ TEXT_SIZE: 0, PADDING: 1, GAP: 2, CORNER_RADIUS: 3, BUTTON_PADDING: 4, BUTTON_WIDTH: 5, FOCUS_WIDTH: 6 });
// wgf: enum VehicleDrive
export const VehicleDrive = Object.freeze({ FRONT: 0, REAR: 1, ALL: 2 });
// wgf: enum WorldEvent
export const WorldEvent = Object.freeze({ NONE: 0, CREATED: 1, DESTROYED: 2, TRIGGER_ENTER: 3, TRIGGER_EXIT: 4 });
