"""The Haxe binding's places and marks, and how a Haxe program is built and run on each
target, for the tools that make and check the binding and the programs on it
(tools/gen_binding.py, tools/check_binding.py, tools/check_features.py). Standard library
only."""
import os
import shutil
import subprocess
import sys
import threading
import time
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parent))  # an embedded Python (Windows) doesn't add it
import browser  # noqa: E402
import examples  # noqa: E402
import server  # noqa: E402
import variants  # noqa: E402
import webhost  # noqa: E402

ROOT = Path(__file__).resolve().parents[1]
BINDING = ROOT / 'bindings' / 'haxe'
SOURCE = BINDING / 'src' / 'wgf'
EXPORTS = ROOT / 'hosts' / 'web' / 'exports.json'
MARK = 'Generated by tools/gen_binding.py from the public headers: edit the headers or the generator, not this.'

ASSETS = ROOT / 'examples' / 'assets'


def haxe():
    return shutil.which('haxe')


def has_hxcpp():
    return haxe() is not None and subprocess.run(['haxelib', 'path', 'hxcpp'], capture_output=True).returncode == 0


def work_dir(name):
    """A program's scratch, under this machine's headless build: build/<preset>/binding/<name>."""
    path = Path(variants.work(variants.native('debug-headless'))) / 'binding' / name
    path.mkdir(parents=True, exist_ok=True)
    return path


def compile_haxe(source, target, defines=(), extra=()):
    """Build the Haxe program whose Main is in `source`; (ok, its output)."""
    command = [haxe(), '-cp', SOURCE.parent, '-cp', source, '--main', 'Main', *target, *extra]
    for define in defines:
        command += ['-D', define]
    done = subprocess.run([str(c) for c in command], cwd=BINDING, stdout=subprocess.PIPE,
                          stderr=subprocess.STDOUT, text=True, errors='replace', timeout=900)
    return done.returncode == 0, done.stdout


def verdict(output, mark):
    """The program's last `mark` line's verdict (PASS, FAIL ...), and its lines of failure."""
    lines = output.splitlines()
    found = [line for line in lines if mark in line]
    fails = [line for line in lines if 'FAIL' in line or '[ERROR]' in line or 'ERROR exception' in line]
    return (found[-1].split(mark, 1)[1].strip() if found else None), fails


def run_hxcpp(name, source, mark, defines=(), assets=False):
    """Build `source` with hxcpp against this machine's staged headless variant and run it,
    from a bin/ directory with ../assets beside it when `assets`; (passed, its output)."""
    variant = variants.native('debug-headless')
    examples.prepare(variant)
    work = work_dir(name)
    ok, out = compile_haxe(source, ['--cpp', work / 'cpp'],
                           ['HXCPP_M64', f'wgf_out={variants.out(variant).as_posix()}', 'wgf_headless',
                            f'wgf_binding={BINDING.as_posix()}', *defines])
    if not ok:
        return False, out
    bin_dir = work / 'bin'
    bin_dir.mkdir(exist_ok=True)
    if assets:
        examples.link_assets(work / 'assets')
    program = work / 'cpp' / ('Main.exe' if os.name == 'nt' else 'Main')
    done = subprocess.run([str(program)], cwd=bin_dir, stdout=subprocess.PIPE, stderr=subprocess.STDOUT,
                          text=True, errors='replace', timeout=300)
    result, _ = verdict(done.stdout, mark)
    return done.returncode == 0 and result == 'PASS', done.stdout


def run_node(name, source, mark, defines=(), assets=False):
    """Build `source` for JS and run it under node on the headless web host, with
    examples/assets at /assets in its storage when `assets`; (passed, its output)."""
    node = shutil.which('node')
    host = webhost.build(variants.web(headless=True))
    work = work_dir(name + '-node')
    ok, out = compile_haxe(source, ['--js', work / 'program.js'], ['js-es=6', *defines])
    if not ok:
        return False, out
    command = [node, BINDING / 'test' / 'node.mjs', host / 'wgf-host.js', host / 'wgf.js', work / 'program.js']
    if assets:
        command.append(f'{ASSETS.as_posix()}=/assets')
    done = subprocess.run([str(c) for c in command], cwd=work, stdout=subprocess.PIPE, stderr=subprocess.STDOUT,
                          text=True, errors='replace', timeout=300)
    result, _ = verdict(done.stdout, mark)
    return done.returncode == 0 and result == 'PASS', done.stdout


def run_browser(name, source, mark, browser_path, defines=(), timeout=120, release=False):
    """Build `source` for JS beside the full web host, in its page (hosts/web/page.html),
    serve it with examples/assets at /assets, and load it in a headless browser until its
    `mark` line; (passed, what it logged). `release`: the release host, and the program
    built as a game's release is (a benchmark's)."""
    work = work_dir(name + '-browser')
    site = work / 'site'
    page_dir = site / name
    page_dir.mkdir(parents=True, exist_ok=True)
    webhost.build(variants.web(debug=not release), out=page_dir)
    ok, out = compile_haxe(source, ['--js', page_dir / f'{name}.js'],
                           ['js-es=6', *(['analyzer-optimize'] if release else []), *defines], ['-dce', 'full'])
    if not ok:
        return False, out
    page = (ROOT / 'hosts' / 'web' / 'page.html').read_text(encoding='utf-8').replace('@WGF_PROGRAM@', name)
    (page_dir / 'index.html').write_text(page, encoding='utf-8')
    base, httpd = server.serve(site)
    processes = browser.RunProcesses('binding-' + name)
    processes.install_handlers()
    lines, done = [], threading.Event()

    def on_event(message):
        if message.get('method') == 'Runtime.consoleAPICalled':
            text = ' '.join(str(a.get('value', a.get('description', ''))) for a in message['params']['args'])
            lines.append(text)
            if mark in text:
                done.set()
        elif message.get('method') == 'Runtime.exceptionThrown':
            details = message['params']['exceptionDetails']
            lines.append('ERROR exception: ' +
                         str(details.get('exception', {}).get('description', details.get('text'))))
            done.set()

    try:
        debug_base, session = browser.launch_browser(processes, browser_path, 'headless')
        session.close()
        page_target = browser.page_target(debug_base)
        session = browser.open_session(page_target['webSocketDebuggerUrl'])
        session.on_event(on_event)
        session.send('Runtime.enable')
        session.send('Page.enable')
        session.send('Page.navigate', {'url': f'{base}/{name}/index.html'})
        if not done.wait(timeout):
            lines.append(f'ERROR no verdict within {timeout} s')
        session.close()
    finally:
        processes.stop()
        httpd.shutdown()
    output = '\n'.join(lines)
    result, _ = verdict(output, mark)
    return result == 'PASS', output


if __name__ == '__main__':
    import argparse
    argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter,
                            epilog='A module the other tools import: there is nothing to run.').parse_args()
    raise SystemExit('binding.py: a module the other tools import: there is nothing to run')
