"""The Haxe binding's places and marks, for the tools that make and check it
(tools/gen_binding.py, tools/check_binding.py). Standard library only."""
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
BINDING = ROOT / 'bindings' / 'haxe'
SOURCE = BINDING / 'src' / 'wgf'
EXPORTS = ROOT / 'hosts' / 'web' / 'exports.json'
MARK = 'Generated by tools/gen_binding.py from the public headers: edit the headers or the generator, not this.'


if __name__ == '__main__':
    import argparse
    argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter,
                            epilog='A module the other tools import: there is nothing to run.').parse_args()
    raise SystemExit('binding.py: a module the other tools import: there is nothing to run')
