#!/usr/bin/env python3
"""Write the environments' split-sum BRDF table, libwgf/gfx/src/data/wgf_gfx_brdf_lut.h.

    tools/gen_brdf_lut.py [--check]

The table image-based lighting reads (libwgf/gfx/src/stage/wgf_gfx_environment.c): for each
n.v (x) and perceptual roughness (y), 64 of each at their texels' centres, the scale A and
bias B that turn F0 into the specular reflectance of a GGX surface under uniform light
(Karis' split sum), integrated over 256 GGX importance samples (Hammersley points) with
Schlick-GGX geometry for image-based lighting (k = alpha / 2) and Schlick's Fresnel, as
wgrender-c's tools/gen_brdf_lut.c and libwgt's table. Stored as RG8, a byte each of A and
B (both 0..1): steps of 1/255, far finer than a reflection shows, where libwgt's half floats
cost every program with an environment 14.4 KB of gzip against these 4.9 (half floats
barely compress). Committed: building libwgf never computes it (it costs tens of
milliseconds, a load apiece). The same bytes every run; --check writes nothing and fails
when the committed header is stale. Standard library only.
"""
import argparse
import math
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
OUT = ROOT / 'libwgf' / 'gfx' / 'src' / 'data' / 'wgf_gfx_brdf_lut.h'
SIZE = 64
SAMPLES = 256


def radical_inverse(bits):
    """Van der Corput's radical inverse in base 2, of 32 bits."""
    bits = ((bits << 16) | (bits >> 16)) & 0xFFFFFFFF
    bits = ((bits & 0x55555555) << 1) | ((bits & 0xAAAAAAAA) >> 1)
    bits = ((bits & 0x33333333) << 2) | ((bits & 0xCCCCCCCC) >> 2)
    bits = ((bits & 0x0F0F0F0F) << 4) | ((bits & 0xF0F0F0F0) >> 4)
    bits = ((bits & 0x00FF00FF) << 8) | ((bits & 0xFF00FF00) >> 8)
    return (bits & 0xFFFFFFFF) * 2.3283064365386963e-10


def importance_ggx(i, n, alpha):
    """The GGX half vector about +z for Hammersley point i of n."""
    phi = 2.0 * math.pi * i / n
    xi = radical_inverse(i)
    cos_theta = math.sqrt((1.0 - xi) / (1.0 + (alpha * alpha - 1.0) * xi))
    sin_theta = math.sqrt(max(0.0, 1.0 - cos_theta * cos_theta))
    return sin_theta * math.cos(phi), sin_theta * math.sin(phi), cos_theta


def table():
    """[(a, b)] for y rows of roughness, x columns of n.v."""
    out = []
    for y in range(SIZE):
        roughness = (y + 0.5) / SIZE
        alpha = roughness * roughness
        k = alpha * 0.5
        h_points = [importance_ggx(i, SAMPLES, alpha) for i in range(SAMPLES)]
        for x in range(SIZE):
            n_dot_v = (x + 0.5) / SIZE
            v = (math.sqrt(1.0 - n_dot_v * n_dot_v), 0.0, n_dot_v)
            a = b = 0.0
            for h in h_points:
                v_dot_h = v[0] * h[0] + v[1] * h[1] + v[2] * h[2]
                l_z = 2.0 * v_dot_h * h[2] - v[2]
                n_dot_l = min(max(l_z, 0.0), 1.0)
                if n_dot_l <= 0.0:
                    continue
                n_dot_h = min(max(h[2], 0.0), 1.0)
                g = (n_dot_v / (n_dot_v * (1.0 - k) + k)) * (n_dot_l / (n_dot_l * (1.0 - k) + k))
                g_vis = g * min(max(v_dot_h, 0.0), 1.0) / (n_dot_h * n_dot_v + 1e-6)
                fc = (1.0 - min(max(v_dot_h, 0.0), 1.0)) ** 5
                a += (1.0 - fc) * g_vis
                b += fc * g_vis
            out.append((a / SAMPLES, b / SAMPLES))
    return out


def header():
    values = [min(255, max(0, round(v * 255.0))) for pair in table() for v in pair]
    rows = []
    for i in range(0, len(values), 16):
        rows.append('    ' + ', '.join(f'0x{v:02X}' for v in values[i:i + 16]) + ',')
    return ('/* Generated by tools/gen_brdf_lut.py: run it again, never edit this. The split-sum BRDF table,\n'
            f' * {SIZE} by {SIZE}, RG8 (A, B, 0..1 as 0..255): x n.v, y perceptual roughness, each at its\n'
            ' * texel\'s centre. */\n'
            '#ifndef WGF_GFX_BRDF_LUT_H\n#define WGF_GFX_BRDF_LUT_H\n\n#include <stdint.h>\n\n'
            f'#define WGF_GFX_BRDF_LUT_SIZE {SIZE}\n\n'
            f'static const uint8_t wgf_gfx_brdf_lut[{SIZE} * {SIZE} * 2] = {{\n' + '\n'.join(rows) + '\n};\n\n#endif\n')


def main():
    ap = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    ap.add_argument('--check', action='store_true', help='write nothing; fail when the committed header is stale')
    args = ap.parse_args()
    text = header()
    if args.check:
        if not OUT.exists() or OUT.read_text(encoding='utf-8') != text:
            print(f'gen_brdf_lut: stale: {OUT.relative_to(ROOT).as_posix()} (run tools/gen_brdf_lut.py)')
            return 1
        print('gen_brdf_lut: the BRDF table is current')
        return 0
    OUT.parent.mkdir(parents=True, exist_ok=True)
    OUT.write_text(text, encoding='utf-8', newline='\n')
    print(f'gen_brdf_lut: wrote {OUT.relative_to(ROOT).as_posix()}')
    return 0


if __name__ == '__main__':
    sys.exit(main())
