"""The JS binding's text, from the binding's model of the headers (tools/gen_binding.py's
Binding), and its trimming for a release export. Standard library only.

wgf.js is one ES module: the version it was made from, the runtime and the run written
by hand (bindings/js/src/runtime.js and app.js, put in whole), the enums, and every call
under its C name, each header comment its JSDoc. wgf.d.ts declares the same for
TypeScript: each handle kind its own branded type (a texture is not a node, and a plain
number is neither; 0, none, is any), each enum the union of its values. Every section
after the hand-written head starts with a `// wgf: ` line, so trim() can keep the calls a
program makes without reading the JS.

How each C type crosses (bindings/js/README.md says it for the binding's users):
  numbers, enums           as they are; a uint32_t (a handle, a color) back unsigned
  bool                     true and false, both ways
  const char *             on the wasm stack for the call alone in; copied out
  an array and its count   a JS array or typed array, its length the count; one C fills
                           is copied back into it before the call returns
  a byte span              a Uint8Array or ArrayBuffer in; a Uint8Array copied out
  wgf_vec2/3/4_t           into the caller's object or array, or a new {x, y, ...}
"""
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
BINDING = ROOT / 'bindings' / 'js'
SOURCES = ('runtime.js', 'app.js')
MARK = 'Generated by tools/gen_binding.py from the public headers: edit the headers or the generator, not this.'
SECTION = '// wgf: '

# What the binding reaches on the host besides the calls: the allocator (its slots) and
# the Emscripten runtime methods of runtime.js and app.js. Every host links them.
LIBRARY = ['_malloc', '_free']
RUNTIME = ['addFunction', 'stackSave', 'stackRestore', 'stackAlloc', 'stringToUTF8', 'lengthBytesUTF8',
           'UTF8ToString', 'HEAPU8', 'HEAP32', 'HEAPU32', 'HEAPF32']
# The calls the binding works itself rather than crossing into the host, and why: arithmetic
# on their arguments alone, which a crossing into wasm costs more than, for a JS program and
# Haxe's JS target alike (which reaches C through this binding alone). Each is worked in
# bindings/js/src/local.js to the same bits as C's, its block put where its call goes in
# wgf.js, a group's helpers (`// wgf: local <group>`, the call's section: color, trig) kept by
# a release copy with any call of its group; a trimmed host leaves their C out
# (local_exports), and the full one keeps it for the binding's test, which holds every one to
# it (bindings/js/tests/local.mjs). Natively a call into C costs a function call, and hxcpp
# makes it.
LOCAL = {
    'wgf_color_get': 'a lookup in a fixed table',
    'wgf_color_make': 'clamps and shifts',
    'wgf_color_make_float': "clamps and shifts, in C's float arithmetic",
    'wgf_color_with_alpha': 'a mask',
    'wgf_color_get_red': 'a shift',
    'wgf_color_get_green': 'a shift',
    'wgf_color_get_blue': 'a shift',
    'wgf_color_get_alpha': 'a mask',
    'wgf_color_lerp': "arithmetic, in C's float arithmetic",
    'wgf_trig_sin': "a polynomial in double: C's bits on every target",
    'wgf_trig_cos': "a polynomial in double: C's bits on every target",
    'wgf_trig_tan': "a polynomial in double: C's bits on every target",
    'wgf_trig_atan2': "a polynomial in double: C's bits on every target",
    'wgf_trig_asin': "a polynomial in double: C's bits on every target",
    'wgf_trig_acos': "a polynomial in double: C's bits on every target",
}
LOCAL_SOURCE = BINDING / 'src' / 'local.js'


def local_blocks():
    """local.js's blocks by their `// wgf: ` line ('call wgf_color_make', 'local color'):
    each the text to its next."""
    blocks, name, lines = {}, None, []
    for line in LOCAL_SOURCE.read_text(encoding='utf-8').splitlines():
        if line.startswith(SECTION):
            if name is not None:
                blocks[name] = '\n'.join(lines).strip() + '\n'
            name, lines = line[len(SECTION):].strip(), []
        elif name is not None:
            lines.append(line)
    if name is not None:
        blocks[name] = '\n'.join(lines).strip() + '\n'
    return blocks


def local_exports(exports):
    """A trimmed host's exports less the calls the binding works itself: their C isn't linked."""
    return [e for e in exports if e.lstrip('_') not in LOCAL]


# The calls the run makes itself (app.js), so every host keeps them, trimmed or not.
RUN_CALLS = ['_wgf_app_run', '_wgf_app_quit', '_wgf_version_get_major', '_wgf_version_get_minor']

# Names a parameter can't have: JS's reserved words, and the names the generated code
# itself uses (a C parameter called `host`, wgf_asset_set_host's, would shadow the host).
RESERVED = {'break', 'case', 'catch', 'class', 'const', 'continue', 'debugger', 'default', 'delete', 'do',
            'else', 'enum', 'export', 'extends', 'false', 'finally', 'for', 'function', 'if', 'import', 'in',
            'instanceof', 'new', 'null', 'return', 'super', 'switch', 'this', 'throw', 'true', 'try',
            'typeof', 'var', 'void', 'while', 'with', 'yield', 'let', 'static', 'await', 'arguments',
            'host', 'cstr', 'str', 'result', 'vector', 'slot', 'lengthOf', 'arrayIn', 'arrayOut', 'arrayBack',
            'bytesIn', 'bytesOut', 'mark', 'value', 'ret', 'into'}

FLOATS_IN = 'readonly number[] | Float32Array | Float64Array'
FLOATS_OUT = 'number[] | Float32Array | Float64Array'


def safe(name):
    return name + '_' if name in RESERVED else name


def jsdoc(text):
    if not text:
        return ''
    lines = text.replace('*/', '* /').split('\n')
    return '/**\n' + ''.join(f' * {line}'.rstrip() + '\n' for line in lines) + ' */\n'


class Emitter:
    def __init__(self, binding):
        self.b = binding
        self.docs = binding.docs()

    # ---- types -----------------------------------------------------------------------

    def base(self, ctype):
        """A type through its typedefs: wgf_actor_t -> uint32_t."""
        ctype = ctype.replace('const ', '').strip()
        seen = set()
        while ctype in self.b.api.typedefs and ctype not in seen:
            seen.add(ctype)
            ctype = self.b.api.typedefs[ctype][0]
        return ctype

    def unsigned(self, ctype):
        return self.base(ctype) in ('uint32_t', 'unsigned int')

    def heap(self, element):
        """The heap an array of `element` crosses through."""
        return 'HEAPF32' if element == 'float' else 'HEAP32' if element == 'int' else 'HEAPU32'

    def ts_scalar(self, ctype, param):
        ctype = ctype.replace('const ', '').strip()
        if ctype == 'bool':
            ctype = '_Bool'
        if ctype in self.b.kinds:
            return f'{ctype} | 0' if param else ctype
        if ctype in self.b.enums or ctype in self.b.ints:
            return ctype
        if ctype == '_Bool':
            return 'boolean'
        return 'number'

    def ts_element(self, element, ctype, out):
        if element == 'float':
            return FLOATS_OUT if out else FLOATS_IN
        if element == 'int':
            return 'number[] | Int32Array' if out else 'readonly number[] | Int32Array'
        kind = ctype.replace('const ', '').replace('*', '').strip()
        return f'{kind}[] | Uint32Array' if out else f'readonly {kind}[] | Uint32Array'

    # ---- one call --------------------------------------------------------------------

    def call(self, f):
        """(its JS, its declaration)."""
        b = self.b
        params = b.params_of(f)
        result, detail = b.result_of(f)
        names = [safe(name) for _, name, _, _ in params]
        lines, args, after, decl = [], [], [], []
        strings = False
        slot = 0
        for (kind, _, ctype, extra), name in zip(params, names):
            if kind == 'scalar':
                args.append(f'({name} ? 1 : 0)' if extra[2] == 'bool' else name)
                decl.append(f'{name}: {self.ts_scalar(ctype, True)}')
            elif kind == 'string':
                strings = True
                args.append(f'cstr({name})')
                decl.append(f'{name}: string | null')
            elif kind == 'bytes':
                lines.append(f'const {name}Pointer = bytesIn({name}, {slot});')
                args += [f'{name}Pointer', f'lengthOf({name})']
                decl.append(f'{name}: Uint8Array | ArrayBuffer | null')
                slot += 1
            else:
                heap = self.heap(extra)
                if kind == 'array_in':
                    lines.append(f'const {name}Pointer = arrayIn({name}, {slot}, "{heap}");')
                else:
                    lines.append(f'const {name}Pointer = arrayOut({name}, {slot});')
                    after.append(f'arrayBack({name}Pointer, {name}, "{heap}");')
                args += [f'{name}Pointer', f'lengthOf({name})']
                decl.append(f'{name}: {self.ts_element(extra, ctype, kind == "array_out")} | null')
                slot += 1
        key = f'host["_{f.name}"]'
        body = []
        if strings:
            body.append('const mark = host["stackSave"]();')
        body += lines
        if result == 'vector':
            _, count = detail
            body.append(f'const ret = result({4 * count});')
            body.append(f'{key}({", ".join(["ret"] + args)});')
        elif result == 'void':
            body.append(f'{key}({", ".join(args)});')
        else:
            body.append(f'const value = {key}({", ".join(args)});')
        body += after
        if strings:
            body.append('host["stackRestore"](mark);')
        js_args = list(names)
        if result == 'string':
            body.append('return str(value);')
            returns = 'string'
        elif result == 'bytes':
            body.append(f'return bytesOut(value, host["_{detail}"]({args[0]}));')
            returns = 'Uint8Array'
        elif result == 'vector':
            _, count = detail
            js_args.append('into')
            body.append(f'return vector(ret, {count}, into);')
            returns = f'wgf_vec{count}_t'
        elif result == 'scalar':
            how = detail[2]
            if how == 'bool':
                body.append('return value !== 0;')
            elif how == 'int' and self.unsigned(f.returns):
                body.append('return value >>> 0;')
            else:
                body.append('return value;')
            returns = self.ts_scalar(f.returns, False)
        else:
            returns = 'void'
        doc = jsdoc(self.docs.get(f.name, ''))
        js = (f'{SECTION}call {f.name}\n{doc}export function {f.name}({", ".join(js_args)}) {{\n'
              + ''.join(f'    {line}\n' for line in body) + '}\n')
        if f.name in LOCAL:  # worked here, not in the host: local.js's block, its group's helpers before it
            blocks = self.local
            block = blocks.get(f'call {f.name}')
            if block is None:
                raise RuntimeError(f'{LOCAL_SOURCE}: no block for {f.name}, which LOCAL lists')
            group = f.name.split('_')[1]
            helpers = ''
            if group not in self.groups_written:
                self.groups_written.add(group)
                helpers = f'{SECTION}local {group}\n' + blocks.get(f'local {group}', '') + '\n'
            js = helpers + f'{SECTION}call {f.name}\n{doc}' + block
        sig = ', '.join(decl)
        if result == 'vector':
            vec = f'wgf_vec{detail[1]}_t'
            lead = sig + ', ' if sig else ''
            dts = (f'{doc}export declare function {f.name}<T extends {FLOATS_OUT}>({lead}into: T): T;\n'
                   f'export declare function {f.name}({lead}into?: {vec} | null): {vec};\n')
        else:
            dts = f'{doc}export declare function {f.name}({sig}): {returns};\n'
        return js, dts

    # ---- the module ------------------------------------------------------------------

    def enums(self):
        js, dts = [], []
        for cname, enum in self.b.api.enums.items():
            doc = jsdoc(enum.doc)
            js.append(doc + ''.join(f'export const {k} = {v};\n' for k, v in enum.values.items()))
            dts.append(doc + ''.join(f'export declare const {k}: {v};\n' for k, v in enum.values.items())
                       + f'export type {cname} = ' + ' | '.join(f'typeof {k}' for k in enum.values) + ';\n')
        return js, dts


def outputs(binding, version, stamp, skipped):
    """{path: text} for wgf.js and wgf.d.ts. `skipped`: the calls the run carries itself."""
    major, minor, patch = version.split('.')
    e = Emitter(binding)
    e.local, e.groups_written = local_blocks(), set()
    built = (f'/** The libwgf this binding was generated from: wgf_app_run compares the host\'s with it. */\n'
             f'export const BUILT_VERSION = Object.freeze({{ "major": {int(major)}, "minor": {int(minor)}, '
             f'"patch": {int(patch)}, "headers": "{stamp}" }});\n')
    head = (f'// {MARK}\n// libwgf\'s JS binding (bindings/js/README.md): every exported call under its C name.\n\n'
            + built + '\n' + ''.join((BINDING / 'src' / name).read_text(encoding='utf-8') + '\n' for name in SOURCES))
    enum_js, enum_dts = e.enums()
    calls = [e.call(f) for f in binding.functions if f.name not in skipped]
    js = head + f'{SECTION}constants\n' + '\n'.join(enum_js) + '\n' + '\n'.join(c[0] for c in calls)
    kinds = ''.join(f'/** A handle of kind {k}; 0 is none. */\n'
                    f'export type {k} = number & {{ readonly [kind]: "{k}" }};\n'
                    for k in binding.kinds if k != 'wgf_handle_t')
    ints = ''.join(f'export type {t} = number;\n' for t in sorted(binding.ints))
    vectors = ''.join(f'export interface wgf_vec{n}_t {{ {" ".join(f"{c}: number;" for c in "xyzw"[:n])} }}\n'
                      for n in (2, 3, 4))
    dts = (f'// {MARK}\n\n'
           '/** The libwgf this binding was generated from. */\nexport declare const BUILT_VERSION: '
            '{ readonly major: number; readonly minor: number; readonly patch: number; readonly headers: string };\n\n'
            + (BINDING / 'src' / 'wgf.d.ts').read_text(encoding='utf-8') + '\n'
            + 'declare const kind: unique symbol;\n'
            '/** Any handle, of any kind; 0 is none. */\n'
            'export type wgf_handle_t = number & { readonly [kind]: string };\n'
            + kinds + ints + vectors + '\n' + '\n'.join(enum_dts) + '\n' + '\n'.join(c[1] for c in calls))
    return {BINDING / 'wgf.js': js, BINDING / 'wgf.d.ts': dts}


TYPED = 'wgf-typed'


def typed_outputs(members, handle_types, enums, extras, docs):
    """{path: text} for wgf-typed.js and wgf-typed.d.ts: the typed layer, beside the raw
    one, in the typed Haxe API's names (Actor.setPosition, Prefab.spawnAt, World.takeEvents).
    Each type is a frozen namespace of the raw binding's own functions -- no wrapper, so
    nothing allocates and nothing costs a call -- taking the handle first where the raw
    call does; each handle kind is also a type, the raw binding's branded one, so an actor
    can't go where a prefab does; each enum an object of its values, literal numbers. Every
    member starts with a `// wgf: call` line naming the raw calls it reaches, so a program's
    copy can be trimmed to what it names (trim_typed)."""
    js = [f'// {MARK}\n// libwgf\'s typed JS layer (bindings/js/README.md): the raw binding\'s calls (wgf.js) in the '
          'typed Haxe API\'s names.\n\nimport * as raw from "./wgf.js";\n'
          '/** The host handed over, as the raw binding takes it: a program on this layer imports nothing else. */\n'
          'export { attach, isAttached } from "./wgf.js";\n']
    dts = [f'// {MARK}\n\nimport * as raw from "./wgf.js";\nexport {{ attach, isAttached }} from "./wgf.js";\n']
    for haxe in sorted(set(members) | set(extras) | set(handle_types)):
        entries = members.get(haxe, [])
        js.append(f'{SECTION}typed {haxe}\nexport const {haxe} = Object.freeze({{\n')
        if haxe in handle_types:
            dts.append(f'/** A handle of kind {handle_types[haxe]}: the raw binding\'s branded type. */\n'
                       f'export type {haxe} = raw.{handle_types[haxe]};\n')
        dts.append(f'export declare const {haxe}: {{\n')
        for member, cname in entries:
            doc = docs.get(cname, '')
            js.append(f'    {SECTION}call {cname}\n    {member}: raw.{cname},\n')
            dts.append(''.join('    ' + line + '\n' for line in jsdoc(doc).splitlines()) if doc else '')
            dts.append(f'    readonly {member}: typeof raw.{cname};\n')
        if haxe in handle_types and haxe != 'Handle':
            js.append(f'    {SECTION}call wgf_handle_is_alive\n    isAlive: raw.wgf_handle_is_alive,\n')
            dts.append(f'    /** Whether the handle refers to something alive (wgf_handle_is_alive). */\n'
                       f'    readonly isAlive: (handle: raw.wgf_handle_t | 0) => boolean;\n')
        if haxe in extras:
            member, doc, calls, body, signature = extras[haxe]
            js.append(f'    {SECTION}call {" ".join(calls)}\n    {body},\n')
            dts.append(''.join('    ' + line + '\n' for line in jsdoc(doc).splitlines()) + f'    readonly {member}: {signature};\n')
        js.append('});\n')
        dts.append('};\n')
    for haxe, (cname, values) in sorted(enums.items()):
        js.append(f'{SECTION}enum {haxe}\nexport const {haxe} = Object.freeze({{ '
                  + ', '.join(f'{short}: {v}' for short, v, _ in values) + ' });\n')
        dts.append(f'export type {haxe} = raw.{cname};\n'
                   f'export declare const {haxe}: {{ ' + ' '.join(f'readonly {short}: {haxe};' for short, _, _ in values)
                   + ' };\n')
    return {BINDING / f'{TYPED}.js': ''.join(js), BINDING / f'{TYPED}.d.ts': ''.join(dts)}


def typed_names_in(program, typed):
    """The typed layer's members a program names (`Actor.setPosition`), read from its text
    as a type, a dot, and a member, and the raw calls they reach: (members as
    (type, member), calls). `typed` is wgf-typed.js's text."""
    layout, current = {}, None
    pending = None
    for line in typed.splitlines():
        stripped = line.strip()
        if stripped.startswith(SECTION + 'typed ') or stripped.startswith(SECTION + 'enum '):
            current = stripped.split()[-1]
            layout.setdefault(current, {})
            if stripped.startswith(SECTION + 'enum '):
                pending = 'enum'
        elif pending == 'enum' and current is not None:  # its one line: each value a member, reaching no call
            body = stripped.split('({', 1)[1].rsplit('})', 1)[0]
            layout[current] = {pair.split(':')[0].strip(): [] for pair in body.split(',') if ':' in pair}
            pending = None
        elif stripped.startswith(SECTION + 'call '):
            pending = stripped[len(SECTION + 'call '):].split()
        elif pending is not None and current is not None:
            layout[current][stripped.split(':', 1)[0].split('(', 1)[0].strip()] = pending
            pending = None
    used, calls = set(), set()
    words, word, last = [], [], ''
    for ch in program + ' ':
        if ch.isalnum() or ch == '_':
            word.append(ch)
            continue
        if word:
            words.append((''.join(word), ch))
            word = []
        elif ch == '.':
            words.append(('', '.'))
    for (a, sep), (b, _) in zip(words, words[1:]):
        if sep == '.' and a in layout and b in layout[a]:
            used.add((a, b))
            calls.update(layout[a][b])
    return used, calls


def trim_typed(typed, used):
    """wgf-typed.js with only the members `used` names ((type, member), as typed_names_in
    gives them): the types holding none of them left out, and each enum cut to the values
    named."""
    keep_types = {a for a, _ in used}
    out, keep_type, in_head = [], False, True
    lines = typed.splitlines()
    i = 0
    while i < len(lines):
        line, stripped = lines[i], lines[i].strip()
        if in_head and not stripped.startswith(SECTION):  # the import and the re-export, before the first type
            if stripped and not stripped.startswith('//') and not stripped.startswith('/*'):
                out.append(line)
            i += 1
            continue
        in_head = False
        if stripped.startswith(SECTION + 'enum '):
            name = stripped.split()[-1]
            if name in keep_types:  # its values the program names, alone
                body = lines[i + 1].split('({', 1)[1].rsplit('})', 1)[0]
                kept = [pair.strip() for pair in body.split(',') if (name, pair.split(':')[0].strip()) in used]
                out.append(f'export const {name} = Object.freeze({{ {", ".join(kept)} }});')
            keep_type = False
            i += 2
            continue
        if stripped.startswith(SECTION + 'typed '):
            name = stripped.split()[-1]
            keep_type = name in keep_types
            i += 1
            continue
        if not keep_type:
            i += 1
            continue
        if stripped.startswith(SECTION + 'call '):
            member = lines[i + 1].strip().split(':', 1)[0].split('(', 1)[0].strip()
            j = i + 1
            depth = 0
            while True:  # the member's lines, to its closing comma at depth 0
                depth += lines[j].count('{') - lines[j].count('}')
                if depth <= 0 and lines[j].rstrip().endswith(','):
                    break
                j += 1
            if (current_type(lines, i), member) in used:
                out.extend(lines[i + 1:j + 1])
            i = j + 1
            continue
        if not stripped.startswith('//'):
            out.append(line)
        i += 1
    return '\n'.join(out) + '\n'


def current_type(lines, at):
    """The typed section a line is in."""
    for line in reversed(lines[:at]):
        stripped = line.strip()
        if stripped.startswith(SECTION + 'typed ') or stripped.startswith(SECTION + 'enum '):
            return stripped.split()[-1]
    return None


def trim(text, names, constants=False):
    """wgf.js with only the calls `names` lists (C names, with or without the host's
    leading _), and no comments: a release program's copy. Its enums too when
    `constants` is true, or those of them `constants` names when it is a set."""
    wanted = {n.lstrip('_') for n in names}
    out, keep, in_doc, in_constants = [], True, False, False
    for line in text.splitlines():
        if line.startswith(SECTION):
            what = line[len(SECTION):].split()
            in_constants = what[0] == 'constants'
            keep = ((in_constants and bool(constants)) or (what[0] == 'call' and what[1] in wanted)
                    or (what[0] == 'local' and any(n.startswith(f'wgf_{what[1]}_') for n in wanted)))
            continue
        if not keep:
            continue
        if in_constants and isinstance(constants, set) and line.startswith('export const '):
            if line[len('export const '):].split(' ', 1)[0] not in constants:
                continue
        stripped = line.strip()
        if in_doc:
            in_doc = '*/' not in stripped
            continue
        if stripped.startswith('/**'):
            in_doc = '*/' not in stripped
            continue
        if stripped.startswith('//') or not stripped:
            continue
        out.append(line)
    return '\n'.join(out) + '\n'


def names_in(program):
    """The calls and the enums a JS program names (`wgf.wgf_draw_text`, `wgf.WGF_KEY_UP`),
    read from its text: identifiers, which a program can't make at run time; a name that
    isn't the binding's is ignored by whatever reads these."""
    calls, constants, word = set(), set(), []
    for ch in program + ' ':
        if ch.isalnum() or ch == '_':
            word.append(ch)
            continue
        name = ''.join(word)
        word = []
        if name.startswith('wgf_'):
            calls.add(name)
        elif name.startswith('WGF_'):
            constants.add(name)
    return calls, constants


if __name__ == '__main__':
    import argparse
    argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter,
                            epilog='A module the other tools import: there is nothing to run.').parse_args()
    raise SystemExit('jsbinding.py: a module the other tools import: there is nothing to run')
