"""The JS binding's text, from the binding's model of the headers (tools/gen_binding.py's
Binding), and its trimming for a release export. Standard library only.

wgf.js is one ES module: the version it was made from, the runtime and the run written
by hand (bindings/js/src/runtime.js and app.js, put in whole), the enums, and every call
under its C name, each header comment its JSDoc. wgf.d.ts declares the same for
TypeScript: each handle kind its own branded type (a texture is not a node, and a plain
number is neither; 0, none, is any), each enum the union of its values. Every section
after the hand-written head starts with a `// wgf: ` line, so trim() can keep the calls a
program makes without reading the JS.

How each C type crosses (bindings/js/README.md says it for the binding's users):
  numbers, enums           as they are; a uint32_t (a handle, a color) back unsigned
  bool                     true and false, both ways
  const char *             on the wasm stack for the call alone in; copied out
  an array and its count   a JS array or typed array, its length the count; one C fills
                           is copied back into it before the call returns
  a byte span              a Uint8Array or ArrayBuffer in; a Uint8Array copied out
  wgf_vec2/3/4_t           into the caller's object or array, or a new {x, y, ...}
"""
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
BINDING = ROOT / 'bindings' / 'js'
SOURCES = ('runtime.js', 'app.js')
MARK = 'Generated by tools/gen_binding.py from the public headers: edit the headers or the generator, not this.'
SECTION = '// wgf: '

# What the binding reaches on the host besides the calls: the allocator (its slots) and
# the Emscripten runtime methods of runtime.js and app.js. Every host links them.
LIBRARY = ['_malloc', '_free']
RUNTIME = ['addFunction', 'stackSave', 'stackRestore', 'stackAlloc', 'stringToUTF8', 'lengthBytesUTF8',
           'UTF8ToString', 'HEAPU8', 'HEAP32', 'HEAPU32', 'HEAPF32']
# The calls the run makes itself (app.js), so every host keeps them, trimmed or not.
RUN_CALLS = ['_wgf_app_run', '_wgf_app_quit', '_wgf_version_get_major', '_wgf_version_get_minor']

# Names a parameter can't have: JS's reserved words, and the names the generated code
# itself uses (a C parameter called `host`, wgf_asset_set_host's, would shadow the host).
RESERVED = {'break', 'case', 'catch', 'class', 'const', 'continue', 'debugger', 'default', 'delete', 'do',
            'else', 'enum', 'export', 'extends', 'false', 'finally', 'for', 'function', 'if', 'import', 'in',
            'instanceof', 'new', 'null', 'return', 'super', 'switch', 'this', 'throw', 'true', 'try',
            'typeof', 'var', 'void', 'while', 'with', 'yield', 'let', 'static', 'await', 'arguments',
            'host', 'cstr', 'str', 'result', 'vector', 'slot', 'lengthOf', 'arrayIn', 'arrayOut', 'arrayBack',
            'bytesIn', 'bytesOut', 'mark', 'value', 'ret', 'into'}

FLOATS_IN = 'readonly number[] | Float32Array | Float64Array'
FLOATS_OUT = 'number[] | Float32Array | Float64Array'


def safe(name):
    return name + '_' if name in RESERVED else name


def jsdoc(text):
    if not text:
        return ''
    lines = text.replace('*/', '* /').split('\n')
    return '/**\n' + ''.join(f' * {line}'.rstrip() + '\n' for line in lines) + ' */\n'


class Emitter:
    def __init__(self, binding):
        self.b = binding
        self.docs = binding.docs()

    # ---- types -----------------------------------------------------------------------

    def base(self, ctype):
        """A type through its typedefs: wgf_actor_t -> uint32_t."""
        ctype = ctype.replace('const ', '').strip()
        seen = set()
        while ctype in self.b.api.typedefs and ctype not in seen:
            seen.add(ctype)
            ctype = self.b.api.typedefs[ctype][0]
        return ctype

    def unsigned(self, ctype):
        return self.base(ctype) in ('uint32_t', 'unsigned int')

    def heap(self, element):
        """The heap an array of `element` crosses through."""
        return 'HEAPF32' if element == 'float' else 'HEAP32' if element == 'int' else 'HEAPU32'

    def ts_scalar(self, ctype, param):
        ctype = ctype.replace('const ', '').strip()
        if ctype == 'bool':
            ctype = '_Bool'
        if ctype in self.b.kinds:
            return f'{ctype} | 0' if param else ctype
        if ctype in self.b.enums or ctype in self.b.ints:
            return ctype
        if ctype == '_Bool':
            return 'boolean'
        return 'number'

    def ts_element(self, element, ctype, out):
        if element == 'float':
            return FLOATS_OUT if out else FLOATS_IN
        if element == 'int':
            return 'number[] | Int32Array' if out else 'readonly number[] | Int32Array'
        kind = ctype.replace('const ', '').replace('*', '').strip()
        return f'{kind}[] | Uint32Array' if out else f'readonly {kind}[] | Uint32Array'

    # ---- one call --------------------------------------------------------------------

    def call(self, f):
        """(its JS, its declaration)."""
        b = self.b
        params = b.params_of(f)
        result, detail = b.result_of(f)
        names = [safe(name) for _, name, _, _ in params]
        lines, args, after, decl = [], [], [], []
        strings = False
        slot = 0
        for (kind, _, ctype, extra), name in zip(params, names):
            if kind == 'scalar':
                args.append(f'({name} ? 1 : 0)' if extra[2] == 'bool' else name)
                decl.append(f'{name}: {self.ts_scalar(ctype, True)}')
            elif kind == 'string':
                strings = True
                args.append(f'cstr({name})')
                decl.append(f'{name}: string | null')
            elif kind == 'bytes':
                lines.append(f'const {name}Pointer = bytesIn({name}, {slot});')
                args += [f'{name}Pointer', f'lengthOf({name})']
                decl.append(f'{name}: Uint8Array | ArrayBuffer | null')
                slot += 1
            else:
                heap = self.heap(extra)
                if kind == 'array_in':
                    lines.append(f'const {name}Pointer = arrayIn({name}, {slot}, "{heap}");')
                else:
                    lines.append(f'const {name}Pointer = arrayOut({name}, {slot});')
                    after.append(f'arrayBack({name}Pointer, {name}, "{heap}");')
                args += [f'{name}Pointer', f'lengthOf({name})']
                decl.append(f'{name}: {self.ts_element(extra, ctype, kind == "array_out")} | null')
                slot += 1
        key = f'host["_{f.name}"]'
        body = []
        if strings:
            body.append('const mark = host["stackSave"]();')
        body += lines
        if result == 'vector':
            _, count = detail
            body.append(f'const ret = result({4 * count});')
            body.append(f'{key}({", ".join(["ret"] + args)});')
        elif result == 'void':
            body.append(f'{key}({", ".join(args)});')
        else:
            body.append(f'const value = {key}({", ".join(args)});')
        body += after
        if strings:
            body.append('host["stackRestore"](mark);')
        js_args = list(names)
        if result == 'string':
            body.append('return str(value);')
            returns = 'string'
        elif result == 'bytes':
            body.append(f'return bytesOut(value, host["_{detail}"]({args[0]}));')
            returns = 'Uint8Array'
        elif result == 'vector':
            _, count = detail
            js_args.append('into')
            body.append(f'return vector(ret, {count}, into);')
            returns = f'wgf_vec{count}_t'
        elif result == 'scalar':
            how = detail[2]
            if how == 'bool':
                body.append('return value !== 0;')
            elif how == 'int' and self.unsigned(f.returns):
                body.append('return value >>> 0;')
            else:
                body.append('return value;')
            returns = self.ts_scalar(f.returns, False)
        else:
            returns = 'void'
        doc = jsdoc(self.docs.get(f.name, ''))
        js = (f'{SECTION}call {f.name}\n{doc}export function {f.name}({", ".join(js_args)}) {{\n'
              + ''.join(f'    {line}\n' for line in body) + '}\n')
        sig = ', '.join(decl)
        if result == 'vector':
            vec = f'wgf_vec{detail[1]}_t'
            lead = sig + ', ' if sig else ''
            dts = (f'{doc}export declare function {f.name}<T extends {FLOATS_OUT}>({lead}into: T): T;\n'
                   f'export declare function {f.name}({lead}into?: {vec} | null): {vec};\n')
        else:
            dts = f'{doc}export declare function {f.name}({sig}): {returns};\n'
        return js, dts

    # ---- the module ------------------------------------------------------------------

    def enums(self):
        js, dts = [], []
        for cname, enum in self.b.api.enums.items():
            doc = jsdoc(enum.doc)
            js.append(doc + ''.join(f'export const {k} = {v};\n' for k, v in enum.values.items()))
            dts.append(doc + ''.join(f'export declare const {k}: {v};\n' for k, v in enum.values.items())
                       + f'export type {cname} = ' + ' | '.join(f'typeof {k}' for k in enum.values) + ';\n')
        return js, dts


def outputs(binding, version, stamp, skipped):
    """{path: text} for wgf.js and wgf.d.ts. `skipped`: the calls the run carries itself."""
    major, minor, patch = version.split('.')
    e = Emitter(binding)
    built = (f'/** The libwgf this binding was generated from: wgf_app_run compares the host\'s with it. */\n'
             f'export const BUILT_VERSION = Object.freeze({{ "major": {int(major)}, "minor": {int(minor)}, '
             f'"patch": {int(patch)}, "headers": "{stamp}" }});\n')
    head = (f'// {MARK}\n// libwgf\'s JS binding (bindings/js/README.md): every exported call under its C name.\n\n'
            + built + '\n' + ''.join((BINDING / 'src' / name).read_text(encoding='utf-8') + '\n' for name in SOURCES))
    enum_js, enum_dts = e.enums()
    calls = [e.call(f) for f in binding.functions if f.name not in skipped]
    js = head + f'{SECTION}constants\n' + '\n'.join(enum_js) + '\n' + '\n'.join(c[0] for c in calls)
    kinds = ''.join(f'/** A handle of kind {k}; 0 is none. */\n'
                    f'export type {k} = number & {{ readonly [kind]: "{k}" }};\n'
                    for k in binding.kinds if k != 'wgf_handle_t')
    ints = ''.join(f'export type {t} = number;\n' for t in sorted(binding.ints))
    vectors = ''.join(f'export interface wgf_vec{n}_t {{ {" ".join(f"{c}: number;" for c in "xyzw"[:n])} }}\n'
                      for n in (2, 3, 4))
    dts = (f'// {MARK}\n\n'
           '/** The libwgf this binding was generated from. */\nexport declare const BUILT_VERSION: '
            '{ readonly major: number; readonly minor: number; readonly patch: number; readonly headers: string };\n\n'
            + (BINDING / 'src' / 'wgf.d.ts').read_text(encoding='utf-8') + '\n'
            + 'declare const kind: unique symbol;\n'
            '/** Any handle, of any kind; 0 is none. */\n'
            'export type wgf_handle_t = number & { readonly [kind]: string };\n'
            + kinds + ints + vectors + '\n' + '\n'.join(enum_dts) + '\n' + '\n'.join(c[1] for c in calls))
    return {BINDING / 'wgf.js': js, BINDING / 'wgf.d.ts': dts}


def trim(text, names, constants=False):
    """wgf.js with only the calls `names` lists (C names, with or without the host's
    leading _), and no comments: a release program's copy. Its enums too when
    `constants` is true, or those of them `constants` names when it is a set."""
    wanted = {n.lstrip('_') for n in names}
    out, keep, in_doc, in_constants = [], True, False, False
    for line in text.splitlines():
        if line.startswith(SECTION):
            what = line[len(SECTION):].split()
            in_constants = what[0] == 'constants'
            keep = (in_constants and bool(constants)) or (what[0] == 'call' and what[1] in wanted)
            continue
        if not keep:
            continue
        if in_constants and isinstance(constants, set) and line.startswith('export const '):
            if line[len('export const '):].split(' ', 1)[0] not in constants:
                continue
        stripped = line.strip()
        if in_doc:
            in_doc = '*/' not in stripped
            continue
        if stripped.startswith('/**'):
            in_doc = '*/' not in stripped
            continue
        if stripped.startswith('//') or not stripped:
            continue
        out.append(line)
    return '\n'.join(out) + '\n'


def names_in(program):
    """The calls and the enums a JS program names (`wgf.wgf_draw_text`, `wgf.WGF_KEY_UP`),
    read from its text: identifiers, which a program can't make at run time; a name that
    isn't the binding's is ignored by whatever reads these."""
    calls, constants, word = set(), set(), []
    for ch in program + ' ':
        if ch.isalnum() or ch == '_':
            word.append(ch)
            continue
        name = ''.join(word)
        word = []
        if name.startswith('wgf_'):
            calls.add(name)
        elif name.startswith('WGF_'):
            constants.add(name)
    return calls, constants


if __name__ == '__main__':
    import argparse
    argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter,
                            epilog='A module the other tools import: there is nothing to run.').parse_args()
    raise SystemExit('jsbinding.py: a module the other tools import: there is nothing to run')
